Repository pixiebrix/pixiebrix-extension, pull requests merged in 2021-08, with the labels that each got.

#959 Avoid injection on extension pages; Avoid duplicates on app pages
  src/background/browserAction.ts
  src/background/util.ts
Labels: bug

#1001 Avoid category card clipping in options page
  src/options/pages/templates/TemplatesPage.scss
Labels: bug

#993 Immediately catch `activeTab` and update editor state
  src/background/browserAction.ts
  src/devTools/editor/panes/PermissionsPane.tsx
  src/popups/PermissionsPopup.tsx
Labels: user experience

#1000 Improve modals’ accessibility
  src/components/AsyncButton.tsx
  src/layout/ErrorModal.tsx
  src/popups/PermissionsPopup.tsx
Labels: user experience

#998 Hide "Show 0 unavailable"
  src/devTools/editor/sidebar/Sidebar.tsx
Labels: user experience

#1016 Correctly track auth data changes in Firefox + Update storage
  src/auth/token.ts
Labels: firefox

#1040 Change Chrome-specific code and copy
  src/actionPanel/native.tsx
  src/background/browserAction.ts
  src/blocks/effects/notification.ts
  src/blocks/readers/meta.ts
  src/blocks/renderers/iframe.ts
  src/contentScript/lifecycle.ts
  src/contrib/uipath/embedApp.ts
  src/devTools/editor/tabs/AvailabilityTab.tsx
  src/devTools/editor/tabs/contextMenu/AvailabilityTab.tsx
  src/devTools/editor/tabs/contextMenu/MenuItemTab.tsx
  src/messaging/external.ts
  src/telemetry/rollbar.ts
Labels: firefox

#1043 Bump @babel/preset-env and @babel/preset-typescript
  package-lock.json
  package.json
  src/types.ts
Labels: dependencies

#1019 Tighten `externalProtocol` messaging
  src/contentScript.ts
  src/contentScript/externalProtocol.ts
Labels: firefox

#995 Increase minimum Firefox version to 91
  src/manifest.json
Labels: firefox

#1062 #1014: Add vendor bundle
  src/action.html
  src/devtools.html
  src/devtoolsPanel.html
  src/frame.html
  src/manifest.json
  src/options.html
  src/permissionsPopup.html
  webpack.config.js
Labels: performance

#1061 Type-check in parallel with webpack to speed up building
  .github/workflows/integration.yml
  package-lock.json
  package.json
  webpack.config.js
  webpack.shared-config.js
Labels: developer experience

#1108 #1103: Handle null icons in getSvgIcon
  src/icons/getSvgIcon.ts
Labels: bug

#1071 Exclude source maps from the extension bundle; Limit source maps creation on CI
  .github/workflows/ci.yml
  .github/workflows/release.yaml
  package.json
  webpack.config.js
Labels: developer experience, performance

#1028 Streamline onboarding process
  src/background/installer.ts
  src/options/pages/SetupPage.tsx
Labels: user experience

#1178 Fix local sourcemaps
  selenium/readme.md
  webpack.config.js
Labels: developer experience

#1199 Skip storybook upload on CI
  .github/workflows/storybook.yml
Labels: developer experience

#1222 Exclude `redux-logger` from production build
  webpack.config.js
Labels: performance
