Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-05, with the labels that each got.

#3333 Initial commit of PR template
  .github/pull_request_template.md
Labels: developer experience

#3325 #3268 Improve error msg layout in Form component
  src/components/form/Form.module.scss
  src/components/form/Form.tsx
  src/pageEditor/sidebar/CreateRecipeModal.tsx
Labels: do not merge

#3073 #3372: Use only `Error#cause`, even outside `ContextError`
  src/auth/token.ts
  src/background/proxyService.test.ts
  src/components/errors/NetworkErrorDetail.tsx
  src/components/errors/getErrorDetails.test.tsx
  src/components/errors/getErrorDetails.tsx
  src/errors.test.ts
  src/errors.ts
  src/services/errorService.ts
  src/services/errors.ts
  src/services/requestErrorUtils.ts
  src/utils/enrichAxiosErrors.ts
Labels: developer experience

#3419 Removing react-redux auto mock
  __mocks__/react-redux.js
  src/components/documentBuilder/edit/DocumentEditor.test.tsx
  src/components/form/widgets/RegistryIdWidget.test.tsx
  src/components/logViewer/LogCard.test.tsx
  src/options/pages/blueprints/modals/ShareExtensionModal.test.tsx
  src/options/pages/blueprints/onboardingView/OnboardingView.test.tsx
  src/options/pages/blueprints/useInstallableViewItemActions.test.tsx
  src/pageEditor/panes/save/RecipeConfigurationModal.test.tsx
  src/pageEditor/panes/save/SaveExtensionWizard.test.tsx
  src/pageEditor/panes/save/useSavingWizard.test.tsx
  src/pageEditor/sidebar/RecipeEntry.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.test.tsx
  src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
  src/sidebar/DefaultContent.test.tsx
Labels: developer experience

#3420 #3353 ObjectWidget tests
  src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx
  src/components/fields/schemaFields/widgets/ObjectWidget.tsx
  src/components/fields/schemaFields/widgets/__snapshots__/ObjectWidget.test.tsx.snap
Labels: testing, page editor

#3421 #3353 Add tests for ArrayWidget
  src/components/fields/schemaFields/widgets/ArrayWidget.test.tsx
  src/components/fields/schemaFields/widgets/__snapshots__/ArrayWidget.test.tsx.snap
Labels: testing, page editor

#3433 Refactor rest render function, pull store outside wrapper
  src/testUtils/testHelpers.tsx
Labels: testing, page editor

#3434 #3353 Schema select widget tests
  src/components/fields/schemaFields/widgets/SchemaSelectWidget.test.tsx
  src/components/fields/schemaFields/widgets/__snapshots__/SchemaSelectWidget.test.tsx.snap
Labels: testing

#3427 #3121: fix nav item alignment on small screen
  src/options/pages/blueprints/ListFilters.tsx
Labels: user experience

#3440 #3353 DataPanel render test
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/PageStateTab.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/FoundationDataPanel.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/PageStateTab.test.tsx.snap
  src/testUtils/factories.ts
Labels: testing

#3443 More snapshot tests and remove unused component
  src/components/form/widgets/OptionsWidget.module.scss
  src/components/form/widgets/OptionsWidget.tsx
  src/components/form/widgets/radioItemList/RadioItemListWidget.test.tsx
  src/components/form/widgets/radioItemList/__snapshots__/RadioItemListWidget.test.tsx.snap
  src/components/tabLayout/EditorTabLayout.test.tsx
  src/components/tabLayout/__snapshots__/EditorTabLayout.test.tsx.snap
Labels: testing

#3444 #3353 Sidebar entry render tests
  src/pageEditor/sidebar/DynamicEntry.test.tsx
  src/pageEditor/sidebar/InstalledEntry.test.tsx
  src/pageEditor/sidebar/__snapshots__/DynamicEntry.test.tsx.snap
  src/pageEditor/sidebar/__snapshots__/InstalledEntry.test.tsx.snap
  src/testUtils/factories.ts
Labels: testing

#3534 Bump Browserslist/caniuse-lite
  package-lock.json
Labels: developer experience, low priority

#3538 Update storybook to v6.5.6
  package-lock.json
  package.json
Labels: dependencies
