Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-01, with the labels that each got.

#2272 #2190: Isolate kbar style via Shadow DOM
  jest.config.json
  scripts/webpack.scripts.js
  src/components/quickBar/QuickBarApp.tsx
Labels: help wanted

#2277 Drop unused attemptTemporaryAccess
  src/background/devtools/internal.ts
Labels: performance

#2288 Compress sound effects
  src/blocks/effects/sound.ts
  static/audio/applause.mp3
  static/audio/applause.wav
  static/audio/doorbell.mp3
  static/audio/doorbell.wav
  static/audio/magic-wand.mp3
  static/audio/magic-wand.wav
  static/audio/sad-trombone.mp3
  static/audio/sad-trombone.wav
  static/audio/success.mp3
  static/audio/success.wav
Labels: performance

#2287 Vendor `@rjsf/bootstrap-4`
  src/__mocks__/webextDetectPage.ts
  src/vendors/webextDetectPage.static.js
  webpack.config.js
Labels: performance

#2289 #2236: Fix external brick icon size
  src/devTools/editor/tabs/editTab/editorNode/EditorNode.module.scss
  src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx
Labels: bug

#2286 Always name dynamic imports
  .eslintrc.js
  src/Globals.d.ts
  src/blocks/effects/attachAutocomplete.ts
  src/blocks/effects/confetti.ts
  src/blocks/effects/exportCsv.ts
  src/blocks/effects/tour.ts
  src/blocks/readers/ImageExifReader.ts
  src/blocks/readers/PageMetadataReader.ts
  src/blocks/readers/PageSemanticReader.ts
  src/blocks/readers/frameworkReader.ts
  src/blocks/registry.ts
  src/blocks/renderers/markdown.ts
  src/blocks/transformers/jq.ts
  src/blocks/transformers/jsonPath.ts
  src/blocks/transformers/parseCsv.ts
  src/blocks/transformers/parseDate.ts
  src/blocks/transformers/parseUrl.ts
  src/permissions/patterns.ts
  src/runtime/renderers.ts
Labels: developer experience

#2275 #2188: Register quickbar with `chrome.commands`
  src/background.ts
  src/background/initBrowserCommands.ts
  src/components/quickBar/QuickBarApp.tsx
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/extensionPoints/quickBarExtension.tsx
  src/hooks/useEventListener.ts
  src/manifest.json
Labels: help wanted, do not merge

#2295 #2294: Improve quickbar style isolation
  src/components/quickBar/QuickBarApp.tsx
Labels: bug

#2312 #2308: Don't create multiple sidebars
  src/actionPanel/native.tsx
Labels: bug

#2300 Use existing components for brick and node lists in editor
  src/devTools/editor/ElementWizard.tsx
  src/devTools/editor/sidebar/DynamicEntry.tsx
  src/devTools/editor/sidebar/InstalledEntry.tsx
  src/devTools/editor/sidebar/Sidebar.tsx
  src/devTools/editor/tabs/editTab/editorNode/EditorNode.module.scss
  src/devTools/editor/tabs/editTab/editorNode/EditorNode.tsx
  src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.module.scss
  src/devTools/editor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
Labels: page editor

#2311 #2309: Fix IconSelector’s spacing
  src/icons/Icon.module.scss
  src/icons/Icon.tsx
  src/icons/IconSelector.tsx
Labels: bug

#1639 Minimal permission grant copy in the editor
  src/devTools/editor/components/Centered.tsx
  src/devTools/editor/panes/PermissionsPane.tsx
Labels: user experience

#2318 Align editor sidebar
  src/devTools/editor/sidebar/DynamicEntry.tsx
  src/devTools/editor/sidebar/Entry.module.scss
  src/devTools/editor/sidebar/Footer.module.scss
  src/devTools/editor/sidebar/InstalledEntry.tsx
  src/devTools/editor/sidebar/Sidebar.tsx
Labels: bug, page editor

#2317 #1005: Don't crash editor on chrome:// pages
  package-lock.json
  package.json
  src/devTools/editor/panes/PermissionsPane.tsx
  src/devTools/utils.ts
Labels: user experience

#2367 Add reload button to editor during development
  src/devTools/editor/sidebar/Sidebar.tsx
Labels: developer experience

#2276 Disable cross-boundary imports
  .eslintrc.js
Labels: user experience, performance

#2470 #2467: fix sharing modal
  src/components/form/Form.tsx
  src/core.ts
  src/devTools/editor/extensionPoints/base.ts
  src/devTools/editor/hooks/useCreate.ts
  src/devTools/editor/panes/save/saveHelpers.ts
  src/devTools/editor/tabs/editTab/EditTab.tsx
  src/options/pages/blueprints/BlueprintsPage.tsx
  src/options/pages/blueprints/installableUtils.ts
  src/options/pages/blueprints/useInstallableActions.tsx
  src/options/pages/blueprints/useInstallables.tsx
  src/options/pages/installed/ExtensionRows.tsx
  src/options/pages/installed/InstalledExtensionRow.tsx
  src/options/pages/installed/InstalledPage.tsx
  src/options/pages/installed/ShareExtensionModal.test.tsx
  src/options/pages/installed/ShareExtensionModal.tsx
  src/options/pages/installed/ShareLinkModal.tsx
  src/options/pages/installed/__snapshots__/ShareExtensionModal.test.tsx.snap
  src/options/pages/installed/installedPageSlice.ts
  src/options/pages/installed/installedPageTypes.ts
  src/runtime/runtimeUtils.ts
  src/store/extensionsSelectors.ts
  src/store/extensionsSlice.ts
  src/store/extensionsTypes.ts
Labels: release blocker

#2463 #2443: Preserve selection on quickbar toggle
  src/blocks/readers/SelectionReader.ts
  src/blocks/readers/registerReaders.ts
  src/components/quickBar/QuickBarApp.tsx
  src/contentScript/devTools.ts
  src/devTools/editor/extensionPoints/base.ts
  src/extensionPoints/contextMenu.ts
  src/extensionPoints/contextMenuReader.ts
  src/extensionPoints/quickBarExtension.tsx
  src/headers.ts
  src/nativeEditor/dynamic.ts
  src/utils/selectionController.ts
Labels: quickbar

#2468 #2466: Fix spacing in BrickHistory dropdowns
  src/options/pages/brickEditor/BrickHistory.tsx
Labels: bug

#2507 Fix dynamic entry highlight on hover in editor
  src/devTools/editor/sidebar/DynamicEntry.tsx
Labels: bug, page editor
