Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-03, with the labels that each got.

#2855 #2822: Show `SelectorSelector` suggestions even if the field is empty
  src/devTools/editor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
Labels: user experience, page editor, small

#2835 Fix SelectorSelectorWidget z-index
  src/devTools/editor/fields/SelectorSelectorWidget.module.scss
  src/devTools/editor/fields/SelectorSelectorWidget.tsx
Labels: bug

#2854 Fix Loader usage and subtle margin-collapsing bug
  src/components/Loader.tsx
  src/options/pages/blueprints/BlueprintsPage.tsx
Labels: bug, user experience, small

#2665 #2214: Notification improvements (timer, dismissal)
  src/utils/notify.module.scss
  src/utils/notify.tsx
Labels: user experience

#2862 Move entry points into their folders
  scripts/webpack.scripts.js
  src/background/background.ts
  src/contentScript/contentScript.scss
  src/contentScript/contentScript.ts
  src/development/headers.ts
  src/globals.d.ts
  src/options/options.html
  src/options/options.scss
  src/options/options.tsx
  src/pageEditor/pageEditor.html
  src/pageEditor/pageEditor.tsx
  src/pageScript/pageScript.ts
  src/sidebar.tsx
  src/sidebar/sidebar.html
  src/sidebar/sidebar.scss
  src/sidebar/sidebar.tsx
  src/tinyPages/PermissionsPopupApp.tsx
  src/tinyPages/devtools.html
  src/tinyPages/devtools.ts
  src/tinyPages/ephemeralForm.html
  src/tinyPages/ephemeralForm.scss
  src/tinyPages/ephemeralForm.tsx
  src/tinyPages/frame.css
  src/tinyPages/frame.html
  src/tinyPages/frame.ts
  src/tinyPages/permissionsPopup.html
  src/tinyPages/permissionsPopup.tsx
  webpack.config.js
Labels: developer experience, small

#2867 Automatically append error details to notifications
  src/background/contextMenus.ts
  src/contrib/google/sheets/FileWidget.tsx
  src/hooks/useDeployments.ts
  src/hooks/useRefresh.ts
  src/hooks/useUserAction.ts
  src/options/pages/activateExtension/useEnsurePermissions.ts
  src/options/pages/brickEditor/useSubmitBrick.ts
  src/options/pages/installed/ShareExtensionModal.tsx
  src/options/pages/marketplace/ActivateWizard.tsx
  src/options/pages/marketplace/useEnsurePermissions.ts
  src/options/pages/settings/FactoryResetSettings.tsx
  src/pageEditor/fields/SelectorSelectorWidget.tsx
  src/pageEditor/hooks/useAddElement.ts
  src/pageEditor/hooks/useCreate.ts
  src/pageEditor/hooks/useRemove.ts
  src/pageEditor/panes/save/useSavingWizard.ts
  src/services/useDependency.ts
  src/utils/notify.tsx
Labels: user experience, developer experience

#2895 Fix notification display
  src/pageEditor/ElementWizard.module.scss
  src/utils/notify.tsx
Labels: bug, priority

#2905 #2899: Avoid length-based filter in `inferSelectors`
  src/contentScript/nativeEditor/infer.test.tsx
  src/contentScript/nativeEditor/infer.ts
Labels: bug

#2901 #2900: Avoid duplicate reporting in menuItemExtension
  src/extensionPoints/menuItemExtension.ts
  src/extensionPoints/triggerExtension.ts
  src/telemetry/BackgroundLogger.ts
  src/utils/notify.tsx
  src/utils/pluralize.ts
Labels: bug

#2918 Allow disabling redux-logger via ENV
  src/options/store.ts
  src/pageEditor/store.ts
  webpack.config.js
Labels: developer experience

#2914 Add documentation to Append to Google Sheets brick metadata
  src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
  src/contrib/google/sheets/append.ts
Labels: documentation, marketplace

#2917 #2902: Throw BusinessError on `runBrick` if tab is closed or has no access
  src/background/executor.ts
  src/chrome.ts
  src/errors.ts
Labels: bug

#2934 Use Messenger for locator in useDependency
  src/background/deployment.test.ts
  src/background/deployment.ts
  src/services/useDependency.ts
Labels: bug

#2921 #2864 Add ability to set multiple match patterns for an extension point
  src/components/fields/schemaFields/BasicSchemaField.test.tsx
  src/components/fields/schemaFields/BasicSchemaField.tsx
  src/components/fields/schemaFields/ChildObjectField.test.tsx
  src/components/fields/schemaFields/SchemaField.test.tsx
  src/components/fields/schemaFields/SchemaFieldContext.tsx
  src/components/fields/schemaFields/getToggleOptions.tsx
  src/components/fields/schemaFields/widgets/ArrayWidget.tsx
  src/components/fields/schemaFields/widgets/BooleanWidget.tsx
  src/components/fields/schemaFields/widgets/IntegerWidget.tsx
  src/components/fields/schemaFields/widgets/NumberWidget.tsx
  src/components/fields/schemaFields/widgets/ObjectWidget.tsx
  src/components/fields/schemaFields/widgets/OmitFieldWidget.tsx
  src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx
  src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
  src/components/fields/schemaFields/widgets/TextWidget.tsx
  src/components/fields/schemaFields/widgets/UnsupportedWidget.tsx
  src/components/fields/schemaFields/widgets/WorkshopMessageWidget.tsx
  src/components/fields/schemaFields/widgets/registerDefaultWidgets.ts
  src/components/fields/schemaFields/widgets/templateToggleWidgetTypes.tsx
  src/components/fields/schemaFields/widgets/widgetsRegistry.ts
  src/components/formBuilder/FormEditor.test.tsx
  src/options/App.tsx
  src/options/pages/marketplace/OptionsBody.test.tsx
  src/options/pages/services/ServiceEditorModal.test.tsx
  src/pageEditor/Panel.tsx
  src/pageEditor/components/UrlMatchPatternWidget.tsx
  src/pageEditor/components/urlMatchPatternWidgetTypes.tsx
  src/pageEditor/extensionPoints/upgrade.ts
  src/pageEditor/fields/UrlMatchPatternField.stories.tsx
  src/pageEditor/fields/UrlMatchPatternField.tsx
  src/pageEditor/tabs/contextMenu/ContextMenuConfiguration.tsx
  src/pageEditor/tabs/editTab/EditTab.tsx
  src/pageEditor/tabs/effect/BlockConfiguration.test.tsx
  src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
  src/pageEditor/tabs/panel/PanelConfiguration.tsx
  src/pageEditor/tabs/quickBar/QuickBarConfiguration.tsx
  src/pageEditor/tabs/sidebar/Configuration.tsx
  src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
Labels: page editor, editor parity

#2947 #2924: page editor session tracking MVP
  src/components/documentBuilder/edit/ElementBlockEdit.tsx
  src/pageEditor/Panel.tsx
  src/pageEditor/hooks/useCreate.ts
  src/pageEditor/hooks/useRemove.ts
  src/pageEditor/hooks/useReset.ts
  src/pageEditor/panes/insert/useAddExisting.ts
  src/pageEditor/sidebar/DynamicEntry.tsx
  src/pageEditor/sidebar/InstalledEntry.tsx
  src/pageEditor/slices/sessionSelectors.ts
  src/pageEditor/slices/sessionSlice.ts
  src/pageEditor/store.ts
  src/pageEditor/tabs/editTab/useBlockPipelineActions.ts
Labels: observability

#2859 #2557 part 3 - Move blueprint options tab
  src/components/tabLayout/EditorTabLayout.tsx
  src/pageEditor/Editor.tsx
  src/pageEditor/ElementWizard.tsx
  src/pageEditor/hooks/useRemoveRecipe.ts
  src/pageEditor/panes/RecipePane.tsx
  src/pageEditor/panes/save/useRecipeSaver.ts
  src/pageEditor/sidebar/RecipeEntry.tsx
  src/pageEditor/sidebar/Sidebar.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/tabs/RecipeOptions.module.scss
  src/pageEditor/tabs/RecipeOptions.tsx
  src/pageEditor/tabs/blueprintOptionsTab/BlueprintOptionsTab.tsx
  src/services/api.ts
Labels: page editor, editor parity

#2915 #2870 Add ability to pass in an array variable or template for dropdown field options
  src/components/fields/schemaFields/widgets/ArrayWidget.tsx
  src/components/formBuilder/FormBuilder.test.tsx
  src/components/formBuilder/FormBuilder.tsx
  src/components/formBuilder/edit/FieldEditor.module.scss
  src/components/formBuilder/edit/FieldEditor.tsx
  src/components/formBuilder/edit/FormEditor.module.scss
  src/components/formBuilder/edit/FormEditor.test.tsx
  src/components/formBuilder/edit/FormEditor.tsx
  src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
  src/components/formBuilder/formBuilderHelpers.test.ts
  src/components/formBuilder/formBuilderHelpers.ts
  src/components/formBuilder/preview/FormPreview.test.tsx
  src/components/formBuilder/preview/FormPreview.tsx
  src/components/formBuilder/preview/FormPreviewBooleanField.module.scss
  src/components/formBuilder/preview/FormPreviewBooleanField.tsx
  src/components/formBuilder/preview/FormPreviewFieldTemplate.module.scss
  src/components/formBuilder/preview/FormPreviewFieldTemplate.tsx
  src/components/formBuilder/preview/FormPreviewSchemaField.tsx
  src/components/formBuilder/preview/FormPreviewStringField.module.scss
  src/components/formBuilder/preview/FormPreviewStringField.tsx
  src/components/formBuilder/preview/ImageCropWidgetPreview.tsx
  src/components/formBuilder/preview/SelectWidgetPreview.tsx
  src/components/formBuilder/preview/__snapshots__/FormPreview.test.tsx.snap
  src/pageEditor/fields/FormModalOptions.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/tabs/RecipeOptions.tsx
  src/pageEditor/tabs/blueprintOptionsTab/BlueprintOptionsTab.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/tests/formHelpers.tsx
Labels: page editor, editor parity

#2961 #2826: clarify promise rejection type check
  src/errors.ts
  src/testEnv.js
Labels: developer experience

#2866 Support Axios errors in `getErrorMessage` + add stack to non-primitive `ErrorEvent`s
  package-lock.json
  package.json
  src/background/proxyUtils.ts
  src/background/requests.ts
  src/components/errors/NetworkErrorDetail.tsx
  src/errors.ts
  src/hooks/useUserAction.ts
  src/options/pages/installed/ShareExtensionModal.tsx
  src/services/requestErrorUtils.test.ts
  src/services/requestErrorUtils.ts
  src/telemetry/reportUncaughtErrors.ts
  src/testEnv.js
  src/tests/errors.test.ts
  src/types/errorContract.ts
Labels: user experience

#2989 Fix type check for append google sheet row
  src/contrib/google/sheets/append.ts
Labels: bug, brick
