Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-08, with the labels that each got.

#3924 Preserve page editor state on error
  src/chrome.ts
  src/pageEditor/ErrorBanner.tsx
  src/pageEditor/context.ts
  src/pageEditor/hooks/useInstallState.ts
Labels: bug, user experience, page editor

#3921 Drop vendors bundle
  src/manifest.json
  src/options/options.html
  src/pageEditor/pageEditor.html
  src/sidebar/sidebar.html
  src/tinyPages/ephemeralForm.html
  src/tinyPages/permissionsPopup.html
  static/background.worker.js
  webpack.config.js
Labels: low priority

#3922 Reduce node polyfills
  src/vendors/process.js
  src/vendors/webextDetectPage.static.js
  webpack.config.js
  webpack.sharedConfig.js
Labels: low priority

#3943 #3724: Avoid screenshotting the quickbar
  src/blocks/transformers/screenshotTab.ts
  src/components/quickBar/QuickBarApp.tsx
Labels: bug, user experience

#3923 AddBlockModal: Drop redundant "Show details" text + use simple components
  src/components/addBlockModal/BlockGridItem.module.scss
  src/components/addBlockModal/BlockGridItem.tsx
  src/pageEditor/panes/EditorPane.test.tsx
Labels: page editor

#4029 #4027: Avoid duplicate error reporting in `ErrorBoundary`
  src/components/ErrorBoundary.tsx
  src/sidebar/ErrorBoundary.tsx
Labels: bug

#4030 #3940: Update "connection lost" banner message in editor
  src/pageEditor/context.ts
Labels: user experience, small

#4059 #4058: Fix contentScript loading logging
  src/contentScript/contentScript.ts
  src/errors/contextInvalidated.ts
Labels: developer experience

#4071 Removing unused customFields and customWidgets properties from SchemaFieldContext
  src/components/fields/schemaFields/SchemaFieldContext.tsx
  src/components/fields/schemaFields/schemaFieldTypes.ts
  src/pageEditor/fields/devtoolFieldOverrides.tsx
Labels: developer experience

#4098 Move messaging code out of `@/common`
  src/blocks/readers/window.ts
  src/common.ts
  src/contentScript/messenger/registration.ts
  src/contrib/pipedrive/readers.ts
  src/messaging/protocol.ts
Labels: small

#4057 Use pre-bound methods to avoid repetition
  src/contentScript/sidebarController.tsx
  src/extensionPoints/sidebarExtension.ts
  src/extensionPoints/triggerExtension.ts
  src/pageEditor/Locator.tsx
  src/services/locator.ts
Labels: developer experience, low priority

#4107 Add support for npm 8
  .npmrc
  package-lock.json
Labels: developer experience

#4110 Optimistically display Blueprints UI
  src/options/pages/blueprints/BlueprintsCard.tsx
  src/options/pages/blueprints/BlueprintsPage.tsx
Labels: user experience, performance

#4116 Ensure the options page doesn't derail the messenger
  package-lock.json
  package.json
Labels: bug, release blocker

#4123 Remove deprecated npm package
  package-lock.json
  package.json
Labels: developer experience

#4109 #4100: Defer loading of Google Fonts
  src/options/options.html
  src/sidebar/sidebar.html
  src/vendors/theme/app/app.scss
  src/vendors/theme/assets/styles/_fonts.scss
Labels: bug, user experience, performance

#4188 #4180: Open option page when clicking the browser action on the Web Store
  src/background/browserAction.ts
Labels: user experience, poc

#4194 Fix a couple of `reportError` mis-uses
  src/auth/ScopeSettings.tsx
  src/contrib/google/initGoogle.ts
  src/options/pages/services/ServiceEditorModal.tsx
Labels: developer experience, low priority, small
