Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-02, with the labels that each got.

#2426 #2235: Limit communication to tabs with access
  src/background.ts
  src/background/activeTab.ts
  src/background/executor.ts
  src/background/navigation.ts
  src/background/util.ts
  src/contentScript/executor.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/devTools/protocol.ts
  src/utils/permissions.ts
Labels: bug

#2608 #580: Improve error logging of uncaught errors
  src/action.tsx
  src/actionPanel/actionPanelSlice.ts
  src/actionPanel/native.tsx
  src/actionPanel/protocol.tsx
  src/auth/ScopeSettings.tsx
  src/background.ts
  src/background/browserAction.ts
  src/background/contextMenus.ts
  src/background/deployment.ts
  src/blocks/renderers/customForm.tsx
  src/blocks/transformers/ephemeralForm/formTransformer.ts
  src/components/ErrorBoundary.tsx
  src/contentScript/lifecycle.ts
  src/devTools/context.ts
  src/devTools/editor/fields/ConfigErrorBoundary.tsx
  src/devTools/editor/hooks/useAddElement.ts
  src/devTools/editor/hooks/useCreate.ts
  src/devTools/editor/hooks/useRemove.ts
  src/devTools/editor/hooks/useReset.ts
  src/devTools/editor/panes/insert/GenericInsertPane.tsx
  src/devTools/editor/panes/insert/useAddExisting.ts
  src/devTools/editor/sidebar/InstalledEntry.tsx
  src/ephemeralForm.tsx
  src/extensionContext.ts
  src/extensionPoints/contextMenu.ts
  src/extensionPoints/menuItemExtension.ts
  src/extensionPoints/quickBarExtension.tsx
  src/extensionPoints/triggerExtension.ts
  src/hooks/useBlockOptions.ts
  src/hooks/useNotifications.ts
  src/hooks/useReportError.ts
  src/options.tsx
  src/options/pages/UpdateBanner.tsx
  src/options/pages/blueprints/useInstallableActions.ts
  src/options/pages/installed/InstalledPage.tsx
  src/options/pages/services/ServiceEditorModal.tsx
  src/permissionsPopup.tsx
  src/popups/PermissionsPopup.tsx
  src/store/extensionsSlice.ts
  src/telemetry/logging.ts
  src/telemetry/reportUncaughtErrors.ts
  src/telemetry/rollbar.ts
Labels: developer experience

#2617 Fix error in useInstallState
  src/devTools/editor/hooks/useInstallState.ts
Labels: bug

#2627 Hide Messenger logging by default
  package-lock.json
  package.json
  webpack.config.js
Labels: developer experience

#2621 Show background errors on badge
  src/telemetry/reportUncaughtErrors.ts
Labels: developer experience

#2609 #1759: Never ask permission to access pixiebrix.com
  package-lock.json
  package.json
  src/utils/permissions.ts
Labels: user experience

#2618 Use global permission events to re-connect editor
  src/devTools/context.ts
  src/devTools/editor/panes/PermissionsPane.tsx
  src/devTools/protocol.ts
  src/tests/factories.ts
Labels: user experience

#2625 Swallow some errors
  src/errors.ts
  src/telemetry/reportUncaughtErrors.ts
  src/telemetry/rollbar.ts
Labels: developer experience

#2587 #2586: Retry connecting to current tab + change tabState error to banner
  src/background/util.ts
  src/devTools/Panel.tsx
  src/devTools/context.ts
Labels: user experience

#2664 Disable some lint rules on mocks and stories
  .eslintrc.js
  __mocks__/connected-react-router.js
  __mocks__/fit-textarea.js
  __mocks__/react-redux.js
  __mocks__/react-toast-notifications.js
  src/__mocks__/browserMocks.ts
  src/__mocks__/svgAsComponentMock.js
Labels: developer experience

#2660 #627: Immediately detect when the context is invalidated
  src/devTools/ErrorBanner.tsx
  src/devTools/context.ts
Labels: user experience, developer experience, page editor

#2655 Move errors badge code to development folder
  src/background.ts
  src/development/darkMode.js
  src/development/errorsBadge.ts
  src/telemetry/reportUncaughtErrors.ts
Labels: developer experience

#2689 #2659: Avoid duplicate registration in context menus
  src/extensionPoints/contextMenu.ts
Labels: bug

#2663 Center GridLoader everywhere
  src/actionPanel/ActionPanelApp.tsx
  src/actionPanel/FormBody.tsx
  src/actionPanel/PanelBody.tsx
  src/blocks/transformers/ephemeralForm/EphemeralForm.tsx
  src/components/Loader.tsx
  src/components/documentBuilder/render/ListElement.tsx
  src/components/fields/schemaFields/ChildObjectField.tsx
  src/components/jsonTree/JsonTree.tsx
  src/devTools/Editor.tsx
  src/devTools/Locator.tsx
  src/devTools/Panel.tsx
  src/devTools/editor/fields/DatabaseCreateModal.tsx
  src/devTools/editor/panes/save/LoadingDataModal.tsx
  src/devTools/editor/panes/save/SavingInProgressModal.tsx
  src/devTools/editor/sidebar/Sidebar.tsx
  src/devTools/editor/tabs/RunLogCard.tsx
  src/devTools/editor/tabs/blueprintOptionsTab/BlueprintOptionsTab.tsx
  src/devTools/editor/tabs/effect/BlockConfiguration.tsx
  src/devTools/editor/tabs/effect/BlockPreview.tsx
  src/devTools/editor/tabs/effect/ExtensionPointPreview.tsx
  src/layout/Page.tsx
  src/options/App.tsx
  src/options/pages/SetupPage.tsx
  src/options/pages/brickEditor/BrickLogs.tsx
  src/options/pages/brickEditor/EditPage.tsx
  src/options/pages/brickEditor/referenceTab/BrickReference.tsx
  src/options/pages/installed/InstalledExtensionRow.tsx
  src/options/pages/installed/OnboardingPage.tsx
  src/options/pages/marketplace/ActivateBlueprintPage.tsx
  src/options/pages/marketplace/PermissionsBody.tsx
  src/options/pages/settings/LoggingSettings.tsx
  src/pages/marketplace/MarketplacePage.tsx
Labels: low priority, small

#2677 Avoid side effects when importing modules
  .eslintrc.js
  src/action.tsx
  src/actionPanel/messenger/registration.ts
  src/background.ts
  src/background/browserAction.ts
  src/background/contextMenus.ts
  src/background/firefoxCompat.ts
  src/background/initContextMenus.ts
  src/background/locator.ts
  src/background/messenger/registration.ts
  src/contentScript.ts
  src/contentScript/messenger/registration.ts
  src/contrib/editors.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/devTools/Panel.tsx
  src/devTools/editor/panes/save/saveHelpers.test.ts
  src/devTools/messenger/registration.ts
  src/devtoolsPanel.tsx
  src/options/App.tsx
Labels: developer experience, small

#2690 #2659: Allow empty context menu item title
  src/extensionPoints/contextMenu.ts
Labels: bug, small

#2601 Make editor layout more flexible
  src/devTools/Editor.module.scss
  src/devTools/Editor.tsx
  src/devTools/Panel.scss
  src/devTools/Panel.tsx
  src/devTools/editor/ElementWizard.module.scss
  src/devTools/editor/ElementWizard.tsx
  src/devTools/editor/components/ToggleField.tsx
  src/devTools/editor/tabs/editTab/EditTab.module.scss
  src/devtoolsPanel.html
Labels: bug

#2706 Only enforce `filenames/match-exported` on components and hooks
  .eslintrc.js
  .storybook/main.js
  src/__mocks__/browserMocks.ts
  src/actionPanel/messenger/registration.ts
  src/background/activeTab.ts
  src/background/browserAction.ts
  src/background/contextMenus.ts
  src/background/deployment.ts
  src/background/executor.ts
  src/background/firefoxCompat.ts
  src/background/iframes.ts
  src/background/installer.ts
  src/background/locator.ts
  src/background/messenger/registration.ts
  src/background/navigation.ts
  src/baseRegistry.ts
  src/blocks/renderers/dataTable.ts
  src/contentScript/messenger/registration.ts
  src/contrib/editors.ts
  src/contrib/zapier/PushOptions.tsx
  src/devTools/Editor.tsx
  src/devTools/editor/extensionPoints/menuItem.ts
  src/devTools/editor/extensionPoints/panel.ts
  src/devTools/editor/extensionPoints/quickBar.tsx
  src/devTools/editor/panes/NoExtensionSelectedPane.tsx
  src/devTools/messenger/registration.ts
  src/frameworks/adapters.ts
  src/frameworks/contrib/angularjs.ts
  src/frameworks/contrib/ember.ts
  src/frameworks/contrib/react.ts
  src/frameworks/contrib/vue.ts
  src/options/pages/brickEditor/Editor.tsx
  src/options/pages/brickEditor/SharingTable.tsx
  src/services/locator.ts
Labels: developer experience, small

#2784 Reduce watch script noise
  webpack.sharedConfig.js
Labels: developer experience

#2781 Improve loading error experience
  static/loadingScreen.js
Labels: user experience, developer experience

#2780 Fix padding in sidebar ephemeral form
  src/blocks/transformers/ephemeralForm/EphemeralForm.tsx
Labels: bug

#2773 Fix height of editor sidebar collapsing animation
  src/devTools/editor/sidebar/Sidebar.module.scss
Labels: bug, small

#2794 Rename "script.ts" to "pageScript.ts" for consistency
  src/contentScript/lifecycle.ts
  src/manifest.json
  src/pageScript.ts
  webpack.config.js
Labels: developer experience, small

#2775 Continue saving while asking for permissions
  src/devTools/editor/hooks/useCreate.ts
Labels: user experience, performance, small

#2819 #2818: fix shared state NPE
  src/blocks/effects/pageState.test.ts
  src/blocks/effects/pageState.ts
Labels: bug

#2793 Replace luxon with tree-shakeable date-fns
  package-lock.json
  package.json
  src/utils/timeUtils.ts
Labels: performance, small

#2779 Avoid wonky sizing of Settings page in Options
  src/options/pages/settings/AdvancedSettings.module.scss
  src/options/pages/settings/AdvancedSettings.tsx
  src/options/pages/settings/SettingsPage.module.scss
  src/options/pages/settings/SettingsPage.tsx
Labels: user experience, small
