Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-06, with the labels that each got.

#3546 #3545: fix anchoring to stable selectors
  src/contentScript/nativeEditor/selectorInference.test.ts
  src/contentScript/nativeEditor/selectorInference.ts
Labels: bug, release blocker

#3512 Avoid saving invalid service URLs
  package-lock.json
  src/options/pages/settings/AdvancedSettings.tsx
Labels: bug, developer experience, low priority

#3609 #3597: Ensure that long words don't break the UI
  src/vendors/overrides.scss
Labels: bug, small

#3610 #2783: Hide page editor sidebar while adding a new extension
  src/pageEditor/Editor.tsx
  src/pageEditor/sidebar/Sidebar.tsx
Labels: user experience, low priority, small

#3608 #3574: Fix extra scrollbar outside the brick modal
  src/components/brickModal/BrickModal.module.scss
Labels: bug, page editor, small

#3639 Data panel button to copy JSON
  src/components/jsonTree/JsonTree.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/FoundationDataPanel.test.tsx.snap
  src/pageEditor/tabs/effect/BlockPreview.tsx
  src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
Labels: user experience, developer experience

#3643 #3638 Fix table headers on log viewer
  src/components/errors/getErrorDetails.tsx
  src/components/logViewer/LogTable.module.scss
  src/components/logViewer/LogTable.tsx
  src/components/logViewer/__snapshots__/LogCard.test.tsx.snap
Labels: bug, page editor

#3642 #3491 Editor node layout - follow up bug fixes and tweaks
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/editTab/editTabTypes.ts
  src/pageEditor/tabs/editTab/editTabVariables.scss
  src/pageEditor/tabs/editTab/editorNodeLayout/EditorNodeLayout.tsx
  src/pageEditor/tabs/editTab/editorNodes/OutputKeyView.module.scss
  src/pageEditor/tabs/editTab/editorNodes/OutputKeyView.tsx
  src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.module.scss
  src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.tsx
  src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.module.scss
  src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx
  src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.module.scss
  src/pageEditor/tabs/editTab/editorNodes/PipelineOffsetView.tsx
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.module.scss
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNodeContent.module.scss
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNodeContent.tsx
  src/pageEditor/tabs/editTab/useBlockPipelineActions.ts
Labels: page editor
