Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-12, with the labels that each got.

#4776 #4732: save refreshed token in token cache
  src/background/auth.ts
  src/background/partnerIntegrations.test.ts
  src/background/partnerIntegrations.ts
Labels: bug

#4824 #4730: rethrow non-nunjucks error in sandbox
  src/sandbox/messenger/executor.test.ts
  src/sandbox/messenger/executor.ts
Labels: bug

#4829 Small code fixes accumulated over time
  src/background/contentScript.ts
  src/blocks/effects/attachAutocomplete.ts
  src/blocks/effects/confetti.ts
  src/blocks/effects/tour.ts
  src/blocks/util.ts
  src/components/errors/getErrorDetails.test.tsx
  src/components/fields/schemaFields/widgets/CssClassWidget.tsx
  src/components/form/widgets/createMenuListWithAddButton.tsx
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/nativeEditor/elementPicker.ts
  src/contentScript/nativeEditor/selectorInference.ts
  src/contentScript/pageEditor.ts
  src/contrib/uipath/LocalProcessOptions.tsx
  src/extensionPoints/triggerExtension.ts
  src/globals.d.ts
  src/options/Navbar.tsx
  src/options/Sidebar.tsx
  src/options/SidebarLink.tsx
  src/options/pages/blueprints/modals/ConvertToRecipeModal.test.tsx
  src/options/pages/blueprints/utils/installableUtils.test.ts
  src/options/pages/blueprints/utils/installableUtils.ts
  src/pageEditor/protocol.ts
  src/sidebar/messenger/registration.ts
  src/utils/expectContext.ts
  src/utils/injectStylesheet.tsx
  src/utils/jqueryHack.ts
Labels: developer experience

#4837 Restore `@/icons/list` mock
  src/__mocks__/@/icons/list.ts
Labels: developer experience

#4836 Import CSS variables instead of depending on global injection
  .storybook/main.js
  src/components/fields/schemaFields/widgets/varPopup/SourceLabel.module.scss
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.module.scss
  src/themes/colors.scss
  webpack.config.js
Labels: developer experience

#4840 Don't show a broken editor on the options page
  src/pageEditor/EditorContent.tsx
  src/pageEditor/EditorLayout.tsx
  src/pageEditor/NonScriptablePage.module.scss
  src/pageEditor/NonScriptablePage.tsx
  src/pageEditor/panes/NonScriptablePage.test.tsx
  src/pageEditor/panes/__snapshots__/NonScriptablePage.test.tsx.snap
Labels: bug, user experience

#4839 #4223: Stop `LoadingDataModal` leak on page editor launch /2
  src/pageEditor/panes/save/LoadingDataModal.tsx
  src/pageEditor/sidebar/modals/CreateRecipeModal.tsx
  src/pageEditor/sidebar/modals/SaveAsNewRecipeModal.tsx
Labels: bug, user experience

#4838 #975: Switch from node-sass to dart-sass
  .storybook/main.js
  package-lock.json
  package.json
  src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.module.scss
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.module.scss
  src/vendors/theme/assets/styles/components/loaders/_variables.scss
  webpack.config.js
Labels: dependencies, low priority

#4890 #4863: Clarify `ensureContentScript` logging
  src/background/contentScript.ts
Labels: small

#4886 #4436: Manually update every Storybook dependency at once
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies

#4900 Bump jQuery to 3.6.3
  package-lock.json
  package.json
  src/contentScript/contentScript.ts
  src/pageScript/pageScript.ts
  src/utils/jqueryHack.ts
Labels: dependencies

#4904 Add analysis rule to check regex pattern validity
  src/analysis/analysisVisitors/regexAnalysis.ts
  src/analysis/analysisVisitors/regexAnalysisTest.test.ts
  src/pageEditor/analysisManager.ts
Labels: analysis

#4902 #4899: disable autosuggest in service configuration
  src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
  src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx
Labels: bug

#4889 #4694: Move more `pageScript`-specific code into its folder
  .eslintrc.js
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor.ts
  src/contentScript/pageEditor/dynamic.ts
  src/contentScript/pageEditor/elementPicker.ts
  src/contentScript/pageEditor/insertButton.tsx
  src/contentScript/pageEditor/insertPanel.tsx
  src/contentScript/pageEditor/types.ts
  src/pageEditor/extensionPoints/contextMenu.tsx
  src/pageEditor/extensionPoints/elementConfig.ts
  src/pageEditor/extensionPoints/formStateTypes.ts
  src/pageEditor/extensionPoints/menuItem.ts
  src/pageEditor/extensionPoints/panel.ts
  src/pageEditor/extensionPoints/quickBar.tsx
  src/pageEditor/extensionPoints/sidebar.tsx
  src/pageEditor/extensionPoints/trigger.tsx
  src/pageEditor/fields/SelectorSelectorWidget.test.ts
  src/pageEditor/fields/SelectorSelectorWidget.tsx
  src/pageEditor/sidebar/SidebarExpanded.tsx
  src/pageEditor/sidebar/arrangeElements.ts
  src/pageEditor/utils.ts
  src/pageScript/frameworks.ts
  src/pageScript/frameworks/adapters.ts
  src/pageScript/frameworks/component.ts
  src/pageScript/frameworks/contrib/angularjs.ts
  src/pageScript/frameworks/contrib/ember.ts
  src/pageScript/frameworks/contrib/react.ts
  src/pageScript/frameworks/contrib/vue.ts
  src/pageScript/frameworks/dom.ts
  src/pageScript/frameworks/errors.ts
  src/pageScript/frameworks/scanner.ts
  src/pageScript/pageScript.ts
  src/pageScript/protocol.ts
  src/testUtils/factories.ts
  src/utils.ts
  src/utils/inference/markupInference.test.tsx
  src/utils/inference/markupInference.ts
  src/utils/inference/selectorInference.test.ts
  src/utils/inference/selectorInference.ts
  src/utils/selectionController.ts
Labels: developer experience, small

#4909 #4914: Avoid wonky sizing in Options
  src/__snapshots__/Storyshots.test.js.snap
  src/components/Centered.tsx
  src/layout/Page.tsx
  src/options/options.tsx
  src/options/pages/settings/SettingsPage.module.scss
  src/options/pages/settings/SettingsPage.tsx
  src/options/pages/workshop/WorkshopPage.tsx
  src/pageEditor/panes/PermissionsPane.tsx
  src/pageEditor/panes/__snapshots__/PermissionsPane.test.tsx.snap
  src/utils/layout.scss
Labels: user experience
