Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-11, with the labels that each got.

#4581 #4525: Avoid double scrollbar in `AddBlockModal`
  src/__mocks__/@xobotyi/scrollbar-width.js
  src/components/addBlockModal/AddBlockModal.module.scss
  src/components/addBlockModal/AddBlockModal.tsx
  src/components/addBlockModal/TagList.module.scss
  src/components/addBlockModal/__snapshots__/AddBlockModal.test.tsx.snap
Labels: bug

#4687 Pin node to 18.x
  package-lock.json
Labels: dependencies

#4703 Avoid duplicate Storybook CI run
  .github/workflows/storybook.yml
Labels: developer experience, low priority
