Repository pixiebrix/pixiebrix-extension, pull requests merged in 2022-04, with the labels that each got.

#3016 Add `eslint-plugin-jest`
  .eslintrc.js
  jest.config.json
  package-lock.json
  package.json
  src/background/deployment.test.ts
  src/background/proxyService.test.ts
  src/blocks/available.test.ts
  src/blocks/effects/getPageState.ts
  src/blocks/effects/pageState.test.ts
  src/blocks/registry.test.ts
  src/blocks/transformers/blockFactory.test.js
  src/components/documentBuilder/documentTree.test.tsx
  src/components/documentBuilder/render/DocumentContext.tsx
  src/components/errors/getErrorDetails.test.tsx
  src/components/fields/schemaFields/BasicSchemaField.test.tsx
  src/components/fields/schemaFields/SchemaField.test.tsx
  src/components/form/FieldTemplate.test.tsx
  src/components/formBuilder/FormBuilder.test.tsx
  src/components/formBuilder/edit/FormEditor.test.tsx
  src/components/formBuilder/preview/FormPreview.test.tsx
  src/contentScript/pageEditor.ts
  src/contentScript/pipelineProtocol.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/errors.test.ts
  src/options/pages/blueprints/modals/ShareExtensionModal.test.tsx
  src/options/pages/blueprints/onboardingView/OnboardingView.test.tsx
  src/options/pages/blueprints/utils/installableUtils.test.ts
  src/options/pages/brickEditor/referenceTab/BrickDetail.test.tsx
  src/options/pages/services/ServiceEditorModal.test.tsx
  src/pageEditor/extensionPoints/upgrade.test.ts
  src/pageEditor/panes/save/RecipeConfigurationModal.test.tsx
  src/pageEditor/panes/save/SaveExtensionWizard.test.tsx
  src/pageEditor/panes/save/SavingExtensionModal.test.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/useSavingWizard.test.tsx
  src/pageEditor/sidebar/arrangeElements.test.ts
  src/pageEditor/tabs/effect/AdvancedLinks.test.tsx
  src/pageEditor/tabs/effect/BlockConfiguration.test.tsx
  src/pageEditor/validation/applyTraceBlockError.test.ts
  src/pageEditor/validation/applyTraceInputError.test.ts
  src/pageEditor/validation/validateOutputKey.test.ts
  src/pageEditor/validation/validateRenderers.test.ts
  src/pageEditor/validation/validateStringTemplates.test.ts
  src/runtime/pipelineTests/deploymentAlert.test.ts
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/runtime/pipelineTests/trace.test.ts
  src/runtime/reducePipeline.ts
  src/sidebar/DefaultContent.test.tsx
  src/sidebar/PanelBody.tsx
  src/testUtils/factories.ts
  src/testUtils/formHelpers.tsx
  src/testUtils/readme.md
  src/testUtils/testAfterEnv.js
  src/testUtils/testEnv.js
  src/testUtils/testHelpers.tsx
  src/testUtils/testItRenders.tsx
  src/utils/ConsoleLogger.ts
Labels: developer experience

#3061 #3021: Wrap invalid selector errors into BusinessErrors
  src/errors.ts
  src/helpers.ts
  src/vendors/initialize.js
Labels: developer experience

#3119 Fix the search input label width in the data panel
  src/components/jsonTree/JsonTree.tsx
Labels: user experience

#3214 Use consistent react-router versions
  package-lock.json
  package.json
Labels: bug
