Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-04, with the labels that each got.

#5477 #5476: add all_urls as optional permission
  src/analysis/analysisVisitors/extensionUrlPatternAnalysis.ts
  src/manifest.json
Labels: customer

#5501 Automatically scroll to Quick Bar shortcut entry on shortcuts screen
  src/chrome.test.ts
  src/chrome.ts
  src/extensionConsole/pages/activateRecipe/PermissionsBody.tsx
  src/pageEditor/extensionPoints/quickBar.tsx
  src/sidebar/activateRecipe/ActivateRecipeInputs.tsx
Labels: user experience

#5500 #5473: add installStarterBlueprints to external messenger api
  src/background/messenger/api.ts
  src/background/messenger/external/_implementation.ts
  src/background/messenger/external/api.ts
  src/background/messenger/registration.ts
  src/background/starterBlueprints.test.ts
  src/background/starterBlueprints.ts
Labels: bug

#5511 #5510: revert marking `type` as required for alert brick
  src/blocks/effects/alert.test.ts
  src/blocks/effects/alert.ts
Labels: bug, release blocker

#5466 Add eslint local plugin and `data-testid` rule
  .eslintrc.js
  eslint-plugin-pixiebrix-extension/index.js
  eslint-plugin-pixiebrix-extension/rules/noInvalidDataTestId.js
  eslint-plugin-pixiebrix-extension/rules/noInvalidDataTestId.test.js
  package-lock.json
  package.json
  src/blocks/transformers/temporaryInfo/EphemeralPanel.test.tsx
  src/blocks/transformers/temporaryInfo/__snapshots__/EphemeralPanel.test.tsx.snap
  src/extensionConsole/pages/onboarding/partner/ControlRoomTokenForm.tsx
Labels: developer experience, low priority

#5550 #5549: track blueprint id for temporary panels
  src/blocks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/blocks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
  src/blocks/transformers/temporaryInfo/EphemeralPanel.tsx
  src/blocks/transformers/tourStep/tourStep.ts
  src/components/documentBuilder/render/BlockElement.tsx
  src/contentScript/pageEditor.ts
  src/pageEditor/tabs/effect/ConfigurationTitle.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/sidebar/PanelBody.test.tsx
  src/sidebar/PanelBody.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/types.ts
  src/testUtils/factories.ts
Labels: bug, runtime

#5542 upload cws version of extension to s3 in rainforestqa workflow
  .github/workflows/rainforestqa.yml
Labels: infrastructure

#5543 #5512: use abort signal for cancelling pending quickbar action generators
  src/blocks/effects/AddQuickBarAction.test.ts
  src/blocks/effects/AddQuickBarAction.tsx
  src/components/quickBar/QuickBarApp.test.tsx
  src/components/quickBar/quickBarRegistry.ts
  src/components/quickBar/quickbarTypes.ts
  src/components/quickBar/useActionGenerators.test.tsx
  src/components/quickBar/useActionGenerators.ts
  src/extensionPoints/quickBarProviderExtension.tsx
  src/hooks/useDebouncedEffect.ts
  src/hooks/useUndo.ts
Labels: user experience, runtime

#5505 #5453: fix repeat notifications and trigger runs on page editor save
  src/__mocks__/@/telemetry/logging.ts
  src/__mocks__/@/utils/injectScriptTag.ts
  src/background/removeExtensionForEveryTab.ts
  src/blocks/transformers/component/TableReader.test.ts
  src/blocks/transformers/controlFlow/ForEach.test.ts
  src/blocks/transformers/controlFlow/ForEachElement.test.ts
  src/blocks/transformers/controlFlow/IfElse.test.ts
  src/blocks/transformers/controlFlow/Retry.test.ts
  src/blocks/transformers/controlFlow/TryExcept.test.ts
  src/blocks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/components/documentBuilder/documentTree.test.tsx
  src/contentScript/lifecycle.test.ts
  src/contentScript/lifecycle.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/dynamic.ts
  src/extensionPoints/contextMenu.ts
  src/extensionPoints/menuItemExtension.test.ts
  src/extensionPoints/menuItemExtension.ts
  src/extensionPoints/panelExtension.ts
  src/extensionPoints/quickBarExtension.test.ts
  src/extensionPoints/quickBarExtension.tsx
  src/extensionPoints/quickBarProviderExtension.tsx
  src/extensionPoints/quickbarProviderExtension.test.ts
  src/extensionPoints/sidebarExtension.ts
  src/extensionPoints/tourExtension.test.ts
  src/extensionPoints/tourExtension.ts
  src/extensionPoints/triggerExtension.test.ts
  src/extensionPoints/triggerExtension.ts
  src/extensionPoints/types.ts
  src/pageEditor/extensionPoints/base.ts
  src/pageEditor/hooks/useSaveExtension.ts
  src/pageEditor/hooks/useSaveRecipe.ts
  src/pageEditor/hooks/useUpsertFormElement.ts
  src/pageEditor/panes/save/useSavingWizard.test.tsx
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/permissionsHelpers.ts
  src/pageEditor/sidebar/modals/CreateRecipeModal.tsx
  src/registry/internal.ts
  src/runtime/pipelineTests/autoescape.test.ts
  src/runtime/pipelineTests/component.test.ts
  src/runtime/pipelineTests/conditional.test.ts
  src/runtime/pipelineTests/deferExpression.test.ts
  src/runtime/pipelineTests/deploymentAlert.test.ts
  src/runtime/pipelineTests/implicitDataFlow.test.ts
  src/runtime/pipelineTests/options.test.ts
  src/runtime/pipelineTests/outputKey.test.ts
  src/runtime/pipelineTests/pipelineExpression.test.ts
  src/runtime/pipelineTests/root.test.ts
  src/runtime/pipelineTests/serviceContext.test.ts
  src/runtime/pipelineTests/templateEngine.test.ts
  src/runtime/pipelineTests/trace.test.ts
  src/runtime/pipelineTests/validateInput.test.ts
Labels: bug, page editor, runtime

#5557 #5556: fix nested brick permissions calculation and use native clipboard API
  src/analysis/analysisVisitors/blockIdVisitor.ts
  src/blocks/effects/clipboard.test.ts
  src/blocks/effects/clipboard.ts
  src/blocks/util.ts
  src/components/AsyncButton.tsx
  src/components/jsonTree/JsonTree.tsx
  src/components/jsonTree/treeHooks.tsx
  src/extensionConsole/pages/blueprints/modals/shareModals/ActivationLink.tsx
  src/extensionConsole/pages/brickEditor/referenceTab/BrickDetail.tsx
  src/extensionConsole/pages/services/ZapierModal.tsx
  src/extensionPoints/contextMenu.ts
  src/extensionPoints/menuItemExtension.ts
  src/extensionPoints/panelExtension.ts
  src/extensionPoints/quickBarExtension.tsx
  src/extensionPoints/quickBarProviderExtension.tsx
  src/extensionPoints/sidebarExtension.ts
  src/extensionPoints/tourExtension.ts
  src/extensionPoints/triggerExtension.ts
  src/permissions/index.ts
  src/testUtils/factories.ts
  src/types/blockTypes.ts
  src/types/extensionPointTypes.ts
  src/utils/clipboardUtils.ts
Labels: bug

#5531 #5499 Mod List Filter
  src/components/quickBar/QuickBarResults.tsx
  src/pageEditor/sidebar/Sidebar.module.scss
  src/pageEditor/sidebar/SidebarExpanded.tsx
  src/pageEditor/sidebar/arrangeElements.test.ts
  src/pageEditor/sidebar/arrangeElements.ts
Labels: user experience

#5552 #5527: Fix faulty regex
  .github/workflows/rainforestqa.yml
Labels: bug, github_actions

#5567 #5566: don't show both loader and content while panel content is re-fetching
  src/sidebar/PanelBody.tsx
Labels: bug, user experience

#5602 #5600: revert singleton IDB connection PR; use fresh IDB connection for each operation
  src/background/telemetry.ts
  src/extensionConsole/pages/settings/StorageSettings.tsx
  src/registry/localRegistry.ts
  src/telemetry/logging.ts
  src/telemetry/trace.ts
Labels: performance

#5604 #5603: fix lifecycle navigation bug for SPAs
  src/contentScript/lifecycle.ts
  src/extensionPoints/menuItemExtension.ts
Labels: bug, runtime

#5609 Fix regex to capture apple emoji variation characters in quickbar
  src/utils/stringUtils.test.ts
  src/utils/stringUtils.ts
Labels: bug

#5626 #5625 Bug fix - Fix quick bar shortcut display in the activate side panel UI
  src/__snapshots__/Storyshots.test.js.snap
  src/extensionConsole/components/IDBErrorDisplay.stories.tsx
  src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx
  src/sidebar/activateRecipe/ActivateRecipePanel.tsx
  src/sidebar/activateRecipe/__snapshots__/ActivateRecipePanel.test.tsx.snap
Labels: bug, release blocker

#5628 #5627 Fix one-click activation with built-in services
  src/activation/useWizard.ts
  src/sidebar/activateRecipe/ActivateRecipePanel.tsx
  src/sidebar/activateRecipe/RequireRecipe.tsx
Labels: release blocker
