Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-08, with the labels that each got.

#6199 Fix No Mods Pane copy in Page Editor
  src/pageEditor/EditorContent.tsx
  src/pageEditor/panes/NoModSelectedPane.tsx
  src/pageEditor/panes/NoModsPane.tsx
  src/pageEditor/panes/RecipePane.tsx
Labels: page editor, papercut

#6207 #6174: mark quickbar/sidebar starter bricks as unavailable in iframes
  src/components/quickBar/QuickBarApp.tsx
  src/contentScript/lifecycle.ts
  src/starterBricks/quickBarExtension.tsx
  src/starterBricks/quickBarProviderExtension.tsx
  src/starterBricks/sidebarExtension.ts
  src/types/starterBrickTypes.ts
Labels: performance, runtime

#6243 #6231: ban uses of crypto random uuid
  .eslintrc.js
  jest.config.json
  src/contentScript/sidebarDomControllerLite.ts
  src/development/cryptoNodePolyfill.js
  src/development/headers.ts
Labels: customer

#6244 defaults getSettingsState to the settingsSlice initialState
  src/store/settingsStorage.ts
Labels: bug

#6247 Bugfix: click through tab decoration
  src/sidebar/Tabs.module.scss
Labels: bug

#6252 #6251: add disableBrowserWarning managed storage option
  src/extensionConsole/pages/BrowserBanner.test.tsx
  src/extensionConsole/pages/BrowserBanner.tsx
  src/extensionConsole/pages/__snapshots__/BrowserBanner.test.tsx.snap
  src/store/enterprise/managedStorageTypes.ts
  static/managedStorageSchema.json
Labels: customer, enterprise

#6254 #6253: add new starter bricks on SPA navigation
  src/contentScript/lifecycle.ts
Labels: bug, regression

#6333 #6332: add element visibility flag
  src/bricks/readers/ElementReader.test.ts
  src/bricks/readers/ElementReader.ts
  src/utils/domUtils.ts
Labels: enhancement, customer
