Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-03, with the labels that each got.

#5308 #5303: fix change handler for GSheets fields
  src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
  src/contrib/google/sheets/LookupSpreadsheetOptions.tsx
  src/contrib/google/sheets/useOnChangeEffect.test.ts
  src/contrib/google/sheets/useOnChangeEffect.ts
Labels: bug, release blocker

#5307 #5305: add test coverage that bot search in Page Editor varies by workspaceType
  src/contrib/automationanywhere/aaApi.test.ts
Labels: developer experience, low priority

#5311 Fix GSheets tab name field defaulting
  src/__snapshots__/Storyshots.test.js.snap
  src/components/ServiceAuthSelector.tsx
  src/components/fields/schemaFields/fieldInputMode.ts
  src/components/fields/schemaFields/fieldTypeCheckers.test.ts
  src/components/fields/schemaFields/fieldTypeCheckers.ts
  src/components/fields/schemaFields/widgets/ServiceSelectWidget.tsx
  src/components/fields/schemaFields/widgets/ServiceWidget.test.tsx
  src/components/fields/schemaFields/widgets/ServiceWidget.tsx
  src/contrib/automationanywhere/__snapshots__/BotOptions.test.tsx.snap
  src/contrib/google/sheets/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/AppendSpreadsheetOptions.tsx
  src/contrib/google/sheets/LookupSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/LookupSpreadsheetOptions.tsx
  src/contrib/google/sheets/SheetsFileWidget.test.tsx
  src/contrib/google/sheets/__snapshots__/AppendSpreadsheetOptions.test.tsx.snap
  src/contrib/google/sheets/__snapshots__/LookupSpreadsheetOptions.test.tsx.snap
  src/contrib/google/sheets/__snapshots__/SheetsFileWidget.test.tsx.snap
  src/contrib/google/sheets/sheetsHelpers.test.ts
  src/contrib/google/sheets/useSpreadsheetId.test.ts
  src/contrib/google/sheets/useSpreadsheetId.ts
  src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
  src/services/apiClient.test.ts
  src/services/baseService.test.ts
  src/services/serviceUtils.test.ts
  src/services/useDependency.test.ts
  src/services/useDependency.ts
  src/testUtils/testHelpers.tsx
Labels: bug, release blocker

#5331 #5332 Fix bug when deactivating mods from the console page before opening page editor
  src/store/dynamicElementStorage.test.ts
  src/store/dynamicElementStorage.ts
Labels: bug

#5341 #4558: show proxied response error details in Page Editor and Logs
  src/background/proxyUtils.test.ts
  src/background/proxyUtils.ts
  src/background/requests.ts
  src/components/errors/ErrorDetail.module.scss
  src/components/errors/RemoteApiErrorDetail.tsx
  src/components/errors/__snapshots__/getErrorDetails.test.tsx.snap
  src/components/errors/getErrorDetails.test.tsx
  src/components/errors/getErrorDetails.tsx
  src/errors/businessErrors.ts
  src/errors/errorHelpers.test.tsx
  src/errors/errorHelpers.ts
Labels: bug

#5344 #5343: fix variable analysis false positives for Document Builder list buttons
  src/analysis/ReduxAnalysisManager.ts
  src/analysis/analysisSlice.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/analysis/analysisVisitors/varAnalysis/varMap.test.ts
  src/analysis/analysisVisitors/varAnalysis/varMap.ts
  src/blocks/PipelineExpressionVisitor.ts
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
Labels: bug, analysis

#5360 #5359: fix "user gesture required" error activating mod in extension console
  src/background/deployment.ts
  src/hooks/activateRecipe/useActivateRecipe.test.ts
  src/options/pages/blueprints/utils/useInstall.ts
  src/options/pages/marketplace/ActivateButton.tsx
  src/options/pages/marketplace/ActivateWizard.test.tsx
  src/options/pages/marketplace/PermissionsBody.tsx
  src/options/pages/marketplace/__snapshots__/ActivateWizard.test.tsx.snap
  src/options/pages/marketplace/useEnsurePermissions.ts
  src/options/pages/marketplace/useWizard.ts
  src/options/pages/marketplace/wizardTypes.ts
  src/store/dynamicElementStorage.test.ts
  src/store/dynamicElementStorage.ts
  src/store/uninstallUtils.ts
Labels: bug, release blocker

#5362 #5361: add support for copying cropped screenshot to clipboard
  src/blocks/effects/clipboard.test.ts
  src/blocks/effects/clipboard.ts
Labels: bug, user experience

#5363 Use fixed width icons for mod 3-dot menu in Extension Console
  src/options/pages/blueprints/BlueprintActions.tsx
Labels: papercut

#5365 #5364: add brick to prompt user to select element
  src/blocks/transformers/getAllTransformers.ts
  src/blocks/transformers/selectElement.test.ts
  src/blocks/transformers/selectElement.ts
  src/development/headers.ts
Labels: bug

#5370 Fix false positive warning in service locator
  src/services/locator.ts
Labels: developer experience

#5404 #5403: fix factory reset to reset all persisted state
  public/mockServiceWorker.js
  src/auth/authSlice.ts
  src/options/pages/blueprints/blueprintsSlice.ts
  src/options/pages/settings/FactoryResetSettings.tsx
  src/pageEditor/slices/editorSlice.ts
  src/recipes/recipesSlice.ts
  src/store/commonActions.ts
  src/store/extensionsSlice.ts
  src/store/servicesSlice.ts
  src/store/sessionChanges/sessionChangesSlice.ts
  src/store/settingsSlice.ts
  src/store/workshopSlice.ts
Labels: bug

#5427 #5356: bump to Typescript 5
  .storybook/main.js
  package-lock.json
  package.json
  src/options/pages/blueprints/BlueprintsPageSidebar.tsx
  src/utils/inference/markupInference.ts
Labels: dependencies
