Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-10, with the labels that each got.

#6578 #6547: Drop "Permission Settings" section from options
  src/extensionConsole/pages/settings/PermissionsSettings.tsx
  src/extensionConsole/pages/settings/SettingsPage.tsx
Labels: low priority

#6598 Avoid injecting into API-only frames
  src/manifest.json
Labels: bug, developer experience

#6600 #6524: Fix redux persist extensions migrations
  src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.stories.tsx
  src/sidebar/store.ts
  src/store/defaultMiddlewareConfig.ts
  src/store/extensionsMigrations.ts
  src/store/extensionsStorage.test.ts
  src/store/extensionsStorage.ts
  src/store/extensionsTypes.ts
  src/store/optionsStore.ts
Labels: release blocker

#6623 #6449: Restore and group storybook updates
  .github/dependabot.yml
Labels: dependencies, developer experience

#6626 #6624: Exclude discarded tabs in broadcasts and other "all tabs" actions
  src/background/activeTab.ts
  src/background/deploymentUpdater.test.ts
  src/background/deploymentUpdater.ts
  src/background/executor.ts
  src/background/modUpdater.test.ts
  src/background/modUpdater.ts
  src/background/navigation.ts
  src/background/removeExtensionForEveryTab.ts
  src/background/starterMods.test.ts
  src/background/starterMods.ts
  src/background/telemetry.ts
  src/bricks/renderers/propertyTable.tsx
  src/contrib/google/sheets/core/useCurrentOrigin.ts
  src/utils/extensionUtils.ts
  src/utils/promiseUtils.test.ts
  src/utils/promiseUtils.ts
Labels: performance

#6731 Avoid transitive webextension-polyfill imports + fix some type imports
  package-lock.json
  package.json
  src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.ts
  src/components/fields/schemaFields/widgets/SchemaButtonVariantWidget.tsx
  src/components/formBuilder/formBuilderHelpers.ts
  src/components/formBuilder/preview/FormPreview.tsx
  src/components/logViewer/logSlice.ts
  src/development/messengerLogging.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/starterBricks/pipelineMapping.ts
  src/sidebar/sidebarSlice.ts
  src/utils/asyncStateUtils.ts
  tsconfig.json
  webpack.sharedConfig.js
Labels: bug

#6772 #6581: lazy load page script to reduce memory footprint
  src/background/contentScript.ts
  src/background/externalProtocol.ts
  src/background/messenger/external/api.ts
  src/contentScript/externalProtocol.ts
  src/contentScript/lifecycle.ts
  src/contentScript/pageEditor.ts
  src/contentScript/pageEditor/elementPicker.ts
  src/contentScript/pageEditor/inferSingleElementSelector.test.ts
  src/contentScript/pageEditor/inferSingleElementSelector.ts
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/pageScript/frameworks.ts
  src/pageScript/messenger/api.ts
  src/pageScript/messenger/pigeon.ts
  src/pageScript/messenger/receiver.ts
  src/pageScript/messenger/sender.ts
  src/pageScript/pageScript.ts
  src/tsconfig.strictNullChecks.json
  src/types/messengerTypes.ts
  src/utils/inference/selectorInference.test.ts
  src/utils/inference/selectorInference.ts
  src/utils/inference/selectorInferenceUtils.test.ts
  src/utils/inference/selectorInferenceUtils.ts
  src/utils/inference/selectorTypes.ts
  src/utils/inference/siteSelectorHints.ts
  src/utils/legacyMessengerUtils.ts
Labels: developer experience, performance

#6775 #6690: eliminate remaining cycle in error code
  src/errors/businessErrors.ts
  src/errors/contextInvalidated.ts
  src/errors/errorHelpers.ts
  src/errors/knownErrorMessages.ts
  src/starterBricks/starterBrickTestUtils.ts
  src/tsconfig.strictNullChecks.json
  src/utils/domUtils.ts
Labels: developer experience

#6776 Drop front-end framework detection code
  src/__snapshots__/Storyshots.test.js.snap
  src/bricks/transformers/component/ComponentReader.ts
  src/bricks/transformers/component/ComponentReaderOptions.tsx
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/elementPicker.test.ts
  src/contentScript/pageEditor/elementPicker.ts
  src/contentScript/pageEditor/types.ts
  src/contrib/editors.ts
  src/pageEditor/fields/SelectorSelectorWidget.test.ts
  src/pageEditor/fields/SelectorSelectorWidget.tsx
  src/pageEditor/fields/selectorListItem/SelectorListItem.stories.tsx
  src/pageEditor/fields/selectorListItem/SelectorListItem.tsx
  src/pageEditor/hooks/useAddElement.ts
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/starterBricks/elementConfig.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/tabState/tabStateSlice.ts
  src/pageEditor/tabState/tabStateTypes.ts
  src/pageScript/elementInfo.ts
  src/pageScript/messenger/api.ts
  src/pageScript/messenger/constants.ts
  src/pageScript/pageScript.ts
  src/utils/inference/inferSingleElementSelector.test.ts
  src/utils/inference/inferSingleElementSelector.ts
  src/utils/inference/selectorInference.ts
  src/utils/inference/selectorTypes.ts
  src/vendors/libraryDetector/detect.ts
  src/vendors/libraryDetector/libraries.js
Labels: developer experience

#6777 #4000: Dynamically load brick UI to reduce bundle size
  src/bricks/effects/ToggleQuickbarEffect.ts
  src/bricks/effects/highlightText.ts
  src/bricks/effects/runSubTour.test.ts
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/renderers/customForm.ts
  src/bricks/renderers/document.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
  src/components/quickBar/QuickBarApp.tsx
  src/components/quickBar/quickBarRegistry.ts
  src/components/quickBar/useActions.test.tsx
  src/starterBricks/quickBarExtension.test.ts
  src/starterBricks/quickBarExtension.tsx
  src/starterBricks/quickBarProviderExtension.tsx
  src/starterBricks/quickbarProviderExtension.test.ts
  src/starterBricks/tourActionIcon.tsx
  src/starterBricks/tourController.test.ts
  src/starterBricks/tourController.ts
  src/starterBricks/tourExtension.test.ts
  src/starterBricks/tourExtension.ts
  src/telemetry/logging.ts
  src/types/contract.ts
Labels: performance
