Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-05, with the labels that each got.

#5649 #5648: fix permissions error when activating from extension console
  src/extensionConsole/components/RequireBrickRegistry.tsx
  src/extensionConsole/pages/activateExtension/ActivateForm.tsx
  src/extensionConsole/pages/activateRecipe/ActivateBlueprintPage.tsx
  src/extensionConsole/pages/activateRecipe/ActivateWizardCard.module.scss
  src/extensionConsole/pages/activateRecipe/ActivateWizardCard.test.tsx
  src/extensionConsole/pages/activateRecipe/ActivateWizardCard.tsx
  src/extensionConsole/pages/activateRecipe/__snapshots__/ActivateWizardCard.test.tsx.snap
  src/extensionConsole/pages/activateRecipe/useActivateUrl.ts
Labels: bug, release blocker

#5659 #5657 Move indexeddb clear operation in `syncPackages` into a single transaction
  src/registry/localRegistry.ts
Labels: bug, runtime

#5662 Remove the useFetch hook in favor of RTK Query
  src/errors/genericErrors.ts
  src/extensionConsole/pages/activateExtension/ServicesRow.tsx
  src/extensionConsole/pages/brickEditor/Editor.tsx
  src/extensionConsole/pages/services/ZapierModal.tsx
  src/extensionConsole/pages/workshop/WorkshopPage.tsx
  src/extensionConsole/pages/workshop/workshopTypes.ts
  src/extensionConsole/pages/workshop/workshopUtils.ts
  src/hooks/fetch.ts
  src/hooks/useFetch.ts
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/services/api.ts
  src/types/contract.ts
  src/types/registryTypes.ts
Labels: developer experience

#5813 assign dependabot PRs to Graham by default
  .github/dependabot.yml
Labels: developer experience
