Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-12, with the labels that each got.

#7022 #7021 Don't normalize onSubmit pipeline fields
  src/pageEditor/starterBricks/pipelineMapping.test.ts
  src/pageEditor/starterBricks/pipelineMapping.ts
Labels: bug

#7029 Fix `assertNotNull` imports
  src/bricks/effects/postMessage.ts
  src/utils/modUtils.ts
Labels: priority

#7056 #7054: fix mod options saving regression
  src/modDefinitions/registry.ts
  src/pageEditor/hooks/useSaveRecipe.test.ts
  src/pageEditor/hooks/useSaveRecipe.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx
  src/services/api.ts
  src/tsconfig.strictNullChecks.json
  src/utils/modUtils.test.ts
  src/utils/modUtils.ts
  src/utils/schemaUtils.ts
Labels: bug, release blocker

#7060 Organize form builder fields into sections
  src/pageEditor/fields/FormModalOptions.test.tsx
  src/pageEditor/fields/FormModalOptions.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
Labels: user experience, page editor, form builder, forms

#7078 #7076 Fix GSheets Append row options so variable expressions aren't cleared from rowValues
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
Labels: bug, regression

#7016 Nullish helper types
  .eslintrc.js
  eslint-local-rules/preferNullish.js
  eslint-local-rules/preferNullish.test.js
  eslint-local-rules/preferNullishable.js
  eslint-local-rules/preferNullishable.test.js
  package-lock.json
  package.json
  src/background/externalProtocol.ts
  src/bricks/effects/postMessage.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
  src/components/AsyncStateGate.tsx
  src/components/documentBuilder/edit/getElementCollectionName.ts
  src/components/formBuilder/ImageCropWidget.tsx
  src/runtime/mapArgs.ts
  src/services/factory.ts
  src/services/requestErrorUtils.ts
  src/tsconfig.strictNullChecks.json
  src/utils/inference/selectorInference.ts
  src/utils/modUtils.ts
  src/utils/nullishUtils.test.ts
  src/utils/nullishUtils.ts
  src/utils/postMessage.ts
  src/utils/typeUtils.ts
Labels: developer experience

#7083 Update swagger
  src/types/swagger.ts
Labels: developer experience

#7099 #7098: support passing HTML to the clipboard
  src/activation/ActivationLink.tsx
  src/bricks/effects/clipboard.test.ts
  src/bricks/effects/clipboard.ts
  src/components/jsonTree/JsonTree.tsx
  src/components/jsonTree/treeHooks.tsx
  src/extensionConsole/pages/brickEditor/referenceTab/BrickDetail.tsx
  src/extensionConsole/pages/integrations/ZapierIntegrationModal.tsx
  src/utils/clipboardUtils.ts
Labels: enhancement, customer

#7107 #7106: fixes empty label being replaced by field name
  src/bricks/renderers/__snapshots__/customForm.test.tsx.snap
  src/bricks/transformers/ephemeralForm/EphemeralForm.test.tsx
  src/components/formBuilder/FieldTemplate.tsx
  src/components/formBuilder/preview/FormPreview.test.tsx
Labels: bug, regression

#7084 #7067: Fix Form Preview padding and focus outline
  package-lock.json
  package.json
  src/__snapshots__/Storyshots.test.js.snap
  src/bricks/renderers/__snapshots__/customForm.test.tsx.snap
  src/components/formBuilder/DescriptionField.tsx
  src/components/formBuilder/FieldTemplate.module.scss
  src/components/formBuilder/FieldTemplate.tsx
  src/components/formBuilder/formBuilderTypes.ts
  src/components/formBuilder/preview/FormPreview.tsx
  src/components/formBuilder/preview/FormPreviewBooleanField.module.scss
  src/components/formBuilder/preview/FormPreviewBooleanField.tsx
  src/components/formBuilder/preview/FormPreviewFieldTemplate.module.scss
  src/components/formBuilder/preview/FormPreviewFieldTemplate.tsx
  src/components/formBuilder/preview/FormPreviewSchemaField.tsx
  src/components/formBuilder/preview/FormPreviewStringField.module.scss
  src/components/formBuilder/preview/FormPreviewStringField.tsx
  src/components/formBuilder/preview/__snapshots__/FormPreview.test.tsx.snap
  src/pageEditor/tabs/dataPanelTabs.module.scss
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
  src/tsconfig.strictNullChecks.json
Labels: bug, regression

#7109 #7104: affordance to pass data from host page to AA Co-Pilot forms
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/partnerHandlers.ts
  src/bricks/renderers/iframe.ts
  src/components/fields/fieldUtils.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contrib/automationanywhere/SetCopilotDataEffect.ts
  src/contrib/automationanywhere/aaFrameProtocol.ts
  src/contrib/registerContribBlocks.ts
  src/development/headers.ts
  src/sidebar/sidebar.tsx
  src/tinyPages/frame.ts
Labels: enhancement, customer, enterprise

#7116 Make default identity brick configuration use property to match column header in UI
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/bricks/transformers/IdentityTransformer.test.ts
  src/bricks/transformers/IdentityTransformer.ts
  src/bricks/transformers/IdentityTransformerOptions.test.tsx
  src/bricks/transformers/IdentityTransformerOptions.tsx
  src/bricks/transformers/getAllTransformers.ts
  src/contrib/editors.ts
  src/pageEditor/exampleBrickConfigs.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience

#7115 #7105: add affordance for sanitized iframes in HTML and Markdown renderer bricks
  src/bricks/renderers/HtmlRenderer.test.ts
  src/bricks/renderers/HtmlRenderer.ts
  src/bricks/renderers/MarkdownRenderer.test.tsx
  src/bricks/renderers/MarkdownRenderer.ts
  src/bricks/renderers/getAllRenderers.ts
  src/components/Markdown.tsx
  src/components/documentBuilder/documentTree.test.tsx
  src/components/documentBuilder/preview/ElementPreview.test.tsx
  src/pageEditor/panes/EditorPane.test.tsx
  src/utils/sanitize.ts
Labels: enhancement, customer

#7118 Fix missing element key for map values brick
  src/bricks/transformers/controlFlow/MapValues.ts
  src/pageEditor/utils.ts
Labels: bug, user experience

#7117 Match show sidebar panel heading field title to starter brick field title
  src/bricks/effects/sidebar.ts
  src/pageEditor/tabs/sidebar/SidebarConfiguration.tsx
  src/types/schemaTypes.ts
Labels: user experience

#7142 Add experimental Run Metadata brick
  src/bricks/transformers/RunMetadataTransformer.test.ts
  src/bricks/transformers/RunMetadataTransformer.ts
  src/bricks/transformers/getAllTransformers.ts
  src/development/headers.ts
Labels: enhancement, brick, customer

#7147 #7143: disable variable popover trigger in mod options to prevent crash when typing `@`
  src/components/fields/schemaFields/widgets/varPopup/useAttachPopup.ts
Labels: bug, page editor

#7146 #7145: 💅use panel title emoji as mod launcher icon
  src/sidebar/modLauncher/ActiveSidebarModsList.tsx
  src/sidebar/modLauncher/ActiveSidebarModsListItem.module.scss
  src/sidebar/modLauncher/ActiveSidebarModsListItem.tsx
  src/sidebar/modLauncher/ModLauncher.test.tsx
Labels: user experience, sidebar

#7155 auto approve and merge all patch dependabot prs
  .github/workflows/dependabot-auto-merge.yml
Labels: developer experience

#7154 automatically mark stale issues and prs weekly
  .github/workflows/stale-issue.yml
Labels: developer experience

#7160 Enable RUM in the Page Editor and Sidebar frames
  src/pageEditor/pageEditor.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/sidebar/sidebar.tsx
  src/telemetry/performance.ts
Labels: telemetry

#7156 #7157: fix regression in required field for HtmlRenderer
  src/activation/useActivateRecipeWizard.test.tsx
  src/bricks/effects/tabs.ts
  src/bricks/renderers/HtmlRenderer.ts
  src/bricks/transformers/parseCsv.ts
  src/bricks/transformers/parseDataUrl.ts
  src/bricks/transformers/prompt.ts
  src/bricks/transformers/randomNumber.ts
  src/bricks/transformers/readable.ts
  src/bricks/transformers/selectElement.ts
  src/bricks/transformers/traverseElements.ts
  src/contrib/google/geocode.ts
  src/pageEditor/starterBricks/upgrade.test.ts
  src/pageEditor/tabs/effect/BrickConfiguration.test.tsx
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/runtime/pipelineTests/root.test.ts
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/starterBricks/tourExtension.ts
  src/starterBricks/triggerExtension.ts
  src/utils/modUtils.ts
  src/validators/generic.ts
Labels: bug, regression

#7125 Add experimental bricks for reflection
  src/analysis/analysisVisitors/pageStateAnalysis/modVariableSchemasVisitor.test.ts
  src/background/deploymentUpdater.ts
  src/bricks/registerBuiltinBricks.ts
  src/bricks/transformers/GetBrickInterfaceTransformer.test.ts
  src/bricks/transformers/GetBrickInterfaceTransformer.ts
  src/bricks/transformers/RunBrickByIdTransformer.test.ts
  src/bricks/transformers/RunBrickByIdTransformer.ts
  src/bricks/transformers/brickFactory.test.ts
  src/bricks/transformers/getAllTransformers.ts
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
  src/contentScript/contentScriptCore.ts
  src/development/headers.ts
  src/extensionConsole/App.tsx
  src/pageEditor/Panel.tsx
  src/pageEditor/tabs/trigger/TriggerConfiguration.test.tsx
  src/sidebar/PanelBody.test.tsx
  src/sidebar/sidebar.tsx
  src/tinyPages/ephemeralPanel.tsx
Labels: enhancement, low priority, brick

#7161 Support markdown to plain text conversion in `@pixiebrix/convert` brick
  src/bricks/transformers/convertDocument.test.ts
  src/bricks/transformers/convertDocument.ts
Labels: customer

#7163 #7103 Editable Comments Tab
  src/components/fields/schemaFields/FieldRuntimeContext.ts
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/sidebar/ActivatedModComponentListItem.test.tsx
  src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
  src/pageEditor/sidebar/ModComponentListItem.tsx
  src/pageEditor/sidebar/SidebarExpanded.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/tabs/CommentsTab.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/CommentsTab.tsx
  src/telemetry/events.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience

#7081 #3059: switch RJSF validator to cfworker/jsonschema
  package-lock.json
  package.json
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/renderers/customForm.test.tsx
  src/bricks/transformers/ephemeralForm/EphemeralForm.tsx
  src/components/formBuilder/preview/FormPreview.tsx
  src/validators/formValidator.test.ts
  src/validators/formValidator.ts
Labels: mv3

#7030 #6649: Avoid background messaging to handle AJAX page updates
  package-lock.json
  package.json
  src/background/navigation.ts
  src/contentScript/contentScriptCore.ts
  src/contentScript/lifecycle.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/pageEditor/pageEditor.tsx
  src/tsconfig.strictNullChecks.json
Labels: performance, runtime, mv3

#7168 #7152 Replace instance of fetch for `/api/bricks` with RTK Query Hook
  src/extensionConsole/pages/brickEditor/Editor.test.tsx
  src/extensionConsole/pages/brickEditor/Editor.tsx
Labels: developer experience

#7164 #7150: Add skunkworks flag to toggle sandboxed execution
  src/extensionConsole/pages/settings/ExperimentalSettings.tsx
  src/sandbox/messenger/api.ts
  src/store/settings/settingsTypes.ts
Labels: runtime, mv3

#7179 #7177: add knip config for dead-code/export/import detection
  .github/workflows/ci.yml
  knip.js
  package-lock.json
  package.json
  src/bricks/blockFilterHelpers.ts
  src/bricks/effects/comment.ts
  src/bricks/effects/scrollIntoView.ts
  src/bricks/effects/submitPanel.ts
  src/bricks/transformers/extensionDiagnostics.ts
  src/bricks/transformers/tourStep/TourStepOptions.tsx
  src/bricks/transformers/tourStep/tourStep.ts
  src/bricks/transformers/traverseElements.ts
  src/components/formBuilder/DescriptionFieldTemplate.tsx
  src/contrib/automationanywhere/SetCopilotDataEffect.ts
  src/contrib/editors.ts
  src/contrib/google/sheets/core/types.ts
  src/contrib/google/sheets/ui/useGoogleSheet.tsx
  src/development/hooks/useMessengerLogging.ts
  src/development/hooks/useRenderCount.ts
  src/errors/contextInvalidated.ts
  src/extensionConsole/pages/settings/LoggingSettings.tsx
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/hooks/useMergeAsyncState.ts
  src/hooks/useRenderCount.ts
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/registry/memoryRegistry.ts
  src/tsconfig.strictNullChecks.json
  src/utils/inference/selectorInference.ts
  src/utils/notify.tsx
Labels: developer experience

#7178 #6649: Exclude navigation events that should not trigger page updates
  jest.config.js
  package-lock.json
  package.json
  src/background/background.ts
  src/background/navigation.ts
  src/contentScript/contentScriptCore.ts
  src/contentScript/lifecycle.ts
Labels: mv3

#7188 #7171: Drop GOOGLE_ ENVs
  .github/workflows/ci.yml
  .github/workflows/rainforestqa.yml
  .github/workflows/release.yaml
  webpack.config.js
Labels: mv3, edge

#7194 #7167 Fix missing brick config warnings
  src/components/form/useFieldAnnotations.test.tsx
  src/components/form/useFieldAnnotations.ts
Labels: bug

#7187 #7171: Build MV3 on CI
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: mv3

#7176 #7175: fix variable popover default setting
  src/extensionConsole/pages/settings/SettingToggle.tsx
  src/store/settings/settingsMigrations.ts
  src/store/settings/settingsSlice.ts
  src/store/settings/settingsTypes.ts
  src/store/settingsMigrations.ts
Labels: bug

#7198 #7196: Improve build artifacts naming for MV3
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: mv3

#7211 #7209: Update MV3 host upgrade; manifest tests
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  scripts/__snapshots__/manifest.test.js.snap
  scripts/env.js
  scripts/manifest.mjs
  scripts/manifest.test.js
  webpack.config.js
Labels: mv3

#7214 #7208: Restore background worker in MV3
  .eslintrc.js
  package-lock.json
  package.json
  scripts/webpack.scripts.js
  src/background/browserAction.ts
  src/starterBricks/tourExtension.ts
  src/starterBricks/triggerExtension.ts
  src/vendors/hoverintent.js
Labels: bug, mv3

#7215 Fix `Check Updates` button in options
  src/contentScript/sidebarDomControllerLite.ts
  src/globals.d.ts
  src/utils/extensionUtils.ts
Labels: bug

#7216 #7190: Auto-forget tab openers and targets
  src/background/executor.ts
  src/mv3/SessionStorage.ts
Labels: performance, mv3

#7219 #7189: Upload MV3 sourcemaps
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: mv3

#7220 #7174: Include "mv3" in package version
  scripts/manifest.mjs
Labels: mv3

#7213 #7211: Drop overlapping URL patterns
  scripts/__snapshots__/manifest.test.js.snap
  src/manifest.json
  src/utils/extensionUtils.ts
Labels: bug

#7223 #7222: Enforce sandbox in MV3
  src/extensionConsole/pages/settings/ExperimentalSettings.tsx
  src/mv3/api.ts
  src/sandbox/messenger/api.ts
Labels: mv3

#7224 #7222: Enforce sandbox in MV3 /2
  src/extensionConsole/pages/settings/ExperimentalSettings.tsx
  webpack.config.mjs
Labels: mv3

#7217 Drop `readStorage`/`setStorage`
  src/mv3/SessionStorage.ts
  src/utils/storageUtils.ts
Labels: developer experience, low priority

#7173 #7183 Refactor page editor sidebar to completely avoid fetching mod definitions
  src/pageEditor/sidebar/ActivatedModComponentListItem.test.tsx
  src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
  src/pageEditor/sidebar/ModComponentListItem.tsx
  src/pageEditor/sidebar/ModListItem.test.tsx
  src/pageEditor/sidebar/ModListItem.tsx
  src/pageEditor/sidebar/SidebarExpanded.tsx
  src/pageEditor/sidebar/__snapshots__/ActivatedModComponentListItem.test.tsx.snap
  src/pageEditor/sidebar/__snapshots__/ModListItem.test.tsx.snap
  src/pageEditor/sidebar/arrangeElements.test.ts
  src/pageEditor/sidebar/arrangeElements.ts
  src/pageEditor/sidebar/arrangeSidebarItems.test.ts
  src/pageEditor/sidebar/arrangeSidebarItems.ts
  src/pageEditor/sidebar/common.ts
  src/pageEditor/sidebar/filterSidebarItems.test.ts
  src/pageEditor/sidebar/filterSidebarItems.ts
Labels: page editor

#7229 #7153 Extract PUT Standalone Mod Component side effect from extensionsSlice
  src/extensionConsole/pages/activateExtension/ActivateExtensionPage.tsx
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModal.test.tsx
  src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModalBody.tsx
  src/mods/hooks/useDeleteExtensionAction.ts
  src/mods/useMods.ts
  src/pageEditor/hooks/useSaveRecipe.ts
  src/pageEditor/hooks/useSaveStandaloneModComponent.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.test.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
  src/pageEditor/panes/save/useSavingWizard.test.tsx
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/sidebar/modals/CreateRecipeModal.tsx
  src/pageEditor/slices/editorSlice.ts
  src/services/api.ts
  src/services/apiClient.ts
  src/sidebar/DefaultContent.test.tsx
  src/store/extensionsSlice.ts
  src/types/contract.ts
Labels: developer experience

#7180 #7181: eslint rule to ban mutable module variables in `src/background/**`
  .eslintrc.js
  eslint-local-rules/persistBackgroundData.js
  src/background/browserAction.ts
  src/background/contentScript.ts
  src/background/deploymentUpdater.ts
  src/background/externalProtocol.ts
  src/background/messenger/external/api.ts
  src/background/navigation.ts
  src/background/partnerIntegrations.ts
  src/background/requests.ts
  src/background/starterMods.ts
  src/background/telemetry.ts
  src/background/webextAlert.ts
Labels: developer experience, mv3
