Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-11, with the labels that each got.

#6785 #6784: remove `js-beautify` from end-user content script
  src/contentScript/pageEditor/insertButton.tsx
  src/contentScript/pageEditor/insertPanel.tsx
  src/utils/inference/selectorInference.ts
Labels: performance

#6788 #6786: explicitly close IDB connections
  src/background/telemetry.ts
  src/registry/packageRegistry.ts
  src/telemetry/logging.test.ts
  src/telemetry/logging.ts
  src/telemetry/trace.ts
  src/tours/tourRunDatabase.ts
Labels: bug, performance

#6796 Add `getExtensionConsoleUrl` utility
  .eslintrc.js
  eslint-local-rules/noBrowserRuntimeGetUrl.js
  eslint-local-rules/noBrowserRuntimeGetUrl.test.js
  src/background/browserAction.ts
  src/background/installer.ts
  src/background/messenger/external/_implementation.ts
  src/components/fields/schemaFields/integrations/IntegrationDependencyField.tsx
  src/extensionConsole/pages/brickEditor/Editor.tsx
  src/sidebar/LoginPanel.tsx
  src/telemetry/logging.test.ts
  src/utils/extensionUtils.test.ts
  src/utils/extensionUtils.ts
Labels: developer experience, low priority

#6780 #4000: lazy load sidebar content/modules
  src/sidebar/Tabs.test.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/staticPanelUtils.tsx
Labels: performance

#6798 #6798: fix dynamic js-beautify import
  src/contentScript/pageEditor/beautify.ts
  src/contentScript/pageEditor/insertButton.tsx
  src/contentScript/pageEditor/insertPanel.tsx
Labels: release blocker

#6802 #4000: eager mount mod panels
  src/sidebar/Tabs.tsx
Labels: bug

#6806 #6804: debounce sidebar panels independently
  src/sidebar/Tabs.tsx
  src/starterBricks/helpers.ts
  src/starterBricks/sidebarExtension.test.ts
  src/starterBricks/sidebarExtension.ts
Labels: bug, performance

#6811 #6797: conditionally log to console
  src/background/background.ts
  src/bricks/effects/logger.ts
  src/contentScript/contentScript.ts
  src/contentScript/loadActivationEnhancements.ts
  src/contentScript/loadActivationEnhancementsCore.test.ts
  src/contentScript/loadActivationEnhancementsCore.ts
  src/contentScript/messenger/registration.ts
  src/development/runtimeLogging.ts
  src/extensionConsole/options.tsx
  src/pageEditor/pageEditor.tsx
  src/sidebar/sidebar.tsx
  src/tinyPages/ephemeralForm.tsx
  src/tinyPages/ephemeralPanel.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience, performance

#6813 #6796: Replace custom lint rule for `getExtensionConsoleUrl`
  .eslintrc.js
  eslint-local-rules/noBrowserRuntimeGetUrl.js
  eslint-local-rules/noBrowserRuntimeGetUrl.test.js
  src/utils/extensionUtils.ts
Labels: developer experience

#6816 #6815: Add timeout to Jest tests on CI
  .github/workflows/ci.yml
  src/testUtils/testEnv.js
Labels: developer experience, priority

#6848 Bump eslint-config-pixiebrix to 0.31.0 correctly
  package-lock.json
  package.json
Labels: dependencies

#6849 Use node 18.18.2 and npm 10.2.3
  .github/workflows/ci.yml
  .github/workflows/rainforestqa.yml
  .github/workflows/release.yaml
  .nvmrc
  package-lock.json
  package.json
  src/__snapshots__/Storyshots.test.js.snap
  src/bricks/transformers/__snapshots__/parseDate.test.ts.snap
Labels: dependencies, low priority

#6903 #6902: relax connect-src CSP to allow `http:` API calls
  src/background/requests.ts
  src/errors/assertProtocolUrl.ts
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/manifest.json
  src/tsconfig.strictNullChecks.json
  src/utils/enrichAxiosErrors.ts
  src/utils/urlUtils.test.ts
  webpack.config.js
Labels: customer

#6856 Log error on duplicate `webext-messenger` execution
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/contentScript/loadActivationEnhancements.ts
Labels: developer experience

#6949 Remove stray semicolon
  src/extensionConsole/App.tsx
Labels: user experience

#6950 Drop code from 2022 bot games promotion
  img/bot-games-arcade-illustration.png
  src/extensionConsole/pages/mods/BotGamesView.tsx
  src/extensionConsole/pages/mods/ModsPageContent.tsx
  src/extensionConsole/pages/mods/ModsPageLayout.test.tsx
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/extensionConsole/pages/mods/ModsPageToolbar.tsx
Labels: developer experience

#7003 Fix JavaScript brick capitalization
  src/bricks/transformers/javascript.ts
Labels: papercut

#6956 Lint warning for snapshots
  .eslintrc.js
  package-lock.json
  package.json
  src/bricks/available.test.ts
  src/bricks/readers/jquery.ts
  src/bricks/transformers/tourStep/overlay.ts
  src/contentScript/ready.ts
  src/contrib/google/sheets/core/useCurrentOrigin.test.ts
  src/errors/errorHelpers.test.tsx
  src/globals.d.ts
  src/hooks/common.ts
  src/utils/injectIframe.test.tsx
  src/utils/postMessage.test.ts
Labels: low priority

#6851 #6548: Load PixieBrix into existing tabs on install
  package-lock.json
  package.json
  src/background/background.ts
  src/background/browserAction.ts
  src/background/initBrowserCommands.ts
  src/background/navigation.ts
  src/pageEditor/EditorLayout.tsx
  src/permissions/permissionsUtils.ts
Labels: bug

#7005 Fix Identity Brick options in Page Editor and allow any value
  src/__snapshots__/Storyshots.test.js.snap
  src/bricks/transformers/IdentityOptions.test.tsx
  src/bricks/transformers/IdentityOptions.tsx
  src/bricks/transformers/identity.test.ts
  src/bricks/transformers/identity.ts
  src/components/errors/getErrorDetails.test.tsx
  src/components/errors/getErrorDetails.tsx
  src/components/fields/schemaFields/schemaUtils.test.ts
  src/components/fields/schemaFields/schemaUtils.ts
  src/components/logViewer/LogTable.stories.tsx
  src/contrib/editors.ts
  src/pageEditor/exampleBlockConfigs.ts
Labels: bug, user experience, page editor, customer

#6960 #6959: add onsubmit handler to custom form
  src/__snapshots__/Storyshots.test.js.snap
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/renderers/customForm.ts
  src/bricks/transformers/tourStep/TourStepOptions.tsx
  src/components/documentBuilder/render/BlockElement.tsx
  src/components/formBuilder/edit/FieldEditor.tsx
  src/components/formBuilder/edit/FormEditor.test.tsx
  src/components/formBuilder/edit/FormEditor.tsx
  src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
  src/pageEditor/fields/CollapsibleFieldSection.tsx
  src/pageEditor/fields/ConnectedCollapsibleFieldSection.test.tsx
  src/pageEditor/fields/ConnectedCollapsibleFieldSection.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/fields/PipelineToggleField.test.tsx
  src/pageEditor/fields/PipelineToggleField.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/ExtraPermissionsSection.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
  src/pageEditor/tabs/effect/__snapshots__/BlockConfiguration.test.tsx.snap
  src/pageEditor/tabs/recipeOptionsDefinitions/RecipeOptionsDefinition.tsx
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
  src/pageEditor/utils.ts
  src/runtime/expressionCreators.ts
  src/runtime/runtimeTypes.ts
  src/sidebar/PanelBody.tsx
  src/types/brickTypes.ts
  src/types/runtimeTypes.ts
  src/types/schemaTypes.ts
Labels: enhancement, customer

#6963 Report `PerformanceMessengerManyTabsBroadcast` event
  src/background/executor.ts
  src/telemetry/events.ts
Labels: performance

#6968 #6967: Page Editor home state
  .git-blame-ignore-revs
  img/home-pane-bg-illustration.png
  img/home.svg
  img/paintbrush.svg
  src/__snapshots__/Storyshots.test.js.snap
  src/pageEditor/EditorContent.tsx
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/panes/HomePane.module.scss
  src/pageEditor/panes/HomePane.stories.tsx
  src/pageEditor/panes/HomePane.tsx
  src/pageEditor/panes/IntroButtons.tsx
  src/pageEditor/panes/NoModsPane.tsx
  src/pageEditor/panes/NoTabAccessPane.test.tsx
  src/pageEditor/panes/RestrictedPane.stories.tsx
  src/pageEditor/panes/__snapshots__/NoTabAccessPane.test.tsx.snap
  src/pageEditor/sidebar/AddStarterBrickButton.tsx
  src/pageEditor/sidebar/HomeButton.module.scss
  src/pageEditor/sidebar/HomeButton.tsx
  src/pageEditor/sidebar/SidebarCollapsed.tsx
  src/pageEditor/sidebar/SidebarExpanded.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.test.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/store/checkActiveElementAvailability.test.ts
  src/store/checkAvailableDynamicElements.test.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/testUtils/storyUtils.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience, page editor

#7012 #6943: add (Copy) suffix to copied mod name by default
  src/pageEditor/sidebar/modals/CreateRecipeModal.tsx
  src/pageEditor/slices/editorSlice.test.ts
  src/pageEditor/slices/editorSlice.ts
Labels: user experience

#7020 Automatically start case default field labels
  src/__snapshots__/Storyshots.test.js.snap
  src/components/fields/fieldUtils.test.ts
  src/components/fields/fieldUtils.ts
  src/components/fields/schemaFields/BasicSchemaField.test.tsx
  src/components/fields/schemaFields/SchemaField.test.tsx
  src/components/fields/schemaFields/widgets/__snapshots__/FixedInnerObjectWidget.test.tsx.snap
  src/extensionConsole/pages/integrations/IntegrationConfigEditorModal.test.tsx
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/effect/__snapshots__/BlockConfiguration.test.tsx.snap
  src/pageEditor/tabs/recipeOptionsValues/RecipeOptionsValues.test.tsx
  src/pageEditor/tabs/recipeOptionsValues/__snapshots__/RecipeOptionsValues.test.tsx.snap
  src/sidebar/activateRecipe/__snapshots__/ActivateModPanel.test.tsx.snap
Labels: user experience, page editor
