Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-01, with the labels that each got.

#4932 #2512: Only reload the browser if the extension has been updated
  src/chrome.ts
  src/hooks/useDeployments.ts
  src/options/pages/settings/AdvancedSettings.tsx
  src/utils.ts
Labels: user experience, low priority, papercut

#4941 Add URL validation analysis rules
  src/analysis/analysisVisitors/requestPermissionAnalysis.test.ts
  src/analysis/analysisVisitors/requestPermissionAnalysis.ts
Labels: analysis

#4873 Bug: Page Editor permissions warning on save #4865
  src/components/ModalLayout.tsx
  src/options/pages/blueprints/modals/convertToRecipeModal/ConvertToRecipeModal.tsx
  src/options/pages/blueprints/modals/extensionLogsModal/ExtensionLogsModal.tsx
  src/options/pages/blueprints/modals/shareModals/ShareRecipeModal.tsx
  src/pageEditor/hooks/useCreate.ts
  src/pageEditor/hooks/useSaveRecipe.ts
  src/pageEditor/sidebar/modals/CreateRecipeModal.tsx
Labels: bug

#4933 #4921: remove export blueprint action
  src/options/pages/blueprints/BlueprintActions.tsx
  src/options/pages/blueprints/useInstallableViewItemActions.test.tsx
  src/options/pages/blueprints/useInstallableViewItemActions.ts
  src/options/pages/blueprints/utils/exportBlueprint.ts
Labels: specification required

#4931 Improve style, alignment and usability of Sidebar tabs
  src/sidebar/Tabs.module.scss
  src/sidebar/Tabs.tsx
Labels: papercut

#4918 Fix Bootstrap color import order + use new colors in options
  img/logo-small-rounded.svg
  src/components/Loader.module.scss
  src/contentScript/sidebarDomControllerLite.ts
  src/options/pages/blueprints/BlueprintsToolbar.tsx
  src/options/pages/blueprints/InstallableIcon.tsx
  src/options/pages/blueprints/ListFilters.module.scss
  src/options/pages/blueprints/Status.tsx
  src/options/pages/marketplace/__snapshots__/ActivateWizard.test.tsx.snap
  src/pageEditor/sidebar/Sidebar.module.scss
  src/vendors/theme/app/app.scss
  src/vendors/theme/assets/styles/_base-colors.scss
  src/vendors/theme/assets/styles/_themes.scss
  src/vendors/theme/assets/styles/_variables.scss
Labels: bug, specification required, design system, backlog

#4969 #4968: Fix ENV config for `WEBEXT_MESSENGER_LOGGING`
  src/utils/postMessage.ts
  webpack.config.js
Labels: bug

#4868 Add `useAutoFocus` hook
  src/components/addBlockModal/TagSearchInput.module.scss
  src/components/addBlockModal/TagSearchInput.tsx
  src/components/addBlockModal/__snapshots__/AddBlockModal.test.tsx.snap
  src/components/brickModalNoTags/BrickModal.tsx
  src/components/fields/schemaFields/widgets/NumberWidget.tsx
  src/components/fields/schemaFields/widgets/PasswordWidget.tsx
  src/hooks/useAutoFocus.test.ts
  src/hooks/useAutoFocus.ts
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
Labels: developer experience, low priority, small

#4987 Silence Jest coverage CLI 1000-lines noise
  jest.config.json
Labels: developer experience

#4995 Drop mistaken `*://*/*` in MV3
  webpack.config.js
Labels: mv3

#4993 #4994: Make links in Field descriptions clickable
  jest.config.json
  package-lock.json
  package.json
  src/__snapshots__/Storyshots.test.js.snap
  src/components/LinkifiedString.test.tsx
  src/components/LinkifiedString.tsx
  src/components/__snapshots__/LinkifiedString.test.tsx.snap
  src/components/form/FieldTemplate.tsx
  src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
  src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
  src/options/pages/blueprints/modals/convertToRecipeModal/__snapshots__/ConvertToRecipeModal.test.tsx.snap
  src/options/pages/services/__snapshots__/ServiceEditorModal.test.tsx.snap
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
Labels: user experience

#4992 #4830 Re-enable page editor data persistence, and fix duplicate/deactivate bugs
  src/options/pages/blueprints/modals/blueprintModalsSlice.ts
  src/options/pages/blueprints/useInstallableViewItemActions.ts
  src/options/pages/blueprints/utils/useInstall.ts
  src/options/pages/blueprints/utils/useReinstall.ts
  src/pageEditor/EditorLayout.tsx
  src/pageEditor/hooks/useRemoveRecipe.ts
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/store.ts
  src/store/dynamicElementStorage.test.ts
  src/store/dynamicElementStorage.ts
  src/store/optionsStore.ts
  src/store/servicesSlice.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/store/sessionChanges/sessionChangesSelectors.test.ts
  src/store/sessionChanges/sessionChangesSelectors.ts
  src/store/sessionChanges/sessionChangesSlice.ts
  src/store/sessionChanges/sessionChangesTypes.ts
  src/store/workshopSlice.ts
Labels: page editor

#4908 #4694: Move the previous unsafe messenger into `@/pageScript`
  .eslintrc.js
  src/background/contentScript.test.ts
  src/background/contentScript.ts
  src/background/externalProtocol.ts
  src/background/messenger/external/api.ts
  src/blocks/effects/vue.ts
  src/blocks/readers/frameworkReader.ts
  src/blocks/readers/window.ts
  src/blocks/transformers/component/ComponentReader.ts
  src/blocks/transformers/component/ComponentReaderOptions.tsx
  src/contentScript/contentScriptCore.ts
  src/contentScript/externalProtocol.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor.ts
  src/contentScript/pageEditor/elementPicker.ts
  src/contentScript/pageEditor/insertButton.tsx
  src/contentScript/pageEditor/insertPanel.tsx
  src/contentScript/ready.ts
  src/contrib/pipedrive/readers.ts
  src/messaging/chrome.ts
  src/messaging/protocol.ts
  src/pageEditor/extensionPoints/elementConfig.ts
  src/pageEditor/fields/SelectorSelectorWidget.tsx
  src/pageEditor/tabState/tabStateSlice.ts
  src/pageEditor/tabState/tabStateTypes.ts
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/pageScript/frameworks.ts
  src/pageScript/frameworks/adapters.ts
  src/pageScript/messenger/api.ts
  src/pageScript/messenger/constants.ts
  src/pageScript/messenger/pigeon.ts
  src/pageScript/pageScript.ts
  src/pageScript/protocol.ts
Labels: developer experience, low priority, requires app updates

#5000 #4985: use cache for inferAllTypes
  package-lock.json
  package.json
  src/baseRegistry.ts
  src/blocks/hooks/useAllBlocks.ts
  src/blocks/registry.test.ts
  src/blocks/registry.ts
  src/pageEditor/panes/EditorPane.test.tsx
Labels: performance

#5001 #4863: Make content script injection visible
  src/contentScript/contentScript.ts
  src/development/visualInjection.ts
Labels: developer experience

#4984 #4983: Extract and improve activeTab tracking
  .eslintrc.js
  package-lock.json
  package.json
  src/background/activeTab.ts
  src/background/background.ts
  src/background/browserAction.ts
  src/background/contentScript.test.ts
  src/background/contentScript.ts
  src/background/contextMenus.test.ts
  src/background/deployment.test.ts
  src/contentScript/contentScript.ts
Labels: bug, runtime

#5037 Drop unused selenium testing dependencies
  package-lock.json
  package.json
Labels: dependencies

#5025 Improve logging around `contentScript` loading/deduplication code
  package-lock.json
  package.json
  src/background/browserAction.ts
  src/contentScript/contentScript.ts
  src/contentScript/contentScriptCore.ts
  webpack.config.js
Labels: runtime

#5043 Live and complete permission list in options
  src/hooks/useExtensionPermissions.test.ts
  src/hooks/useExtensionPermissions.ts
  src/options/pages/settings/PermissionsSettings.tsx
  src/testUtils/testHelpers.tsx
Labels: user experience, developer experience, low priority

#5066 Drop unused `file-saver` dependency
  package-lock.json
  package.json
Labels: dependencies

#5074 Adds test that redux serializableCheck fails
  src/options/pages/blueprints/BlueprintsPageLayout.test.tsx
Labels: testing
