Repository pixiebrix/pixiebrix-extension, pull requests merged in 2023-02, with the labels that each got.

#5137 #4697: notify on non-config field errors in workshop
  src/options/pages/brickEditor/useSubmitBrick.test.tsx
  src/options/pages/brickEditor/useSubmitBrick.ts
Labels: bug

#5138 #3751: show in progress indicator on bricks
  src/runtime/pipelineTests/trace.test.ts
  src/runtime/reducePipeline.ts
Labels: bug

#5164 #5163: fix brick cache initialization
  src/baseRegistry.ts
  src/blocks/registry.test.ts
  src/blocks/registry.ts
  src/development/headers.ts
  src/pageEditor/extensionPoints/pipelineMapping.ts
  src/pageEditor/panes/EditorPane.test.tsx
  src/registry/localRegistry.ts
Labels: bug

#5166 Import jest mock for storybook
  .storybook/main.js
Labels: developer experience

#5139 #5135: remove actions from quick bar on update
  src/components/quickBar/QuickBarApp.tsx
  src/components/quickBar/quickBarRegistry.ts
  src/components/quickBar/useActions.test.tsx
  src/components/quickBar/useActions.ts
Labels: bug

#5173 #5172: isolate quickbar from host page hot-keys
  package-lock.json
  package.json
  src/components/quickBar/QuickBarApp.tsx
Labels: bug

#5177 #5176: fix await element performance regression
  package-lock.json
  package.json
  src/blocks/effects/wait.test.ts
  src/blocks/transformers/tourStep/tourStep.test.ts
  src/extensionPoints/helpers.test.ts
  src/extensionPoints/triggerExtension.test.ts
  src/vendors/initialize.js
Labels: performance

#5198 #5134 Bug: Blueprint showing up multiple times in QuickBar
  src/background/activeTab.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/navigation.ts
  src/contentScript/lifecycle.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/options/pages/blueprints/useInstallableViewItemActions.ts
  src/options/pages/blueprints/utils/uninstallRecipe.ts
  src/options/pages/blueprints/utils/useInstall.ts
  src/options/pages/blueprints/utils/useReinstall.test.ts
  src/options/pages/blueprints/utils/useReinstall.ts
  src/options/testHelpers.tsx
  src/pageEditor/PanelContent.test.tsx
  src/pageEditor/PanelContent.tsx
  src/store/dynamicElementStorage.ts
  src/store/extensionsSlice.ts
  src/testUtils/testHelpers.tsx
Labels: bug

#5233 #5211: fix "Set up Quick Bar shortcut" button
  src/components/Effect.tsx
  src/options/pages/marketplace/PermissionsBody.tsx
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/tabs/editRecipeTab/EditRecipe.tsx
  src/pageEditor/tabs/recipeOptionsDefinitions/RecipeOptionsDefinition.tsx
  src/pageEditor/tabs/recipeOptionsValues/RecipeOptionsValues.tsx
  src/sidebar/activateRecipe/ActivateRecipeInputs.tsx
  src/sidebar/activateRecipe/ActivateRecipePanel.test.tsx
  src/sidebar/activateRecipe/__snapshots__/ActivateRecipePanel.test.tsx.snap
Labels: bug

#5208 #5171 uiSchema in integration definition not taking effect in integration configuration
  contrib/services/automation-anywhere.yaml
  src/services/factory.test.ts
  src/services/factory.ts
  src/types/definitions.ts
Labels: bug

#5240 #5239: drop unused Google big query brick
  package-lock.json
  package.json
  src/__mocks__/@/background/messenger/api.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/contrib/google/bigquery/handlers.ts
  src/contrib/google/bigquery/query.ts
  src/contrib/google/initGoogle.ts
  src/contrib/registerContribBlocks.ts
  src/development/headers.ts
Labels: mv3

#5253 Remove unused code for using existing extension point definition
  src/pageEditor/extensionPoints/contextMenu.tsx
  src/pageEditor/extensionPoints/elementConfig.ts
  src/pageEditor/extensionPoints/menuItem.ts
  src/pageEditor/extensionPoints/panel.ts
  src/pageEditor/extensionPoints/quickBar.tsx
  src/pageEditor/extensionPoints/quickBarProvider.ts
  src/pageEditor/extensionPoints/sidebar.tsx
  src/pageEditor/extensionPoints/tour.ts
  src/pageEditor/extensionPoints/trigger.tsx
  src/pageEditor/hooks/useAvailableExtensionPoints.ts
  src/pageEditor/panes/insert/GenericInsertPane.tsx
  src/pageEditor/panes/insert/InsertMenuItemPane.tsx
  src/pageEditor/panes/insert/InsertPanelPane.tsx
  src/pageEditor/panes/insert/useAddExisting.ts
Labels: developer experience

#5252 Provide explicit default for list element in document builder
  src/components/documentBuilder/createNewElement.ts
  src/components/documentBuilder/edit/ListOptions.tsx
Labels: page editor, papercut

#5256 #5255: fix var analysis false positives and enable var analysis
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/analysis/analysisVisitors/varAnalysis/varMap.ts
  src/blocks/PipelineExpressionVisitor.ts
  src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx
  src/contentScript/pageEditor/dynamic.ts
  src/core.ts
  src/extensionPoints/contextMenu.test.ts
  src/extensionPoints/contextMenu.ts
  src/extensionPoints/contextMenuReader.ts
  src/extensionPoints/helpers.ts
  src/extensionPoints/quickBarProviderExtension.tsx
  src/extensionPoints/quickbarProviderExtension.test.ts
  src/extensionPoints/quickbarQueryReader.ts
  src/extensionPoints/triggerEventReaders.ts
  src/extensionPoints/triggerExtension.test.ts
  src/extensionPoints/triggerExtension.ts
  src/extensionPoints/triggerExtensionTypes.ts
  src/extensionPoints/types.ts
  src/options/pages/settings/ExperimentalSettings.tsx
  src/pageEditor/analysisManager.ts
  src/pageEditor/extensionPoints/formStateTypes.ts
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
  src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
  src/pageEditor/utils.ts
  src/store/settingsSlice.ts
  src/store/settingsTypes.ts
Labels: analysis

#5257 Show full version string in extension console footer
  src/layout/Footer.tsx
Labels: developer experience

#5267 #5210: update display names in the workshop to mod and starter brick
  src/options/pages/workshop/CustomBricksCard.tsx
  src/options/pages/workshop/WorkshopPage.tsx
  src/options/pages/workshop/workshopUtils.test.ts
  src/options/pages/workshop/workshopUtils.ts
Labels: papercut

#5269 #5268: infer dynamic output schema for a few bricks
  src/analysis/analysisVisitors/regexAnalysis.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/blocks/transformers/ephemeralForm/formTransformer.test.ts
  src/blocks/transformers/ephemeralForm/formTransformer.ts
  src/blocks/transformers/jquery/JQueryReader.test.ts
  src/blocks/transformers/jquery/JQueryReader.ts
  src/blocks/transformers/regex.test.ts
  src/blocks/transformers/regex.ts
  src/core.ts
  src/types.ts
Labels: analysis

#5271 #5270: fix trigger reader error
  src/extensionPoints/triggerExtension.test.ts
  src/extensionPoints/triggerExtension.ts
Labels: bug, release blocker
