Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-09, with the labels that each got.

#9094 #9089: deployment key does't take effect if team has an associated aa control room
  src/auth/useRequiredPartnerAuth.test.tsx
  src/auth/useRequiredPartnerAuth.ts
  src/extensionConsole/pages/onboarding/SetupPage.test.tsx
Labels: bug, release blocker

#9096 #9095 Fix Mods page table filters (other than active)
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/extensionConsole/pages/mods/listView/ListView.tsx
Labels: bug

#9104 #9093 force session replay recording in sidebar welcome page
  src/sidebar/ConnectedSidebar.test.tsx
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/sidebar.tsx
  src/sidebar/telemetryConstants.ts
  src/telemetry/performance.test.ts
  src/telemetry/performance.ts
Labels: bug

#9074 #8791: Migrate /api/me/ from version 1.0 to 1.1 to remove telemetry organization
  .secrets.baseline
  src/auth/authSelectors.ts
  src/auth/authTypes.ts
  src/auth/authUtils.ts
  src/background/deploymentUpdater.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/components/floatingActions/initFloatingActions.ts
  src/data/model/Me.ts
  src/data/model/MeOrganization.ts
  src/data/service/api.ts
  src/data/service/apiClient.ts
  src/data/service/apiVersioning.ts
  src/data/service/errorService.ts
  src/extensionConsole/pages/packageEditor/PackageHistory.test.tsx
  src/hooks/useIsEnterpriseUser.ts
  src/telemetry/telemetryHelpers.ts
  src/testUtils/factories/authFactories.ts
  src/types/swagger.ts
Labels: 30% time

#9120 #9105: move state controller to content script
  src/bricks/effects/assignModVariable.test.ts
  src/bricks/effects/assignModVariable.ts
  src/bricks/effects/pageState.test.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/stateController.test.ts
  src/contentScript/stateController.ts
  src/platform/platformTypes/stateProtocol.ts
  src/runtime/extendModVariableContext.test.ts
  src/runtime/extendModVariableContext.ts
  src/runtime/pipelineTests/modVariableContext.test.ts
  src/starterBricks/sidebar/sidebarStarterBrick.test.ts
Labels: developer experience

#9122 #9105: make getState and setState async
  src/bricks/effects/assignModVariable.test.ts
  src/bricks/effects/assignModVariable.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/contentScript/pageEditor/runBrickPreview.ts
  src/contentScript/pipelineProtocol/runMapArgs.ts
  src/contentScript/stateController.test.ts
  src/contentScript/stateController.ts
  src/platform/platformTypes/stateProtocol.ts
  src/runtime/extendModVariableContext.test.ts
  src/runtime/extendModVariableContext.ts
  src/runtime/pipelineTests/modVariableContext.test.ts
  src/runtime/reducePipeline.ts
  src/starterBricks/sidebar/sidebarStarterBrick.test.ts
Labels: enhancement

#9108 #9031 Show personal deployments
  src/activation/mapModComponentDefinitionToActivatedModComponent.ts
  src/extensionConsole/pages/mods/labels/SharingLabel.tsx
  src/extensionConsole/pages/mods/utils/buildGetModSharingSource.test.ts
  src/extensionConsole/pages/mods/utils/buildGetModSharingSource.ts
  src/types/contract.ts
  src/types/modComponentTypes.ts
  src/types/modTypes.ts
  src/types/swagger.ts
Labels: enhancement

#9126 #9087 Skip tests for pre-release e2e workflow on msedge/msedge-beta
  end-to-end-tests/pageObjects/extensionsShortcutsPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts
  end-to-end-tests/tests/pageEditor/liveEditing.spec.ts
  end-to-end-tests/tests/regressions/sidebarLinks.spec.ts
  end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarAuth.spec.ts
  end-to-end-tests/utils.ts
Labels: testing

#9121 Bug - Fix click propagation on ellipsis menus
  src/__snapshots__/Storyshots.test.js.snap
  src/components/ellipsisMenu/EllipsisMenu.test.tsx
  src/components/ellipsisMenu/EllipsisMenu.tsx
  src/pageEditor/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
Labels: bug

#9107 #9069: Don't require control room integration for users authenticating with PixieBrix Token
  public/mockServiceWorker.js
  src/auth/useRequiredPartnerAuth.test.tsx
  src/auth/useRequiredPartnerAuth.ts
Labels: bug, enterprise

#9134 #9133: add variables section to mod definition JSON schema
  schemas/recipe.json
Labels: enhancement

#9136 eslint rule for prefer axios mock adapter
  .eslintrc.js
  eslint-local-rules/persistBackgroundData.txt
  eslint-local-rules/preferAxiosMockAdapter.js
  eslint-local-rules/preferAxiosMockAdapter.test.js
  src/activation/useActivateModWizard.test.tsx
  src/activation/useActivateModWizard.ts
  src/background/getBuiltInIntegrationConfigs.ts
  src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.test.tsx
  src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx
  src/contrib/automationanywhere/BotOptions.test.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/extensionConsole/pages/activateMod/IntegrationsBody.test.tsx
  src/extensionConsole/pages/activateMod/IntegrationsBody.tsx
  src/hooks/auth.test.ts
  src/hooks/useAuthOptions.test.ts
  src/hooks/useAuthOptions.ts
  src/integrations/components/RequireIntegrationConfig.test.tsx
  src/sidebar/activateMod/RequireMods.tsx
Labels: developer experience, 30% time

#9135 #9129: slice 1 display banner for in progress and expired team trials
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/TeamTrialBanner.test.tsx
  src/extensionConsole/pages/TeamTrialBanner.tsx
  src/extensionConsole/pages/useTeamTrialStatus.ts
  src/testUtils/factories/organizationFactories.ts
Labels: enhancement

#9141 precommit eslint hook
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  .secrets.baseline
  package.json
Labels: developer experience, 30% time

#9140 #9103 No update button for pinned deployments
  src/extensionConsole/pages/mods/Status.test.tsx
  src/extensionConsole/pages/mods/Status.tsx
  src/extensionConsole/pages/mods/utils/buildGetModVersionStatus.ts
  src/extensionConsole/pages/mods/utils/buildModViewItems.ts
  src/testUtils/factories/modViewItemFactory.ts
  src/types/modTypes.ts
Labels: bug

#9147 #9130: Slice 2 - disable all team mod activate buttons
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateModPage.test.tsx.snap
  src/extensionConsole/pages/mods/Status.tsx
  src/extensionConsole/pages/teamTrials/TeamTrialBanner.test.tsx
  src/extensionConsole/pages/teamTrials/TeamTrialBanner.tsx
  src/extensionConsole/pages/teamTrials/TrialAwareButton.test.tsx
  src/extensionConsole/pages/teamTrials/TrialAwareButton.tsx
  src/extensionConsole/pages/teamTrials/TrialCallToActionLink.tsx
  src/extensionConsole/pages/teamTrials/useGetAllTeamScopes.ts
  src/extensionConsole/pages/teamTrials/useTeamTrialStatus.ts
Labels: enhancement

#9148 #9131: Slice 3 - deactivate all team mods not in a deployment
  src/background/background.ts
  src/background/deploymentUpdater.ts
  src/background/modUpdater.test.ts
  src/background/modUpdater.ts
  src/background/teamTrialUpdater.ts
  src/background/utils/deactivateMod.test.ts
  src/background/utils/deactivateMod.ts
  src/background/utils/deactivateModComponent.test.ts
  src/background/utils/deactivateModComponent.ts
  src/background/utils/deactivateModComponentsAndSaveState.ts
  src/background/utils/saveModComponentStateAndReloadTabs.ts
  src/data/service/backgroundApi.ts
Labels: enhancement

#9153 #9091 create personal deployment console
  src/activation/useActivateMod.test.ts
  src/activation/useActivateMod.ts
  src/activation/useActivateModWizard.ts
  src/data/service/api.ts
  src/data/service/urlPaths.ts
  src/extensionConsole/pages/packageEditor/PackageHistory.tsx
  src/types/contract.ts
Labels: enhancement

#9168 #9150 Introduce SandboxInjectionError and increase sandbox timeouts to 5s
  src/sandbox/messenger/api.ts
  src/utils/injectIframe.tsx
  src/utils/postMessage.ts
Labels: runtime

#9167 Improve typing for api paths and update playwright documentation
  .eslintrc.js
  end-to-end-tests/README.md
  end-to-end-tests/fixtures/modDefinitions.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  src/background/messenger/external/_implementation.ts
  src/data/service/urlPaths.ts
  src/extensionConsole/pages/mods/ModsPageActions.test.tsx
  src/extensionConsole/pages/mods/ModsPageActions.tsx
  src/extensionConsole/pages/mods/Status.tsx
  src/extensionConsole/pages/packageEditor/PackageHistory.test.tsx
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
Labels: developer experience, 30% time

#9172 #9171: Fix EllipsisMenu wrapping to next line
  src/__snapshots__/Storyshots.test.js.snap
  src/components/ellipsisMenu/EllipsisMenu.tsx
  src/pageEditor/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
Labels: bug, regression

#9170 Rename Organizations to Teams in the data model
  .secrets.baseline
  src/auth/authTypes.ts
  src/auth/authUtils.ts
  src/auth/selectAuthUserOrganizations.ts
  src/auth/useRequiredPartnerAuth.ts
  src/background/teamTrialUpdater.ts
  src/components/fields/schemaFields/widgets/DatabaseCreateModal.tsx
  src/components/floatingActions/initFloatingActions.ts
  src/data/model/Me.ts
  src/data/model/MeTeam.ts
  src/data/model/MeTeamMembership.ts
  src/data/model/Organization.ts
  src/data/model/Team.ts
  src/data/model/TeamMembershipGroups.ts
  src/data/model/TeamMembershipUser.ts
  src/data/model/TeamMemberships.ts
  src/data/model/TeamTheme.ts
  src/data/model/UserRole.ts
  src/data/service/api.ts
  src/data/service/backgroundApi.ts
  src/data/service/responseTypeHelpers.ts
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/extensionConsole/pages/mods/onboardingView/OnboardingView.test.tsx
  src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx
  src/extensionConsole/pages/packageEditor/SharingTable.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageResult.tsx
  src/hooks/useDatabaseOptions.ts
  src/testUtils/factories/authFactories.ts
Labels: developer experience, 30% time

#9155 #9154: mod variable session sync (2/3)
  end-to-end-tests/tests/runtime/modVariables/variableSync.spec.ts
  end-to-end-tests/utils.ts
  src/background/background.ts
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/stateController.test.ts
  src/contentScript/stateController.ts
  src/platform/platformTypes/stateProtocol.ts
  src/platform/state/stateTypes.ts
  src/starterBricks/types.ts
  src/testUtils/platformMock.ts
Labels: enhancement

#9181 #9156: tab synchronized mod variable storage (3/3)
  end-to-end-tests/tests/runtime/modVariables/variableSync.spec.ts
  src/background/background.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/stateControllerListeners.test.ts
  src/background/stateControllerListeners.ts
  src/bricks/effects/pageState.test.ts
  src/bricks/renderers/customForm.test.tsx
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/stateController/modVariablePolicyController.ts
  src/contentScript/stateController/stateController.test.ts
  src/contentScript/stateController/stateController.ts
  src/contentScript/stateController/stateEventHelpers.ts
  src/platform/platformTypes/stateProtocol.ts
  src/platform/state/stateHelpers.test.ts
  src/platform/state/stateHelpers.ts
  src/platform/state/stateTypes.ts
  src/store/deactivateUtils.ts
Labels: enhancement, do not merge

#9195 fix sweepLogs abort functionality
  src/telemetry/logging.test.ts
  src/telemetry/logging.ts
Labels: bug

#9149 Add Mixpanel Lexicon to version control
  .github/workflows/upload-mixpanel-lexicon.yml
  knip.mjs
  scripts/uploadMixpanelLexicon.ts
  src/telemetry/lexicon.ts
Labels: telemetry, 30% time

#9201 #9198: properly serialize axios errors in report error, and skip non mod logs for idb
  end-to-end-tests/tests/runtime/localIntegrations.spec.ts
  end-to-end-tests/tests/telemetry/errors.spec.ts
  src/components/errors/NetworkErrorDetail.tsx
  src/data/service/errorService.ts
  src/data/service/requestErrorUtils.ts
  src/errors/clientRequestErrors.ts
  src/errors/networkErrorHelpers.ts
  src/telemetry/logging.ts
  src/telemetry/reportError.test.ts
  src/telemetry/reportError.ts
  src/utils/enrichAxiosErrors.ts
Labels: bug

#9205 Fix managed schema JSON Schema documentation for `disableBrowserWarning`
  src/store/enterprise/managedStorageTypes.ts
Labels: documentation

#9203 #9202: add with cache brick with memoization/expiry
  src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts
  src/bricks/transformers/controlFlow/WithCache.test.ts
  src/bricks/transformers/controlFlow/WithCache.ts
  src/bricks/transformers/getAllTransformers.ts
  src/development/headers.test.ts
  src/runtime/pipelineTests/pipelineTestHelpers.ts
Labels: enhancement, brick

#9207 #9200 Remove save button from components - Slice 1
  end-to-end-tests/fixtures/modDefinitions/brick-actions.yaml
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-added.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-copy-pasted.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-removed.diff
  end-to-end-tests/tests/pageEditor/brickConfiguration.spec.ts
  src/__snapshots__/Storyshots.test.js.snap
  src/bricks/exampleBrickConfigs.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/modListingPanel/ActionMenu.tsx
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModComponents.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
Labels: enhancement, user experience, page editor

#9199 removes no-unnecessary-type-assertion eslint disables
  .eslintrc.js
  src/analysis/analysisSlice.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/background/auth/codeGrantFlow.ts
  src/background/auth/implicitGrantFlow.ts
  src/background/auth/partnerIntegrations/launchAuthIntegration.test.ts
  src/background/modUpdater.test.ts
  src/contrib/google/sheets/core/useSpreadsheetId.ts
  src/extensionConsole/pages/mods/ModsPageActions.test.tsx
  src/integrations/store/integrationsSlice.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/store/editorMigrations.test.ts
  src/utils/extensionUtils.ts
  src/utils/parseDomTable.ts
  src/vendors/reactPerformanceTesting/getPatchedComponent.ts
Labels: 30% time
