Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-08, with the labels that each got.

#8961 Strict null checks -- 93.2%
  src/bricks/readers/getAllReaders.ts
  src/bricks/transformers/jquery/JQueryReaderOptions.tsx
  src/contrib/automationanywhere/RunApiTask.ts
  src/contrib/zapier/PushOptions.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/activateMod/ActivateModDefinitionPage.tsx
  src/extensionConsole/pages/deployments/DeploymentModal.tsx
  src/extensionConsole/pages/mods/listView/ListView.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModalBody.tsx
  src/extensionConsole/pages/mods/modals/shareModals/CancelPublishContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/EditPublishContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishModContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishModModals.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishedContent.tsx
  src/pageEditor/panes/ModEditorPane.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/sidebarSelectors.ts
  src/store/extensionsSelectors.ts
  src/store/settings/settingsSelectors.ts
  src/store/sidebar/eventKeyUtils.test.ts
  src/store/sidebar/eventKeyUtils.tsx
  src/store/sidebar/initialState.ts
  src/store/sidebar/sidebarSlice.test.ts
  src/tsconfig.strictNullChecks.json
  src/types/sidebarTypes.ts
  src/utils/registryUtils.ts
Labels: developer experience

#8963 Trigger correct events
  end-to-end-tests/tests/runtime/customEvents.spec.ts
  jest.config.js
  package-lock.json
  package.json
  src/bricks/effects/customEvent.ts
  src/bricks/effects/event.ts
  src/utils/domFieldUtils.ts
Labels: runtime

#8971 #8587: Fix bad logging MessageContext
  end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts
  end-to-end-tests/tests/pageEditor/logsPane.spec.ts
  src/components/logViewer/LogCard.tsx
  src/components/logViewer/logSlice.ts
  src/components/logViewer/logViewerTypes.ts
  src/extensionConsole/pages/mods/modals/modLogsModal/ModLogsModal.tsx
  src/extensionConsole/pages/packageEditor/useLogContext.ts
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/panes/ModEditorPane.tsx
  src/types/loggerTypes.ts
Labels: bug

#8960 Add support for brick feature flags
  knip.mjs
  src/bricks/effects/captureAudio.ts
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/onboarding/SetupPage.test.tsx
  src/extensionConsole/pages/packageEditor/Editor.tsx
  src/hooks/useFlags.ts
  src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
  src/pageEditor/modals/addBrickModal/AddBrickModal.tsx
  src/runtime/pipelineTests/featureFlag.test.ts
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/runtime/reducePipeline.ts
  src/store/enterprise/managedStorage.ts
  src/store/enterprise/useManagedStorageState.test.ts
  src/tsconfig.strictNullChecks.json
  src/types/registryTypes.ts
Labels: developer experience

#8985 Update mod options form tab name to match form builder
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
Labels: user experience, page editor

#8987 #8976: show sidebar brick not showing active tab
  src/bricks/effects/sidebarEffects.ts
  src/contentScript/sidebarController.tsx
  src/sidebar/protocol.tsx
  src/store/sidebar/sidebarSlice.ts
Labels: bug, sidebar

#8989 #8979 Migrate standalone mod components
  src/auth/authUtils.ts
  src/background/deploymentUpdater.test.ts
  src/background/starterMods.test.ts
  src/contentScript/loadActivationEnhancementsCore.test.ts
  src/mods/utils/mapStandaloneModDefinitionToModDefinition.ts
  src/pageEditor/hooks/useMigrateStandaloneComponentsToMods.ts
  src/pageEditor/layout/EditorLayout.tsx
  src/store/extensionsMigrations.test.ts
  src/store/extensionsMigrations.ts
  src/store/extensionsStorage.test.ts
  src/store/extensionsStorage.ts
  src/store/extensionsTypes.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement, developer experience

#8988 Strict null checks -- 94.6%
  src/background/contextMenus/initContextMenus.ts
  src/background/deploymentUpdater.ts
  src/background/modUpdater.ts
  src/bricks/transformers/temporaryInfo/EphemeralPanel.tsx
  src/components/formBuilder/FormBuilder.tsx
  src/components/packageSearchModal/PackageDetail.tsx
  src/components/packageSearchModal/PackageSearchModal.tsx
  src/components/packageSearchModal/QuickAdd.tsx
  src/errors/networkErrorHelpers.ts
  src/extensionConsole/pages/activateMod/ActivateModDefinitionIdPage.tsx
  src/extensionConsole/pages/mods/modals/shareModals/CancelPublishContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishModContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/ShareModModalBody.tsx
  src/extensionConsole/pages/mods/modals/shareModals/useHasEditPermissions.ts
  src/extensionConsole/pages/packageEditor/EditPage.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.tsx
  src/extensionConsole/pages/packageEditor/useSubmitPackage.ts
  src/modDefinitions/modDefinitionHooks.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModComponents.tsx
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/store/editor/editorSelectors.ts
  src/sidebar/ConnectedSidebar.tsx
  src/tsconfig.strictNullChecks.json
  src/types/registryTypes.ts
  src/utils/registryUtils.ts
Labels: developer experience

#9002 Fix the form state cleanup related to standalone mod component migration
  end-to-end-tests/pageObjects/basePageObject.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  src/pageEditor/hooks/useMigrateStandaloneComponentsToMods.ts
Labels: bug, regression

#8982 #8953 Add GitHub Workflow for running e2e tests on pre-release browsers
  .env.example
  .github/workflows/e2e-test-pre-release-browsers.yml
  .github/workflows/end-to-end-tests.yml
  .secrets.baseline
  end-to-end-tests/README.md
  end-to-end-tests/env.ts
  end-to-end-tests/fixtures/authentication.ts
  end-to-end-tests/fixtures/pageContext.ts
  end-to-end-tests/fixtures/utils.ts
  end-to-end-tests/pageObjects/extensionsShortcutsPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/regressions/sidebarLinks.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarAuth.spec.ts
  playwright.config.ts
Labels: developer experience, testing

#9008 improve end-to-end test flakiness
  end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarActivation.spec.ts
Labels: developer experience, testing

#9006 #8980 Remove standalone mod api calls
  end-to-end-tests/tests/telemetry/errors.spec.ts
  src/activation/mapModComponentDefinitionToActivatedModComponent.ts
  src/activation/useActivateMod.ts
  src/data/service/api.ts
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/activateMod/ActivateModDefinitionIdPage.tsx
  src/extensionConsole/pages/activateMod/ActivateModPage.test.tsx
  src/extensionConsole/pages/activateMod/ActivateModPage.tsx
  src/extensionConsole/pages/activateMod/ActivateStandaloneModDefinitionIdPage.test.tsx
  src/extensionConsole/pages/activateMod/ActivateStandaloneModDefinitionIdPage.tsx
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateModPage.test.tsx.snap
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateStandaloneModDefinitionIdPage.test.tsx.snap
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/extensionConsole/pages/mods/hooks/useModsPageActions.ts
  src/extensionConsole/pages/mods/modals/Modals.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModalBody.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/__snapshots__/ConvertToModModal.test.tsx.snap
  src/extensionConsole/pages/mods/modals/modModalsSelectors.ts
  src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts
  src/modDefinitions/util/pickModDefinitionMetadata.test.ts
  src/modDefinitions/util/pickModDefinitionMetadata.ts
  src/mods/hooks/useDeleteStandaloneModDefinitionAction.ts
  src/mods/useMods.test.ts
  src/mods/useMods.ts
  src/mods/utils/mapStandaloneModDefinitionToModDefinition.test.ts
  src/mods/utils/mapStandaloneModDefinitionToModDefinition.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/runtime/runtimeUtils.ts
  src/store/checkAvailableActivatedModComponents.test.ts
  src/store/extensionsSlice.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/testUtils/factories/modComponentFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/contract.ts
Labels: developer experience

#9012 DX - Add more tests to mod component redux-persist migrations
  src/extensionConsole/pages/mods/ModsPage.tsx
  src/extensionConsole/pages/mods/hooks/useShowPublishUrlEffect.tsx
  src/store/modComponents/modComponentMigrations.test.ts
  src/store/modComponents/modComponentMigrations.ts
  src/store/modComponents/modComponentTypes.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience, testing

#9017 Rename remaining uses of service context to integration context
  eslint-local-rules/persistBackgroundData.txt
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/bricks/transformers/brickFactory.ts
  src/bricks/transformers/controlFlow/IfElse.test.ts
  src/components/fields/schemaFields/widgets/varPopup/SourceLabel.tsx
  src/components/fields/schemaFields/widgets/varPopup/menuFilters.ts
  src/contentScript/pipelineProtocol/runHeadlessPipeline.ts
  src/contentScript/pipelineProtocol/runRendererPipeline.ts
  src/integrations/util/makeIntegrationContextFromDependencies.ts
  src/pageEditor/tabs/effect/BrickPreview.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/runtime/pipelineTests/integrationContext.test.ts
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/runtime/pipelineTests/validateInput.test.ts
  src/runtime/reducePipeline.ts
  src/starterBricks/button/buttonStarterBrick.ts
  src/starterBricks/contextMenu/contextMenuStarterBrick.ts
  src/starterBricks/dynamicQuickBar/dynamicQuickBarStarterBrick.tsx
  src/starterBricks/quickBar/quickBarStarterBrick.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/tsconfig.strictNullChecks.json
  src/types/runtimeTypes.ts
Labels: developer experience

#9025 #8526: fallback button starter brick on invalid template
  src/runtime/renderers.test.ts
  src/runtime/renderers.ts
  src/starterBricks/button/buttonStarterBrick.test.ts
  src/starterBricks/button/buttonStarterBrick.ts
  src/tsconfig.strictNullChecks.json
  src/utils/domUtils.test.ts
  src/utils/domUtils.ts
Labels: bug

#9026 #8860: show activated mod metadata in mod metadata form
  src/components/AsyncStateGate.tsx
  src/pageEditor/tabs/MatchRulesSection.test.tsx
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.test.tsx
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  src/tsconfig.strictNullChecks.json
  src/types/modComponentTypes.ts
Labels: bug

#9018 Introduce feature flag constants
  src/auth/featureFlagStorage.test.ts
  src/auth/featureFlagStorage.ts
  src/auth/featureFlags.ts
  src/background/deploymentUpdater.ts
  src/background/modUpdater.ts
  src/background/navigation.ts
  src/bricks/effects/captureAudio.ts
  src/components/floatingActions/initFloatingActions.ts
  src/components/quickBar/QuickBarApp.tsx
  src/components/quickBar/useActions.test.tsx
  src/contentScript/contentScriptCore.ts
  src/contentScript/contentScriptPlatform.test.ts
  src/contentScript/contentScriptPlatform.ts
  src/data/service/errorService.ts
  src/extensionConsole/App.tsx
  src/extensionConsole/Sidebar.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/useAutoDeploy.ts
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/extensionConsole/pages/mods/hooks/useReactivateAction.ts
  src/extensionConsole/pages/mods/hooks/useViewPublishAction.ts
  src/extensionConsole/pages/mods/onboardingView/useOnboarding.tsx
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/extensionConsole/pages/settings/SettingsPage.tsx
  src/hooks/useFlags.test.tsx
  src/hooks/useFlags.ts
  src/mods/hooks/useDeactivateAction.ts
  src/mods/hooks/useEditInWorkshopAction.ts
  src/pageEditor/layout/EditorLayout.tsx
  src/pageEditor/modListingPanel/ModListingPanel.tsx
  src/pageEditor/starterBricks/dynamicQuickBar.ts
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/tabs/editTab/FoundationNodeConfigPanel.tsx
  src/pageEditor/tabs/editTab/dataPanel/BrickDataPanel.tsx
  src/pageEditor/tabs/editTab/dataPanel/StarterBrickDataPanel.tsx
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/sidebar/DefaultPanel.tsx
  src/sidebar/Header.tsx
  src/sidebar/modLauncher/ModLauncher.tsx
  src/starterBricks/dynamicQuickBar/dynamicQuickBarStarterBrick.test.ts
  src/starterBricks/quickBar/quickBarStarterBrick.test.ts
  src/telemetry/logging.ts
  src/telemetry/performance.ts
  src/testUtils/factories/featureFlagFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/registryTypes.ts
Labels: developer experience

#9029 #9028: flag to force sidebar RUM recording during onboarding
  src/auth/featureFlags.ts
  src/sidebar/sidebar.tsx
  src/telemetry/performance.ts
  src/utils/urlUtils.ts
Labels: telemetry

#9030 Strict null checks: 95.7%
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/modListingPanel/ModListItem.test.tsx
  src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
  src/pageEditor/starterBricks/base.test.ts
  src/pageEditor/starterBricks/pipelineMapping.test.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/tabs/editTab/dataPanel/BrickDataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/StarterBrickDataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/CommentsTab.test.tsx
  src/pageEditor/tabs/editTab/editHelpers.test.ts
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/CommentsPreview.test.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.test.tsx
  src/pageEditor/tabs/trigger/TriggerConfiguration.test.tsx
  src/registry/packageRegistry.test.ts
  src/runtime/pipelineTests/validateInput.test.ts
  src/sidebar/Tabs.test.tsx
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/starterBricks/starterBrickModUtils.test.ts
  src/store/checkAvailableActivatedModComponents.test.ts
  src/store/editorStorage.test.ts
  src/store/sidebar/sidebarSlice.test.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#9032 Introduce milestones constant
  src/auth/useRequiredPartnerAuth.test.tsx
  src/auth/useRequiredPartnerAuth.ts
  src/data/model/UserMilestone.ts
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/hooks/useMilestones.test.ts
  src/hooks/useMilestones.ts
  src/testUtils/factories/milestoneFactories.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#9033 #9015: improve sidebar diagnostics telemetry
  src/sidebar/Tabs.tsx
  src/sidebar/hooks/useHideEmptySidebarEffect.ts
  src/sidebar/sidebarSelectors.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience, telemetry

#9036 fix integration dependency validation in the extension console
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/smoke/sidebar.spec.ts
  src/activation/useActivateModWizard.ts
  src/integrations/components/IntegrationAuthSelector.tsx
Labels: bug, regression

#9035 Revert "Bump iframe-resizer from 4.4.5 to 5.2.4"
  package-lock.json
  package.json
Labels: bug, dependencies, regression

#9038 Strict null checks -- 98.0%
  src/components/fields/schemaFields/widgets/SchemaButtonVariantWidget.test.tsx
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
  src/components/fields/schemaFields/widgets/varPopup/menuFilters.test.ts
  src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.test.ts
  src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.ts
  src/components/form/Form.stories.tsx
  src/components/form/makeFieldActionForAnnotationAction.test.tsx
  src/components/form/widgets/AsyncRemoteSelectWidget.test.tsx
  src/components/form/widgets/RegistryIdWidget.test.tsx
  src/components/formBuilder/FormBuilder.stories.tsx
  src/components/formBuilder/FormBuilder.test.tsx
  src/components/formBuilder/edit/FormEditor.test.tsx
  src/components/integrations/AuthWidget.test.tsx
  src/components/integrations/IntegrationConfigEditorModal.test.tsx
  src/contentScript/lifecycle.test.ts
  src/contrib/automationanywhere/BotOptions.test.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/extensionConsole/pages/activateMod/ActivateModPage.test.tsx
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateModPage.test.tsx.snap
  src/extensionConsole/pages/deployments/DeploymentModal.stories.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx
  src/extensionConsole/pages/deployments/useAutoDeploy.test.ts
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/extensionConsole/pages/mods/onboardingView/OnboardingView.stories.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.stories.tsx
  src/extensionConsole/pages/packageEditor/useSubmitPackage.test.tsx
  src/integrations/components/RequireIntegrationConfig.test.tsx
  src/modDefinitions/modDefinitionPermissionsHelpers.test.ts
  src/modDefinitions/modDefinitions.test.tsx
  src/pageEditor/components/DimensionGate.stories.tsx
  src/pageEditor/documentBuilder/documentTree.test.tsx
  src/pageEditor/documentBuilder/edit/DocumentOptions.test.tsx
  src/pageEditor/documentBuilder/hooks/useMoveElement.test.ts
  src/pageEditor/documentBuilder/preview/DocumentPreview.test.tsx
  src/pageEditor/documentBuilder/preview/ElementPreview.test.tsx
  src/pageEditor/fields/FormModalOptions.test.tsx
  src/pageEditor/fields/FormRendererOptions.test.tsx
  src/pageEditor/fields/PipelineToggleField.test.tsx
  src/pageEditor/fields/UrlMatchPatternField.stories.tsx
  src/pageEditor/fields/UrlPatternField.stories.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#9042 #9014: race condition waiting for welcome mods to be activated on first run
  src/background/background.ts
  src/background/messenger/api.ts
  src/background/messenger/external/_implementation.ts
  src/background/messenger/external/api.ts
  src/background/messenger/registration.ts
  src/background/welcomeMods.test.ts
  src/background/welcomeMods.ts
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/telemetry/reportEvent.ts
  src/tsconfig.strictNullChecks.json
Labels: bug

#9045 Fix bug with form state migration
  src/pageEditor/hooks/useMigrateStandaloneComponentsToMods.test.ts
  src/pageEditor/hooks/useMigrateStandaloneComponentsToMods.ts
  src/tsconfig.strictNullChecks.json
Labels: bug, regression, release blocker

#9048 Strict null checks -- 99.7%
  src/activation/useActivateMod.test.ts
  src/activation/useActivateModWizard.test.tsx
  src/analysis/analysisVisitors/regexAnalysisTest.test.ts
  src/analysis/analysisVisitors/traceAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/auth/authStorage.test.ts
  src/auth/useRequiredPartnerAuth.test.tsx
  src/background/contextMenus/initContextMenus.test.ts
  src/background/deploymentUpdater.test.ts
  src/background/initBrowserCommands.ts
  src/background/modUpdater.test.ts
  src/background/welcomeMods.test.ts
  src/bricks/PipelineExpressionVisitor.test.ts
  src/bricks/PipelineVisitor.test.ts
  src/bricks/effects/AddDynamicTextSnippet.test.ts
  src/bricks/effects/AddTextSnippets.test.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/transformers/FormData.test.ts
  src/bricks/transformers/brickFactory.test.ts
  src/bricks/transformers/jquery/JQueryReaderOptions.test.tsx
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/bricks/transformers/temporaryInfo/EphemeralPanel.test.tsx
  src/components/fields/schemaFields/SchemaField.test.tsx
  src/components/fields/schemaFields/getToggleOptions.test.ts
  src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.test.ts
  src/components/fields/schemaFields/widgets/CodeEditorWidget.test.tsx
  src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx
  src/components/fields/schemaFields/widgets/cssClassWidgets/CssClassWidget.stories.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience, 30% time

#9063 #9039: restrict public marketplace activation
  src/__mocks__/@/auth/featureFlagStorage.ts
  src/activation/useActivateModWizard.test.tsx
  src/activation/useActivateModWizard.ts
  src/activation/useOrganizationActivationPolicy.ts
  src/background/welcomeMods.test.ts
  src/background/welcomeMods.ts
  src/hooks/useFlags.ts
  src/tsconfig.strictNullChecks.json
Labels: enterprise

#9067 Bug - Fix redux persist migrations for sidebar state, related to welcome mod activation
  src/store/migratePersistedState.test.ts
  src/store/migratePersistedState.ts
Labels: bug

#9070 remove a non-null assertion for ModComponentFormStateWizard
  src/pageEditor/layout/ModComponentFormStateWizard.tsx
Labels: developer experience, 30% time

#9047 #9046 Fix unlinked extension console bug
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  src/__snapshots__/Storyshots.test.js.snap
  src/extensionConsole/pages/mods/ModsPage.test.tsx
  src/extensionConsole/pages/mods/ModsPage.tsx
  src/extensionConsole/pages/mods/ModsPageContent.tsx
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/extensionConsole/pages/mods/ModsPageTableLayout.test.tsx
  src/extensionConsole/pages/mods/__snapshots__/ModsPageTableLayout.test.tsx.snap
  src/extensionConsole/pages/mods/modsPageSelectors.ts
  src/extensionConsole/pages/mods/modsPageSlice.ts
  src/extensionConsole/pages/mods/onboardingView/OnboardingView.stories.tsx
  src/extensionConsole/pages/mods/onboardingView/OnboardingView.tsx
  src/extensionConsole/store.ts
  src/testUtils/testHelpers.tsx
  src/utils/asyncStateUtils.ts
Labels: bug, regression

#9077 Bug fix - Navigate to mods tab when extension token is cleared
  src/auth/RequireAuth.tsx
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
Labels: bug

#9078 #9065: allow dependabot to write the playwright report comment to the PR
  .github/workflows/ci.yml
Labels: 30% time
