Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-06, with the labels that each got.

#8536 #8519: add text option only when select is not an option in non-expression contexts
  src/components/fields/schemaFields/BasicSchemaField.test.tsx
  src/components/fields/schemaFields/getToggleOptions.test.ts
  src/components/fields/schemaFields/getToggleOptions.tsx
  src/sidebar/activateMod/ActivateModPanel.module.scss
Labels: bug, user experience

#8533 #6529: fix starter brick duplication on save; normalize mod definition structure on save
  src/bricks/available.test.ts
  src/bricks/available.ts
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/starterBricks/base.test.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/menuItem.ts
  src/pageEditor/starterBricks/panel.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/quickBarProvider.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/tour.ts
  src/pageEditor/starterBricks/trigger.ts
  src/starterBricks/quickBar/quickBarExtension.tsx
  src/starterBricks/quickBarProvider/quickBarProviderExtension.tsx
  src/starterBricks/starterBrickUtils.ts
  src/starterBricks/types.ts
  src/store/checkActiveElementAvailability.test.ts
  src/store/checkAvailableDynamicElements.test.ts
  src/testUtils/factories/modDefinitionFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/availabilityTypes.ts
  src/types/registryTypes.ts
  src/utils/modUtils.ts
Labels: bug

#8542 Strict null checks next
  src/background/executor.test.ts
  src/background/messenger/external/_implementation.ts
  src/bricks/effects/attachAutocomplete.test.ts
  src/bricks/effects/clipboard.test.ts
  src/bricks/effects/customEvent.test.ts
  src/bricks/effects/disable.test.ts
  src/bricks/effects/enable.test.ts
  src/bricks/effects/event.test.ts
  src/bricks/effects/forms.test.ts
  src/bricks/effects/hide.test.ts
  src/bricks/effects/highlight.test.ts
  src/bricks/effects/highlightText.test.ts
  src/bricks/effects/postMessage.test.ts
  src/bricks/effects/replaceText.test.ts
  src/bricks/effects/scrollToElement.test.ts
  src/bricks/effects/show.test.ts
  src/bricks/effects/wait.test.ts
  src/bricks/registry.test.ts
  src/bricks/transformers/IdentityTransformer.test.ts
  src/bricks/transformers/component/TableReader.test.ts
  src/bricks/transformers/detect.test.ts
  src/bricks/transformers/ephemeralForm/formTransformer.test.ts
  src/bricks/transformers/readable.test.ts
  src/bricks/transformers/selectElement.test.ts
  src/bricks/transformers/tourStep/tourStep.test.ts
  src/contentScript/loadActivationEnhancementsCore.test.ts
  src/contentScript/sidebarActivation.ts
  src/contrib/automationanywhere/RunApiTask.test.ts
  src/contrib/automationanywhere/RunBot.test.ts
  src/contrib/automationanywhere/RunBot.ts
  src/extensionConsole/pages/brickEditor/BrickHistory.test.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/onboarding/SetupPage.tsx
  src/layout/EnvironmentBanner.tsx
  src/runtime/pipelineTests/root.test.ts
  src/runtime/reducePipeline.ts
  src/store/extensionsStorage.ts
  src/testUtils/factories/runtimeFactories.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8527 #8327: toggle for running mod only in the top-level frame
  end-to-end-tests/tests/runtime/allFrames.spec.ts
  src/bricks/available.test.ts
  src/bricks/available.ts
  src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.test.ts
  src/pageEditor/starterBricks/base.test.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/tabs/menuItem/MenuItemConfiguration.tsx
  src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
  src/types/availabilityTypes.ts
Labels: enhancement

#8547 #8543: Adding detect-secrets precommit
  .pre-commit-config.yaml
  .secrets.baseline
Labels: developer experience

#8544 Strict null checks next 2
  src/components/documentBuilder/preview/DocumentPreview.test.tsx
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/elementConfig.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/menuItem.ts
  src/pageEditor/starterBricks/panel.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/quickBarProvider.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/tour.ts
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/tabs/editTab/editHelpers.ts
  src/pageEditor/tabs/trigger/TriggerConfiguration.test.tsx
  src/pageEditor/uiState/uiStateTypes.ts
  src/starterBricks/contextMenu/contextMenu.test.ts
  src/starterBricks/menuItem/menuItemExtension.test.ts
  src/starterBricks/quickBar/quickBarExtension.test.ts
  src/starterBricks/quickBarProvider/quickbarProviderExtension.test.ts
  src/starterBricks/sidebar/sidebarExtension.test.ts
  src/starterBricks/triggerExtension.test.ts
  src/starterBricks/triggerExtension.ts
  src/testUtils/factories/deploymentFactories.ts
  src/tsconfig.strictNullChecks.json
  src/utils/deploymentUtils.test.ts
Labels: developer experience

#8545 encrypt playwright report artifact
  .github/workflows/ci.yml
  .gitignore
  end-to-end-tests/README.md
Labels: testing

#8538 #8058 sheets e2e test
  .env.example
  .github/workflows/ci.yml
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/env.ts
  end-to-end-tests/pageObjects/extensionConsole/localIntegrationsPage.ts
  end-to-end-tests/pageObjects/external/googleAuthPopup.ts
  end-to-end-tests/tests/runtime/googleSheetsIntegration.spec.ts
  end-to-end-tests/utils.ts
  package-lock.json
  package.json
  playwright.config.ts
  src/integrations/components/IntegrationAuthSelector.tsx
Labels: testing

#8560 #8058 make sheets e2e local only and wait for google email label to be present in setup
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/tests/runtime/googleSheetsIntegration.spec.ts
Labels: testing

#8557 #8553: fix mod saving invariant checks in Page Editor
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/sidebar/modals/CreateModModal.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/selectors/selectGetCleanComponentsAndDirtyFormStatesForMod.ts
Labels: bug, regression, release blocker

#8558 Restrict sidebar activation redirection to PixieBrix domains
  end-to-end-tests/tests/runtime/sidebarActivation.spec.ts
  src/activation/activationLinkUtils.ts
  src/utils/urlUtils.test.ts
  src/utils/urlUtils.ts
Labels: bug

#8563 #8546: Add an error-once, and never report mode for trigger extensions
  src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/starterBricks/triggerExtension.test.ts
  src/starterBricks/triggerExtension.ts
  src/starterBricks/triggerExtensionTypes.ts
Labels: telemetry

#8564 Split playwright runs into chrome and edge runs
  .github/workflows/ci.yml
  .gitignore
  .secrets.baseline
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/env.ts
  end-to-end-tests/pageObjects/external/googleAuthPopup.ts
  playwright.config.ts
Labels: testing

#8577 Extract end-to-end tests job into own github action workflow
  .github/workflows/beta-release.yaml
  .github/workflows/ci.yml
  .github/workflows/end-to-end-tests.yml
  .secrets.baseline
Labels: infrastructure, testing

#8628 #4887: move add brick modal to `pageEditor` and rename
  src/pageEditor/Modals.tsx
  src/pageEditor/modals/addBrickModal/AddBrickModal.module.scss
  src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
  src/pageEditor/modals/addBrickModal/AddBrickModal.tsx
  src/pageEditor/modals/addBrickModal/BrickDetail.tsx
  src/pageEditor/modals/addBrickModal/BrickGridItem.module.scss
  src/pageEditor/modals/addBrickModal/BrickGridItem.tsx
  src/pageEditor/modals/addBrickModal/BrickGridItemRenderer.tsx
  src/pageEditor/modals/addBrickModal/QuickAdd.module.scss
  src/pageEditor/modals/addBrickModal/TagList.module.scss
  src/pageEditor/modals/addBrickModal/TagList.tsx
  src/pageEditor/modals/addBrickModal/TagSearchInput.module.scss
  src/pageEditor/modals/addBrickModal/TagSearchInput.tsx
  src/pageEditor/modals/addBrickModal/__snapshots__/AddBrickModal.test.tsx.snap
  src/pageEditor/modals/addBrickModal/addBrickModalConstants.ts
  src/pageEditor/modals/addBrickModal/addBrickModalHelpers.ts
  src/pageEditor/modals/addBrickModal/addBrickModalTypes.ts
  src/pageEditor/modals/addBrickModal/addBrickModalVariables.scss
  src/pageEditor/modals/addBrickModal/groupListingsByTag.test.ts
  src/pageEditor/modals/addBrickModal/groupListingsByTag.ts
  src/pageEditor/modals/addBrickModal/useAddBrick.ts
  src/pageEditor/modals/addBrickModal/useBrickSearch.ts
  src/pageEditor/panes/EditorPane.test.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8634 #8605: link directly to mod re-activation from Page Editor version warning
  src/extensionConsole/pages/mods/hooks/useActivateAction.ts
  src/extensionConsole/shared/routeHelpers.ts
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  src/tsconfig.strictNullChecks.json
Labels: enhancement, user experience

#8632 #8601: drop legacy label copy from data binding locations
  src/bricks/effects/pageState.ts
Labels: user experience

#8631 #8600: drop deprecated `localStorage` data binding for embedded forms
  src/__mocks__/@/background/messenger/api.ts
  src/background/dataStore.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/renderers/customForm.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/testUtils/factories/runtimeFactories.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience, brick

#8635 #8404: fix variable path regex to not switch to text entry mode during optional chaining
  src/components/fields/schemaFields/widgets/TextWidget.test.tsx
  src/components/fields/schemaFields/widgets/TextWidget.tsx
Labels: bug, page editor

#8637 #8636: fix search/insert for variable popover using optional chaining
  src/components/fields/schemaFields/widgets/varPopup/VarPopup.tsx
  src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.test.ts
  src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.ts
  src/components/fields/schemaFields/widgets/varPopup/menuFilters.test.ts
  src/components/fields/schemaFields/widgets/varPopup/menuFilters.ts
  src/runtime/pathHelpers.test.ts
  src/runtime/pathHelpers.ts
Labels: bug, page editor

#8641 #8607 Rename editorPermissionsHelpers and ElementWizard
  src/pageEditor/ModComponentFormStateWizard.module.scss
  src/pageEditor/ModComponentFormStateWizard.tsx
  src/pageEditor/editorPermissionsHelpers.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/toolbar/PermissionsToolbar.tsx
  src/pageEditor/toolbar/ReloadToolbar.tsx
Labels: developer experience

#8644 #8283: webext-messenger -> 0.28.0
  package-lock.json
  package.json
Labels: bug, dependencies

#8639 #6656: DX - Move partner auth functions into separate files
  src/auth/authStorage.ts
  src/auth/usePartnerAuthData.ts
  src/background/auth/partnerIntegrations/getPartnerPrincipals.test.ts
  src/background/auth/partnerIntegrations/getPartnerPrincipals.ts
  src/background/auth/partnerIntegrations/launchAuthIntegration.ts
  src/background/auth/partnerIntegrations/partnerIntegrations.test.ts
  src/background/auth/partnerIntegrations/partnerIntegrations.ts
  src/background/auth/partnerIntegrations/types.ts
  src/background/background.ts
  src/background/messenger/external/api.ts
  src/background/messenger/registration.ts
  src/background/partnerIntegrations.ts
  src/extensionConsole/Navbar.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8643 #8614: rename share/publish modals
  src/extensionConsole/pages/mods/modals/Modals.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModalBody.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/__snapshots__/ConvertToModModal.test.tsx.snap
  src/extensionConsole/pages/mods/modals/shareModals/PublishModContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishModModals.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishRecipeModals.test.tsx
  src/extensionConsole/pages/mods/modals/shareModals/ShareModModal.tsx
  src/extensionConsole/pages/mods/modals/shareModals/ShareModModalBody.tsx
Labels: developer experience

#8648 Rename trigger starter brick files
  src/components/BrickIcon.tsx
  src/contentScript/lifecycle.test.ts
  src/contentScript/pageEditor/dynamic/updateDynamicElement.ts
  src/extensionConsole/pages/mods/hooks/useViewLogsAction.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
  src/starterBricks/contextMenu/contextMenu.ts
  src/starterBricks/factory.ts
  src/starterBricks/helpers.ts
  src/starterBricks/menuItem/menuItemExtension.ts
  src/starterBricks/panel/panelExtension.ts
  src/starterBricks/quickBar/quickBarExtension.tsx
  src/starterBricks/quickBarProvider/quickBarProviderExtension.tsx
  src/starterBricks/sidebar/sidebarExtension.ts
  src/starterBricks/tour/tourExtension.ts
  src/starterBricks/trigger/triggerEventReaders.ts
  src/starterBricks/trigger/triggerStarterBrick.test.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrickTypes.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8649 Add documentation link to pages
  src/__snapshots__/Storyshots.test.js.snap
  src/extensionConsole/pages/activateExtension/ActivateExtensionPage.tsx
  src/extensionConsole/pages/activateMod/ActivateModPage.tsx
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateModCard.test.tsx.snap
  src/extensionConsole/pages/brickEditor/CreatePage.tsx
  src/extensionConsole/pages/brickEditor/EditPage.tsx
  src/extensionConsole/pages/integrations/IntegrationsPage.tsx
  src/extensionConsole/pages/settings/SettingsPage.tsx
  src/extensionConsole/pages/workshop/WorkshopPage.tsx
  src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap
  src/layout/Page.stories.tsx
  src/layout/Page.tsx
  src/vendors/theme/assets/styles/_misc.scss
Labels: user experience

#8652 #8607 Refactor rename "element" in editor slice actions
  src/background/deploymentUpdater.ts
  src/background/modUpdater.ts
  src/pageEditor/hooks/useDeactivateMod.tsx
  src/pageEditor/hooks/useRemoveModComponentFromStorage.test.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/hooks/useResetExtension.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/sidebar/DynamicModComponentListItem.test.tsx
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.test.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/utils.ts
  src/store/editorStorage.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
Labels: developer experience

#8653 Update menu item to use starter brick terminology
  src/analysis/analysisVisitors/selectorAnalysis.test.ts
  src/components/BrickIcon.tsx
  src/contentScript/pageEditor/types.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/menuItem.ts
  src/starterBricks/factory.ts
  src/starterBricks/menuItem/menuItemStarterBrick.test.ts
  src/starterBricks/menuItem/menuItemStarterBrick.ts
  src/starterBricks/menuItem/menuItemTypes.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8655 #8647 custom profile name fixture + deployment activation spec
  .env.example
  .github/workflows/end-to-end-tests.yml
  end-to-end-tests/README.md
  end-to-end-tests/env.ts
  end-to-end-tests/fixtures/authentication.ts
  end-to-end-tests/fixtures/pageContext.ts
  end-to-end-tests/fixtures/utils.ts
  end-to-end-tests/setup/affiliated.setup.ts
  end-to-end-tests/setup/unaffiliated.setup.ts
  end-to-end-tests/setup/utils.ts
  end-to-end-tests/tests/deployments/deploymentActivation.spec.ts
  knip.mjs
  playwright.config.ts
  src/extensionConsole/pages/deployments/DeploymentModal.tsx
  src/extensionConsole/pages/deployments/__snapshots__/DeploymentModal.test.tsx.snap
  src/tsconfig.strictNullChecks.json
Labels: testing

#8657 #8610: rename dynamicElement -> draftModComponent
  src/background/deploymentUpdater.test.ts
  src/background/removeExtensionForEveryTab.ts
  src/bricks/types.ts
  src/contentScript/lifecycle.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/draft/clearDraftModComponents.ts
  src/contentScript/pageEditor/draft/overlay.ts
  src/contentScript/pageEditor/draft/runStarterBrickReader.ts
  src/contentScript/pageEditor/draft/updateDraftModComponent.ts
  src/contentScript/pageEditor/resetTab.ts
  src/contentScript/pageEditor/types.ts
  src/pageEditor/EditorContent.test.tsx
  src/pageEditor/EditorContent.tsx
  src/pageEditor/PanelContent.test.tsx
  src/pageEditor/PanelContent.tsx
  src/pageEditor/editorPermissionsHelpers.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.test.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
  src/pageEditor/sidebar/DraftModComponentListItem.test.tsx
  src/pageEditor/sidebar/DraftModComponentListItem.tsx
  src/pageEditor/sidebar/Extensions.tsx
  src/pageEditor/sidebar/ModComponentListItem.tsx
  src/pageEditor/sidebar/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/menuItem.ts
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/starterBricks/panel.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/quickBarProvider.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/tour.ts
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/tabState/tabStateSlice.ts
  src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/store/checkActiveModComponentAvailability.test.ts
  src/store/checkAvailableDraftModComponents.test.ts
  src/store/editorStorage.test.ts
  src/store/editorStorage.ts
  src/store/uninstallUtils.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8656 Rename Quick Bar to match starter brick naming conventions
  src/components/quickBar/quickBarRegistry.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/quickBarProvider.ts
  src/pageEditor/tabs/quickBarProvider/QuickBarProviderConfiguration.tsx
  src/starterBricks/factory.ts
  src/starterBricks/quickBar/quickBarStarterBrick.test.ts
  src/starterBricks/quickBar/quickBarStarterBrick.tsx
  src/starterBricks/quickBar/quickBarTypes.ts
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.test.ts
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.tsx
  src/starterBricks/quickBarProvider/quickBarProviderTypes.ts
  src/starterBricks/quickBarProvider/quickBarQueryReader.ts
  src/starterBricks/starterBrickModUtils.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8659 Rename panel/side panel to match starter brick naming conventions
  src/components/BrickIcon.tsx
  src/contentScript/lifecycle.ts
  src/contentScript/pageEditor/types.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/panel.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/tabs/sidebar/SidebarConfiguration.tsx
  src/starterBricks/factory.ts
  src/starterBricks/panel/panelStarterBrick.ts
  src/starterBricks/panel/panelStarterBrickTypes.ts
  src/starterBricks/sidebar/sidebarStarterBrick.test.ts
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/sidebar/sidebarStarterBrickTypes.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8662 #8582 e2e fixture method for verifying mod definition yaml
  .pre-commit-config.yaml
  end-to-end-tests/fixtures/modDefinitions.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/modEditor.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/workshop/createMod.spec.ts
  end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/simple-sidebar-panel-chrome-can create a new mod from a yaml definition
  end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/simple-sidebar-panel-edge-can create a new mod from a yaml definition
  src/tsconfig.strictNullChecks.json
Labels: testing

#8661 Rename extension actions to use mod/mod component terminology
  src/__mocks__/@/store/uninstallUtils.ts
  src/activation/useActivateMod.test.ts
  src/activation/useActivateMod.ts
  src/background/deploymentUpdater.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/modUpdater.ts
  src/extensionConsole/pages/activateExtension/ActivateExtensionCard.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.test.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModalBody.tsx
  src/extensionConsole/pages/mods/utils/useReinstall.test.ts
  src/extensionConsole/pages/mods/utils/useReinstall.ts
  src/mods/hooks/useDeactivateAction.ts
  src/mods/useModViewItems.test.tsx
  src/mods/useMods.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useDeactivateMod.tsx
  src/pageEditor/hooks/useRemoveModComponentFromStorage.test.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/sidebar/DraftModComponentListItem.tsx
  src/pageEditor/sidebar/modals/AddToRecipeModal.tsx
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/sidebar/activateMod/ActivateModPanel.tsx
  src/sidebar/activateMod/ActivateMultipleModsPanel.tsx
  src/store/checkAvailableInstalledExtensions.test.ts
  src/store/extensionsSlice.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/store/uninstallUtils.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8664 remove inclusiveness analyzer workflow
  .github/workflows/inclusiveness-analyzer.yaml
Labels: developer experience

#8666 Rename block to brick in some file/methods/type names
  src/analysis/analysisVisitors/brickIdVisitor.ts
  src/analysis/analysisVisitors/brickTypeAnalysis.ts
  src/background/deploymentUpdater.ts
  src/bricks/PipelineVisitor.ts
  src/bricks/brickFilterHelpers.ts
  src/bricks/util.ts
  src/components/brickModalNoTags/BrickResult.tsx
  src/contentScript/contentScriptCore.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/runBrickPreview.ts
  src/contentScript/pageEditor/runRendererBrick.ts
  src/contentScript/pageEditor/types.ts
  src/contrib/registerContribBricks.ts
  src/development/headers.test.ts
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/brickEditor/referenceTab/BrickReference.tsx
  src/extensionConsole/pages/brickEditor/referenceTab/BrickResult.module.scss
  src/extensionConsole/pages/brickEditor/referenceTab/BrickResult.tsx
  src/pageEditor/Panel.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/tabs/editTab/editorNodeLayout/usePasteBrick.ts
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/runtime/getType.ts
  src/runtime/reducePipeline.ts
  src/runtime/runtimeTypes.ts
  src/runtime/runtimeUtils.ts
  src/sidebar/sidebar.tsx
  src/starterBricks/contextMenu/contextMenuStarterBrick.ts
  src/starterBricks/menuItem/menuItemStarterBrick.test.ts
  src/starterBricks/menuItem/menuItemStarterBrick.ts
  src/starterBricks/panel/panelStarterBrick.ts
  src/starterBricks/quickBar/quickBarStarterBrick.tsx
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/tour/tourStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/tinyPages/ephemeralPanel.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8679 Don't mutate uiSchema in normalizeModOptionsDefinition
  src/utils/modUtils.test.ts
  src/utils/modUtils.ts
  src/utils/objectUtils.ts
Labels: bug

#8668 Rename RTK Query endpoints for mod definition CRUD
  src/data/service/api.ts
  src/extensionConsole/pages/activateMod/ActivateModCard.test.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/activateMod/ActivateModPage.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModalBody.tsx
  src/extensionConsole/pages/mods/modals/shareModals/CancelPublishContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishModContent.tsx
  src/extensionConsole/pages/mods/modals/shareModals/ShareModModalBody.tsx
  src/modDefinitions/modDefinitionsListenerMiddleware.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/panes/save/useSavingWizard.test.tsx
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
  src/pageEditor/sidebar/ModListItem.tsx
  src/types/contract.ts
Labels: developer experience

#8680 Clarify run brick action name in content script API
  src/contentScript/executor.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/pageEditor/tabs/effect/BrickPreview.tsx
Labels: developer experience

#8667 update PR template
  .github/pull_request_template.md
Labels: developer experience

#8682 #8681: add edit/delete mod actions to mods screen
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/pageEditorPage.ts
  end-to-end-tests/tests/extensionConsole/modsPage.spec.ts
  src/auth/authUtils.ts
  src/extensionConsole/pages/brickEditor/useSubmitBrick.ts
  src/extensionConsole/pages/mods/ModsPageActions.tsx
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/extensionConsole/pages/mods/hooks/useModsPageActions.ts
  src/extensionConsole/pages/mods/hooks/useViewPublishAction.ts
  src/mods/hooks/useDeleteModDefinitionAction.ts
  src/mods/hooks/useDeleteStandaloneModDefinitionAction.ts
  src/mods/hooks/useEditInWorkshopAction.ts
  src/mods/hooks/useHasModPackageEditPermission.ts
  src/mods/hooks/useModPermissions.ts
  src/mods/useModViewItems.test.tsx
  src/mods/useModViewItems.tsx
  src/mods/useMods.ts
  src/telemetry/events.ts
  src/tsconfig.strictNullChecks.json
  src/utils/modUtils.test.ts
  src/utils/modUtils.ts
Labels: enhancement, user experience

#8658 Fix flaky partner theming
  src/background/initTheme.ts
  src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/hooks/useTheme.ts
  src/store/settings/settingsSlice.ts
Labels: bug, enterprise

#8685 #8615: change remaining instances of dynamic -> draft
  src/contentScript/lifecycle.ts
  src/pageEditor/EditorContent.tsx
  src/pageEditor/sidebar/DraftModComponentListItem.tsx
Labels: developer experience

#8690 #8654: page editor editorstate name migration
  src/background/deploymentUpdater.test.ts
  src/background/deploymentUpdater.ts
  src/pageEditor/EditorContent.tsx
  src/pageEditor/PanelContent.tsx
  src/pageEditor/analysisManager.ts
  src/pageEditor/baseFormStateTypes.ts
  src/pageEditor/documentBuilder/preview/DocumentPreview.tsx
  src/pageEditor/hooks/useResetRecipe.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/sidebar/Extensions.tsx
  src/pageEditor/sidebar/ModComponentListItem.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.test.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.test.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/slices/runtimeSelectors.ts
  src/pageEditor/slices/selectors/selectGetCleanComponentsAndDirtyFormStatesForMod.test.ts
  src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePasteBrick.ts
  src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
  src/store/editorStorage.test.ts
  src/store/editorStorage.ts
Labels: developer experience

#8693 Rename `resolved` prefix to `hydrated`
  src/background/contextMenus/initContextMenus.ts
  src/background/contextMenus/preloadContextMenus.ts
  src/background/deploymentUpdater.ts
  src/background/modUpdater.ts
  src/bricks/effects/runSubTour.test.ts
  src/contentScript/lifecycle.test.ts
  src/contentScript/lifecycle.ts
  src/contentScript/pageEditor/draft/updateDraftModComponent.ts
  src/extensionConsole/pages/mods/utils/exportBlueprint.test.ts
  src/extensionConsole/pages/mods/utils/exportBlueprint.ts
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/modDefinitions/modDefinitionPermissionsHelpers.ts
  src/mods/useModViewItems.test.tsx
  src/mods/useMods.ts
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/permissions/cloudExtensionPermissionsHelpers.ts
  src/permissions/extensionPermissionsHelpers.ts
  src/registry/hydrateInnerDefinitions.ts
  src/runtime/runtimeUtils.ts
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/starterBricks/contextMenu/contextMenuStarterBrick.test.ts
  src/starterBricks/contextMenu/contextMenuStarterBrick.ts
  src/starterBricks/helpers.ts
  src/starterBricks/menuItem/menuItemStarterBrick.test.ts
  src/starterBricks/menuItem/menuItemStarterBrick.ts
  src/starterBricks/panel/panelStarterBrick.ts
  src/starterBricks/quickBar/quickBarStarterBrick.test.ts
  src/starterBricks/quickBar/quickBarStarterBrick.tsx
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.test.ts
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.test.ts
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/starterBrickModUtils.ts
  src/starterBricks/tour/tourController.test.ts
  src/starterBricks/tour/tourController.ts
  src/starterBricks/tour/tourStarterBrick.test.ts
  src/starterBricks/tour/tourStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrick.test.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/starterBricks/types.ts
  src/store/extensionsSlice.ts
  src/store/extensionsTypes.ts
  src/store/uninstallUtils.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/modDefinitionFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/modComponentTypes.ts
  src/types/modDefinitionTypes.ts
  src/types/modTypes.ts
  src/types/starterBrickTypes.ts
  src/utils/modUtils.test.ts
  src/utils/modUtils.ts
Labels: developer experience

#8695 #8686: add additional type assertions to improve messaging if NPE reoccurs
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
Labels: developer experience

#8689 #8688 additional props for error reporting
  src/telemetry/logging.ts
  src/telemetry/reportError.test.ts
  src/telemetry/reportError.ts
  src/tsconfig.strictNullChecks.json
  src/types/loggerTypes.ts
Labels: telemetry

#8698 #8607 Replace remaining instances of "element" in editorSlice
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
  src/pageEditor/EditorContent.test.tsx
  src/pageEditor/PanelContent.test.tsx
  src/pageEditor/analysisManager.ts
  src/pageEditor/documentBuilder/edit/DocumentOptions.test.tsx
  src/pageEditor/documentBuilder/hooks/useDeleteElement.ts
  src/pageEditor/documentBuilder/hooks/useMoveElement.ts
  src/pageEditor/documentBuilder/hooks/useMoveWithinParent.ts
  src/pageEditor/documentBuilder/hooks/useSelectParentElement.ts
  src/pageEditor/documentBuilder/preview/DocumentPreview.test.tsx
  src/pageEditor/documentBuilder/preview/ElementPreview.test.tsx
  src/pageEditor/fields/FormModalOptions.test.tsx
  src/pageEditor/fields/FormModalOptions.tsx
  src/pageEditor/fields/FormRendererOptions.test.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useResetRecipe.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/sidebar/DraftModComponentListItem.tsx
  src/pageEditor/sidebar/ModListItem.tsx
  src/pageEditor/sidebar/modals/AddToRecipeModal.tsx
  src/pageEditor/sidebar/modals/MoveFromModModal.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.test.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.test.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/PageStateTab.test.tsx
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/CommentsPreview.test.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.test.tsx
  src/pageEditor/tabs/trigger/TriggerConfiguration.test.tsx
  src/pageEditor/uiState/uiState.ts
  src/pageEditor/uiState/uiStateTypes.ts
  src/store/checkActiveModComponentAvailability.test.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
Labels: developer experience, page editor

#8700 Script for downloading and viewing e2e test report for PRs
  .env.example
  .gitignore
  end-to-end-tests/README.md
  scripts/show-pr-e2e-report.sh
Labels: developer experience, testing

#8705 #8704: default availability for cross-site starter bricks
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/contextMenu.test.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/menuItem.ts
  src/pageEditor/starterBricks/panel.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/quickBarProvider.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/tour.ts
  src/pageEditor/starterBricks/trigger.ts
Labels: user experience, page editor

#8707 Make sidebar navigation e2e test less flaky
  end-to-end-tests/tests/runtime/sidebarNavigation.spec.ts
Labels: testing

#8708 Refactor lifecycle module names
  src/activation/useActivateMod.test.ts
  src/activation/useActivateMod.ts
  src/background/deploymentUpdater.ts
  src/background/messenger/registration.ts
  src/background/modUpdater.ts
  src/background/removeModComponentForEveryTab.ts
  src/background/starterMods.ts
  src/bricks/effects/reactivate.ts
  src/contentScript/lifecycle.test.ts
  src/contentScript/lifecycle.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/draft/clearDraftModComponents.ts
  src/contentScript/pageEditor/draft/runStarterBrickReaderPreview.ts
  src/contentScript/pageEditor/draft/updateDraftModComponent.ts
  src/contentScript/pageEditor/resetTab.ts
  src/extensionConsole/pages/brickEditor/useSubmitBrick.ts
  src/extensionConsole/pages/settings/FactoryResetSettings.tsx
  src/pageEditor/EditorContent.test.tsx
  src/pageEditor/PanelContent.tsx
  src/pageEditor/hooks/useRemoveModComponentFromStorage.test.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
  src/sidebar/ConnectedSidebar.test.tsx
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/SidebarBody.test.tsx
  src/store/checkAvailableInstalledExtensions.test.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8706 #8607 More replacing element -> modComponentFormState
  src/pageEditor/PanelContent.tsx
  src/pageEditor/analysisManager.ts
  src/pageEditor/documentBuilder/edit/DocumentOptions.tsx
  src/pageEditor/documentBuilder/edit/ElementEditor.tsx
  src/pageEditor/documentBuilder/edit/RemoveElement.tsx
  src/pageEditor/documentBuilder/hooks/useMoveElement.ts
  src/pageEditor/documentBuilder/hooks/useMoveWithinParent.ts
  src/pageEditor/documentBuilder/preview/DocumentPreview.tsx
  src/pageEditor/fields/FormModalOptions.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useExtensionTrace.ts
  src/pageEditor/hooks/useResetRecipe.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/hooks/useSaveStandaloneModComponent.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.test.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/panes/save/savingExtensionSelectors.ts
  src/pageEditor/panes/save/savingExtensionSlice.ts
  src/pageEditor/panes/save/useSavingWizard.test.tsx
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/runtimeSelectors.ts
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/pageEditor/toolbar/PermissionsToolbar.tsx
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8711 fix error reporting in background script
  src/telemetry/reportError.ts
Labels: bug

#8714 #8713 Fix bug with OAuth2 login request params
  src/background/auth/codeGrantFlow.ts
  src/background/performConfiguredRequest.test.ts
Labels: bug, regression

#8720 Update danger banner colors
  src/__snapshots__/Storyshots.test.js.snap
  src/components/banner/Banner.module.scss
  src/components/banner/Banner.stories.tsx
  src/themes/colors.scss
Labels: user experience

#8650 #6656 Partner refresh tokens
  .secrets.baseline
  eslint-local-rules/persistBackgroundData.txt
  package-lock.json
  package.json
  src/__mocks__/@/background/messenger/api.ts
  src/auth/authStorage.ts
  src/auth/authTypes.ts
  src/auth/featureFlagStorage.ts
  src/auth/isAuthenticationAxiosError.ts
  src/auth/useLinkState.ts
  src/auth/usePartnerAuthData.ts
  src/auth/useRequiredPartnerAuth.test.tsx
  src/background/auth/authStorage.ts
  src/background/auth/partnerIntegrations/getPartnerPrincipals.test.ts
  src/background/auth/partnerIntegrations/launchAuthIntegration.test.ts
  src/background/auth/partnerIntegrations/launchAuthIntegration.ts
  src/background/auth/partnerIntegrations/partnerIntegrations.test.ts
  src/background/auth/partnerIntegrations/partnerIntegrations.ts
  src/background/auth/partnerIntegrations/refreshPartnerAuthentication.test.ts
  src/background/auth/partnerIntegrations/refreshPartnerAuthentication.ts
  src/background/background.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/refreshToken.test.ts
  src/background/refreshToken.ts
  src/background/requests.ts
  src/background/restrictUnauthenticatedUrlAccess.ts
  src/contrib/google/sheets/core/sheetsApi.test.ts
  src/data/service/apiClient.ts
  src/extensionConsole/Navbar.tsx
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/hooks/auth.ts
  src/hooks/useFlags.ts
  src/integrations/locator.ts
  src/integrations/registry.ts
  src/integrations/util/readRawConfigurations.ts
  src/telemetry/initErrorReporter.ts
  src/telemetry/performance.ts
  src/testUtils/factories/authFactories.ts
  src/testUtils/testAfterEnv.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience, enterprise

#8712 #8607 Replace remaining occurrences of mod component form state "elements"
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/sidebar/AddStarterBrickButton.tsx
  src/pageEditor/sidebar/arrangeSidebarItems.test.ts
  src/pageEditor/sidebar/modals/CreateModModal.tsx
  src/pageEditor/sidebar/modals/MoveFromModModal.tsx
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/tabs/editTab/dataPanel/FoundationDataPanel.tsx
  src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
Labels: developer experience

#8722 Rename `menuItem` starter brick to `button`
  src/analysis/analysisVisitors/selectorAnalysis.test.ts
  src/analysis/analysisVisitors/selectorAnalysis.ts
  src/background/deploymentUpdater.test.ts
  src/bricks/PipelineVisitor.test.ts
  src/components/BrickIcon.tsx
  src/contentScript/pageEditor/insertButton.tsx
  src/contentScript/pageEditor/types.ts
  src/pageEditor/panes/insert/InsertPane.tsx
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/sidebar/ActivatedModComponentListItem.test.tsx
  src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
  src/pageEditor/sidebar/DraftModComponentListItem.tsx
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.test.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/menuItem.ts
  src/pageEditor/tabs/effect/BrickConfiguration.test.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.tsx
  src/starterBricks/button/buttonStarterBrick.test.ts
  src/starterBricks/button/buttonStarterBrick.ts
  src/starterBricks/button/buttonStarterBrickTypes.ts
  src/starterBricks/factory.ts
  src/starterBricks/starterBrickModUtils.test.ts
  src/store/checkActiveModComponentAvailability.test.ts
  src/store/checkAvailableDraftModComponents.test.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/telemetry/events.ts
  src/testUtils/factories/modDefinitionFactories.ts
  src/testUtils/factories/pageEditorFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/starterBrickTypes.ts
Labels: developer experience

#8723 Drop inline panel starter brick
  eslint-local-rules/persistBackgroundData.txt
  src/bricks/PipelineVisitor.test.ts
  src/bricks/renderers/common.ts
  src/components/BrickIcon.tsx
  src/components/fields/schemaFields/widgets/varPopup/__snapshots__/VarMenu.test.tsx.snap
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/insertPanel.tsx
  src/contentScript/pageEditor/types.ts
  src/pageEditor/PanelContent.tsx
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/panes/insert/InsertPane.tsx
  src/pageEditor/panes/insert/InsertPanelPane.tsx
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/sidebar/DraftModComponentListItem.test.tsx
  src/pageEditor/sidebar/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.test.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/panel.ts
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/panel/PanelConfiguration.tsx
  src/starterBricks/dom.tsx
  src/starterBricks/factory.ts
  src/starterBricks/panel/panelStarterBrick.ts
  src/starterBricks/panel/panelStarterBrickTypes.ts
  src/testUtils/factories/modDefinitionFactories.ts
  src/testUtils/factories/pageEditorFactories.ts
  src/testUtils/factories/sidebarEntryFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/starterBrickTypes.ts
Labels: developer experience

#8718 #8609 Rename nodePreviewElement -> builderPreviewElement
  src/pageEditor/documentBuilder/edit/DocumentOptions.test.tsx
  src/pageEditor/documentBuilder/edit/DocumentOptions.tsx
  src/pageEditor/documentBuilder/edit/ElementEditor.tsx
  src/pageEditor/documentBuilder/edit/RemoveElement.tsx
  src/pageEditor/documentBuilder/hooks/useDeleteElement.ts
  src/pageEditor/documentBuilder/hooks/useMoveElement.ts
  src/pageEditor/documentBuilder/hooks/useMoveWithinParent.ts
  src/pageEditor/documentBuilder/hooks/useSelectParentElement.ts
  src/pageEditor/documentBuilder/preview/ElementPreview.test.tsx
  src/pageEditor/fields/FormModalOptions.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.test.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/tabs/editTab/editorNodes/PipelineHeaderNode.tsx
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
Labels: developer experience

#8717 e2e test for background error telemetry
  .github/workflows/ci.yml
  end-to-end-tests/tests/telemetry/errors.spec.ts
  src/registry/packageRegistry.ts
Labels: testing

#8721 base page object model for proxying locator calls
  end-to-end-tests/README.md
  end-to-end-tests/pageObjects/basePageObject.ts
  end-to-end-tests/pageObjects/extensionsShortcutsPage.ts
  end-to-end-tests/pageObjects/floatingActionButton.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
Labels: testing
