Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-10, with the labels that each got.

#9223 #9221: Attach db name and operation name to idb errors
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  src/registry/packageRegistry.ts
  src/telemetry/logging.test.ts
  src/telemetry/logging.ts
  src/telemetry/reportToApplicationErrorTelemetry.test.ts
  src/telemetry/reportToApplicationErrorTelemetry.ts
  src/telemetry/trace.ts
  src/utils/idbUtils.ts
Labels: customer, error-telemetry, telemetry

#9208 #9150 Additional sandbox TimeoutError logging and reinjection
  src/sandbox/messenger/api.ts
  src/sandbox/messenger/registration.ts
  src/sandbox/postMessage.test.ts
  src/sandbox/postMessage.ts
Labels: bug, runtime

#9204 Add `AUTH_WIDGET_*` events to lexicon
  src/components/integrations/AuthWidget.tsx
  src/integrations/components/IntegrationAuthSelector.tsx
  src/telemetry/events.ts
  src/telemetry/lexicon.ts
Labels: telemetry, 30% time

#9225 Only clear mod component debug logs if logValues is enabled
  src/contentScript/contentScriptPlatform.test.ts
  src/contentScript/contentScriptPlatform.ts
  src/extensionPages/extensionPagePlatform.test.ts
  src/extensionPages/extensionPagePlatform.ts
  src/platform/platformTypes/debuggerProtocol.ts
  src/runtime/reducePipeline.ts
Labels: enhancement, runtime

#9226 Implement withIdbErrorHandling for telemetry database
  src/background/telemetry.ts
  src/utils/idbUtils.ts
Labels: enhancement, runtime

#9224 #9222 Add policy for hiding the sidebar logo
  src/hooks/useTheme.test.ts
  src/hooks/useTheme.ts
  src/sidebar/Header.tsx
  src/store/enterprise/managedStorageTypes.ts
  static/managedStorageSchema.json
Labels: enhancement

#9229 #9211 Retry on failed to read large indexeddb value
  src/background/telemetry.ts
  src/registry/packageRegistry.ts
  src/telemetry/logging.test.ts
  src/telemetry/logging.ts
  src/telemetry/trace.ts
  src/utils/idbUtils.ts
Labels: bug

#9230 Add lexicon entries for BrickCommentsUpdate, BrowserActionRestrictedUrl, and CustomUserEvent
  src/telemetry/lexicon.ts
Labels: developer experience, 30% time

#9219 #9209: eliminate standalone mod components from Page Editor UI via "unsaved" mods
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-button-starter-brick-to-mod.yaml
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-context-menu-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-quick-bar-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-sidebar-panel-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-trigger-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  end-to-end-tests/tests/pageEditor/specialPages.spec.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  end-to-end-tests/tests/smoke/floatingActionButton.spec.ts
  src/auth/authSelectors.ts
  src/components/form/widgets/RegistryIdWidget.tsx
  src/modDefinitions/modDefinitions.test.tsx
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/hooks/useBuildAndValidateMod.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts
  src/pageEditor/hooks/useCompareModComponentCounts.test.ts
  src/pageEditor/hooks/useCompareModComponentCounts.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useCreateModFromModComponent.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/modListingPanel/ModComponents.tsx
  src/pageEditor/modListingPanel/ModListItem.test.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/ModListingPanel.tsx
  src/pageEditor/modListingPanel/NewModButton.tsx
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.module.scss
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  src/utils/modUtils.ts
Labels: enhancement, user experience, page editor

#9240 #9239: rename "reset" to "clear changes" in the Page Editor
  src/pageEditor/hooks/useClearModChanges.ts
  src/pageEditor/hooks/useClearModComponentChanges.ts
  src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/modListingPanel/ActionMenu.stories.tsx
  src/pageEditor/modListingPanel/ActionMenu.tsx
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModComponents.tsx
  src/pageEditor/modListingPanel/ModListItem.test.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/ModListingPanel.test.tsx
  src/pageEditor/store/editor/editorSlice.ts
  src/store/modComponents/modComponentSlice.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/telemetry/events.ts
  src/telemetry/lexicon.ts
Labels: user experience, page editor

#9243 #9241: add "Duplicate" action to mod components
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModActionMenu.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.stories.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.tsx
  src/pageEditor/modListingPanel/ModComponents.tsx
  src/pageEditor/modListingPanel/ModListItem.test.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/ModListingPanel.test.tsx
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
Labels: user experience, page editor

#9245 #9244: add Move/Copy mod component actions
  end-to-end-tests/pageObjects/pageEditor/createModModal.ts
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/moveCopyModComponent.spec.ts
  src/pageEditor/modListingPanel/ActionMenu.module.scss
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.stories.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.tsx
  src/pageEditor/modListingPanel/modals/AddToModModal.tsx
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/modListingPanel/modals/MoveCopyToModModal.tsx
  src/pageEditor/modListingPanel/modals/MoveFromModModal.tsx
  src/pageEditor/modals/Modals.tsx
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
Labels: user experience, page editor

#9246 #9242: migrate unsaved standalone mod components in the Page Editor
  end-to-end-tests/tests/pageEditor/moveOrCopyModComponent.spec.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.test.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/hooks/useClearModChanges.ts
  src/pageEditor/hooks/useMigrateStandaloneComponentsToMods.test.ts
  src/pageEditor/hooks/useMigrateStandaloneComponentsToMods.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/layout/EditorLayout.tsx
  src/pageEditor/modListingPanel/ActivatedModComponentListItem.tsx
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/pageEditor/modListingPanel/arrangeSidebarItems.test.ts
  src/pageEditor/modListingPanel/arrangeSidebarItems.ts
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/modListingPanel/modals/MoveOrCopyToModModal.tsx
  src/pageEditor/modals/Modals.tsx
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/button.ts
  src/pageEditor/starterBricks/contextMenu.test.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/dynamicQuickBar.ts
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/store/editor/baseFormStateTypes.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/pageEditor/store/editor/selectGetCleanComponentsAndDirtyFormStatesForMod.ts
  src/pageEditor/tabs/editTab/dataPanel/BrickDataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/CommentsTab.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/ModVariablesTab.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/__snapshots__/ModVariablesTab.test.tsx.snap
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.test.tsx
  src/pageEditor/utils.ts
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
  src/store/modComponents/modComponentMigrations.test.ts
  src/store/modComponents/modComponentSelectors.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/pageEditorFactories.ts
Labels: user experience, developer experience, page editor

#9191 Slice 3: Use `ModInstance` type on the mods screen (3/3)
  src/activation/useActivateModWizard.test.tsx
  src/background/deploymentUpdater.test.ts
  src/background/modUpdater.test.ts
  src/extensionConsole/pages/mods/ModsPage.test.tsx
  src/extensionConsole/pages/mods/modsPageSelectors.ts
  src/extensionConsole/pages/mods/utils/buildGetModActivationStatus.test.ts
  src/extensionConsole/pages/mods/utils/buildGetModActivationStatus.ts
  src/extensionConsole/pages/mods/utils/buildGetModSharingSource.test.ts
  src/extensionConsole/pages/mods/utils/buildGetModSharingSource.ts
  src/extensionConsole/pages/mods/utils/buildGetModVersionStatus.test.ts
  src/extensionConsole/pages/mods/utils/buildGetModVersionStatus.ts
  src/extensionConsole/pages/mods/utils/buildModsList.test.ts
  src/extensionConsole/pages/mods/utils/buildModsList.ts
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/modDefinitions/modDefinitionsSelectors.ts
  src/mods/hooks/useModPermissions.ts
  src/sidebar/activateMod/RequireMods.tsx
  src/store/modComponents/modComponentSelectors.ts
  src/store/modComponents/modInstanceUtils.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/modDefinitionFactories.ts
  src/testUtils/factories/modInstanceFactories.ts
  src/testUtils/factories/registryFactories.ts
  src/types/deploymentTypes.ts
  src/types/modInstanceTypes.ts
  src/utils/modUtils.ts
  src/validators/schemaValidator.test.ts
Labels: developer experience, 30% time

#9192 Slice 4: Use `ModInstance` type in mods updater
  src/background/deploymentUpdater.ts
  src/background/modUpdater.test.ts
  src/background/modUpdater.ts
  src/background/utils/deactivateMod.test.ts
  src/background/utils/deactivateMod.ts
Labels: developer experience, 30% time

#9252 Add idb error handling for Internal error opening backing store
  src/utils/idbUtils.test.ts
  src/utils/idbUtils.ts
Labels: bug, runtime

#9258 #9257: fix heartbeat telemetry regression
  src/types/contract.ts
  src/types/helpers.test.ts
  src/types/registryTypes.ts
  src/utils/deploymentUtils.test.ts
  src/utils/deploymentUtils.ts
Labels: bug, regression

#9254 #9250 Refactor ModActionItem remove unnecessary props
  src/pageEditor/modListingPanel/ModActionMenu.tsx
  src/pageEditor/modListingPanel/ModComponents.tsx
  src/pageEditor/modListingPanel/ModListItem.test.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
Labels: developer experience

#9255 #9250 Delete action for unsaved Mods
  src/pageEditor/hooks/useDeactivateMod.tsx
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/modListingPanel/ModActionMenu.tsx
Labels: user experience, page editor

#9256 Remove remaining mentions of standalone mod components
  end-to-end-tests/fixtures/modDefinitions.ts
  end-to-end-tests/fixtures/pageContext.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  src/activation/mapModComponentDefinitionToActivatedModComponent.ts
  src/background/welcomeMods.ts
  src/bricks/transformers/RunMetadataTransformer.test.ts
  src/bricks/transformers/RunMetadataTransformer.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/extensionConsole/pages/activateMod/ActivateModPage.tsx
  src/extensionConsole/pages/packageEditor/EditPage.tsx
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/modDefinitions/util/mapModDefinitionToModMetadata.test.ts
  src/modDefinitions/util/mapModDefinitionToModMetadata.ts
  src/mods/hooks/useFindModInstance.ts
  src/mods/util/getModComponentsForMod.ts
  src/pageEditor/hooks/useClearModComponentChanges.ts
  src/pageEditor/hooks/useDeactivateMod.tsx
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/hooks/useUpsertModComponentFormState.test.ts
  src/pageEditor/modListingPanel/ActivatedModComponentListItem.tsx
  src/pageEditor/panes/save/SaveDataIntegrityErrorModal.tsx
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  src/pageEditor/utils.ts
  src/runtime/extendModVariableContext.test.ts
  src/runtime/pipelineTests/trace.test.ts
  src/sidebar/sidebarSelectors.ts
  src/starterBricks/types.ts
  src/store/checkAvailableActivatedModComponents.test.ts
  src/store/modComponents/modComponentSelectors.ts
  src/store/modComponents/modInstanceSelectors.ts
  src/store/modComponents/modInstanceUtils.ts
  src/store/sidebar/sidebarSlice.ts
  src/testUtils/factories/modComponentFactories.ts
  src/types/modComponentTypes.ts
  src/utils/modUtils.test.ts
  src/utils/modUtils.ts
  src/utils/registryUtils.test.ts
Labels: developer experience, 30% time

#9264 Require version on ModDefinition.metadata
  src/__snapshots__/Storyshots.test.js.snap
  src/extensionConsole/pages/mods/GetStartedView.stories.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/testUtils/factories/metadataFactory.ts
  src/types/modComponentTypes.ts
  src/types/modDefinitionTypes.ts
  src/types/registryTypes.ts
  src/utils/deploymentUtils.ts
Labels: developer experience, 30% time

#9228 #9227 Refactor `useTheme` to use `useManagedStorageState`
  src/auth/useRequiredPartnerAuth.test.tsx
  src/extensionConsole/pages/BrowserBanner.test.tsx
  src/hooks/useTheme.test.ts
  src/hooks/useTheme.ts
  src/store/enterprise/managedStorage.ts
  src/store/enterprise/useManagedStorageState.test.ts
  src/store/enterprise/useManagedStorageState.ts
Labels: developer experience

#9249 Fix e2e test flakiness
  .github/workflows/ci.yml
  .secrets.baseline
  end-to-end-tests/README.md
  end-to-end-tests/fixtures/authentication.ts
  end-to-end-tests/fixtures/utils.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/setup/affiliated.setup.ts
  end-to-end-tests/setup/unaffiliated.setup.ts
  end-to-end-tests/setup/utils.ts
  end-to-end-tests/tests/bricks/sidebarEffects.spec.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/extensionConsole/modsPage.spec.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  end-to-end-tests/tests/pageEditor/liveEditing.spec.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  end-to-end-tests/tests/regressions/sidebarLinks.spec.ts
  end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarController.spec.ts
  end-to-end-tests/tests/smoke/floatingActionButton.spec.ts
  end-to-end-tests/utils.ts
  playwright.config.ts
  scripts/show-pr-e2e-report.sh
Labels: developer experience, testing

#9267 Fix e2e flakiness for setup test
  end-to-end-tests/setup/utils.ts
  playwright.config.ts
Labels: developer experience, testing

#9270 Refactor ModComponentActionMenu remove unnecessary props
  src/__snapshots__/Storyshots.test.js.snap
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.stories.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.tsx
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/testUtils/storyUtils.ts
Labels: developer experience, 30% time

#9285 Fix type error when pinning 2.1.4 extension to app
  src/utils/idbUtils.ts
Labels: infrastructure

#9271 #9196 Paywall banner in Sidebar and Page Editor
  src/components/teamTrials/TeamTrialBanner.test.tsx
  src/components/teamTrials/TeamTrialBanner.tsx
  src/components/teamTrials/TrialAwareButton.test.tsx
  src/components/teamTrials/TrialAwareButton.tsx
  src/components/teamTrials/TrialCallToActionLink.tsx
  src/components/teamTrials/useGetAllTeamScopes.ts
  src/components/teamTrials/useTeamTrialStatus.ts
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/mods/Status.tsx
  src/pageEditor/layout/EditorLayout.module.scss
  src/pageEditor/layout/PanelContent.tsx
  src/pageEditor/pageEditor.html
  src/sidebar/SidebarBody.test.tsx
  src/sidebar/SidebarBody.tsx
Labels: enhancement

#9286 #9092: slice 2.3 support deleting user deployment in extension console
  src/activation/modOptionsHelpers.ts
  src/activation/useActivateMod.test.ts
  src/activation/useActivateMod.ts
  src/data/service/api.ts
  src/data/service/urlPaths.ts
  src/store/modComponents/modInstanceUtils.ts
Labels: enhancement

#9295 Remove unused mod component sidebar item code
  src/pageEditor/modListingPanel/ModListingPanel.tsx
  src/pageEditor/modListingPanel/ModSidebarListItems.module.scss
  src/pageEditor/modListingPanel/ModSidebarListItems.tsx
  src/pageEditor/modListingPanel/arrangeSidebarItems.ts
  src/pageEditor/modListingPanel/common.ts
  src/pageEditor/modListingPanel/filterSidebarItems.test.ts
  src/pageEditor/modListingPanel/filterSidebarItems.ts
Labels: developer experience

#9290 Add deployment event descriptions to lexicon
  src/telemetry/lexicon.ts
Labels: documentation, telemetry, 30% time

#9291 Drop uipath local process brick
  eslint-local-rules/persistBackgroundData.txt
  package-lock.json
  package.json
  src/__mocks__/@uipath/robot.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/uipath.ts
  src/contrib/editors.ts
  src/contrib/registerContribBricks.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/LocalProcessOptions.tsx
  src/contrib/uipath/UiPathRobot.ts
  src/contrib/uipath/__snapshots__/LocalProcessOptions.test.tsx.snap
  src/contrib/uipath/localProcess.ts
  src/contrib/uipath/quietLogger.ts
  src/development/headers.test.ts
  tsconfig.json
  webpack.config.mjs
Labels: developer experience, brick

#9292 Group/organize editor slice reducer methods
  src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/tabs/editTab/EditTab.tsx
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/CommentsPreview.test.tsx
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/CommentsPreview.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
Labels: developer experience, 30% time

#9294 Drop unused starter brick registry package save code
  src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
  src/pageEditor/starterBricks/button.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/dynamicQuickBar.ts
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/pageEditor/tabs/editTab/EditTab.tsx
  src/pageEditor/tabs/editTab/StarterBrickConfigPanel.tsx
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
Labels: developer experience, page editor, 30% time

#9288 fix e2e test flakiness due to workshop page fixture
  end-to-end-tests/fixtures/modDefinitions.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts
  end-to-end-tests/tests/pageEditor/liveEditing.spec.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  playwright.config.ts
Labels: testing

#9296 Hide disabled mod save buttons
  src/pageEditor/modListingPanel/ModActionMenu.tsx
Labels: user experience, page editor

#9299 DraftModComponent type refactoring
  src/contentScript/pageEditor/draft/runStarterBrickReaderPreview.ts
  src/contentScript/pageEditor/draft/updateDraftModComponent.ts
  src/contentScript/pageEditor/types.ts
  src/contentScript/sidebarController.tsx
  src/pageEditor/editorPermissionsHelpers.ts
  src/pageEditor/layout/EditorContent.tsx
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/panes/ModComponentEditorPane.tsx
  src/pageEditor/starterBricks/button.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/dynamicQuickBar.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/store/editor/selectGetCleanComponentsAndDirtyFormStatesForMod.ts
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.test.tsx
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx
  src/pageEditor/toolbar/ReloadToolbar.tsx
Labels: developer experience

#9314 fix axe-core in package-lock
  package-lock.json
Labels: bug, testing, regression

#9312 Drop unused `FormState.optionsDefinition` property and related code
  src/pageEditor/hooks/useClearModComponentChanges.ts
  src/pageEditor/modListingPanel/ActivatedModComponentListItem.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/store/editor/baseFormStateTypes.ts
  src/registry/hydrateInnerDefinitions.ts
  src/starterBricks/starterBrickUtils.ts
  src/testUtils/factories/modDefinitionFactories.ts
Labels: developer experience

#9310 Wrap experimental Local Chromium AI APIs as bricks
  package-lock.json
  package.json
  src/bricks/transformers/ai/LocalChatCompletion.ts
  src/bricks/transformers/ai/LocalPrompt.ts
  src/bricks/transformers/ai/LocalSummarization.ts
  src/bricks/transformers/ai/domAiHelpers.ts
  src/bricks/transformers/getAllTransformers.ts
  src/development/headers.test.ts
  src/utils/schemaUtils.ts
Labels: enhancement, brick

#9300 MS Edge e2e flakiness fixes
  end-to-end-tests/fixtures/utils.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/regressions/hideModalsOnPageEditorRefresh.spec.ts
Labels: testing

#9318 Drop unused code
  src/components/AbortSignalGate.test.tsx
  src/components/AbortSignalGate.tsx
  src/components/form/widgets/radioItemList/RadioItemListWidget.module.scss
  src/components/form/widgets/radioItemList/RadioItemListWidget.test.tsx
  src/components/form/widgets/radioItemList/RadioItemListWidget.tsx
  src/components/form/widgets/radioItemList/__snapshots__/RadioItemListWidget.test.tsx.snap
  src/components/form/widgets/radioItemList/radioItemListWidgetTypes.ts
  src/contrib/google/sheets/core/useCurrentOrigin.test.ts
  src/contrib/google/sheets/core/useCurrentOrigin.ts
  src/contrib/google/sheets/core/useOnChangeEffect.test.ts
  src/contrib/google/sheets/core/useOnChangeEffect.ts
Labels: developer experience, 30% time

#9316 Add descriptions for devtools events to lexicon
  src/telemetry/lexicon.ts
Labels: documentation, developer experience, 30% time

#9298 Inject entire draft mod instance from Page Editor
  src/contentScript/lifecycle.test.ts
  src/contentScript/lifecycle.ts
  src/contentScript/pageEditor/draft/updateDraftModComponent.ts
  src/pageEditor/events.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts
  src/pageEditor/layout/PanelContent.tsx
  src/pageEditor/panes/ModComponentEditorPane.test.tsx
  src/pageEditor/panes/ModComponentEditorPane.tsx
  src/pageEditor/panes/ModEditorPane.tsx
  src/pageEditor/panes/__snapshots__/ModComponentEditorPane.test.tsx.snap
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/starterBrickModUtils.ts
  src/starterBricks/trigger/triggerStarterBrick.test.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/types/runtimeTypes.ts
  src/vendors/jQueryInitialize.d.ts
Labels: enhancement, user experience, page editor

#9321 #9283: fix prerelease browser workflow flakiness
  .github/workflows/end-to-end-tests.yml
  .secrets.baseline
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/pageObjects/extensionsShortcutsPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/pageEditor/liveEditing.spec.ts
  end-to-end-tests/tests/runtime/customEvents.spec.ts
  end-to-end-tests/tests/runtime/screenshotTab.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarNavigation.spec.ts
Labels: testing

#9320 #9313: fix delete draft mod component
  src/__mocks__/@/store/deactivateModHelpers.ts
  src/activation/useActivateMod.test.ts
  src/activation/useActivateMod.ts
  src/background/utils/deactivateMod.ts
  src/extensionConsole/pages/mods/ModsPageActions.test.tsx
  src/extensionConsole/pages/mods/ModsPageActions.tsx
  src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts
  src/extensionConsole/pages/mods/utils/useReactivateMod.ts
  src/pageEditor/hooks/useClearModChanges.ts
  src/pageEditor/hooks/useClearModComponentChanges.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useDeactivateMod.tsx
  src/pageEditor/hooks/useDeleteDraftModComponent.test.ts
  src/pageEditor/hooks/useDeleteDraftModComponent.tsx
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/modListingPanel/ModComponentActionMenu.tsx
  src/pageEditor/modListingPanel/ModListingPanel.test.tsx
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
  src/pageEditor/store/editor/selectGetCleanComponentsAndDirtyFormStatesForMod.ts
  src/store/deactivateModHelpers.ts
  src/store/editorStorage.test.ts
  src/store/editorStorage.ts
  src/store/modComponents/modComponentSlice.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/telemetry/events.ts
  src/testUtils/factories/modDefinitionFactories.ts
Labels: bug, page editor

#9328 #9150 Refactor `formBuilder/` directory
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/renderers/customForm.test.tsx
  src/bricks/transformers/ephemeralForm/EphemeralFormContent.tsx
  src/components/formBuilder/demo/FormBuilderDemo.module.scss
  src/components/formBuilder/demo/FormBuilderDemo.stories.tsx
  src/components/formBuilder/demo/FormBuilderDemo.test.tsx
  src/components/formBuilder/demo/FormBuilderDemo.tsx
  src/components/formBuilder/preview/FormPreview.tsx
  src/components/formBuilder/widgets/ImageCropWidget.tsx
  src/components/formBuilder/widgets/RjsfSelectWidget.test.tsx
  src/components/formBuilder/widgets/RjsfSelectWidget.tsx
  src/components/formBuilder/widgets/TextAreaWidget.module.scss
  src/components/formBuilder/widgets/TextAreaWidget.test.tsx
  src/components/formBuilder/widgets/TextAreaWidget.tsx
Labels: developer experience

#9330 Implement knip production mode in CI
  .github/workflows/ci.yml
  .secrets.baseline
Labels: developer experience

#9331 #9322 ensure type safety of injected sandbox
  end-to-end-tests/tests/runtime/sandbox.spec.ts
  src/utils/injectIframe.test.tsx
  src/utils/injectIframe.tsx
Labels: runtime

#9332 #9323: deduplicate Page Editor save helpers (2/2)
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-button-starter-brick-to-mod.yaml
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-context-menu-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-quick-bar-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-sidebar-panel-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-trigger-starter-brick-to-mod.diff
  src/__mocks__/@/store/deactivateModHelpers.ts
  src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts
  src/pageEditor/hooks/updateReduxForSavedModDefinition.ts
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useBuildAndValidateMod.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts
  src/pageEditor/hooks/useClearModChanges.ts
  src/pageEditor/hooks/useClearModComponentChanges.ts
  src/pageEditor/hooks/useCompareModComponentCounts.test.ts
  src/pageEditor/hooks/useCompareModComponentCounts.ts
  src/pageEditor/hooks/useCreateModFromMod.test.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  src/pageEditor/hooks/useDeactivateMod.tsx
  src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.test.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
  src/pageEditor/modListingPanel/ModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModSidebarListItems.tsx
  src/pageEditor/modListingPanel/common.ts
  src/pageEditor/modListingPanel/filterSidebarItems.ts
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/store/editor/editorSelectors.test.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/selectGetCleanComponentsAndDirtyFormStatesForMod.ts
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx
  src/pageEditor/utils.ts
  src/sidebar/DefaultContent.test.tsx
  src/store/modComponents/modComponentSlice.ts
  src/store/modComponents/modComponentUtils.test.ts
  src/store/modComponents/modComponentUtils.ts
  src/store/modComponents/modInstanceUtils.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/telemetry/events.ts
Labels: developer experience, page editor

#9341 Make action helpers use the dispatch(actionCreator()) pattern
  src/__mocks__/@/store/deactivateModHelpers.ts
  src/activation/useActivateMod.test.ts
  src/activation/useActivateMod.ts
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.test.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.ts
  src/extensionConsole/pages/mods/ModsPageActions.test.tsx
  src/extensionConsole/pages/mods/ModsPageActions.tsx
  src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts
  src/extensionConsole/pages/mods/utils/useReactivateMod.ts
  src/extensionConsole/store.ts
  src/pageEditor/hooks/updateReduxForSavedModDefinition.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/store/store.ts
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/TemporaryPanelTabPane.tsx
  src/sidebar/store.ts
  src/store/deactivateModHelpers.ts
Labels: developer experience

#9342 #9322: sandbox injection changes
  src/sandbox/sandbox.html
  src/utils/injectIframe.tsx
Labels: runtime

#9348 Refactor useTypedBrickMap to return AsyncState
  src/bricks/hooks/useAllBricks.ts
  src/bricks/hooks/useTypedBrickMap.ts
  src/bricks/transformers/jquery/JQueryReaderOptions.tsx
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
  src/extensionConsole/pages/activateMod/IntegrationsBody.tsx
  src/hooks/useDeriveAsyncState.ts
  src/mods/hooks/useModPermissions.ts
  src/pageEditor/modals/addBrickModal/AddBrickModal.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/BrickOutputTab.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/toolbar/PermissionsToolbar.tsx
  src/types/sliceTypes.ts
  src/utils/asyncStateUtils.test.ts
  src/utils/asyncStateUtils.ts
Labels: developer experience

#9334 Split editor slice selectors into separate files by domain
  src/pageEditor/modals/addBrickModal/useAddBrick.ts
  src/pageEditor/panes/ModEditorPane.tsx
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorAnalysisSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorClipboardSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorDataPanelSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorDesignViewSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorErrorSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorModComponentSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.test.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorNavigationSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorPipelineSelectors.ts
  src/pageEditor/store/editor/editorSelectors/index.ts
  src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.test.tsx
  src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx
  src/pageEditor/tabs/modOptionsArgs/__snapshots__/ModOptionsArgsEditor.test.tsx.snap
Labels: developer experience

#9343 #9151 Add FAB events to lexicon
  src/components/floatingActions/FloatingActions.tsx
  src/telemetry/events.ts
  src/telemetry/lexicon.ts
Labels: telemetry, 30% time

#9351 Fixes brick position reset and simplifies form reinitialization
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-added.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-removed.diff
  src/pageEditor/panes/ModComponentEditorPane.test.tsx
  src/pageEditor/panes/ModComponentEditorPane.tsx
  src/pageEditor/store/editor/editorSelectors/editorPipelineSelectors.ts
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.tsx
Labels: user experience, performance

#9344 #9151 Add GoogleFilePickerEvent to lexicon and support for hiding events
  src/telemetry/lexicon.ts
Labels: telemetry, 30% time

#9350 #9349: fix unsaved mod saving and refactor page editor modal state
  .env.example
  end-to-end-tests/README.md
  end-to-end-tests/env.ts
  end-to-end-tests/pageObjects/pageEditor/createModModal.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  playwright.config.ts
  src/components/form/FieldTemplate.tsx
  src/pageEditor/hooks/useCreateModFromMod.test.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useCreateModFromModComponent.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/modListingPanel/ModActionMenu.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/modListingPanel/modals/MoveOrCopyToModModal.tsx
  src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx
  src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
  src/pageEditor/modals/addBrickModal/useAddBrick.ts
  src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorPipelineSelectors.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
  src/testUtils/factories/pageEditorFactories.ts
Labels: bug, developer experience, regression

#9345 #9151 Add mod runtime and IDB error events to lexicon
  src/telemetry/lexicon.ts
Labels: telemetry, 30% time

#9346 #9151 Add IntegrationWidget events to lexicon
  src/telemetry/lexicon.ts
Labels: telemetry, 30% time

#9359 #9358: fix regression in options args assignment
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
Labels: bug, regression, release blocker

#9360 Prevent deletion of the last mod component in a mod and enforce editor slice invariants
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  end-to-end-tests/tests/pageEditor/moveOrCopyModComponent.spec.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/hooks/useCreateModFromModComponent.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useDeleteDraftModComponent.test.ts
  src/pageEditor/hooks/useDeleteDraftModComponent.tsx
  src/pageEditor/modListingPanel/DraftModComponentListItem.test.tsx
  src/pageEditor/modListingPanel/ModComponentActionMenu.tsx
  src/pageEditor/modListingPanel/ModListingPanel.test.tsx
  src/pageEditor/modListingPanel/ModSidebarListItems.tsx
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/store/editor/editorInvariantMiddleware.ts
  src/pageEditor/store/editor/editorSelectors/editorModComponentSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.test.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
  src/pageEditor/store/store.ts
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.test.tsx
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
  src/pageEditor/testHelpers.ts
  src/store/editorStorage.ts
Labels: bug, developer experience, page editor

#9357 #9354: fix Page Editor lag regression when clicking between mods
  src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts
  src/pageEditor/store/editor/editorSlice.ts
Labels: performance, regression

#9371 8348: making telemetry e2e tests faster
  end-to-end-tests/tests/telemetry/errors.spec.ts
  src/telemetry/initErrorReporter.ts
Labels: developer experience, testing

#9377 #9376: fix options args focus/active subtab resetting
  end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts
  src/components/tabLayout/EditorTabLayout.tsx
  src/components/tabLayout/__snapshots__/EditorTabLayout.test.tsx.snap
  src/pageEditor/panes/ModEditorPane.tsx
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
Labels: bug, regression, page editor, release blocker

#9379 #9378: decouple mod options args from form states to apply to all mod components
  end-to-end-tests/tests/pageEditor/optionsArgs.spec.ts
  src/analysis/ReduxAnalysisManager.ts
  src/analysis/analysisTypes.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.test.ts
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
  src/pageEditor/editorPermissionsHelpers.ts
  src/pageEditor/hooks/updateReduxForSavedModDefinition.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts
  src/pageEditor/modals/addBrickModal/useAddBrick.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/button.ts
  src/pageEditor/starterBricks/contextMenu.test.ts
  src/pageEditor/starterBricks/contextMenu.ts
  src/pageEditor/starterBricks/dynamicQuickBar.ts
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/starterBricks/quickBar.ts
  src/pageEditor/starterBricks/sidebar.ts
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/store/editor/baseFormStateTypes.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/pageEditor/tabs/effect/StarterBrickPreview.tsx
  src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
  src/testUtils/factories/pageEditorFactories.ts
Labels: bug, page editor

#9361 #9355: fix dirty flag on Formik reinitialization regression
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/tests/pageEditor/clearChanges.spec.ts
  src/__snapshots__/Storyshots.test.js.snap
  src/icons/Icon.tsx
  src/pageEditor/layout/EditorContent.tsx
  src/pageEditor/modListingPanel/ModComponentIcons.tsx
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/pageEditor/panes/ModComponentEditorPane.tsx
  src/pageEditor/store/editor/editorSlice.ts
Labels: bug, regression, release blocker

#9384 Fix selection of variable with trailing number
  src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.test.ts
  src/runtime/pathHelpers.ts
Labels: bug, page editor

#9383 Refactor Offscreen page to use webext-messenger
  end-to-end-tests/tests/pageEditor/optionsArgs.spec.ts
  src/background/capture.ts
  src/offscreen/errorReport.ts
  src/offscreen/messenger/api.ts
  src/offscreen/messenger/registration.ts
  src/offscreen/offscreen.html
  src/offscreen/offscreen.ts
  src/offscreen/offscreenDocumentController.ts
  src/offscreen/recording.ts
  src/telemetry/logging.test.ts
  src/telemetry/reportToApplicationErrorTelemetry.test.ts
  src/telemetry/reportToApplicationErrorTelemetry.ts
  src/tinyPages/offscreenProtocol.ts
  webpack.config.mjs
Labels: developer experience

#9385 Move mod variables definition out of mod component form state
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-button-starter-brick-to-mod.yaml
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-added.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-copied-to-another-mod.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-copy-pasted.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-removed.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/bricks-moved.diff
  end-to-end-tests/tests/pageEditor/brickConfiguration.spec.ts-snapshots/brick-configuration/starter-brick-configuration-changes.diff
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts-snapshots/copying-a-mod-that-uses-the-PixieBrix-API-is-copied-correctly/write-to-db-static-copy.diff
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts-snapshots/run-a-copied-mod-with-a-built-in-integration/giphy-search-copy.diff
  end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts-snapshots/mod-editor-pane-behavior/updated-inputs.diff
  end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts-snapshots/mod-editor-pane-behavior/updated-metadata.diff
  src/analysis/ReduxAnalysisManager.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.test.ts
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.test.tsx
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
  src/pageEditor/editorPermissionsHelpers.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/hooks/useBuildAndValidateMod.ts
  src/pageEditor/hooks/useClearModChanges.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/modListingPanel/ModComponentActionMenu.stories.tsx
  src/pageEditor/modals/addBrickModal/useAddBrick.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/contextMenu.test.ts
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/store/editor/baseFormStateTypes.ts
  src/pageEditor/store/editor/editorSelectors/editorModComponentSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.test.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/pageEditor/tabs/effect/StarterBrickPreview.tsx
  src/pageEditor/tabs/modOptionsArgs/ModOptionsArgsEditor.tsx
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
  src/store/modComponents/modComponentUtils.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
  src/testUtils/factories/pageEditorFactories.ts
Labels: bug, developer experience

#9382 #9381: fix missing sidepanel tab title
  end-to-end-tests/tests/pageEditor/draftInjection.spec.ts
  src/contentScript/lifecycle.ts
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.ts
Labels: bug, testing, regression

#9390 Fixes resetting dirty form states outside the mod that was saved
  src/pageEditor/store/editor/editorSelectors/editorModComponentSelectors.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
Labels: bug, regression, release blocker
