Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-05, with the labels that each got.

#8383 #8382: brick to export data url as file
  src/bricks/effects/exportFileEffect.test.ts
  src/bricks/effects/exportFileEffect.ts
  src/bricks/effects/getAllEffects.ts
  src/development/headers.test.ts
  src/tsconfig.strictNullChecks.json
Labels: brick, customer

#8379 Fix mv2 permissions
  scripts/__snapshots__/manifest.test.js.snap
  scripts/manifest.mjs
  src/manifest.json
Labels: bug, infrastructure

#8381 #8380: add isInViewport property to element reader
  src/bricks/readers/ElementReader.test.ts
  src/bricks/readers/ElementReader.ts
  src/utils/domUtils.ts
Labels: enhancement, brick, customer

#8378 Axios upgrade
  package-lock.json
  package.json
  src/components/errors/NetworkErrorDetail.tsx
  src/contrib/google/sheets/core/handleGoogleRequestRejection.ts
  src/data/service/errorService.ts
  src/utils/urlUtils.ts
Labels: dependencies

#8388 Avoid running CI workflow twice for PRs
  .github/workflows/ci.yml
Labels: testing

#8377 #8070 Page Editor formik-validation/field-annotation fixes and AA remote fetch brick errors
  src/__snapshots__/Storyshots.test.js.snap
  src/analysis/AnalysisAnnotationsContext.ts
  src/components/fields/schemaFields/BasicSchemaField.tsx
  src/components/form/ConnectedFieldTemplate.test.tsx
  src/components/form/ConnectedFieldTemplate.tsx
  src/components/form/FieldTemplate.tsx
  src/components/form/Form.stories.tsx
  src/components/form/Form.tsx
  src/components/form/makeFieldActionForAnnotationAction.ts
  src/components/form/makeFieldAnnotationsForValue.ts
  src/components/form/useFieldAnnotations.test.tsx
  src/components/form/useFieldAnnotations.ts
  src/components/form/widgets/AsyncRemoteSelectWidget.test.tsx
  src/components/form/widgets/AsyncRemoteSelectWidget.tsx
  src/components/formBuilder/edit/FieldEditor.tsx
  src/contrib/automationanywhere/ApiTaskOptions.tsx
  src/contrib/automationanywhere/BotOptions.tsx
  src/contrib/automationanywhere/RemoteFileSelectField.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx
  src/extensionConsole/pages/activateMod/OptionsBody.test.tsx
  src/extensionConsole/pages/activateMod/__snapshots__/OptionsBody.test.tsx.snap
  src/pageEditor/EditorContent.tsx
  src/pageEditor/ElementWizard.tsx
  src/pageEditor/fields/UrlMatchPatternField.stories.tsx
  src/pageEditor/fields/UrlPatternField.stories.tsx
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/sidebar/modals/CreateModModal.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/tabs/editTab/AnalysisResult.tsx
  src/pageEditor/tabs/editTab/FoundationNodeConfigPanel.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.tsx
  src/testUtils/testHelpers.tsx
  src/tsconfig.strictNullChecks.json
Labels: user experience, developer experience

#8391 Fix ci running twice
  .github/workflows/ci.yml
  .github/workflows/rainforestqa.yml
Labels: infrastructure, testing

#8387 Strict Null Checks - background/contextMenus
  src/background/background.ts
  src/background/contextMenus.ts
  src/background/contextMenus/ensureContextMenu.ts
  src/background/contextMenus/initContextMenus.test.ts
  src/background/contextMenus/initContextMenus.ts
  src/background/contextMenus/makeMenuId.ts
  src/background/contextMenus/preloadContextMenus.ts
  src/background/contextMenus/uninstallContextMenu.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/background/modUpdater.test.ts
  src/background/modUpdater.ts
  src/background/removeExtensionForEveryTab.ts
  src/contentScript/contentScriptPlatform.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/starterBricks/contextMenu/contextMenu.test.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8396 Strict null checks after file split
  src/background/getBuiltInIntegrationConfigs.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/background/partnerHandlers.ts
  src/background/removeExtensionForEveryTab.ts
  src/background/starterMods.test.ts
  src/background/starterMods.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/messenger/strict/api.ts
  src/contentScript/messenger/strict/registration.ts
  src/contrib/automationanywhere/SetCopilotDataEffect.ts
  src/contrib/automationanywhere/aaFrameProtocol.ts
  src/contrib/automationanywhere/aaTypes.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8395 adds test to activate mod with database and run it
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
Labels: testing

#8403 #8315: update focus dialog messaging
  end-to-end-tests/tests/runtime/sidebarController.spec.ts
  end-to-end-tests/utils.ts
  src/contentScript/focusCaptureDialog.ts
  src/contentScript/sidebarController.tsx
  src/utils/clipboardUtils.ts
Labels: user experience, mv3

#8401 #8203 Fix missing error toast notifications when saving mod
  end-to-end-tests/pageObjects/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  src/pageEditor/hooks/useSaveMod.ts
Labels: bug, regression

#8419 #8418: make RJSF select clearable in Form Builder
  src/components/formBuilder/RjsfSelectWidget.test.tsx
  src/components/formBuilder/RjsfSelectWidget.tsx
Labels: bug, form builder, customer

#8420 Add isMV3 to blobToImageData
  src/utils/canvasUtils.ts
Labels: mv3

#8417 #8397: Fix App crashing when chrome runtime is undefined
  src/tinyPages/offscreen.ts
Labels: infrastructure

#8425 #8104 Do not automatically close the sidebar when saving in the Page Editor
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/pageEditorPage.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  end-to-end-tests/utils.ts
  src/contentScript/lifecycle.ts
Labels: mv3

#8424 Strict null checks exclude 3
  src/components/fields/schemaFields/selectFieldUtils.ts
  src/components/fields/schemaFields/widgets/DatabaseCreateModal.tsx
  src/components/fields/schemaFields/widgets/DatabaseWidget.tsx
  src/components/fields/schemaFields/widgets/NumberWidget.tsx
  src/components/fields/schemaFields/widgets/PasswordWidget.tsx
  src/components/fields/schemaFields/widgets/SchemaButtonVariantWidget.tsx
  src/components/fields/schemaFields/widgets/SchemaSelectWidget.tsx
  src/components/fields/schemaFields/widgets/varPopup/varSelectors.ts
  src/components/form/widgets/RemoteMultiSelectWidget.tsx
  src/components/form/widgets/SelectWidget.test.tsx
  src/components/form/widgets/SelectWidget.tsx
  src/components/form/widgets/switchButton/SwitchButtonWidget.test.tsx
  src/components/formBuilder/BaseInputTemplate.test.tsx
  src/components/formBuilder/formBuilderHelpers.test.ts
  src/components/formBuilder/formBuilderHelpers.ts
  src/components/formBuilder/formBuilderTypes.ts
  src/components/formBuilder/formEditor.testCases.ts
  src/components/formBuilder/preview/FormPreview.tsx
  src/components/pagination/Pagination.stories.tsx
  src/components/schemaTree/SchemaTree.stories.tsx
  src/contentScript/pageEditor/elementPicker.test.ts
  src/contentScript/pageEditor/selectElement.test.ts
  src/contrib/automationanywhere/aaUtils.ts
  src/contrib/google/sheets/core/sheetsApi.test.ts
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.tsx
  src/data/service/api.test.tsx
  src/errors/clientRequestErrors.test.ts
  src/errors/errorHelpers.test.tsx
  src/errors/errorHelpers.ts
  src/extensionConsole/pages/mods/GetStartedView.stories.tsx
  src/extensionConsole/pages/mods/modsPageSlice.ts
  src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/extensionConsole/pages/workshop/CustomBricksCard.tsx
  src/extensionConsole/pages/workshop/WorkshopPage.tsx
  src/extensionConsole/pages/workshop/workshopTypes.ts
  src/hooks/useMilestones.test.ts
  src/hooks/useTimeoutState.test.ts
  src/hooks/useToggleFormField.tsx
  src/integrations/UserDefinedIntegration.test.ts
  src/integrations/util/extractIntegrationIdsFromSchema.test.ts
  src/mv3/SessionStorage.test.ts
  src/pageEditor/fields/SelectorSelectorWidget.tsx
  src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.stories.tsx
  src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
  src/pageEditor/hooks/useExtensionTrace.ts
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/runtimeSelectors.ts
  src/store/settings/settingsSlice.ts
  src/telemetry/trace.ts
  src/tsconfig.enforceStrictNullChecks.json
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8430 Strict null checks exclude 4
  src/components/fields/schemaFields/schemaFieldUtils.ts
  src/components/form/FieldTemplate.test.tsx
  src/integrations/components/RequireIntegrationConfig.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/tabs/editTab/AnalysisResult.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/PageStateTab.tsx
  src/pageEditor/tabs/editTab/editorNodes/brickNode/BrickNode.tsx
  src/pageEditor/tabs/editTab/useReportTraceError.ts
  src/pageEditor/tabs/effect/AdvancedLinks.test.tsx
  src/pageEditor/tabs/effect/AdvancedLinks.tsx
  src/pageEditor/utils.ts
  src/pageScript/frameworks/component.ts
  src/pageScript/pageScript.ts
  src/runtime/extendModVariableContext.test.ts
  src/runtime/mapArgs.test.ts
  src/runtime/mapArgs.ts
  src/tinyPages/frame.ts
  src/tsconfig.enforceStrictNullChecks.json
  src/tsconfig.strictNullChecks.json
  src/utils/formUtils.ts
Labels: developer experience

#8434 Strict null checks - deferredLoginController
  src/contentScript/integrations/deferredLoginController.test.tsx
  src/contentScript/integrations/deferredLoginController.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/messenger/strict/api.ts
  src/contentScript/messenger/strict/registration.ts
  src/tsconfig.enforceStrictNullChecks.json
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8431 custom eslint rule for e2e test length
  .eslintrc.js
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
  end-to-end-tests/tests/runtime/insertAtCursor.spec.ts
  eslint-local-rules/preferUsingStepsForLongTests.js
Labels: developer experience, testing

#8452 ensure path is set when opening the sidebar
  src/utils/sidePanelUtils.ts
Labels: bug

#8429 #8428: playwright activating a quick bar mod when you dont have a quick bar shortcut configured
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/extensionsShortcutsPage.ts
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
  end-to-end-tests/utils.ts
Labels: testing

#8457 fix e2e flakiness with deleting mods cleanup
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
Labels: developer experience, testing

#8437 Fix AA CoPilot sidebar window messaging
  src/contrib/automationanywhere/aaFrameProtocol.ts
Labels: bug

#8461 fix invalid semver version error
  src/background/installer.test.ts
  src/background/installer.ts
Labels: bug, regression

#8216 #8206: playwright tests for MS Edge sidebar links
  end-to-end-tests/tests/regressions/sidebarLinks.spec.ts
  end-to-end-tests/utils.ts
  src/sidebar/Header.tsx
  src/sidebar/__snapshots__/Header.test.tsx.snap
  src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
Labels: testing, low priority

#8462 #8127: adds test for activation url
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
Labels: testing

#8467 form validation errors support showing a button link
  src/components/form/ConnectedFieldTemplate.tsx
  src/components/form/Form.stories.tsx
  src/utils/stringUtils.test.ts
  src/utils/stringUtils.ts
Labels: user experience

#8472 #8376 Fix show sidebar brick not refreshing panel
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
  src/contentScript/sidebarController.tsx
Labels: bug, regression

#8473 DX - Add BETA to dev tools panel title for the beta extension build
  src/tinyPages/devtools.ts
Labels: user experience, developer experience

#8468 Add SelectWidget support for grouped options and placeholder prop
  src/components/form/widgets/SelectWidget.test.tsx
  src/components/form/widgets/SelectWidget.tsx
  src/components/form/widgets/__snapshots__/SelectWidget.test.tsx.snap
Labels: enhancement, user experience

#8460 #8459 Fix activation and deployments for mods that have more than one integration config for the same integration
  src/integrations/util/getUnconfiguredComponentIntegrations.test.ts
  src/integrations/util/getUnconfiguredComponentIntegrations.ts
Labels: bug

#8474 #8287: Improve UX for long sidebar open times
  package-lock.json
  package.json
  src/contentScript/sidebarController.tsx
Labels: user experience

#8484 Fix beta release Github action
  .github/workflows/beta-release.yaml
Labels: infrastructure

#8482 removes mv2 builds; simplifies workflows
  .github/workflows/beta-release.yaml
  .github/workflows/ci.yml
  .github/workflows/release.yaml
  webpack.config.mjs
Labels: infrastructure

#8475 DX - Refactor some of the sidebar frame function names to clarify behavior, and fix sidebar-sub-frame console error
  src/__mocks__/@/utils/expectContext.ts
  src/contrib/automationanywhere/aaFrameProtocol.ts
  src/contrib/google/sheets/core/useCurrentOrigin.ts
  src/errors/contextInvalidated.ts
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/connectedTarget.tsx
  src/tinyPages/RestrictedUrlPopupApp.tsx
  src/utils/expectContext.ts
  src/utils/sidePanelUtils.ts
Labels: developer experience

#8483 #8470: isolate focusCaptureDialog from host page styles
  end-to-end-tests/tests/runtime/sidebarController.spec.ts
  src/contentScript/contentScript.scss
  src/contentScript/focusCaptureDialog.scss
  src/contentScript/focusCaptureDialog.ts
Labels: bug, user experience

#8488 Rainforest - switch from mv2 to mv3
  .github/workflows/rainforestqa.yml
Labels: testing

#8495 Reduce padding of footer buttons in Mod Activation Panel
  src/sidebar/activateMod/ActivateModPanel.module.scss
Labels: user experience

#8498 #8496: add default value to handle empty storage
  src/background/messenger/external/_implementation.ts
Labels: bug, regression

#8491 Update manifest.json to mv3
  scripts/__snapshots__/manifest.test.js.snap
  scripts/manifest.mjs
  scripts/manifest.test.js
  src/manifest.json
Labels: mv3

#8501 fix web_accessible_resources path
  scripts/manifest.mjs
Labels: infrastructure

#8502 #8494 Fix sidebar mod activation flows that involve user onboarding
  src/contentScript/sidebarActivation.ts
Labels: bug, mv3

#8505 #8504: link to admin console for remote config error
  src/integrations/components/RequireIntegrationConfig.test.tsx
  src/integrations/components/RequireIntegrationConfig.tsx
Labels: bug

#8518 #8516: include mod metadata with TextCommandRun event
  src/bricks/effects/AddDynamicTextSnippet.test.ts
  src/bricks/effects/AddDynamicTextSnippet.ts
  src/bricks/effects/AddTextSnippets.test.ts
  src/bricks/effects/AddTextSnippets.ts
  src/contentScript/snippetShortcutMenu/SnippetShortcutMenu.stories.tsx
  src/contentScript/snippetShortcutMenu/SnippetShortcutMenu.test.tsx
  src/contentScript/snippetShortcutMenu/SnippetShortcutMenu.tsx
  src/contentScript/snippetShortcutMenu/snippetShortcutMenuController.test.tsx
  src/contentScript/snippetShortcutMenu/snippetShortcutMenuSlice.test.ts
  src/platform/platformTypes/snippetShortcutMenuProtocol.ts
Labels: telemetry

#8517 #8385: drop obsolete upgradePipelineToV3 code
  src/components/fields/schemaFields/WorkshopMessage.module.scss
  src/components/fields/schemaFields/WorkshopMessage.tsx
  src/pageEditor/ElementWizard.tsx
  src/pageEditor/fields/ApiVersionField.tsx
  src/pageEditor/pageEditorTypes.ts
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.test.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/starterBricks/upgrade.test.ts
  src/pageEditor/starterBricks/upgrade.ts
  src/pageEditor/tabs/editTab/EditTab.tsx
  src/pageEditor/tabs/editTab/FoundationNodeConfigPanel.tsx
  src/pageEditor/tabs/editTab/UnsupportedRuntimeVersion.tsx
  src/pageEditor/tabs/editTab/UpgradedToApiV3.tsx
  src/tsconfig.strictNullChecks.json
  src/types/runtimeTypes.ts
Labels: developer experience

#8521 Fix offscreen errors
  end-to-end-tests/tests/telemetry/errors.spec.ts
  src/telemetry/logging.test.ts
  src/telemetry/logging.ts
  src/tinyPages/offscreen.ts
Labels: mv3

#8520 Remove background mv2 code
  src/background/background.ts
  src/background/backgroundPlatform.ts
  src/background/browserAction.ts
  src/background/initTheme.ts
  src/background/setToolbarBadge.test.ts
  src/background/setToolbarIconFromTheme.test.ts
  src/background/setToolbarIconFromTheme.ts
  src/background/sidePanel.ts
  src/background/telemetry.ts
  src/background/toolbarBadge.ts
  src/mv3/api.ts
  src/utils/canvasUtils.test.ts
  src/utils/canvasUtils.ts
  src/utils/sidePanelUtils.ts
Labels: developer experience, mv3

#8522 Remove sidebar mv2 code
  src/contentScript/messenger/strict/api.ts
  src/contentScript/messenger/strict/registration.ts
  src/contentScript/sidebarController.tsx
  src/extensionConsole/toggleSidebar.tsx
  src/sidebar/ConnectedSidebar.test.tsx
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/Header.tsx
  src/sidebar/SidebarBody.test.tsx
  src/sidebar/Tabs.test.tsx
  src/sidebar/__snapshots__/Header.test.tsx.snap
  src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/sidebar/connectedTarget.tsx
  src/sidebar/hooks/useConnectedTargetUrl.tsx
  src/sidebar/messenger/registration.ts
  src/sidebar/protocol.tsx
  src/sidebar/sidePanel.tsx
  src/sidebar/sidebar.tsx
  src/sidebar/useHideEmptySidebar.ts
  src/tsconfig.strictNullChecks.json
Labels: mv3

#8492 #8463: playwright create run package and update mod
  end-to-end-tests/pageObjects/extensionConsole/editWorkshopModPage.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshopPage.ts
  end-to-end-tests/pageObjects/pageEditorPage.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  src/components/AsyncButton.tsx
  src/components/ellipsisMenu/EllipsisMenu.tsx
  src/extensionConsole/pages/mods/ModsPageActions.tsx
  src/pageEditor/sidebar/ActionMenu.tsx
  src/pageEditor/sidebar/DynamicModComponentListItem.tsx
  src/pageEditor/sidebar/ModListItem.tsx
  src/pageEditor/sidebar/SaveButton.tsx
  src/pageEditor/sidebar/__snapshots__/DynamicModComponentListItem.test.tsx.snap
Labels: testing

#8525 #8524: swap out aa logo for png; catch errors attempt to set cached logo
  img/aa-logo-small.png
  img/aa-logo-small.svg
  src/background/initTheme.ts
  src/components/addBlockModal/AddBlockModal.tsx
  src/themes/themeUtils.ts
Labels: bug

#8529 Strict null checks more content script messenger files
  src/background/messenger/registration.ts
  src/bricks/renderers/documentView/DocumentView.tsx
  src/bricks/transformers/brickFactory.ts
  src/components/documentBuilder/documentBuilderTypes.ts
  src/components/documentBuilder/documentTree.test.tsx
  src/components/documentBuilder/documentTree.tsx
  src/components/documentBuilder/render/BlockElement.tsx
  src/components/documentBuilder/render/ButtonElement.tsx
  src/components/documentBuilder/render/DocumentContext.tsx
  src/components/documentBuilder/render/ListElement.tsx
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/messenger/strict/api.ts
  src/contentScript/messenger/strict/registration.ts
  src/contentScript/pageEditor/dynamic/runStarterBrickReader.ts
  src/contentScript/pipelineProtocol/runRendererPipeline.ts
  src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/runtime/reducePipeline.ts
  src/sidebar/PanelBody.tsx
  src/sidebar/RendererComponent.tsx
  src/starterBricks/contextMenu/contextMenu.ts
  src/starterBricks/menuItem/menuItemExtension.ts
  src/starterBricks/panel/panelExtension.ts
  src/starterBricks/quickBar/quickBarExtension.tsx
  src/starterBricks/quickBarProvider/quickBarProviderExtension.tsx
  src/starterBricks/sidebar/sidebarExtension.ts
  src/starterBricks/tour/tourExtension.test.ts
  src/starterBricks/tour/tourExtension.ts
  src/starterBricks/triggerExtension.ts
  src/tsconfig.enforceStrictNullChecks.json
  src/tsconfig.strictNullChecks.json
  src/types/helpers.ts
  src/types/modComponentTypes.ts
  src/types/runtimeTypes.ts
Labels: developer experience

#8528 #8485: deployment telemetry improvements
  src/background/deploymentUpdater.test.ts
  src/background/deploymentUpdater.ts
  src/telemetry/events.ts
  src/utils/deploymentUtils.ts
Labels: bug, telemetry
