Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-07, with the labels that each got.

#8728 Prevent retired starter bricks in saved standalone mods from crashing mods screen
  src/mods/useModViewItems.test.tsx
  src/mods/useMods.test.ts
  src/mods/useMods.ts
Labels: bug, developer experience

#8729 Drop tour starter brick and related bricks
  end-to-end-tests/pageObjects/pageEditorPage.ts
  schemas/extensionPoint.json
  src/analysis/analysisVisitors/brickTypeAnalysis.ts
  src/bricks/brickFilterHelpers.ts
  src/bricks/effects/getAllEffects.ts
  src/bricks/effects/runSubTour.test.ts
  src/bricks/effects/runSubTour.ts
  src/bricks/effects/tourEffect.ts
  src/bricks/effects/wait.ts
  src/bricks/transformers/getAllTransformers.ts
  src/bricks/transformers/tourStep/TourStepOptions.module.scss
  src/bricks/transformers/tourStep/TourStepOptions.test.tsx
  src/bricks/transformers/tourStep/TourStepOptions.tsx
  src/bricks/transformers/tourStep/__snapshots__/TourStepOptions.test.tsx.snap
  src/bricks/transformers/tourStep/overlay.ts
  src/bricks/transformers/tourStep/tourStep.test.ts
  src/bricks/transformers/tourStep/tourStep.ts
  src/contentScript/pageEditor/draft/updateDraftModComponent.ts
  src/contentScript/popoverDom.ts
  src/contrib/editors.ts
  src/development/headers.test.ts
  src/pageEditor/exampleBrickConfigs.ts
  src/pageEditor/exampleStarterBrickConfigs.ts
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/starterBricks/tour.ts
  src/pageEditor/tabs/effect/BrickConfiguration.tsx
  src/pageEditor/tabs/tour/TourConfiguration.tsx
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/pageEditor/utils.ts
  src/starterBricks/factory.ts
  src/starterBricks/tour/tourActionIcon.tsx
  src/starterBricks/tour/tourController.test.ts
  src/starterBricks/tour/tourController.ts
  src/starterBricks/tour/tourStarterBrick.test.ts
  src/starterBricks/tour/tourStarterBrick.ts
  src/starterBricks/tour/tourTypes.ts
  src/tours/tourRunDatabase.test.ts
  src/tours/tourRunDatabase.ts
  src/tsconfig.strictNullChecks.json
  src/types/starterBrickTypes.ts
  src/utils/schemaUtils.ts
Labels: developer experience

#8730 Rename `menuItem` to `button` starter brick in Page Editor code
  src/analysis/analysisVisitors/selectorAnalysis.ts
  src/background/deploymentUpdater.test.ts
  src/pageEditor/panes/insert/InsertButtonPane.tsx
  src/pageEditor/panes/insert/InsertPane.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/sidebar/arrangeSidebarItems.test.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/starterBricks/button.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/tabs/button/ButtonConfiguration.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.tsx
  src/starterBricks/button/buttonStarterBrickTypes.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/pageEditorFactories.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience, page editor

#8732 Update `webext-tools` usage
  package-lock.json
  package.json
  src/background/navigation.ts
  src/permissions/permissionsUtils.ts
Labels: dependencies

#8731 Replace `webext-detect-page` with `webext-detect`
  package-lock.json
  package.json
  src/__mocks__/webext-detect.ts
  src/auth/authStorage.ts
  src/background/backgroundDomWatcher.ts
  src/background/contentScript.test.ts
  src/background/contextMenus/initContextMenus.test.ts
  src/background/deploymentUpdater.test.ts
  src/background/externalProtocol.ts
  src/background/performConfiguredRequest.test.ts
  src/bricks/transformers/brickFactory.test.ts
  src/bricks/transformers/brickFactory.ts
  src/contrib/google/sheets/core/useCurrentOrigin.test.ts
  src/contrib/google/sheets/core/useCurrentOrigin.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/data/service/baseService.ts
  src/layout/EnvironmentBanner.tsx
  src/layout/Footer.tsx
  src/runtime/pipelineTests/component.test.ts
  src/telemetry/initErrorReporter.ts
  src/telemetry/reportError.ts
  src/tsconfig.strictNullChecks.json
  src/types/loggerTypes.ts
  src/utils/browserUtils.ts
  src/utils/expectContext.ts
  src/utils/preventNativeFormSubmission.ts
  src/utils/sidePanelUtils.ts
Labels: dependencies

#8727 #8581 refactoring POMs to use the BasePageObject
  end-to-end-tests/pageObjects/basePageObject.ts
  end-to-end-tests/pageObjects/extensionConsole/localIntegrationsPage.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/createWorkshopModPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/editWorkshopModPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/modEditor.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/pageObjects/pageEditorPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  end-to-end-tests/tests/runtime/localIntegrations.spec.ts
  end-to-end-tests/tests/smoke/modsPage.spec.ts
  end-to-end-tests/tests/smoke/pageEditor.spec.ts
  end-to-end-tests/tests/smoke/sidebar.spec.ts
  end-to-end-tests/tests/workshop/createMod.spec.ts
Labels: developer experience, testing

#8735 rename PageEditor sidebar -> ModListingPanel
  src/pageEditor/EditorLayout.tsx
  src/pageEditor/Modals.tsx
  src/pageEditor/modListingPanel/ActionButtons.module.scss
  src/pageEditor/modListingPanel/ActionMenu.module.scss
  src/pageEditor/modListingPanel/ActionMenu.stories.tsx
  src/pageEditor/modListingPanel/ActionMenu.tsx
  src/pageEditor/modListingPanel/ActivatedModComponentListItem.test.tsx
  src/pageEditor/modListingPanel/ActivatedModComponentListItem.tsx
  src/pageEditor/modListingPanel/AddStarterBrickButton.tsx
  src/pageEditor/modListingPanel/DraftModComponentListItem.test.tsx
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/Entry.module.scss
  src/pageEditor/modListingPanel/HomeButton.module.scss
  src/pageEditor/modListingPanel/HomeButton.tsx
  src/pageEditor/modListingPanel/ModComponentIcons.test.tsx
  src/pageEditor/modListingPanel/ModComponentIcons.tsx
  src/pageEditor/modListingPanel/ModComponentListItem.tsx
  src/pageEditor/modListingPanel/ModComponents.module.scss
  src/pageEditor/modListingPanel/ModComponents.tsx
  src/pageEditor/modListingPanel/ModListItem.test.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/ModListingPanel.module.scss
  src/pageEditor/modListingPanel/ModListingPanel.tsx
  src/pageEditor/modListingPanel/ReloadButton.tsx
  src/pageEditor/modListingPanel/SaveButton.module.scss
  src/pageEditor/modListingPanel/SaveButton.stories.tsx
  src/pageEditor/modListingPanel/SaveButton.tsx
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/pageEditor/modListingPanel/__snapshots__/ModComponentIcons.test.tsx.snap
  src/pageEditor/modListingPanel/arrangeSidebarItems.test.ts
  src/pageEditor/modListingPanel/arrangeSidebarItems.ts
  src/pageEditor/modListingPanel/common.ts
  src/pageEditor/modListingPanel/filterSidebarItems.test.ts
  src/pageEditor/modListingPanel/filterSidebarItems.ts
  src/pageEditor/modListingPanel/modals/AddToModModal.tsx
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/modListingPanel/modals/MoveFromModModal.tsx
  src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx
  src/pageEditor/utils.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8736 Page Editor data test ids
  src/pageEditor/modListingPanel/ModListingPanel.tsx
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/panes/ModEditorPane.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/editTab/EditTab.tsx
Labels: testing

#8741 #8611 Rename UIState types
  src/components/fields/schemaFields/widgets/varPopup/SourceLabel.tsx
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
  src/pageEditor/documentBuilder/preview/DocumentPreview.tsx
  src/pageEditor/fields/ConnectedCollapsibleFieldSection.tsx
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/slices/editorSliceHelpers.test.ts
  src/pageEditor/slices/editorSliceHelpers.ts
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/pageEditor/uiState/uiState.ts
  src/pageEditor/uiState/uiStateTypes.ts
  src/store/editorStorage.test.ts
Labels: developer experience, page editor

#8742 #8581 mod listing page object model and organizing page editor POMs
  end-to-end-tests/fixtures/pageContext.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  end-to-end-tests/tests/telemetry/errors.spec.ts
  knip.mjs
  playwright.config.ts
Labels: testing

#8747 #8740 fix welcome starter mods not loading in welcome page
  end-to-end-tests/setup/utils.ts
  end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts
  src/background/starterMods.test.ts
  src/background/starterMods.ts
Labels: bug

#8748 #8581: More page editor poms
  end-to-end-tests/pageObjects/pageEditor/brickActionsPanel.ts
  end-to-end-tests/pageObjects/pageEditor/brickConfigurationPanel.ts
  end-to-end-tests/pageObjects/pageEditor/dataPanel.ts
  end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/pageObjects/pageEditor/utils.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
Labels: testing

#8750 Improve e2e test flakiness
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts
Labels: testing

#8752 Improve Page Editor utils method names
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/pageEditor/utils.ts
Labels: developer experience

#8757 Use type-fest's `Tagged` type for simple nominal types
  src/types/modComponentTypes.ts
  src/types/registryTypes.ts
  src/types/runtimeTypes.ts
  src/types/stringTypes.ts
Labels: developer experience

#8754 #8596: improving mod definition snapshot capabilities - diffing
  .eslintrc.js
  .prettierignore
  end-to-end-tests/env.ts
  end-to-end-tests/fixtures/environmentCheck.ts
  end-to-end-tests/fixtures/modDefinitions.ts
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/editWorkshopModPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/modEditor.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  end-to-end-tests/tests/workshop/createMod.spec.ts
  end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/can-create-a-new-mod-from-a-yaml-definition-and-update-it/description-change.json
  end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/can-create-a-new-mod-from-a-yaml-definition-and-update-it/final-definition.yaml
  end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/can-create-a-new-mod-from-a-yaml-definition-and-update-it/heading-change.json
  end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/can-create-a-new-mod-from-a-yaml-definition-and-update-it/no-changes.json
  end-to-end-tests/tests/workshop/createMod.spec.ts-snapshots/simple-sidebar-panel-edge-can create a new mod from a yaml definition
  package-lock.json
  package.json
  playwright.config.ts
Labels: testing

#8756 Use `ModComponentRef` instead of flat `extensionId` and `blueprintId` in panel entries
  src/bricks/transformers/ephemeralForm/formTransformer.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
  src/bricks/transformers/temporaryInfo/EphemeralPanel.tsx
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/ephemeralForm.ts
  src/contentScript/ephemeralPanel.ts
  src/contentScript/lifecycle.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/runRendererBrick.ts
  src/contentScript/sidebarController.tsx
  src/pageEditor/starterBricks/modComponentFormStateAdapter.ts
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/platform/forms/formController.ts
  src/platform/panels/panelController.ts
  src/platform/platformBase.ts
  src/platform/platformProtocol.ts
  src/sidebar/Tabs.tsx
  src/sidebar/TemporaryPanelTabPane.tsx
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/sidebar/modLauncher/ActiveSidebarModsList.tsx
  src/sidebar/sidebarSelectors.ts
  src/starterBricks/sidebar/sidebarStarterBrick.test.ts
  src/store/sidebar/eventKeyUtils.test.ts
  src/store/sidebar/eventKeyUtils.tsx
  src/store/sidebar/sidebarSlice.test.ts
  src/store/sidebar/sidebarSlice.ts
  src/store/sidebar/thunks/addFormPanel.ts
  src/store/sidebar/thunks/addTemporaryPanel.ts
  src/telemetry/deployments.ts
  src/telemetry/telemetryHelpers.test.ts
  src/telemetry/telemetryHelpers.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/runtimeFactories.ts
  src/testUtils/factories/sidebarEntryFactories.ts
  src/types/modComponentTypes.ts
  src/types/sidebarTypes.ts
  src/utils/modUtils.ts
Labels: developer experience

#8762 #8761: update internal/external naming from `brick` to `package` in the Workshop
  end-to-end-tests/pageObjects/extensionConsole/workshop/createWorkshopModPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/editWorkshopModPage.ts
  end-to-end-tests/pageObjects/extensionConsole/workshop/workshopPage.ts
  end-to-end-tests/tests/smoke/workshopPage.spec.ts
  src/__snapshots__/Storyshots.test.js.snap
  src/components/brickModalNoTags/BrickResult.tsx
  src/components/paginatedTable/PaginatedTable.tsx
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/packageEditor/CodeEditor.tsx
  src/extensionConsole/pages/packageEditor/CreatePage.tsx
  src/extensionConsole/pages/packageEditor/EditPage.tsx
  src/extensionConsole/pages/packageEditor/Editor.test.tsx
  src/extensionConsole/pages/packageEditor/Editor.tsx
  src/extensionConsole/pages/packageEditor/PackageHistory.module.scss
  src/extensionConsole/pages/packageEditor/PackageHistory.test.tsx
  src/extensionConsole/pages/packageEditor/PackageHistory.tsx
  src/extensionConsole/pages/packageEditor/SharingTable.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/DetailSection.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.module.scss
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.stories.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.test.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageReference.module.scss
  src/extensionConsole/pages/packageEditor/referenceTab/PackageReference.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageResult.module.scss
  src/extensionConsole/pages/packageEditor/referenceTab/PackageResult.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/__snapshots__/PackageDetail.test.tsx.snap
  src/extensionConsole/pages/packageEditor/useLogContext.ts
  src/extensionConsole/pages/packageEditor/useSubmitPackage.test.tsx
  src/extensionConsole/pages/packageEditor/useSubmitPackage.ts
  src/extensionConsole/pages/packageEditor/validate.test.ts
  src/extensionConsole/pages/packageEditor/validate.ts
  src/extensionConsole/pages/workshop/EditablePackagesCard.module.scss
  src/extensionConsole/pages/workshop/EditablePackagesCard.tsx
  src/extensionConsole/pages/workshop/WorkshopPage.test.tsx
  src/extensionConsole/pages/workshop/WorkshopPage.tsx
  src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap
  src/extensionConsole/pages/workshop/workshopTypes.ts
  src/modDefinitions/modDefinitions.test.tsx
  src/store/workshopSlice.ts
  src/tsconfig.strictNullChecks.json
  src/types/registryTypes.ts
Labels: user experience, developer experience, workshop

#8758 Use `ModComponentRef` in Quick Bar protocol
  src/bricks/effects/AddQuickBarAction.test.ts
  src/bricks/effects/AddQuickBarAction.tsx
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/components/quickBar/quickBarRegistry.ts
  src/extensionConsole/pages/mods/hooks/useViewLogsAction.ts
  src/platform/platformTypes/quickBarProtocol.ts
  src/sidebar/Tabs.tsx
  src/sidebar/TemporaryPanelTabPane.tsx
  src/starterBricks/button/buttonStarterBrick.ts
  src/starterBricks/contextMenu/contextMenuStarterBrick.ts
  src/starterBricks/helpers.ts
  src/starterBricks/quickBar/quickBarStarterBrick.tsx
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.test.ts
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/telemetry/telemetryHelpers.test.ts
  src/telemetry/telemetryHelpers.ts
  src/utils/modUtils.ts
Labels: developer experience

#8770 #8769: introduce `PackageInstance` type to disambiguate from `Metadata` definition/instance use cases
  src/components/BrickIcon.tsx
  src/components/brickModalNoTags/BrickDetail.tsx
  src/components/brickModalNoTags/BrickModal.tsx
  src/components/brickModalNoTags/BrickResult.tsx
  src/components/brickModalNoTags/QuickAdd.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageReference.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageResult.tsx
  src/integrations/integrationTypes.ts
  src/runtime/getType.ts
  src/types/brickTypes.ts
  src/types/registryTypes.ts
  src/types/starterBrickTypes.ts
Labels: developer experience

#8772 Rename service -> integration in Page Editor
  src/components/fields/schemaFields/fieldTypeCheckers.ts
  src/contrib/google/sheets/bricks/append.ts
  src/contrib/google/sheets/bricks/lookup.ts
  src/integrations/constants.ts
  src/integrations/util/getModDefinitionIntegrationIds.test.ts
  src/integrations/util/getUnconfiguredComponentIntegrations.test.ts
  src/pageEditor/documentBuilder/edit/DocumentOptions.test.tsx
  src/pageEditor/documentBuilder/hooks/useDeleteElement.ts
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/sidebar/activateMod/ActivateModPanel.test.tsx
Labels: developer experience

#8771 #8771 initial brick actions panel end to end test
  .eslintrc.js
  end-to-end-tests/fixtures/modDefinitions/brick-actions.yaml
  end-to-end-tests/pageObjects/extensionConsole/workshop/modEditor.ts
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts
Labels: testing

#8775 DX - Fix flaky sidebar playwright test
  end-to-end-tests/pageObjects/pageEditor/utils.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
Labels: developer experience, testing

#8777 #8220: Inject sandbox into document root instead of body
  src/utils/domUtils.ts
  src/utils/injectIframe.tsx
Labels: bug

#8779 Update filename/function names in the mods screen
  src/extensionConsole/pages/mods/modals/Modals.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModalBody.tsx
  src/extensionConsole/pages/mods/modals/modLogsModal/ModLogsModal.module.scss
  src/extensionConsole/pages/mods/modals/modLogsModal/ModLogsModal.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishModModals.test.tsx
  src/extensionConsole/pages/mods/modals/shareModals/__snapshots__/PublishModModals.test.tsx.snap
  src/extensionConsole/pages/mods/modals/shareModals/useHasEditPermissions.ts
  src/extensionConsole/pages/mods/utils/mapModComponentToModDefinition.test.ts
  src/extensionConsole/pages/mods/utils/mapModComponentToModDefinition.ts
  src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts
  src/extensionConsole/pages/mods/utils/useReactivateMod.ts
  src/extensionConsole/pages/packageEditor/useSubmitPackage.test.tsx
  src/extensionConsole/pages/packageEditor/useSubmitPackage.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8776 Rename `locator` to `integrationConfigLocator`
  .secrets.baseline
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/background/auth/launchInteractiveOAuth2Flow.ts
  src/background/auth/partnerIntegrations/getPartnerPrincipals.test.ts
  src/background/auth/partnerIntegrations/getPartnerPrincipals.ts
  src/background/auth/partnerIntegrations/launchAuthIntegration.ts
  src/background/background.ts
  src/background/deploymentUpdater.ts
  src/background/installer.test.ts
  src/background/installer.ts
  src/background/integrationConfigLocator.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/performConfiguredRequest.test.ts
  src/background/refreshRegistries.ts
  src/background/refreshToken.test.ts
  src/background/refreshToken.ts
  src/background/requests.ts
  src/components/integrations/AuthWidget.test.tsx
  src/components/integrations/AuthWidget.tsx
  src/contrib/automationanywhere/RunApiTask.test.ts
  src/contrib/google/sheets/core/sheetsApi.test.ts
  src/contrib/google/sheets/core/useGoogleAccount.ts
  src/contrib/google/sheets/core/useSpreadsheetId.test.tsx
  src/contrib/google/sheets/core/useSpreadsheetId.ts
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx
  src/extensionConsole/pages/activateExtension/useCloudExtensionPermissions.ts
  src/extensionConsole/pages/activateMod/IntegrationsBody.test.tsx
  src/extensionConsole/pages/activateMod/useModPermissions.ts
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/integrations/IntegrationsPage.tsx
  src/extensionConsole/pages/onboarding/SetupPage.tsx
  src/extensionConsole/pages/onboarding/partner/ControlRoomTokenForm.tsx
  src/extensionConsole/pages/packageEditor/useSubmitPackage.ts
  src/hooks/useRefreshRegistries.ts
  src/integrations/autoConfigure.ts
  src/integrations/components/RequireIntegrationConfig.test.tsx
  src/integrations/integrationConfigLocator.test.ts
  src/integrations/integrationConfigLocator.ts
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.test.ts
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.ts
  src/integrations/util/findSanitizedIntegrationConfigWithRetry.ts
  src/integrations/util/makeIntegrationsContextFromDependencies.ts
  src/integrations/util/permissionsHelpers.ts
  src/permissions/deploymentPermissionsHelpers.ts
  src/runtime/pipelineTests/integrationsContext.test.ts
  src/runtime/pipelineTests/validateInput.test.ts
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/tsconfig.strictNullChecks.json
  src/utils/deploymentUtils.ts
Labels: developer experience

#8773 Rename `brickModalNoTags` and `BrickIcon` to use `package` terminology
  src/components/PackageIcon.tsx
  src/components/packageSearchModal/PackageDetail.tsx
  src/components/packageSearchModal/PackageResult.tsx
  src/components/packageSearchModal/PackageSearchModal.module.scss
  src/components/packageSearchModal/PackageSearchModal.tsx
  src/components/packageSearchModal/QuickAdd.module.scss
  src/components/packageSearchModal/QuickAdd.tsx
  src/extensionConsole/pages/integrations/IntegrationsPage.tsx
  src/extensionConsole/pages/integrations/PrivateIntegrationsCard.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageResult.tsx
  src/pageEditor/modals/addBrickModal/BrickDetail.tsx
  src/pageEditor/modals/addBrickModal/BrickGridItem.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8782 #8781: strict null checks for BrickConfiguration.tsx
  src/bricks/effects/CommentOptions.tsx
  src/bricks/transformers/IdentityTransformerOptions.tsx
  src/bricks/transformers/jquery/JQueryReaderOptions.tsx
  src/components/fields/optionsRegistry.ts
  src/components/fields/schemaFields/BasicSchemaField.tsx
  src/components/fields/schemaFields/SchemaField.tsx
  src/components/fields/schemaFields/fieldTypeCheckers.ts
  src/components/fields/schemaFields/genericOptionsFactory.tsx
  src/components/fields/schemaFields/schemaFieldUtils.ts
  src/components/fields/schemaFields/widgets/FixedInnerObjectWidget.tsx
  src/components/fields/schemaFields/widgets/ObjectWidget.tsx
  src/components/fields/schemaFields/widgets/TemplateToggleWidget.tsx
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
  src/components/fields/schemaFields/widgets/varPopup/VariablesTree.stories.tsx
  src/components/fields/schemaFields/widgets/varPopup/VariablesTree.test.tsx
  src/components/fields/schemaFields/widgets/varPopup/VariablesTree.tsx
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.ts
  src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.ts
  src/components/fields/schemaFields/widgets/varPopup/menuFilters.ts
  src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.ts
  src/components/fields/schemaFields/widgets/varPopup/useTreeRow.ts
  src/components/integrations/IntegrationConfigEditorModal.tsx
  src/contrib/automationanywhere/ApiTaskOptions.tsx
  src/contrib/automationanywhere/BotOptions.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx
  src/contrib/uipath/LocalProcessOptions.tsx
  src/contrib/uipath/ProcessOptions.tsx
  src/contrib/zapier/PushOptions.tsx
  src/hooks/useBrickOptions.ts
  src/pageEditor/fields/AlertOptions.tsx
  src/pageEditor/fields/AssignModVariableOptions.tsx
  src/pageEditor/fields/CollapsibleFieldSection.tsx
  src/pageEditor/fields/ConnectedCollapsibleFieldSection.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.tsx
  src/runtime/getType.ts
  src/tsconfig.strictNullChecks.json
  src/utils/schemaUtils.ts
Labels: bug, developer experience

#8785 Update naming in panel and starter brick API
  src/background/contextMenus/ensureContextMenu.ts
  src/background/contextMenus/initContextMenus.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/bricks/transformers/temporaryInfo/temporaryPanelProtocol.test.ts
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/contextMenus.ts
  src/contentScript/ephemeralPanel.ts
  src/contentScript/lifecycle.ts
  src/contentScript/pageEditor/runRendererBrick.ts
  src/contentScript/sidebarController.tsx
  src/platform/panels/panelController.ts
  src/platform/platformTypes/contextMenuProtocol.ts
  src/platform/platformTypes/panelProtocol.ts
  src/starterBricks/button/buttonStarterBrick.ts
  src/starterBricks/contextMenu/contextMenuStarterBrick.test.ts
  src/starterBricks/contextMenu/contextMenuStarterBrick.ts
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/testUtils/platformMock.ts
  src/types/runtimeTypes.ts
Labels: developer experience

#8780 #8596 more brick action specs
  end-to-end-tests/pageObjects/basePageObject.ts
  end-to-end-tests/pageObjects/pageEditor/brickActionsPanel.ts
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-added.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-copy-pasted.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-removed.diff
  end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/bricks-moved.diff
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
Labels: testing

#8745 #8737 Package standalone mods on save - Slice 1
  end-to-end-tests/pageObjects/pageEditor/createModModal.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  end-to-end-tests/tests/regressions/doNotCloseSidebarOnPageEditorSave.spec.ts
  src/__snapshots__/Storyshots.test.js.snap
  src/components/form/FieldTemplate.module.scss
  src/components/form/FieldTemplate.tsx
  src/components/form/Form.stories.tsx
  src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useSaveStandaloneModComponent.ts
  src/pageEditor/modListingPanel/DraftModComponentListItem.tsx
  src/pageEditor/modListingPanel/modals/AddToModModal.tsx
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/tsconfig.strictNullChecks.json
Labels: enhancement

#8799 Enabling warn for no-param-reassign eslint rule
  .eslintrc.js
  src/components/formBuilder/formBuilderHelpers.ts
Labels: developer experience

#8802 #8801: fix browser warning on MS Edge
  src/extensionConsole/pages/BrowserBanner.test.tsx
  src/extensionConsole/pages/BrowserBanner.tsx
  src/extensionConsole/pages/__snapshots__/BrowserBanner.test.tsx.snap
  src/utils/browserUtils.ts
Labels: bug

#8798 Rename `block`/`extension` in runtime and tracing
  src/analysis/analysisVisitors/traceAnalysis.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/background/executor.test.ts
  src/bricks/effects/AddDynamicTextSnippet.test.ts
  src/bricks/errors.ts
  src/bricks/renderers/documentView/DocumentView.tsx
  src/bricks/renderers/documentView/DocumentViewProps.tsx
  src/bricks/transformers/RunMetadataTransformer.test.ts
  src/bricks/transformers/brickFactory.test.ts
  src/bricks/transformers/brickFactory.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/contentScript/ephemeralPanel.ts
  src/contentScript/pageEditor/runBrickPreview.ts
  src/contentScript/pageEditor/runRendererBrick.ts
  src/contentScript/pipelineProtocol/runHeadlessPipeline.ts
  src/contentScript/pipelineProtocol/runRendererPipeline.ts
  src/pageEditor/documentBuilder/documentTree.test.tsx
  src/pageEditor/documentBuilder/render/ButtonElement.tsx
  src/pageEditor/documentBuilder/render/DocumentContext.tsx
  src/pageEditor/store/runtime/runtimeSelectors.ts
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/pageEditor/tabs/editTab/useReportTraceError.ts
  src/runtime/pipelineTests/trace.test.ts
  src/runtime/reducePipeline.ts
  src/sidebar/PanelBody.test.tsx
  src/sidebar/PanelBody.tsx
  src/sidebar/RendererComponent.test.tsx
  src/sidebar/RendererComponent.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/telemetry/trace.ts
  src/telemetry/traceHelpers.ts
  src/testUtils/factories/pageEditorFactories.ts
  src/testUtils/factories/runtimeFactories.ts
  src/testUtils/factories/traceFactories.ts
  src/types/rendererTypes.ts
  src/types/runtimeTypes.ts
  src/types/sidebarTypes.ts
Labels: developer experience

#8804 #8059 snippet shortcut e2e test
  end-to-end-tests/tests/runtime/textSnippets.spec.ts
  end-to-end-tests/utils.ts
  src/contentScript/snippetShortcutMenu/snippetShortcutMenuController.tsx
  src/contentScript/textSelectionMenu/selectionMenuController.tsx
  src/domConstants.ts
Labels: testing

#8807 prevent concurrent workflow runs in prs
  .github/workflows/ci.yml
  .secrets.baseline
Labels: performance

#8808 fix flakiness handling
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
Labels: testing

#8809 #8751: move loginController inside the useEffect
  src/contrib/google/sheets/core/useGoogleAccount.ts
Labels: bug

#8810 Adding a link to our readme from the PR e2e report comment
  .github/workflows/ci.yml
Labels: developer experience

#8805 Shard e2e tests
  .github/workflows/end-to-end-tests.yml
  .secrets.baseline
Labels: developer experience, testing

#8800 #5441: Add side effect to hide modals on StaleSessionPane in Page Editor
  end-to-end-tests/tests/regressions/hideModalsOnPageEditorRefresh.spec.ts
  src/pageEditor/layout/EditorLayout.tsx
  src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  src/pageEditor/store/editor/editorSlice.ts
Labels: bug, user experience

#8822 Only retry sandbox postMessage on TimeoutErrors
  src/sandbox/messenger/api.ts
Labels: bug, regression, release blocker

#8816 Use mod component ref for page state
  .secrets.baseline
  src/bricks/effects/AddDynamicTextSnippet.test.ts
  src/bricks/effects/assignModVariable.test.ts
  src/bricks/effects/assignModVariable.ts
  src/bricks/effects/pageState.test.ts
  src/bricks/effects/pageState.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/renderers/customForm.tsx
  src/bricks/transformers/brickFactory.test.ts
  src/bricks/transformers/controlFlow/ForEach.test.ts
  src/bricks/transformers/controlFlow/ForEachElement.test.ts
  src/bricks/transformers/controlFlow/IfElse.test.ts
  src/bricks/transformers/controlFlow/MapValues.test.ts
  src/bricks/transformers/controlFlow/Retry.test.ts
  src/bricks/transformers/controlFlow/Run.test.ts
  src/bricks/transformers/controlFlow/TryExcept.test.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
  src/contentScript/pageEditor/runBrickPreview.ts
  src/contentScript/pageEditor/runRendererBrick.ts
  src/contentScript/pageEditor/types.ts
  src/contentScript/pipelineProtocol/runMapArgs.ts
  src/pageEditor/documentBuilder/render/ListElement.tsx
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/tabs/editTab/dataPanel/tabs/ModVariablesTab.tsx
  src/pageEditor/tabs/effect/BrickPreview.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/platform/state/stateController.test.ts
  src/platform/state/stateController.ts
  src/runtime/extendModVariableContext.test.ts
  src/runtime/extendModVariableContext.ts
  src/runtime/pipelineTests/autoescape.test.ts
  src/runtime/pipelineTests/component.test.ts
  src/runtime/pipelineTests/conditional.test.ts
  src/runtime/pipelineTests/deferExpression.test.ts
  src/runtime/pipelineTests/deploymentAlert.test.ts
  src/runtime/pipelineTests/implicitDataFlow.test.ts
  src/runtime/pipelineTests/integrationsContext.test.ts
  src/runtime/pipelineTests/modVariableContext.test.ts
  src/runtime/pipelineTests/options.test.ts
  src/runtime/pipelineTests/outputKey.test.ts
  src/runtime/pipelineTests/pipelineExpression.test.ts
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/runtime/pipelineTests/root.test.ts
  src/runtime/pipelineTests/templateEngine.test.ts
  src/runtime/pipelineTests/trace.test.ts
  src/runtime/pipelineTests/validateInput.test.ts
  src/runtime/reducePipeline.ts
  src/starterBricks/sidebar/sidebarStarterBrick.test.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/runtimeFactories.ts
Labels: developer experience

#8823 handle dropdown flakiness
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
Labels: testing

#8843 #8828: constant brick condition lint and analysis action bug fixes
  src/analysis/analysisTypes.ts
  src/analysis/analysisVisitors/conditionAnalysis.test.ts
  src/analysis/analysisVisitors/conditionAnalysis.ts
  src/bricks/types.ts
  src/components/form/makeFieldActionForAnnotationAction.test.tsx
  src/components/form/makeFieldActionForAnnotationAction.ts
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/tabs/effect/AdvancedLinks.test.tsx
  src/pageEditor/tabs/effect/AdvancedLinks.tsx
  src/runtime/runtimeUtils.test.ts
  src/runtime/runtimeUtils.ts
  src/tsconfig.strictNullChecks.json
Labels: bug, user experience

#8825 Add e2e test for Javascript brick errors
  end-to-end-tests/tests/regressions/sandboxBrickErrors.spec.ts
Labels: testing

#8842 #8813: support deployment key authentication via Advanced Settings and managed storage
  .secrets.baseline
  src/auth/authStorage.test.ts
  src/auth/authStorage.ts
  src/auth/authTypes.ts
  src/auth/deploymentKey.ts
  src/data/service/baseService.ts
  src/extensionConsole/Navbar.tsx
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/extensionConsole/pages/settings/useDeploymentKeySetting.test.ts
  src/extensionConsole/pages/settings/useDeploymentKeySetting.ts
  src/extensionConsole/pages/settings/useServiceUrlSetting.ts
  src/hooks/useAdminConsoleUrl.ts
  src/hooks/useUpdatableAsyncState.ts
  src/store/enterprise/managedStorageTypes.ts
  src/store/settings/settingsSelectors.ts
  src/store/settings/settingsSlice.ts
  src/store/settings/settingsTypes.ts
  src/testUtils/factories/authFactories.ts
  src/tsconfig.strictNullChecks.json
  static/managedStorageSchema.json
Labels: enhancement, enterprise

#8826 Add state change event type definition and refactor related constants
  src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.test.ts
  src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.ts
  src/bricks/effects/assignModVariable.test.ts
  src/bricks/effects/assignModVariable.ts
  src/bricks/effects/pageState.test.ts
  src/bricks/effects/pageState.ts
  src/bricks/exampleBrickConfigs.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/renderers/customForm.tsx
  src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
  src/contentScript/ephemeralPanel.ts
  src/pageEditor/documentBuilder/createNewDocumentBuilderElement.ts
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/tabs/editTab/dataPanel/tabs/ModVariablesTab.tsx
  src/pageEditor/tabs/sidebar/SidebarConfiguration.tsx
  src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
  src/platform/panels/panelTypes.ts
  src/platform/state/stateController.test.ts
  src/platform/state/stateController.ts
  src/platform/state/stateTypes.ts
  src/runtime/extendModVariableContext.test.ts
  src/runtime/extendModVariableContext.ts
  src/runtime/pipelineTests/modVariableContext.test.ts
  src/starterBricks/helpers.ts
  src/starterBricks/sidebar/sidebarStarterBrick.test.ts
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/sidebar/sidebarStarterBrickTypes.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrickTypes.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8824 DX - Fix interface for `formStateFactory`
  src/analysis/analysisVisitors/eventNameAnalysis/checkEventNamesAnalysis.test.ts
  src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/components/fields/schemaFields/integrations/integrationDependencyFieldUtils.test.ts
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
  src/components/form/ConnectedFieldTemplate.test.tsx
  src/integrations/components/RequireIntegrationConfig.test.tsx
  src/pageEditor/documentBuilder/edit/DocumentOptions.test.tsx
  src/pageEditor/documentBuilder/preview/DocumentPreview.test.tsx
  src/pageEditor/documentBuilder/preview/ElementPreview.test.tsx
  src/pageEditor/fields/FormModalOptions.test.tsx
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useCompareModComponentCounts.test.ts
  src/pageEditor/layout/PanelContent.test.tsx
  src/pageEditor/modListingPanel/ActivatedModComponentListItem.test.tsx
  src/pageEditor/modListingPanel/filterSidebarItems.test.ts
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/store/editor/selectGetCleanComponentsAndDirtyFormStatesForMod.test.ts
  src/pageEditor/tabs/editTab/dataPanel/tabs/ModVariablesTab.test.tsx
  src/pageEditor/tabs/effect/BrickConfiguration.test.tsx
  src/store/editorMigrations.test.ts
  src/store/editorStorage.test.ts
  src/testUtils/factories/pageEditorFactories.ts
Labels: developer experience

#8847 eslint rule for consistent `it` test title usage
  .eslintrc.js
  src/analysis/analysisVisitors/requestPermissionAnalysis.test.ts
  src/background/installer.test.ts
  src/bricks/effects/CancelEffect.test.ts
  src/bricks/effects/assignModVariable.test.ts
  src/bricks/effects/attachAutocomplete.test.ts
  src/bricks/effects/customEvent.test.ts
  src/bricks/effects/disable.test.ts
  src/bricks/effects/enable.test.ts
  src/bricks/effects/error.test.ts
  src/bricks/effects/event.test.ts
  src/bricks/effects/forms.test.ts
  src/bricks/effects/hide.test.ts
  src/bricks/effects/scrollToElement.test.ts
  src/bricks/effects/show.test.ts
  src/bricks/effects/wait.test.ts
  src/bricks/readers/ElementReader.test.ts
  src/bricks/transformers/IdentityTransformer.test.ts
  src/bricks/transformers/detect.test.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/components/fields/schemaFields/schemaFieldUtils.test.ts
  src/components/fields/schemaFields/widgets/varPopup/VariablesTree.test.tsx
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.test.ts
  src/components/fields/schemaFields/widgets/varPopup/menuFilters.test.ts
  src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.test.ts
  src/components/form/widgets/AsyncRemoteSelectWidget.test.tsx
  src/components/form/widgets/radioItemList/RadioItemListWidget.test.tsx
  src/components/form/widgets/radioItemList/__snapshots__/RadioItemListWidget.test.tsx.snap
  src/components/formBuilder/preview/FormPreview.test.tsx
  src/components/tabLayout/EditorTabLayout.test.tsx
  src/components/tabLayout/__snapshots__/EditorTabLayout.test.tsx.snap
  src/contentScript/pageEditor/elementInformation.test.ts
  src/contrib/ckeditor/ckeditor.test.ts
  src/errors/errorHelpers.test.tsx
  src/pageEditor/documentBuilder/preview/DocumentPreview.test.tsx
  src/pageEditor/modListingPanel/DraftModComponentListItem.test.tsx
  src/pageEditor/modListingPanel/__snapshots__/DraftModComponentListItem.test.tsx.snap
  src/pageEditor/modals/addBrickModal/AddBrickModal.test.tsx
  src/pageEditor/modals/addBrickModal/__snapshots__/AddBrickModal.test.tsx.snap
  src/pageEditor/panes/NoTabAccessPane.test.tsx
  src/pageEditor/panes/NonScriptablePage.test.tsx
  src/pageEditor/panes/__snapshots__/NoTabAccessPane.test.tsx.snap
  src/pageEditor/panes/__snapshots__/NonScriptablePage.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/StarterBrickDataPanel.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/StarterBrickDataPanel.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/tabs/ModVariablesTab.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/__snapshots__/ModVariablesTab.test.tsx.snap
  src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
  src/sidebar/ConnectedSidebar.test.tsx
  src/sidebar/SidebarBody.test.tsx
  src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
  src/store/checkActiveModComponentAvailability.test.ts
  src/store/checkAvailableDraftModComponents.test.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/utils/detectRandomString.test.ts
  src/utils/promiseUtils.test.ts
  src/utils/stringUtils.test.ts
Labels: developer experience, testing

#8850 handling flaky loading of the mods page
  end-to-end-tests/pageObjects/extensionConsole/modsPage.ts
Labels: testing

#8855 DX - Quick followup to clean up `insertingStarterBrick` call site
  src/pageEditor/layout/EditorLayout.tsx
  src/pageEditor/panes/insert/InsertPane.tsx
  src/pageEditor/store/editor/editorSelectors.ts
Labels: developer experience

#8849 Rename `BLOCK_ID` to `BRICK_ID` and exclude `scripts/bin` from IDE search
  pixiebrix-extension.iml
  src/analysis/analysisVisitors/conditionAnalysis.test.ts
  src/analysis/analysisVisitors/httpRequestAnalysis.test.ts
  src/analysis/analysisVisitors/httpRequestAnalysis.ts
  src/analysis/analysisVisitors/outputKeyAnalysis.test.ts
  src/analysis/analysisVisitors/requestPermissionAnalysis.test.ts
  src/analysis/analysisVisitors/requestPermissionAnalysis.ts
  src/analysis/analysisVisitors/templateAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/bricks/effects/AddQuickBarAction.tsx
  src/bricks/effects/tourEffect.ts
  src/bricks/transformers/remoteMethod.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/components/form/makeFieldActionForAnnotationAction.test.tsx
  src/pageEditor/tabs/editTab/editHelpers.test.ts
  src/runtime/pipelineTests/pipelineTestHelpers.ts
  src/testUtils/factories/traceFactories.ts
Labels: developer experience

#8853 #8853: mod editor pane metadata e2e tests
  end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts
  end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts-snapshots/mod-editor-pane-behavior/updated-metadata.diff
Labels: testing

#8854 Pass mod component ref via `BrickOptions.meta` instead of logger
  src/background/executor.test.ts
  src/bricks/effects/AddDynamicTextSnippet.test.ts
  src/bricks/effects/AddDynamicTextSnippet.ts
  src/bricks/effects/AddQuickBarAction.test.ts
  src/bricks/effects/AddQuickBarAction.tsx
  src/bricks/effects/AddTextSnippets.ts
  src/bricks/effects/assignModVariable.test.ts
  src/bricks/effects/assignModVariable.ts
  src/bricks/effects/attachAutocomplete.test.ts
  src/bricks/effects/customEvent.test.ts
  src/bricks/effects/pageState.test.ts
  src/bricks/effects/pageState.ts
  src/bricks/effects/sidebarEffects.ts
  src/bricks/effects/tourEffect.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/renderers/customForm.tsx
  src/bricks/renderers/documentView/DocumentView.tsx
  src/bricks/renderers/documentView/DocumentViewProps.tsx
  src/bricks/transformers/RunMetadataTransformer.test.ts
  src/bricks/transformers/RunMetadataTransformer.ts
  src/bricks/transformers/brickFactory.test.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.test.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/bricks/transformers/ephemeralForm/formTransformer.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
  src/contentScript/ephemeralPanel.ts
  src/contentScript/pageEditor/runBrickPreview.ts
  src/contentScript/pageEditor/runRendererBrick.ts
  src/contentScript/pipelineProtocol/runHeadlessPipeline.ts
  src/pageEditor/documentBuilder/render/BlockElement.tsx
  src/pageEditor/documentBuilder/render/ButtonElement.tsx
  src/pageEditor/documentBuilder/render/DocumentContext.tsx
  src/pageEditor/documentBuilder/render/ListElement.tsx
  src/runtime/pipelineTests/modVariableContext.test.ts
  src/runtime/pipelineTests/trace.test.ts
  src/runtime/reducePipeline.ts
  src/sidebar/PanelBody.test.tsx
  src/sidebar/PanelBody.tsx
  src/sidebar/RendererComponent.test.tsx
  src/sidebar/RendererComponent.tsx
  src/starterBricks/button/buttonStarterBrick.ts
  src/starterBricks/contextMenu/contextMenuStarterBrick.ts
  src/starterBricks/quickBar/quickBarStarterBrick.tsx
  src/starterBricks/quickBarProvider/quickBarProviderStarterBrick.tsx
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/telemetry/trace.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/runtimeFactories.ts
  src/types/rendererTypes.ts
  src/types/runtimeTypes.ts
  src/types/sidebarTypes.ts
Labels: developer experience, runtime

#8851 Strict null checks -- 88.4%
  src/components/fields/schemaFields/propTypes.ts
  src/components/fields/schemaFields/widgets/TextWidget.tsx
  src/components/fields/schemaFields/widgets/UrlMatchPatternWidget.tsx
  src/components/formBuilder/edit/ActiveField.tsx
  src/components/formBuilder/edit/FieldEditor.tsx
  src/components/formBuilder/edit/FormEditor.tsx
  src/components/formBuilder/formBuilderHelpers.ts
  src/components/formBuilder/formBuilderTypes.ts
  src/components/integrations/IntegrationConfigEditorModal.tsx
  src/contrib/google/sheets/ui/RequireGoogleSheet.tsx
  src/contrib/google/sheets/ui/TabField.tsx
  src/extensionConsole/pages/activateMod/IntegrationDescriptor.tsx
  src/extensionConsole/pages/activateMod/IntegrationsBody.tsx
  src/extensionConsole/pages/activateMod/OptionsBody.tsx
  src/pageEditor/components/SelectorMatchWidget.tsx
  src/pageEditor/components/UrlPatternWidget.test.tsx
  src/pageEditor/components/UrlPatternWidget.tsx
  src/pageEditor/components/__snapshots__/UrlPatternWidget.test.tsx.snap
  src/pageEditor/fields/FormModalOptions.tsx
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/store/analysisManager.ts
  src/tsconfig.strictNullChecks.json
  src/utils/stringUtils.ts
Labels: developer experience

#8857 #8856: require `modId` in `modComponentRef`
  src/bricks/effects/pageState.test.ts
  src/bricks/transformers/RunMetadataTransformer.test.ts
  src/bricks/transformers/RunMetadataTransformer.ts
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/platform/state/stateController.ts
  src/runtime/extendModVariableContext.test.ts
  src/starterBricks/sidebar/sidebarStarterBrick.ts
  src/telemetry/telemetryHelpers.test.ts
  src/testUtils/factories/modComponentFactories.ts
  src/types/modComponentTypes.ts
  src/utils/modUtils.test.ts
  src/utils/modUtils.ts
Labels: developer experience, runtime

#8852 #8584 Add E2E tests for page-specific features
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/tests/pageEditor/specialPages.spec.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
Labels: testing

#8859 #8856: fix display of mod variables and page state warnings for standalone mod components
  src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.test.ts
  src/analysis/analysisVisitors/pageStateAnalysis/pageStateAnalysis.ts
  src/pageEditor/tabs/editTab/dataPanel/tabs/ModVariablesTab.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/__snapshots__/ModVariablesTab.test.tsx.snap
Labels: bug, page editor, analysis

#8863 Strict null checks -- 90%
  src/pageEditor/documentBuilder/documentBuilderTypes.ts
  src/pageEditor/documentBuilder/edit/DocumentOptions.tsx
  src/pageEditor/documentBuilder/edit/MoveElement.tsx
  src/pageEditor/documentBuilder/edit/RemoveElement.tsx
  src/pageEditor/documentBuilder/hooks/useMoveElement.test.ts
  src/pageEditor/documentBuilder/hooks/useMoveElement.ts
  src/pageEditor/documentBuilder/preview/ElementPreview.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Card.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Container.tsx
  src/pageEditor/documentBuilder/preview/getPreviewComponentDefinition.tsx
  src/pageEditor/fields/AlertOptions.tsx
  src/pageEditor/fields/AssignModVariableOptions.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/fields/RemoteMethodOptions.tsx
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/modals/addBrickModal/AddBrickModal.tsx
  src/pageEditor/modals/addBrickModal/TagList.tsx
  src/pageEditor/modals/addBrickModal/addBrickModalHelpers.ts
  src/pageEditor/modals/addBrickModal/useAddBrick.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/selectGetCleanComponentsAndDirtyFormStatesForMod.ts
  src/pageEditor/store/runtime/runtimeSelectors.ts
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx
  src/permissions/useRequestPermissionsCallback.ts
  src/telemetry/traceHelpers.ts
  src/tsconfig.strictNullChecks.json
  src/utils/formUtils.ts
Labels: developer experience

#8873 Update automation-anywhere/control-room integration definition
  contrib/integrations/automation-anywhere.yaml
  src/integrations/UserDefinedIntegration.test.ts
Labels: bug, regression

#8862 #8815 E2E test for sidebar partner auth
  end-to-end-tests/tests/runtime/sidebar/sidebarActivation.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarAuth.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarController.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarNavigation.spec.ts
  end-to-end-tests/tests/runtime/sidebar/sidebarPanelTheme.spec.ts
Labels: testing

#8876 #8875: show info annotation if selector literal contains template characters
  src/analysis/analysisVisitors/selectorAnalysis.test.ts
  src/analysis/analysisVisitors/selectorAnalysis.ts
Labels: user experience, page editor

#8877 #8864: fix select similar in selection tool
  src/components/selectionToolPopover/SelectionToolPopover.tsx
Labels: bug, regression

#8874 live editing sidebar and trigger e2e test
  end-to-end-tests/pageObjects/basePageObject.ts
  end-to-end-tests/pageObjects/pageEditor/configurationForm.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/liveEditing.spec.ts
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
Labels: testing

#8880 fix style regression
  src/pageEditor/layout/ModComponentFormStateWizard.tsx
  src/pageEditor/panes/EditorPane.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
Labels: bug, user experience

#8858 #8817: copy mod playwright tests
  end-to-end-tests/README.md
  end-to-end-tests/fixtures/modDefinitions.ts
  end-to-end-tests/pageObjects/pageEditor/createModModal.ts
  end-to-end-tests/pageObjects/pageEditor/deactivateModModal.ts
  end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/extensionConsole/activation.spec.ts
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts-snapshots/copying-a-mod-that-uses-the-PixieBrix-API-is-copied-correctly/write-to-db-static-copy.diff
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts-snapshots/copying-a-mod-that-uses-the-PixieBrix-API-is-copied-correctly/write-to-db-static-origin.yaml
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts-snapshots/run-a-copied-mod-with-a-built-in-integration/giphy-search-copy.diff
  end-to-end-tests/tests/pageEditor/copyMod.spec.ts-snapshots/run-a-copied-mod-with-a-built-in-integration/giphy-search-origin.yaml
  end-to-end-tests/tests/pageEditor/specialPages.spec.ts
Labels: testing

#8884 Update AA control room integration definition
  contrib/integrations/automation-anywhere.yaml
Labels: user experience

#8886 #8882 Consolidate useAutoInsert into useAddNewModComponent hook
  end-to-end-tests/pageObjects/pageEditor/brickActionsPanel.ts
  end-to-end-tests/tests/pageEditor/starterBrickAdd.spec.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/layout/EditorLayout.tsx
  src/pageEditor/layout/PanelContent.tsx
  src/pageEditor/panes/insert/InsertPane.tsx
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/store/editor/editorSelectors.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
  src/telemetry/events.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8892 Standardize timestamp creation
  scripts/manifest.mjs
  src/activation/getActivatedModComponentFromDefinition.ts
  src/bricks/readers/DocumentReader.ts
  src/contentScript/lifecycle.test.ts
  src/contrib/automationanywhere/RunApiTask.test.ts
  src/data/service/errorService.ts
  src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/mods/useMods.test.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
  src/runtime/reducePipeline.ts
  src/sidebar/DefaultContent.test.tsx
  src/store/enterprise/managedStorage.test.ts
  src/store/enterprise/managedStorage.ts
  src/store/extensionsMigrations.ts
  src/testUtils/factories/databaseFactories.ts
  src/testUtils/factories/deploymentFactories.ts
  src/testUtils/factories/modComponentFactories.ts
  src/testUtils/factories/modDefinitionFactories.ts
  src/testUtils/factories/stringFactories.ts
  src/types/helpers.ts
  src/types/modComponentTypes.ts
  src/utils/deploymentUtils.test.ts
  src/utils/modUtils.test.ts
  src/utils/timeUtils.ts
Labels: developer experience

#8907 Remove `[Experimental]` from comment brick name
  src/bricks/effects/comment.ts
Labels: user experience, page editor

#8908 Use consistent terminology for experimental settings
  src/extensionConsole/pages/settings/ExperimentalSettings.tsx
  src/store/settings/settingsTypes.ts
Labels: user experience, developer experience

#8920 Disable failing tests caused by Chromium 127 bug
  end-to-end-tests/tests/runtime/allFrames.spec.ts
  end-to-end-tests/tests/runtime/insertAtCursor.spec.ts
  end-to-end-tests/tests/runtime/srcdocFrames.spec.ts
Labels: developer experience, testing

#8909 Bug - Fix active mod ref selector
  src/pageEditor/store/editor/editorSelectors.ts
Labels: bug, regression, page editor

#8919 Strict null checks -- 91.3%
  src/activation/useActivateModWizard.ts
  src/components/ellipsisMenu/EllipsisMenu.tsx
  src/components/fields/schemaFields/RemoteSchemaObjectField.tsx
  src/contrib/google/sheets/bricks/append.ts
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx
  src/contrib/uipath/LocalProcessOptions.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/mods/gridView/GridView.tsx
  src/extensionConsole/pages/mods/listView/ListGroupHeader.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishContentLayout.tsx
  src/extensionConsole/pages/mods/onboardingView/useOnboarding.tsx
  src/extensionConsole/pages/packageEditor/Editor.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageDetail.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageReference.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/PackageResult.tsx
  src/modDefinitions/modDefinitionHooks.ts
  src/sidebar/activateMod/ActivateModInputs.tsx
  src/sidebar/activateMod/ActivateModPanel.tsx
  src/sidebar/activateMod/RequireMods.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8917 improvements to add starter brick e2e spec
  end-to-end-tests/pageObjects/pageEditor/brickActionsPanel.ts
  end-to-end-tests/pageObjects/pageEditor/configurationForm.ts
  end-to-end-tests/pageObjects/pageEditor/createModModal.ts
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/pageObjects/pageEditor/utils.ts
  end-to-end-tests/tests/modLifecycle.spec.ts
  end-to-end-tests/tests/pageEditor/starterBrickAdd.spec.ts
  end-to-end-tests/tests/regressions/welcomeStarterBricks.spec.ts
Labels: testing

#8931 #8933: adds mousedown handler to solve document mousedown handler bug
  src/contentScript/focusCaptureDialog.ts
Labels: bug

#8926 Define report mode constants
  src/pageEditor/starterBricks/trigger.ts
  src/pageEditor/tabs/trigger/TriggerConfiguration.tsx
  src/starterBricks/trigger/triggerStarterBrick.test.ts
  src/starterBricks/trigger/triggerStarterBrick.ts
  src/starterBricks/trigger/triggerStarterBrickTypes.ts
Labels: developer experience

#8918 #8421: default sidebar to a panel for mod that set the badge
  src/background/browserAction.ts
  src/background/toolbarBadge.ts
  src/bricks/effects/setToolbarBadge.test.ts
  src/bricks/effects/setToolbarBadge.ts
  src/platform/platformTypes/badgeProtocol.ts
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/Tabs.test.tsx
  src/sidebar/sidebarSelectors.ts
  src/store/sidebar/sidebarSlice.ts
  src/store/sidebar/sidebarUtils.ts
  src/store/sidebar/utils.ts
  src/tsconfig.strictNullChecks.json
  src/types/modComponentTypes.ts
  src/utils/sidePanelUtils.ts
Labels: enhancement, user experience

#8929 Fix beta starter brick feature flag detection
  .eslintrc.js
  src/auth/featureFlagStorage.ts
  src/components/quickBar/QuickBarApp.tsx
  src/hooks/useFlags.test.tsx
  src/hooks/useFlags.ts
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/modListingPanel/AddStarterBrickButton.tsx
Labels: bug, page editor

#8934 Prevent crash with `getContexts` and fix the window reference in `reportError`
  src/data/service/errorService.ts
  src/tinyPages/offscreen.ts
Labels: bug, release blocker

#8935 Add a feature flag check to disable reporting errors to the PixieBrix error service
  src/data/service/errorService.ts
Labels: infrastructure

#8937 Rename `quickBarProvider` to `dynamicQuickBar` to match UI naming
  src/bricks/effects/AddQuickBarAction.tsx
  src/components/quickBar/quickbarTypes.ts
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/dynamicQuickBar.ts
  src/pageEditor/starterBricks/formStateTypes.ts
  src/pageEditor/tabs/dynamicQuickBar/DynamicQuickBarConfiguration.tsx
  src/starterBricks/dynamicQuickBar/dynamicQuickBarStarterBrick.test.ts
  src/starterBricks/dynamicQuickBar/dynamicQuickBarStarterBrick.tsx
  src/starterBricks/dynamicQuickBar/dynamicQuickBarTypes.ts
  src/starterBricks/dynamicQuickBar/quickBarQueryReader.ts
  src/starterBricks/factory.ts
  src/starterBricks/starterBrickModUtils.ts
  src/tsconfig.strictNullChecks.json
  src/types/starterBrickTypes.ts
Labels: developer experience

#8950 Make output variable names optional in the page editor
  src/analysis/analysisVisitors/outputKeyAnalysis.ts
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/editTab/editHelpers.ts
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/OutputVariableField.test.tsx
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/OutputVariableField.tsx
  src/runtime/runtimeUtils.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience, page editor

#8936 Add mutationObserver to sandboxed srcdoc iframe hack
  end-to-end-tests/tests/runtime/srcdocFrames.spec.ts
  src/contentScript/contentScriptCore.ts
Labels: bug, runtime

#8946 Allow undefined condition value and warn on constant if-else conditions
  src/analysis/analysisVisitors/conditionAnalysis.test.ts
  src/analysis/analysisVisitors/conditionAnalysis.ts
  src/bricks/exampleBrickConfigs.ts
  src/bricks/transformers/controlFlow/IfElse.test.ts
  src/bricks/transformers/controlFlow/IfElse.ts
Labels: user experience, page editor, brick

#8948 #8827: add support for re-ordering array items in the Page Editor
  src/components/fields/schemaFields/widgets/ArrayWidget.module.scss
  src/components/fields/schemaFields/widgets/ArrayWidget.test.tsx
  src/components/fields/schemaFields/widgets/ArrayWidget.tsx
  src/components/fields/schemaFields/widgets/__snapshots__/ArrayWidget.test.tsx.snap
  src/pageEditor/components/__snapshots__/UrlPatternWidget.test.tsx.snap
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/ExtraPermissionsSection.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
Labels: user experience, page editor

#8947 Add "duplicate" element button to document builder
  src/icons/duplicate.svg
  src/pageEditor/documentBuilder/hooks/useDuplicateElement.test.ts
  src/pageEditor/documentBuilder/hooks/useDuplicateElement.ts
  src/pageEditor/documentBuilder/preview/flaps/ActiveElementFlap.tsx
  src/pageEditor/starterBricks/pipelineMapping.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience, page editor

#8916 #8869 Add new starter bricks directly to mod
  end-to-end-tests/pageObjects/pageEditor/modListingPanel.ts
  end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-button-starter-brick-to-mod.yaml
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-context-menu-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-quick-bar-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-sidebar-panel-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-trigger-starter-brick-to-mod.diff
  end-to-end-tests/tests/pageEditor/starterBrickAdd.spec.ts
  src/components/ellipsisMenu/EllipsisMenu.tsx
  src/extensionConsole/pages/mods/ModsPageActions.tsx
  src/pageEditor/documentBuilder/preview/AddElementAction.tsx
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/modListingPanel/ActionMenu.module.scss
  src/pageEditor/modListingPanel/ActionMenu.tsx
  src/pageEditor/modListingPanel/AddStarterBrickButton.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/common.ts
  src/pageEditor/starterBricks/adapter.ts
Labels: enhancement, user experience, page editor

#8958 Experimental Deepgram streaming integration
  package-lock.json
  package.json
  scripts/__snapshots__/manifest.test.js.snap
  src/background/capture.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/bricks/effects/captureAudio.ts
  src/bricks/effects/getAllEffects.ts
  src/bricks/transformers/screenshotTab.ts
  src/contentScript/audio.ts
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contrib/deepgram/deepgramTypes.ts
  src/development/headers.test.ts
  src/integrations/integrationTypes.ts
  src/manifest.json
  src/platform/capabilities.ts
  src/platform/platformBase.ts
  src/platform/platformProtocol.ts
  src/platform/platformTypes/captureProtocol.ts
  src/telemetry/logging.ts
  src/testUtils/platformMock.ts
  src/tinyPages/offscreen.ts
  src/tinyPages/offscreenDocumentController.ts
  src/tinyPages/offscreenProtocol.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement

#8957 #8870: Add ModAddNewStarterBrick event
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/telemetry/events.ts
Labels: telemetry

#8955 DX - Remove unused `savingModComponentSlice` and clean up some naming
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/BrowserBanner.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/integrations/PrivateIntegrationsCard.tsx
  src/extensionConsole/pages/mods/modals/convertToModModal/ConvertToModModal.test.tsx
  src/extensionConsole/pages/mods/modals/modModalsSelectors.ts
  src/extensionConsole/store.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/pageEditor/store/savingModComponentSlice.ts
  src/pageEditor/store/store.ts
  src/pageEditor/testHelpers.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience
