Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-01, with the labels that each got.

#7237 Drop vestigial Firefox support
  pixiebrix-extension.iml
  src/__mocks__/@/background/messenger/api.ts
  src/background/background.ts
  src/background/eventUtils.ts
  src/background/firefoxCompat.ts
  src/background/messenger/api.ts
  src/background/messenger/external/api.ts
  src/background/messenger/registration.ts
  src/background/permissionPrompt.ts
  src/background/webextAlert.ts
  src/components/errors/NetworkErrorDetail.tsx
  src/contrib/zapier/PushOptions.tsx
  src/modDefinitions/modDefinitionPermissionsHelpers.ts
  src/pageEditor/editorPermissionsHelpers.ts
  src/permissions/extensionPermissionsHelpers.ts
  src/permissions/permissionsUtils.ts
  src/testUtils/permissionsMock.ts
  src/tinyPages/PermissionsPopupApp.tsx
  src/tinyPages/permissionsPopup.html
  src/tinyPages/permissionsPopup.tsx
  src/tsconfig.strictNullChecks.json
  webpack.config.mjs
Labels: firefox

#7257 Knip unused files
  .github/workflows/ci.yml
  knip.mjs
  src/components/fields/schemaFields/ButtonVariantSchemaField.tsx
  src/components/fields/schemaFields/CustomEventField.tsx
  src/extensionConsole/messenger/api.ts
  src/extensionConsole/messenger/registration.ts
  src/extensionConsole/options.tsx
  src/pageEditor/messenger/api.ts
  src/pageEditor/messenger/registration.ts
  src/registry/packageRegistry.ts
  src/testUtils/storePersistorMock.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#7258 Knip unused dependencies
  .github/workflows/ci.yml
  jest.config.js
  knip.mjs
  package-lock.json
  package.json
  src/testUtils/FixJsdomEnvironment.js
Labels: developer experience

#7261 Drop unused brick icon parameter
  src/bricks/effects/logger.ts
  src/bricks/effects/redirectPage.ts
  src/bricks/effects/sound.ts
  src/bricks/renderers/table.tsx
  src/bricks/transformers/GetBrickInterfaceTransformer.ts
  src/bricks/transformers/IdentityTransformer.ts
  src/bricks/transformers/ParseJson.ts
  src/bricks/transformers/RunBrickByIdTransformer.ts
  src/bricks/transformers/RunMetadataTransformer.ts
  src/bricks/transformers/brickFactory.ts
  src/bricks/transformers/convertDocument.ts
  src/bricks/transformers/encode.ts
  src/bricks/transformers/ephemeralForm/formTransformer.ts
  src/bricks/transformers/httpGet.ts
  src/bricks/transformers/jq.ts
  src/bricks/transformers/jsonPath.ts
  src/bricks/transformers/mapping.ts
  src/bricks/transformers/parseCsv.ts
  src/bricks/transformers/parseDate.ts
  src/bricks/transformers/parseUrl.ts
  src/bricks/transformers/prompt.ts
  src/bricks/transformers/randomNumber.ts
  src/bricks/transformers/readable.ts
  src/bricks/transformers/regex.ts
  src/bricks/transformers/searchText.ts
  src/bricks/transformers/splitText.ts
  src/bricks/transformers/template.ts
  src/bricks/transformers/traverseElements.ts
  src/bricks/transformers/url.ts
  src/contrib/google/sheets/bricks/append.ts
  src/contrib/pipedrive/create.ts
  src/integrations/UserDefinedIntegration.ts
  src/integrations/integrationTypes.ts
  src/starterBricks/types.ts
  src/types/brickTypes.ts
  src/types/registryTypes.ts
Labels: developer experience

#7262 Drop brick run count telemetry experiment
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/telemetry.test.ts
  src/background/telemetry.ts
  src/runtime/pipelineTests/trace.test.ts
  src/runtime/reducePipeline.ts
Labels: developer experience

#7221 #7172: Merge `build` and `build-for-store` CI jobs; add per-manifest KEY
  .github/workflows/release.yaml
Labels: developer experience, mv3

#7267 #7057: Fix image sizing bug in builder
  src/components/documentBuilder/documentTree.tsx
Labels: bug

#7269 #7268: Fix editor sidebar logo sizing
  src/pageEditor/sidebar/HomeButton.module.scss
  src/pageEditor/sidebar/ReloadButton.tsx
  src/pageEditor/sidebar/Sidebar.module.scss
  src/pageEditor/sidebar/SidebarCollapsed.tsx
  src/pageEditor/sidebar/SidebarExpanded.tsx
Labels: bug, low priority

#7286 Drop `as jest.Mock`/`as jest.MockedFunction` assertions
  .eslintrc.js
  src/analysis/analysisVisitors/requestPermissionAnalysis.test.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/auth/RequireAuth.test.tsx
  src/auth/useRequiredPartnerAuth.test.tsx
  src/background/contentScript.test.ts
  src/background/deploymentUpdater.test.ts
  src/background/installer.test.ts
  src/background/makeConfiguredRequest.test.ts
  src/bricks/effects/AddQuickBarAction.test.ts
  src/bricks/effects/scrollToElement.test.ts
  src/bricks/registry.test.ts
  src/bricks/renderers/customForm.test.tsx
  src/bricks/transformers/selectElement.test.ts
  src/bricks/transformers/temporaryInfo/EphemeralPanel.test.tsx
  src/bricks/transformers/tourStep/tourStep.test.ts
  src/components/documentBuilder/documentTree.test.tsx
  src/components/form/useFieldAnnotations.test.tsx
  src/components/quickBar/QuickBarApp.test.tsx
  src/contentScript/loadActivationEnhancementsCore.test.ts
  src/contrib/google/sheets/core/useCurrentOrigin.test.ts
  src/contrib/google/sheets/core/useSpreadsheetId.test.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.test.tsx
  src/extensionConsole/pages/brickEditor/useSubmitBrick.test.tsx
  src/extensionConsole/pages/deployments/DeploymentModal.test.tsx
  src/extensionConsole/pages/mods/Status.test.tsx
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModal.test.tsx
  src/extensionConsole/pages/mods/onboardingView/OnboardingView.test.tsx
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.test.ts
  src/modDefinitions/modDefinitionHooks.test.ts
  src/modDefinitions/modDefinitionsSlice.test.ts
  src/pageEditor/EditorContent.test.tsx
  src/pageEditor/panes/NoTabAccessPane.test.tsx
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/panes/save/useSavingWizard.test.tsx
  src/pageEditor/tabs/editTab/dataPanel/tabs/PageStateTab.test.tsx
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.test.tsx
  src/sidebar/SidebarBody.test.tsx
  src/sidebar/Tabs.test.tsx
  src/starterBricks/menuItemExtension.test.ts
  src/store/checkActiveElementAvailability.test.ts
  src/store/checkAvailableDynamicElements.test.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/utils/extensionUtils.test.ts
Labels: infrastructure, low priority

#7304 #7297: Restore `externally_connectable` for the app
  .github/workflows/ci.yml
  scripts/__snapshots__/manifest.test.js.snap
  scripts/manifest.mjs
Labels: bug, infrastructure, developer experience

#7299 #7276 Fix mod copy functionality
  src/modDefinitions/modDefinitionsSlice.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/sidebar/modals/CreateRecipeModal.tsx
  src/pageEditor/slices/editorSlice.ts
Labels: bug, page editor

#7302 #7269: Fix pageEditor sidebar buttons style
  src/pageEditor/sidebar/Sidebar.module.scss
Labels: bug, regression, page editor

#7315 Add Jest reporter to GitHub Actions
  jest.config.js
Labels: infrastructure, low priority

#7316 #7294: Fix sidebar scrolling behavior
  src/sidebar/Tabs.tsx
  src/sidebar/__snapshots__/ConnectedSidebar.test.tsx.snap
Labels: bug, user experience

#7308 #7113 Fix Sheets append when there are empty columns in front of headers
  src/contrib/google/sheets/bricks/append.ts
  src/contrib/google/sheets/core/sheetsApi.ts
Labels: bug, gdrive

#7326 #7170 Add custom eslint rule noNullRtkQueryArgs
  .eslintrc.js
  eslint-local-rules/noNullRtkQueryArgs.js
  eslint-local-rules/noNullRtkQueryArgs.test.js
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
Labels: developer experience

#7358 Drop UiPath local robot brick
  eslint-local-rules/persistBackgroundData.txt
  knip.mjs
  package-lock.json
  package.json
  src/__mocks__/@uipath/robot.ts
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/uipath.ts
  src/contrib/editors.ts
  src/contrib/registerContribBlocks.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/LocalProcessOptions.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/contrib/uipath/UiPathRobot.ts
  src/contrib/uipath/__snapshots__/LocalProcessOptions.test.tsx.snap
  src/contrib/uipath/localProcess.ts
  src/contrib/uipath/quietLogger.ts
  src/development/headers.test.ts
  src/tsconfig.strictNullChecks.json
  tsconfig.json
  webpack.config.mjs
Labels: developer experience, brick

#7352 Include details in mod error notifications
  src/modDefinitions/modDefinitionHooks.ts
  src/starterBricks/contextMenu.ts
  src/starterBricks/menuItemExtension.ts
  src/starterBricks/panelExtension.ts
  src/starterBricks/quickBarExtension.tsx
  src/starterBricks/quickBarProviderExtension.tsx
Labels: user experience, low priority

#7305 #7300: Enable contextMenus on `srcdoc` iframes
  package-lock.json
  package.json
  src/bricks/available.test.ts
  src/bricks/available.ts
  src/contentScript/contextMenus.ts
Labels: bug, low priority

#7373 Page Editor: Improve shadow and fix sizing of tabs
  src/components/tabLayout/EditorTabLayout.module.scss
  src/pageEditor/ElementWizard.module.scss
  src/pageEditor/sidebar/HomeButton.module.scss
  src/pageEditor/sidebar/Sidebar.module.scss
Labels: user experience, low priority, page editor

#7391 #7378: Fix page editor detection
  src/__mocks__/@/utils/expectContext.ts
  src/background/executor.ts
  src/contrib/google/sheets/core/useCurrentOrigin.test.ts
  src/contrib/google/sheets/core/useCurrentOrigin.ts
  src/contrib/uipath/LocalProcessOptions.tsx
  src/pageEditor/hooks/useCurrentUrl.ts
  src/pageEditor/utils.ts
  src/telemetry/BackgroundLogger.ts
  src/testUtils/detectPageMock.ts
  src/utils/expectContext.ts
Labels: bug

#7378 #7377: fix local UiPath process configuration and page editor detection
  src/__mocks__/@/utils/expectContext.ts
  src/background/executor.ts
  src/contrib/editors.ts
  src/contrib/google/sheets/core/useCurrentOrigin.test.ts
  src/contrib/google/sheets/core/useCurrentOrigin.ts
  src/contrib/registerContribBlocks.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/LocalProcessOptions.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/contrib/uipath/localProcess.ts
  src/contrib/uipath/uipathHooks.ts
  src/pageEditor/hooks/useCurrentUrl.ts
  src/pageEditor/utils.ts
  src/telemetry/BackgroundLogger.ts
  src/testUtils/detectPageMock.ts
  src/utils/expectContext.ts
Labels: bug, page editor

#7383 Reduce chance of piling up notifications after a reload
  src/bricks/effects/alert.ts
  src/errors/contextInvalidated.ts
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/utils/clipboardUtils.ts
  src/utils/notify.tsx
Labels: bug, low priority

#7384 #7237: Drop unused `webextAlert`
  knip.mjs
  package-lock.json
  package.json
  src/background/browserAction.ts
  src/background/webextAlert.ts
  src/tinyPages/alert.html
  src/tinyPages/alert.scss
  src/tinyPages/alert.ts
  src/tsconfig.strictNullChecks.json
  webpack.config.mjs
Labels: firefox

#7379 #7355 Fix bug with copying mod with optional integrations
  src/activation/useActivateRecipeWizard.ts
  src/background/modUpdater.ts
  src/extensionConsole/pages/mods/utils/useReinstall.ts
  src/integrations/util/collectExistingConfiguredDependenciesForMod.test.ts
  src/integrations/util/collectExistingConfiguredDependenciesForMod.ts
  src/pageEditor/sidebar/modals/CreateModModal.tsx
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx
  src/store/extensionsUtils.test.ts
  src/store/extensionsUtils.ts
Labels: bug

#7382 Incremental strict null checks adoption: Slice 15
  knip.mjs
  src/activation/activateLinkClickHandler.ts
  src/components/AsyncStateGate.tsx
  src/components/documentBuilder/render/DocumentContext.tsx
  src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
  src/permissions/permissionsUtils.ts
  src/sidebar/messenger/registration.ts
  src/starterBricks/contextMenuReader.ts
  src/tsconfig.strictNullChecks.json
  src/types/typeOnlyMessengerRegistration.ts
  src/utils/inference/inferSingleElementSelector.ts
  src/utils/inference/selectorInference.ts
Labels: developer experience

#7381 Avoid some counter-productive lazy loaded files
  eslint-local-rules/persistBackgroundData.txt
  src/__mocks__/@/components/MarkdownInlineLazy.tsx
  src/__mocks__/@/components/MarkdownLazy.tsx
  src/bricks/renderers/MarkdownRenderer.ts
  src/bricks/transformers/selectElement.ts
  src/components/MarkdownInlineLazy.tsx
  src/components/MarkdownLazy.tsx
  src/components/formBuilder/DescriptionField.tsx
  src/components/formBuilder/DescriptionFieldTemplate.tsx
  src/components/schemaTree/SchemaTree.tsx
  src/tsconfig.strictNullChecks.json
Labels: performance, low priority

#7406 Replace noisy `remove-files-webpack-plugin`
  package-lock.json
  package.json
  scripts/DiscardFilePlugin.mjs
  webpack.config.mjs
Labels: developer experience

#7413 Incremental strict null checks adoption: Slice 16
  src/bricks/transformers/ephemeralForm/formTransformer.ts
  src/components/addBlockModal/addBlockModalHelpers.ts
  src/components/imagePlaceholder/ImagePlaceholder.tsx
  src/contentScript/ephemeralFormProtocol.ts
  src/extensionConsole/pages/activateMod/UrlPermissionsList.tsx
  src/pageEditor/sidebar/ActionMenu.tsx
  src/pageScript/frameworks/component.ts
  src/testUtils/testHelpers.tsx
  src/tsconfig.strictNullChecks.json
  src/types/reactTableConfig.d.ts
Labels: developer experience, low priority

#7412 Add allSettled helper
  .eslintrc.js
  eslint-local-rules/noRestrictedSyntax.ts
  src/analysis/analysisVisitors/requestPermissionAnalysis.ts
  src/background/contextMenus.ts
  src/background/deploymentUpdater.ts
  src/background/executor.ts
  src/bricks/registry.ts
  src/components/quickBar/quickBarRegistry.ts
  src/contentScript/lifecycle.ts
  src/contentScript/sidebarActivation.ts
  src/extensionConsole/pages/settings/FactoryResetSettings.tsx
  src/runtime/reducePipeline.ts
  src/starterBricks/contextMenu.ts
  src/starterBricks/quickBarExtension.tsx
  src/starterBricks/quickBarProviderExtension.tsx
  src/starterBricks/triggerExtension.ts
  src/utils/extensionUtils.ts
  src/utils/promiseUtils.test.ts
  src/utils/promiseUtils.ts
Labels: developer experience

#7421 Avoid errors in `loggingConfig` getter
  src/__mocks__/@/telemetry/logging.ts
  src/hooks/logging.ts
  src/runtime/reducePipeline.ts
  src/telemetry/logging.ts
Labels: bug, low priority

#7424 Update eqeqeq eslint rule
  src/bricks/transformers/mapping.ts
  src/components/fields/fieldUtils.ts
  src/components/fields/schemaFields/widgets/TextWidget.tsx
  src/components/fields/schemaFields/widgets/varPopup/likelyVariableUtils.ts
  src/contentScript/lifecycle.ts
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/hooks/useInterval.ts
  src/hooks/useTheme.ts
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/usePipelineNodes.tsx
  src/permissions/permissionsTypes.ts
  src/utils/typeUtils.ts
Labels: developer experience

#7425 Make worker more resilient to DOM API usage attempts
  src/bricks/transformers/selectElement.ts
  static/background.worker.js
Labels: developer experience, mv3

#7419 Close sidebar on context invalidated in MV2 (matches MV3 behavior)
  package-lock.json
  package.json
  src/__mocks__/@/hooks/useContextInvalidated.ts
  src/background/sidePanel.ts
  src/contentScript/contentScript.ts
  src/contentScript/contentScriptCore.ts
  src/contentScript/lifecycle.ts
  src/contentScript/sidebarActivation.ts
  src/contentScript/sidebarController.tsx
  src/errors/contextInvalidated.ts
  src/hooks/useContextInvalidated.ts
  src/pageEditor/tabState/tabStateSlice.ts
  src/sidebar/ErrorBanner.tsx
  src/sidebar/Header.tsx
  src/sidebar/SidebarBody.test.tsx
  src/sidebar/SidebarBody.tsx
  src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
  src/telemetry/BackgroundLogger.ts
  src/tinyPages/RestrictedUrlPopupApp.tsx
  src/tsconfig.strictNullChecks.json
Labels: user experience, sidebar

#7431 #7430: Avoid RECORD_ERROR loops
  src/development/errorsBadge.ts
  src/errors/errorHelpers.ts
Labels: bug

#7429 Restore ability to toggle sidebar via `action` click in MV3
  src/background/browserAction.ts
Labels: enhancement, mv3, sidebar

#7436 Allow exclusion from knip via `@knip` JSDoc tag
  .github/workflows/ci.yml
  knip.mjs
  package.json
  src/__mocks__/@/hooks/useContextInvalidated.ts
  src/hooks/useContextInvalidated.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#7374 #7300: Add support for sandboxed iframes (MV2 only)
  package-lock.json
  package.json
  webpack.config.mjs
Labels: bug, customer

#7426 #7265: Move Nunjucks template validation to sandbox
  src/analysis/analysisVisitors/requestPermissionAnalysis.ts
  src/analysis/analysisVisitors/templateAnalysis.test.ts
  src/analysis/analysisVisitors/templateAnalysis.ts
  src/contentScript/sidebarController.tsx
  src/sandbox/messenger/api.ts
  src/sandbox/messenger/executor.ts
  src/sandbox/messenger/registration.ts
  src/starterBricks/contextMenu.ts
  src/starterBricks/menuItemExtension.ts
  src/starterBricks/sidebarExtension.ts
  src/utils/postMessage.ts
Labels: page editor, mv3

#7441 #4663: Extension console marketplace text minor fix
  src/__snapshots__/Storyshots.test.js.snap
  src/extensionConsole/pages/mods/onboardingView/OnboardingView.tsx
Labels: papercut

#7445 #7442: Restore space in page editor ActionMenu
  src/pageEditor/sidebar/ActionMenu.tsx
Labels: regression

#7444 Clarify MV3 zombie worker error
  static/background.worker.js
Labels: developer experience, mv3

#7469 #7467: Add support for sidebar forms brick in MV3
  src/bricks/transformers/ephemeralForm/formTransformer.ts
  src/sidebar/sidebar.tsx
Labels: bug, mv3, sidebar

#7446 #4258: Remove quickbar after invalidation
  src/components/quickBar/QuickBarApp.tsx
  src/development/visualInjection.ts
  src/domConstants.ts
  src/hooks/useContextInvalidated.ts
  src/starterBricks/quickBarExtension.test.ts
  src/starterBricks/quickbarProviderExtension.test.ts
  src/utils/notify.tsx
Labels: bug, quickbar

#7466 #4258: Remove contextmenu right-click listener after invalidation
  src/starterBricks/contextMenu.ts
Labels: bug

#7472 #7300: Add support for sandboxed iframes (MV3 too)
  package-lock.json
  package.json
  scripts/__snapshots__/manifest.test.js.snap
  scripts/manifest.mjs
  static/background.worker.js
  static/grayIconWhileLoading.js
  webpack.config.mjs
Labels: bug, customer, mv3

#7473 #7353: Avoid duplicate error notifications on screen
  jest.config.js
  package-lock.json
  package.json
  src/starterBricks/contextMenu.ts
Labels: user experience
