Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-02, with the labels that each got.

#7490 #7476: Open sidebar from iframe
  src/background/sidePanel.ts
  src/bricks/effects/sidebar.ts
  src/contentScript/sidebarController.tsx
  src/sidebar/protocol.tsx
  src/types/strictMessengerApi.ts
  src/types/typeOnlyMessengerRegistration.ts
  src/utils/sidePanelUtils.ts
Labels: sidebar

#7488 Drop self-referencing extension console link in sidePanel
  src/tinyPages/RestrictedUrlPopupApp.tsx
Labels: bug, mv3, sidebar

#7470 #618: Drop secondary dev-only reload for `web-ext run`
  eslint-local-rules/persistBackgroundData.txt
  src/background/background.ts
  src/development/autoreload.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#7489 Make Extension Console "Get Started" view consistent with other views
  src/__snapshots__/Storyshots.test.js.snap
  src/extensionConsole/pages/mods/GetStartedView.module.scss
  src/extensionConsole/pages/mods/GetStartedView.tsx
  src/extensionConsole/pages/mods/__snapshots__/ModsPageLayout.test.tsx.snap
Labels: low priority, design system, papercut

#7443 Avoid Bootstrap columns unless there are columns
  .eslintrc.js
  src/__snapshots__/Storyshots.test.js.snap
  src/components/documentBuilder/edit/ElementEditor.tsx
  src/components/documentBuilder/edit/PipelineOptions.tsx
  src/components/formBuilder/edit/FormEditor.tsx
  src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
  src/components/logViewer/details/OutputDetail.tsx
  src/extensionConsole/pages/activateExtension/ActivateExtensionCard.tsx
  src/extensionConsole/pages/activateExtension/ActivateExtensionPage.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.module.scss
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/activateMod/ActivateModPage.tsx
  src/extensionConsole/pages/activateMod/UrlPermissionsList.tsx
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateModCard.test.tsx.snap
  src/extensionConsole/pages/brickEditor/CreatePage.tsx
  src/extensionConsole/pages/brickEditor/EditPage.tsx
  src/extensionConsole/pages/integrations/IntegrationsPage.tsx
  src/extensionConsole/pages/mods/GetStartedView.module.scss
  src/extensionConsole/pages/mods/GetStartedView.tsx
  src/extensionConsole/pages/mods/__snapshots__/ModsPageLayout.test.tsx.snap
  src/extensionConsole/pages/onboarding/SetupPage.tsx
  src/pageEditor/NonScriptablePage.tsx
  src/pageEditor/components/DimensionGate.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/editTab/AnalysisResult.tsx
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.module.scss
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.tsx
  src/pageEditor/tabs/modOptionsValues/__snapshots__/ModOptionsValuesEditor.test.tsx.snap
  src/sidebar/DefaultPanel.tsx
  src/sidebar/LoginPanel.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/__snapshots__/ConnectedSidebar.test.tsx.snap
  src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
  src/sidebar/modLauncher/ActiveSidebarModsList.tsx
  src/sidebar/modLauncher/ModLauncher.tsx
Labels: user experience, developer experience, low priority

#7471 #7327: Add modal UI to capture focus
  src/__mocks__/@/contentScript/focusCaptureDialog.ts
  src/background/messenger/api.ts
  src/bricks/effects/sidebar.ts
  src/contentScript/contentScript.scss
  src/contentScript/focusCaptureDialog.ts
  src/contentScript/sidebarController.tsx
  src/tsconfig.strictNullChecks.json
  src/utils/clipboardUtils.ts
Labels: bug, user experience, mv3, sidebar

#7502 Update swagger
  src/auth/authUtils.ts
  src/background/deploymentUpdater.test.ts
  src/extensionConsole/pages/brickEditor/BrickHistory.test.tsx
  src/pageEditor/panes/EditorPane.test.tsx
  src/services/errorService.ts
  src/testUtils/factories/databaseFactories.ts
  src/testUtils/factories/marketplaceFactories.ts
  src/types/swagger.ts
Labels: infrastructure

#7505 Create spec slice template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/specification.md
Labels: developer experience

#7551 Restore content script due to duplicate Messenger registration
  src/contentScript/messenger/registration.ts
Labels: release blocker

#7544 Remind contributors to add new files to `strictNullChecks`
  .github/workflows/pr.yml
Labels: developer experience

#7487 Remove redundant/unnecessary brick refresh on extension console (speeds up by several seconds)
  src/extensionConsole/App.tsx
Labels: performance

#7464 Improve responsiveness of forms and field labels
  src/__snapshots__/Storyshots.test.js.snap
  src/bricks/transformers/tourStep/__snapshots__/TourStepOptions.test.tsx.snap
  src/components/fields/schemaFields/widgets/__snapshots__/ArrayWidget.test.tsx.snap
  src/components/fields/schemaFields/widgets/__snapshots__/FixedInnerObjectWidget.test.tsx.snap
  src/components/fields/schemaFields/widgets/__snapshots__/ObjectWidget.test.tsx.snap
  src/components/form/FieldTemplate.module.scss
  src/components/form/FieldTemplate.test.tsx
  src/components/form/FieldTemplate.tsx
  src/components/form/Form.stories.tsx
  src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
  src/contrib/automationanywhere/__snapshots__/BotOptions.test.tsx.snap
  src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateModCard.test.tsx.snap
  src/extensionConsole/pages/activateMod/__snapshots__/OptionsBody.test.tsx.snap
  src/extensionConsole/pages/mods/modals/convertToRecipeModal/__snapshots__/ConvertToRecipeModal.test.tsx.snap
  src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap
  src/mv3/api.ts
  src/pageEditor/components/__snapshots__/UrlPatternWidget.test.tsx.snap
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/ExtraPermissionsSection.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/DataPanel.test.tsx.snap
  src/pageEditor/tabs/editTab/dataPanel/__snapshots__/FoundationDataPanel.test.tsx.snap
  src/pageEditor/tabs/effect/__snapshots__/BrickConfiguration.test.tsx.snap
  src/pageEditor/tabs/modOptionsValues/__snapshots__/ModOptionsValuesEditor.test.tsx.snap
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
  src/sidebar/activateMod/__snapshots__/ActivateModPanel.test.tsx.snap
Labels: user experience, page editor, mv3, sidebar

#7557 Warn of DOM changes in background page
  src/background/background.ts
  src/background/backgroundDomWatcher.ts
  src/tsconfig.strictNullChecks.json
Labels: bug, developer experience, mv3

#7559 Extend "This target is not in a frame" error
  package-lock.json
  package.json
Labels: developer experience

#7563 #7019: Fix "Selecting one of multiple forms in a Render Document selects all of them"
  src/components/documentBuilder/createNewElement.test.ts
  src/components/documentBuilder/createNewElement.ts
Labels: bug, page editor

#7593 Hand-roll faster and safer version of `import/no-restricted-paths`
  .eslintrc.js
  eslint-local-rules/noCrossBoundaryImports.js
  eslint-local-rules/noCrossBoundaryImports.test.js
  knip.mjs
  package-lock.json
  package.json
  src/extensionConsole/components/IDBErrorDisplay.tsx
  src/utils/notify.tsx
Labels: developer experience

#7594 #7100: Don't show error if context menu "contexts" isn't specified
  src/background/contextMenus.ts
Labels: bug, user experience

#7606 #4258: Remove extension points on context invalidated
  src/contentScript/lifecycle.ts
Labels: bug

#7562 #5796: Run Rainforest QA on `main` after each PR merge
  .github/workflows/rainforestqa.yml
Labels: developer experience

#7599 Page Editor: Unify context invalidation message
  src/components/InvalidatedContextGate.test.tsx
  src/components/InvalidatedContextGate.tsx
  src/pageEditor/ErrorBanner.tsx
  src/pageEditor/Panel.tsx
  src/pageEditor/panes/NoTabAccessPane.tsx
  src/pageEditor/tabState/tabStateSelectors.ts
  src/pageEditor/tabState/tabStateSlice.ts
  src/testUtils/permissionsMock.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience, page editor

#7600 #7233: Avoid flash of gray icon on MV3 worker restart
  scripts/__snapshots__/manifest.test.js.snap
  src/manifest.json
  static/background.worker.js
  static/backgroundCanary.js
Labels: mv3

#7615 #5551: Drop unused availability count code
  src/pageEditor/slices/editorSlice.ts
Labels: developer experience

#7608 #6648: Update iframes from page editor without full page reload
  package-lock.json
  package.json
  src/background/removeExtensionForEveryTab.ts
  src/contentScript/messenger/api.ts
  src/pageEditor/PanelContent.tsx
  src/pageEditor/hooks/useAddElement.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/protocol.ts
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/pageEditor/utils.ts
Labels: bug, page editor

#7626 #7617: Fix sidebar header aligment
  src/sidebar/Header.tsx
  src/sidebar/__snapshots__/Header.test.tsx.snap
  src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
Labels: bug, user experience, regression

#7633 #7631: fix iframed modal form regression
  jest.config.js
  src/__mocks__/webext-messenger.js
  src/bricks/transformers/ephemeralForm/formTransformer.test.ts
  src/bricks/transformers/ephemeralForm/formTransformer.ts
  src/contentScript/ephemeralFormProtocol.ts
Labels: bug

#7638 #7613: refine registry null check
  src/registry/memoryRegistry.ts
  src/registry/packageRegistry.ts
Labels: developer experience, low priority

#7643 #7640: Reduce form label size
  src/components/form/FieldTemplate.module.scss
Labels: bug, user experience

#7639 Bump copyright year in footer
  src/background/backgroundDomWatcher.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/background/restrictUnauthenticatedUrlAccess.test.ts
  src/background/restrictUnauthenticatedUrlAccess.ts
  src/components/documentBuilder/edit/DocumentOptions.test.tsx
  src/components/documentBuilder/edit/DocumentOptions.tsx
  src/contentScript/messenger/strict/api.ts
  src/contentScript/messenger/strict/registration.ts
  src/extensionConsole/App.tsx
  src/layout/Footer.tsx
Labels: papercut

#7645 #7632: Fix slow browser action icon
  src/background/background.ts
Labels: bug

#7644 #7630: Fix DraftJS support on empty fields
  src/bricks/effects/forms.ts
  src/tsconfig.strictNullChecks.json
  src/utils/domFieldUtils.test.ts
  src/utils/domFieldUtils.ts
Labels: bug

#7648 #6681: support running the page editor outside the dev tools
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/bricks/transformers/jquery/JQueryReaderOptions.tsx
  src/components/fields/schemaFields/widgets/UrlMatchPatternWidget.tsx
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.tsx
  src/contrib/uipath/LocalProcessOptions.tsx
  src/pageEditor/EditorContent.test.tsx
  src/pageEditor/EditorContent.tsx
  src/pageEditor/EditorLayout.tsx
  src/pageEditor/Panel.tsx
  src/pageEditor/PanelContent.tsx
  src/pageEditor/analysisManager.ts
  src/pageEditor/context/TabInspectionGate.tsx
  src/pageEditor/context/connection.ts
  src/pageEditor/fields/SelectorSelectorWidget.tsx
  src/pageEditor/hooks/useAddElement.ts
  src/pageEditor/hooks/useCurrentInspectedUrl.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/panes/HomePane.tsx
  src/pageEditor/panes/NoTabAccessPane.test.tsx
  src/pageEditor/panes/NoTabAccessPane.tsx
  src/pageEditor/panes/insert/InsertPane.tsx
  src/pageEditor/panes/insert/useAutoInsert.ts
  src/pageEditor/protocol.ts
  src/pageEditor/sidebar/ActivatedModComponentListItem.tsx
  src/pageEditor/sidebar/AddStarterBrickButton.tsx
  src/pageEditor/sidebar/DynamicModComponentListItem.tsx
  src/pageEditor/sidebar/ReloadButton.tsx
  src/pageEditor/slices/editorSlice.ts
  src/pageEditor/tabState/tabStateSlice.ts
  src/pageEditor/tabs/editTab/dataPanel/tabs/PageStateTab.tsx
  src/pageEditor/tabs/effect/BrickPreview.tsx
  src/pageEditor/tabs/effect/ExtensionPointPreview.tsx
  src/pageEditor/tabs/effect/useDocumentPreviewRunBlock.ts
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/pageEditor/utils.ts
  src/store/checkActiveElementAvailability.test.ts
  src/store/checkAvailableDynamicElements.test.ts
  src/store/checkAvailableInstalledExtensions.test.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience, testing

#7666 #7665: add a text selection popover behind skunkworks flag
  src/__snapshots__/Storyshots.test.js.snap
  src/bricks/transformers/temporaryInfo/popoverUtils.ts
  src/contentScript/selectionTooltip/ActionRegistry.test.ts
  src/contentScript/selectionTooltip/ActionRegistry.ts
  src/contentScript/selectionTooltip/SelectionToolbar.scss
  src/contentScript/selectionTooltip/SelectionToolbar.stories.tsx
  src/contentScript/selectionTooltip/SelectionToolbar.tsx
  src/contentScript/selectionTooltip/tooltipController.test.ts
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/contentScript/selectionTooltip/useActionRegistry.ts
  src/contentScript/tooltipDom.ts
  src/extensionConsole/pages/settings/ExperimentalSettings.tsx
  src/hooks/useDocumentSelection.ts
  src/starterBricks/contextMenu.ts
  src/store/settings/settingsTypes.ts
  src/testUtils/factories/domFactories.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement

#7637 Remove remaining usages of `useQueryState`
  src/__snapshots__/Storyshots.test.js.snap
  src/auth/RequireAuth.test.tsx
  src/auth/RequireAuth.tsx
  src/auth/token.ts
  src/auth/useRequiredPartnerAuth.test.tsx
  src/auth/useRequiredPartnerAuth.ts
  src/components/BrickIcon.tsx
  src/components/MarketplaceListingIcon.tsx
  src/components/addBlockModal/__snapshots__/AddBlockModal.test.tsx.snap
  src/extensionConsole/Sidebar.tsx
  src/extensionConsole/pages/brickEditor/referenceTab/__snapshots__/BrickDetail.test.tsx.snap
  src/extensionConsole/pages/mods/ModsPageLayout.test.tsx
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishRecipeModals.tsx
  src/extensionConsole/pages/onboarding/SetupPage.test.tsx
  src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx
  src/hooks/useTheme.test.ts
  src/hooks/useTheme.ts
  src/mods/ModIcon.tsx
  src/pageEditor/panes/EditorPane.test.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/services/api.ts
  src/sidebar/ConnectedSidebar.test.tsx
  src/sidebar/Header.test.tsx
  src/sidebar/modLauncher/ActiveSidebarModsListItem.tsx
  src/testUtils/factories/authFactories.ts
  src/testUtils/rtkQueryFactories.ts
  src/testUtils/userMock.ts
  src/utils/modUtils.ts
Labels: developer experience

#7675 #4258: Remove trigger listeners after invalidation
  eslint-local-rules/persistBackgroundData.js
  package-lock.json
  package.json
  src/analysis/ReduxAnalysisManager.ts
  src/auth/token.ts
  src/components/quickBar/quickBarRegistry.ts
  src/starterBricks/menuItemExtension.ts
  src/starterBricks/panelExtension.ts
  src/starterBricks/sidebarExtension.ts
  src/starterBricks/triggerExtension.ts
  src/store/enterprise/managedStorage.ts
  src/utils/SimpleEventTarget.ts
Labels: bug, developer experience

#7669 #7668: add experimental insert text at cursor brick
  jest.config.js
  package-lock.json
  package.json
  src/bricks/effects/InsertAtCursorEffect.test.ts
  src/bricks/effects/InsertAtCursorEffect.ts
  src/bricks/effects/getAllEffects.ts
  src/components/quickBar/QuickBarApp.tsx
  src/development/headers.test.ts
  src/tsconfig.strictNullChecks.json
  src/types/inputTypes.ts
  src/types/runtimeTypes.ts
  src/utils/focusController.ts
  src/utils/selectionController.ts
  src/validators/generic.ts
Labels: enhancement, brick

#7686 #6904: Stop propagation of certain events in QuickBar
  package-lock.json
  package.json
  src/components/StopPropagation.test.tsx
  src/components/StopPropagation.tsx
  src/components/quickBar/QuickBarApp.tsx
  src/tsconfig.strictNullChecks.json
Labels: bug

#7697 #7682: skip flaky tests for skunkworks features to improve CI health
  src/contentScript/commandPopover/commandController.test.tsx
  src/contentScript/selectionTooltip/tooltipController.test.ts
Labels: developer experience

#7696 #7693: add background platform for http requests to fix Google API calls
  src/background/background.ts
  src/background/backgroundPlatform.ts
  src/contrib/google/sheets/core/sheetsApi.test.ts
Labels: bug, regression

#7699 #7695: QuickBar: Avoid dark scrollbar on dark websites
  src/components/quickBar/QuickBarApp.tsx
Labels: bug, quickbar

#7679 #7679: Refactor and centralize theme logic
  src/background/background.ts
  src/background/initTheme.ts
  src/background/setToolbarIconFromTheme.test.ts
  src/background/setToolbarIconFromTheme.ts
  src/components/addBlockModal/AddBlockModal.tsx
  src/extensionConsole/App.tsx
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/hooks/useIsEnterpriseUser.ts
  src/hooks/useTheme.test.ts
  src/hooks/useTheme.ts
  src/pageEditor/PanelContent.test.tsx
  src/sidebar/Header.test.tsx
  src/sidebar/Header.tsx
  src/sidebar/SidebarBody.test.tsx
  src/store/settings/settingsSlice.ts
  src/testUtils/appApiMock.ts
  src/testUtils/userMock.ts
  src/themes/themeStore.test.ts
  src/themes/themeStore.ts
  src/themes/themeUtils.ts
  src/tsconfig.strictNullChecks.json
  src/types/helpers.ts
Labels: developer experience

#7708 #7707: text selection popover placement fixes/UI improvements
  src/contentScript/selectionTooltip/SelectionToolbar.scss
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/types/inputTypes.ts
  src/utils/textAreaUtils.ts
Labels: bug, user experience

#7727 Fix EditorNodeConfigPanel label alignment
  src/components/fields/schemaFields/genericOptionsFactory.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.module.scss
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
Labels: bug, page editor

#7728 Text Command Popover Fixes/UI Improvements
  src/bricks/effects/InsertAtCursorEffect.ts
  src/contentScript/commandPopover/CommandPopover.scss
  src/contentScript/commandPopover/CommandPopover.stories.tsx
  src/contentScript/commandPopover/CommandPopover.tsx
  src/contentScript/commandPopover/commandController.tsx
  src/contentScript/commandPopover/commandPopoverSlice.ts
  src/contentScript/commandPopover/commandUtils.ts
  src/contentScript/commandPopover/useKeyboardQuery.ts
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/contentScript/textEditorDom.ts
  src/contentScript/tooltipDom.ts
  src/contrib/ckeditor.ts
  src/contrib/ckeditor/ckeditor.test.ts
  src/contrib/ckeditor/ckeditorDom.ts
  src/contrib/ckeditor/ckeditorProtocol.ts
  src/pageScript/messenger/api.ts
  src/pageScript/messenger/constants.ts
  src/pageScript/pageScript.ts
  src/tsconfig.strictNullChecks.json
  src/utils/domFieldUtils.ts
  src/utils/editorUtils.ts
Labels: bug, user experience

#7731 #7566: Don't load content script in tab-less frames
  src/background/contentScript.ts
  src/contentScript/contentScript.ts
Labels: bug

#7664 Add dev-only Reload button to sidebar + immediate page reload
  src/contentScript/messenger/strict/api.ts
  src/contentScript/messenger/strict/registration.ts
  src/contentScript/sidebarController.tsx
  src/pageEditor/sidebar/ReloadButton.tsx
  src/pageEditor/sidebar/Sidebar.module.scss
  src/sidebar/Header.tsx
  src/sidebar/SidebarErrorBoundary.tsx
Labels: developer experience, performance, sidebar

#7702 #7680: Add `platform` to `noCrossBoundaryImports` lint rule
  .eslintrc.js
Labels: infrastructure, low priority

#7598 Enable hot-module reload (the React app updates without reloading)
  package-lock.json
  package.json
  scripts/__snapshots__/manifest.test.js.snap
  scripts/manifest.mjs
  scripts/manifest.test.js
  webpack.config.mjs
  webpack.sharedConfig.js
Labels: developer experience

#7737 Introducing playwright for e2e tests
  .github/workflows/ci.yml
  .gitignore
  end-to-end-tests/example.spec.ts
  env.d.ts
  jest.config.js
  package-lock.json
  package.json
  playwright.config.ts
Labels: infrastructure, testing

#7742 Use `console.debug` instead of `console.trace` in trigger cancelObserver method
  src/starterBricks/triggerExtension.ts
Labels: developer experience

#7743 Throw an error on axios call from content script
  src/contentScript/contentScriptCore.ts
Labels: developer experience

#7746 Warn of wrong lockfile changes in PR
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/pr.yml
Labels: developer experience

#7748 Add CI instructions when strictNullChecks fails due to Messenger
  .github/workflows/pr.yml
Labels: developer experience

#7752 #7684: adds error details for multiple selectors and no selectors found errors
  src/components/errors/InvalidSelectorErrorDetail.tsx
  src/components/errors/__snapshots__/getErrorDetails.test.tsx.snap
  src/components/errors/getErrorDetails.test.tsx
  src/components/errors/getErrorDetails.tsx
  src/tsconfig.strictNullChecks.json
Labels: user experience

#7750 Avoid shrinking drawn pipeline with long output names
  src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.module.scss
Labels: papercut

#7751 strictNullChecks: ShadowRoot, navigateTab, quickBarApp, auto-add
  src/bricks/renderers/documentView/DocumentView.tsx
  src/bricks/transformers/ephemeralForm/EphemeralForm.tsx
  src/components/EmotionShadowRoot.ts
  src/components/floatingActions/FloatingActions.tsx
  src/components/quickBar/QuickBarApp.tsx
  src/components/selectionToolPopover/SelectionToolPopover.tsx
  src/contentScript/commandPopover/CommandPopover.tsx
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/messenger/strict/registration.ts
  src/contentScript/pageEditor.ts
  src/contentScript/selectionTooltip/SelectionToolbar.tsx
  src/pageEditor/panes/HomePane.tsx
  src/pageEditor/sidebar/AddStarterBrickButton.tsx
  src/sidebar/PanelBody.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#7749 Add spacing below form builder fields
  src/__snapshots__/Storyshots.test.js.snap
  src/components/formBuilder/FieldTemplate.tsx
  src/components/formBuilder/preview/__snapshots__/FormPreview.test.tsx.snap
Labels: papercut

#7755 Update local ESLint config to match shared config + apply new rules
  .eslintrc.js
  .pre-commit-config.yaml
  eslint-local-rules/noRestrictedSyntax.ts
  package-lock.json
  package.json
  src/bricks/readers/jquery.ts
  src/components/EmotionShadowRoot.ts
  src/components/StopPropagation.test.tsx
  src/components/quickBar/QuickBarResults.tsx
  src/contentScript/selectionTooltip/ActionRegistry.test.ts
  src/extensionConsole/pages/onboarding/SetupPage.test.tsx
  src/globals.d.ts
  src/types/reactDragAndDropNext.d.ts
  src/utils/inference/selectorInference.ts
  src/utils/nullishUtils.ts
  src/utils/stringUtils.ts
Labels: developer experience, low priority

#7754 #7735: adds very basic null checks to prevent NPE
  src/pageEditor/tabs/editTab/editorNodeConfigPanel/EditorNodeConfigPanel.tsx
Labels: bug

#7760 Add feature flag to remotely enable text selection popover
  src/background/deploymentUpdater.test.ts
  src/background/starterMods.test.ts
  src/extensionConsole/pages/settings/ExperimentalSettings.tsx
  src/starterBricks/contextMenu.ts
Labels: enhancement, customer

#7769 Drop experimental menu item dependencies feature
  src/starterBricks/menuItemExtension.ts
  src/types/runtimeTypes.ts
Labels: developer experience

#7771 Fix bug in `useAsyncState` -- memoize the `refetch` function properly
  src/hooks/useAsyncState.test.ts
  src/hooks/useIsMounted.ts
Labels: bug

#7765 #7675: Reuse `SimpleEventTarget` wherever possible
  src/bricks/hooks/useAllBricks.ts
  src/bricks/registry.ts
  src/components/fields/schemaFields/widgets/varPopup/VarMenu.module.scss
  src/components/fields/schemaFields/widgets/varPopup/useTreeRow.ts
  src/components/quickBar/quickBarRegistry.ts
  src/components/quickBar/quickbarTypes.ts
  src/components/quickBar/useActions.ts
  src/contentScript/lifecycle.ts
  src/hooks/useAsyncExternalStore.ts
  src/registry/memoryRegistry.ts
  src/utils/SimpleEventTarget.ts
  webpack.config.mjs
Labels: developer experience, low priority
