Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-04, with the labels that each got.

#8023 Fix integration baseURL and set up tests for the AA Run API Task brick
  package-lock.json
  package.json
  src/bricks/effects/highlightText.ts
  src/contrib/automationanywhere/RunApiTask.test.ts
  src/contrib/automationanywhere/aaTypes.ts
  src/integrations/UserDefinedIntegration.ts
  src/testUtils/appApiMock.ts
Labels: testing, release blocker, brick

#8083 #8076: add starter mod sidebar panels to closedtabs on install
  src/background/starterMods.test.ts
  src/background/starterMods.ts
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/Tabs.test.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/TemporaryPanelTabPane.tsx
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/sidebar/activateMod/ActivateModPanel.tsx
  src/sidebar/activateMod/ActivateMultipleModsPanel.tsx
  src/sidebar/modLauncher/ActiveSidebarModsListItem.tsx
  src/sidebar/modLauncher/ModLauncher.test.tsx
  src/sidebar/sidebarSelectors.ts
  src/sidebar/sidebarSlice.test.ts
  src/sidebar/store.ts
  src/sidebar/testHelpers.ts
  src/sidebar/useHideEmptySidebar.ts
  src/starterBricks/starterBrickModUtils.test.ts
  src/starterBricks/starterBrickModUtils.ts
  src/store/sidebar/constants.ts
  src/store/sidebar/eventKeyUtils.test.ts
  src/store/sidebar/eventKeyUtils.tsx
  src/store/sidebar/initialState.ts
  src/store/sidebar/sidebarSlice.ts
  src/store/sidebar/sidebarStorage.test.ts
  src/store/sidebar/sidebarStorage.ts
  src/store/sidebar/thunks/addFormPanel.ts
  src/store/sidebar/thunks/addTemporaryPanel.ts
  src/store/sidebar/thunks/removeTemporaryPanel.ts
  src/store/sidebar/thunks/resolveTemporaryPanel.ts
  src/store/sidebar/utils.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement, user experience

#8125 Animate page editor sidebar
  package-lock.json
  package.json
  src/pageEditor/sidebar/Extensions.module.scss
  src/pageEditor/sidebar/Extensions.tsx
  src/pageEditor/sidebar/ReloadButton.tsx
  src/pageEditor/sidebar/Sidebar.module.scss
  src/pageEditor/sidebar/Sidebar.tsx
  src/pageEditor/sidebar/SidebarCollapsed.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.tsx
Labels: user experience, low priority, page editor

#8100 Refactor rename extensionConsoleActivation test
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
Labels: testing

#8093 #8092: Automatically close user-gesture dialog for sidebar
  package-lock.json
  package.json
  src/background/sidePanel.ts
  src/contentScript/focusCaptureDialog.ts
  src/contentScript/sidebarController.tsx
  src/utils/postMessage.ts
  src/utils/promiseUtils.ts
Labels: bug, sidebar

#8133 #7255: Update content script readiness checks to drop mentions of "manual injection"
  jest.config.js
  package-lock.json
  package.json
  src/background/background.ts
  src/background/contentScript.test.ts
  src/background/contentScript.ts
  src/background/contextMenus.ts
  src/background/executor.ts
  src/background/initBrowserCommands.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/background/navigation.ts
  src/contentScript/contentScript.ts
  src/contentScript/contentScriptCore.ts
  src/contentScript/loadActivationEnhancementsCore.test.ts
  src/contentScript/loadActivationEnhancementsCore.ts
  src/contentScript/ready.ts
  src/pageEditor/tabState/tabStateSlice.ts
  src/starterBricks/triggerExtension.test.ts
  src/testUtils/extendedExpectations.ts
  src/testUtils/testAfterEnv.ts
  src/testUtils/testEnv.js
  src/tsconfig.strictNullChecks.json
Labels: runtime

#8130 #8065 Add browser version to event telemetry
  src/background/telemetry.test.ts
  src/background/telemetry.ts
  src/tsconfig.strictNullChecks.json
  src/vendors/mixpanelBrowser.ts
Labels: telemetry

#8097 More strict null checks work
  src/auth/authTypes.ts
  src/bricks/effects/wait.ts
  src/bricks/transformers/tourStep/tourStep.ts
  src/components/asyncIcon.ts
  src/contrib/google/sheets/core/handleGoogleRequestRejection.ts
  src/contrib/google/sheets/core/sheetsApi.ts
  src/extensionConsole/pages/mods/modals/modModalsSlice.ts
  src/hooks/useAsyncModOptionsValidationSchema.ts
  src/hooks/useMergeAsyncState.ts
  src/integrations/components/IntegrationAuthSelector.tsx
  src/integrations/integrationTypes.ts
  src/integrations/locator.ts
  src/integrations/store/integrationsSlice.ts
  src/integrations/util/permissionsHelpers.ts
  src/platform/panels/panelTypes.ts
  src/tsconfig.strictNullChecks.json
  src/types/sidebarTypes.ts
  src/types/sliceTypes.ts
Labels: developer experience

#8134 Drop redundant `param` descriptions (unless other parameters are described)
  src/activation/activationLinkUtils.ts
  src/background/executor.ts
  src/background/messenger/external/_implementation.ts
  src/components/fields/schemaFields/fieldTypeCheckers.ts
  src/components/fields/schemaFields/widgets/varPopup/getMenuOptions.ts
  src/components/fields/schemaFields/widgets/widgetUtils.ts
  src/components/quickBar/quickBarRegistry.ts
  src/contentScript/contextMenus.ts
  src/contentScript/elementReference.ts
  src/pageEditor/starterBricks/upgrade.ts
  src/platform/forms/formController.ts
  src/platform/panels/panelController.ts
  src/registry/memoryRegistry.ts
  src/runtime/extendModVariableContext.ts
  src/runtime/runtimeTypes.ts
  src/sidebar/activateMod/ActivateModPanel.tsx
  src/sidebar/activateMod/ActivateMultipleModsPanel.tsx
  src/starterBricks/starterBrickModUtils.ts
  src/starterBricks/tourExtension.ts
  src/telemetry/traceHelpers.ts
  src/types/brickTypes.ts
  src/utils/asyncStateUtils.ts
  src/utils/expressionUtils.ts
  src/utils/formUtils.ts
  src/utils/idbUtils.ts
  src/utils/modUtils.ts
  src/utils/objectUtils.ts
  src/utils/schemaUtils.ts
  src/utils/variableUtils.ts
Labels: developer experience, low priority

#8146 #8143: pass explicit base URL in validateBrickInputOutput to support srcdoc iframes
  end-to-end-tests/tests/runtime/srcdocFrames.spec.ts
  src/validators/schemaValidator.ts
Labels: bug, regression

#8153 #8152: change manifest name for beta builds
  scripts/__snapshots__/manifest.test.js.snap
  scripts/manifest.mjs
Labels: bug, infrastructure

#8149 #8086: fixed width icons in page editor mod sidebar
  src/pageEditor/sidebar/ExtensionIcons.tsx
  src/pageEditor/sidebar/__snapshots__/DynamicModComponentListItem.test.tsx.snap
Labels: papercut

#8148 #8147: add custom form submit reset affordance
  src/background/contentScript.test.ts
  src/bricks/renderers/CustomFormComponent.test.tsx
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/renderers/customForm.test.tsx
  src/bricks/renderers/customForm.ts
  src/components/formBuilder/edit/FieldEditor.tsx
  src/pageEditor/fields/FormRendererOptions.test.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/fields/PipelineToggleField.tsx
  src/testUtils/extendedExpectations.ts
  src/testUtils/factories/pageEditorFactories.ts
  src/testUtils/userEventHelpers.ts
  src/utils/objectUtils.test.ts
  src/utils/objectUtils.ts
Labels: enhancement, form builder

#8160 #8157: fix insert at cursor for draftjs editors
  end-to-end-tests/tests/runtime/insertAtCursor.spec.ts
  src/contentScript/textEditorDom.ts
  src/contrib/draftjs/draftJsDom.ts
  src/tsconfig.strictNullChecks.json
  src/utils/domFieldUtils.ts
Labels: bug

#8167 #8166: fix draftjs set value
  end-to-end-tests/tests/runtime/setInputValue.spec.ts
  src/contentScript/textEditorDom.ts
  src/contrib/draftjs/draftJsDom.ts
  src/utils/domFieldUtils.ts
Labels: bug

#8163 #8161: fix selector analysis false positives and improve warning text
  src/analysis/analysisVisitors/selectorAnalysis.test.ts
  src/analysis/analysisVisitors/selectorAnalysis.ts
  src/utils/detectRandomString.test.ts
  src/utils/detectRandomString.ts
Labels: bug

#8162 #8068: removing unnecessary css override for the button dropdown caret
  src/vendors/theme/assets/styles/components/_dropdowns.scss
Labels: user experience

#8156 #7475 Fix updating deployed mod id leaves both mods activated
  src/background/deploymentUpdater.test.ts
  src/background/deploymentUpdater.ts
  src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.test.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.ts
  src/utils/deploymentUtils.test.ts
  src/utils/deploymentUtils.ts
Labels: bug

#8164 #8131 Auto-deactivate unassigned mods on Mods Page
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.test.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.ts
  src/extensionConsole/pages/deployments/useDeactivateUnassignedDeploymentsEffect.ts
Labels: bug

#8175 Bump node to 20.12
  .nvmrc
  package.json
Labels: dependencies, developer experience

#8197 #4914: Fix extension console sidebar wrapping
  src/extensionConsole/pages/mods/ModsPageLayout.module.scss
  src/extensionConsole/pages/mods/ModsPageLayout.tsx
  src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  src/extensionConsole/pages/mods/__snapshots__/ModsPageLayout.test.tsx.snap
Labels: user experience, small

#8176 Minor code changes extracted from #8151
  .eslintrc.js
  src/components/InvalidatedContextGate.tsx
  src/components/jsonTree/treeHooks.tsx
  src/contentScript/messenger/registration.ts
  src/contentScript/pageEditor/elementPicker.test.ts
  src/contentScript/pageEditor/elementPicker.ts
  src/contentScript/pageEditor/selectElement.test.ts
  src/contentScript/pageEditor/selectElement.ts
Labels: low priority, small

#8106 #8015: Consolidate URL utils
  eslint-local-rules/persistBackgroundData.txt
  jest.config.js
  package-lock.json
  package.json
  src/activation/useActivateRecipe.ts
  src/analysis/analysisVisitors/requestPermissionAnalysis.ts
  src/background/requests.ts
  src/bricks/renderers/propertyTable.tsx
  src/components/documentBuilder/preview/elementsPreview/Image.tsx
  src/components/errors/NetworkErrorDetail.tsx
  src/data/model/OrganizationTheme.ts
  src/data/service/apiClient.ts
  src/data/service/errorService.ts
  src/data/service/requestErrorUtils.test.ts
  src/data/service/requestErrorUtils.ts
  src/errors/assertProtocolUrl.ts
  src/errors/errorHelpers.test.tsx
  src/errors/errorHelpers.ts
  src/errors/networkErrorHelpers.test.ts
  src/extensionConsole/pages/integrations/ConnectExtensionCard.tsx
  src/extensionConsole/pages/settings/AdvancedSettings.tsx
  src/integrations/UserDefinedIntegration.ts
  src/testUtils/appApiMock.ts
  src/tsconfig.strictNullChecks.json
  src/utils/enrichAxiosErrors.ts
  src/utils/urlUtils.test.ts
  src/utils/urlUtils.ts
Labels: bug

#8195 Share lint config
  .eslintrc.js
  package-lock.json
  package.json
  src/Storyshots.test.js
  src/testUtils/testEnv.js
Labels: infrastructure, low priority, small

#8201 skip auth setup when developing e2e tests locally
  .eslintrc.js
  end-to-end-tests/fixtures/extensionBase.ts
  playwright.config.ts
Labels: testing

#8208 GitHub action auto upload beta
  .github/workflows/beta-release.yaml
  .github/workflows/release.yaml
Labels: infrastructure

#8214 Improve e2e test docs and error handling
  end-to-end-tests/README.md
  end-to-end-tests/fixtures/extensionBase.ts
  package-lock.json
  package.json
  playwright.config.ts
Labels: testing

#8213 #7670: Ensure stylesheets are removed in `IsolatedComponent`
  src/components/IsolatedComponent.tsx
Labels: bug, regression

#8226 #8141: Ignore `updateDynamicElement` in iframes for `actionPanel`
  src/contentScript/pageEditor/dynamic.ts
Labels: bug, page editor

#8200 #7670: Use `<IsolatedComponent>` for `DocumentView`, `EphemeralFormContent`, `CustomFormComponent`
  scripts/DiscardFilePlugin.mjs
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/renderers/customForm.test.tsx
  src/bricks/renderers/customForm.tsx
  src/bricks/renderers/document.tsx
  src/bricks/renderers/documentView/DocumentView.tsx
  src/bricks/renderers/documentView/DocumentViewLazy.tsx
  src/bricks/renderers/documentView/DocumentViewProps.tsx
  src/bricks/transformers/ephemeralForm/EphemeralForm.tsx
  src/bricks/transformers/ephemeralForm/EphemeralFormContent.tsx
  src/components/EmotionShadowRoot.ts
  src/components/IsolatedComponent.tsx
  src/components/Stylesheets.tsx
  src/components/StylesheetsContext.ts
  src/components/isolatedComponentList.mjs
  src/sidebar/sidebarBootstrapOverrides.scss
  src/tsconfig.strictNullChecks.json
  webpack.config.mjs
Labels: infrastructure, developer experience

#8230 swap beta logo
  img/beta-logo.svg
Labels: bug, user experience

#8234 Sidebar and modal styling fixes
  src/components/IsolatedComponent.scss
  src/contentScript/modalDom.tsx
  src/store/optionsStore.ts
Labels: bug, user experience, regression

#8231 #8227: throw business error on showing temporary panel from frame
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.test.ts
  src/contentScript/ephemeralPanel.ts
Labels: bug, mv3

#8221 #8102 Add extension console activation e2e test for mod with built-in integration
  .idea/icon.svg
  end-to-end-tests/fixtures/extensionBase.ts
  end-to-end-tests/fixtures/responses/giphy-search.json
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
  end-to-end-tests/utils.ts
  src/components/quickBar/QuickBarApp.tsx
  src/types/stringTypes.ts
Labels: testing

#8207 #8138: Improve bot/task search-select widget UX
  public/mockServiceWorker.js
  src/components/fields/schemaFields/ChildObjectField.tsx
  src/components/form/widgets/AsyncRemoteSelectWidget.test.tsx
  src/components/form/widgets/AsyncRemoteSelectWidget.tsx
  src/contrib/automationanywhere/ApiTaskOptions.tsx
  src/contrib/automationanywhere/AwaitResultField.tsx
  src/contrib/automationanywhere/BotOptions.test.tsx
  src/contrib/automationanywhere/BotOptions.tsx
  src/contrib/automationanywhere/FolderIdConfigAlert.tsx
  src/contrib/automationanywhere/RemoteFileInputArguments.tsx
  src/contrib/automationanywhere/RemoteFileSelectField.test.tsx
  src/contrib/automationanywhere/RemoteFileSelectField.tsx
  src/contrib/automationanywhere/WorkspaceTypeField.tsx
  src/contrib/automationanywhere/aaUtils.ts
  src/contrib/automationanywhere/useWorkspaceTypeOptionsFactoryArgs.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
  src/tsconfig.strictNullChecks.json
Labels: user experience

#8280 #8279: cancel forms/panels brick
  src/analysis/analysisVisitors/brickTypeAnalysis.test.ts
  src/bricks/blockFilterHelpers.ts
  src/bricks/effects/CancelEffect.test.ts
  src/bricks/effects/CancelEffect.ts
  src/bricks/effects/CancelEphemeralElements.ts
  src/bricks/effects/getAllEffects.ts
  src/bricks/transformers/ephemeralForm/formTransformer.test.ts
  src/development/headers.test.ts
  src/platform/forms/formController.ts
  src/platform/panels/panelController.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement, brick, customer

#8278 #8277: add toggle sidebar brick
  end-to-end-tests/tests/bricks/sidebarEffects.spec.ts
  end-to-end-tests/tests/runtime/insertAtCursor.spec.ts
  end-to-end-tests/utils.ts
  src/bricks/effects/getAllEffects.ts
  src/bricks/effects/sidebarEffects.ts
  src/contentScript/messenger/strict/registration.ts
  src/contentScript/sidebarController.tsx
  src/development/headers.test.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement, brick, customer

#8271 Sidepanel open check failing in some browsers
  src/contentScript/sidebarController.tsx
Labels: bug, customer

#8275 #8273: Fix App crashing when chrome runtime is undefined
  src/mv3/api.ts
Labels: infrastructure

#8286 #8285: sort team filter names
  src/extensionConsole/pages/mods/ModsPageLayout.tsx
Labels: papercut

#8289 #8210: support PixieBrix API in starter mod
  src/background/starterMods.test.ts
  src/background/starterMods.ts
Labels: bug

#8290 #8222: support auto-create databases for starter mods
  src/activation/modOptionsHelpers.ts
  src/activation/useActivateModWizard.test.tsx
  src/activation/useActivateModWizard.ts
  src/activation/useActivateRecipe.test.ts
  src/activation/useActivateRecipe.ts
  src/background/starterMods.test.ts
  src/background/starterMods.ts
  src/components/fields/schemaFields/fieldTypeCheckers.ts
  src/store/sidebar/sidebarStorage.ts
Labels: enhancement

#8300 #8137 aa bricks two integrations bug
  src/auth/authTypes.ts
  src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx
  src/contentScript/pageEditor.ts
  src/contrib/automationanywhere/ApiTaskOptions.tsx
  src/contrib/automationanywhere/BotOptions.tsx
  src/contrib/uipath/LocalProcessOptions.tsx
  src/contrib/uipath/ProcessOptions.tsx
  src/contrib/uipath/uipathHooks.ts
  src/integrations/components/RequireIntegrationConfig.tsx
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.test.ts
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.ts
  src/utils/variableUtils.ts
Labels: bug

#8317 DX - Strict null checks 4/22
  src/background/auth/getToken.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/background/partnerIntegrations.ts
  src/background/refreshToken.ts
  src/background/requests.ts
  src/contentScript/contentScriptPlatform.test.ts
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/pageEditor/elementPicker.ts
  src/contentScript/partnerIntegrations.ts
  src/contrib/automationanywhere/RunBot.test.ts
  src/contrib/google/sheets/core/sheetsApi.test.ts
  src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
  src/extensionPages/extensionPagePlatform.ts
  src/tsconfig.strictNullChecks.json
  src/vendors/Overlay.tsx
Labels: developer experience

#8324 DX - Strict null checks 4/22 - part 3
  src/background/requests.ts
  src/background/restrictUnauthenticatedUrlAccess.ts
  src/bricks/effects/assignModVariable.ts
  src/bricks/effects/insertHtml.ts
  src/bricks/effects/pageState.ts
  src/bricks/effects/runSubTour.ts
  src/bricks/effects/scrollIntoView.ts
  src/bricks/transformers/RunMetadataTransformer.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/bricks/transformers/splitText.ts
  src/components/fields/schemaFields/widgets/varPopup/useTreeRow.ts
  src/components/walkthroughModal/WalkthroughModalApp.tsx
  src/extensionConsole/pages/brickEditor/BrickHistory.tsx
  src/extensionConsole/pages/mods/utils/exportBlueprint.ts
  src/pageEditor/fields/creatableAutosuggest/CreatableAutosuggest.tsx
  src/pageScript/elementInfo.ts
  src/platform/state/stateController.ts
  src/runtime/extendModVariableContext.ts
  src/runtime/pipelineTests/modVariableContext.test.ts
  src/sidebar/LoginPanel.tsx
  src/testUtils/factories/authFactories.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience

#8325 #8320: prevent IsolatedComponent and brick renderers from recreating components
  end-to-end-tests/tests/regressions/formFlicker.spec.ts
  src/bricks/renderers/customForm.tsx
  src/bricks/renderers/document.tsx
  src/bricks/renderers/propertyTable.tsx
  src/bricks/transformers/ephemeralForm/EphemeralForm.tsx
  src/components/IsolatedComponent.tsx
Labels: bug, regression

#8331 #8292: MV3 sidebar is less flaky about staying open during navigation
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/tests/runtime/sidebarNavigation.spec.ts
  end-to-end-tests/utils.ts
  playwright.config.ts
  src/contentScript/contentScriptCore.ts
  src/contentScript/lifecycle.ts
Labels: mv3

#8332 #8312 Fix e2e error logging test for MV2
  end-to-end-tests/tests/telemetry/errors.spec.ts
  src/tsconfig.strictNullChecks.json
Labels: testing

#8334 Validate that form autosaving works as correctly
  end-to-end-tests/tests/regressions/formFlicker.spec.ts
Labels: testing

#8321 Improve guideline documentation for business errors
  src/errors/businessErrors.ts
Labels: developer experience, low priority

#8299 #8228: run show sidebar in top-level frame
  end-to-end-tests/tests/runtime/sidebarController.spec.ts
  src/contentScript/messenger/strict/registration.ts
  src/contentScript/sidebarController.tsx
  src/utils/sidePanelUtils.ts
Labels: bug, runtime

#8346 #8343: handle 4 digit extension version numbers
  scripts/__snapshots__/manifest.test.js.snap
  scripts/manifest.mjs
  scripts/manifest.test.js
  src/background/backgroundPlatform.ts
  src/background/deploymentUpdater.test.ts
  src/background/deploymentUpdater.ts
  src/background/installer.ts
  src/background/messenger/external/api.ts
  src/background/restrictUnauthenticatedUrlAccess.test.ts
  src/background/telemetry.ts
  src/contentScript/contentScriptPlatform.ts
  src/data/service/errorService.ts
  src/extensionConsole/pages/UpdateBanner.tsx
  src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModalBody.tsx
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/extensionPages/extensionPagePlatform.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/sidebar/ModListItem.test.tsx
  src/pageEditor/sidebar/modals/CreateModModal.tsx
  src/pageEditor/starterBricks/base.ts
  src/platform/platformContext.ts
  src/registry/packageRegistry.test.ts
  src/runtime/pipelineTests/component.test.ts
  src/testUtils/factories/brickFactories.ts
  src/testUtils/factories/deploymentFactories.ts
  src/testUtils/factories/metadataFactory.ts
  src/testUtils/platformMock.ts
  src/testUtils/testAfterEnv.ts
  src/tsconfig.strictNullChecks.json
  src/types/helpers.test.ts
  src/types/helpers.ts
  src/utils/deploymentUtils.test.ts
  src/utils/deploymentUtils.ts
  src/utils/extensionUtils.ts
  src/utils/objToYaml.test.ts
Labels: bug, regression, mv3

#8340 More strict null checks work
  src/background/installer.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/background/telemetry.ts
  src/bricks/transformers/jquery/JQueryReaderOptions.test.tsx
  src/bricks/transformers/jquery/JQueryReaderOptions.tsx
  src/contentScript/messenger/api.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/messenger/strict/api.ts
  src/contentScript/messenger/strict/registration.ts
  src/contentScript/pageEditor/selectElement.ts
  src/extensionConsole/pages/UpdateBanner.tsx
  src/pageEditor/fields/SelectorSelectorWidget.tsx
  src/sidebar/activateMod/ActivateModPanel.tsx
  src/store/editorMigrations.ts
  src/store/extensionsMigrations.ts
  src/tsconfig.strictNullChecks.json
  src/utils/inference/inferSingleElementSelector.ts
  src/utils/inference/selectorInference.ts
Labels: developer experience

#8341 Add required env variables for e2e telemetry tests to README
  .env.example
  .github/workflows/ci.yml
  end-to-end-tests/README.md
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/env.ts
  end-to-end-tests/fixtures/authSetup.ts
  end-to-end-tests/fixtures/authSetupFixture.ts
  end-to-end-tests/fixtures/envSetup.ts
  end-to-end-tests/fixtures/extensionBase.ts
  end-to-end-tests/tests/telemetry/errors.spec.ts
  src/tsconfig.strictNullChecks.json
Labels: developer experience, testing

#8351 #8293 Unavailable overlay for sidebar forms and temp panels on nav
  .eslintrc.js
  end-to-end-tests/fixtures/envSetup.ts
  end-to-end-tests/tests/bricks/sidebarEffects.spec.ts
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
  end-to-end-tests/tests/regressions/formFlicker.spec.ts
  end-to-end-tests/tests/runtime/sidebarController.spec.ts
  end-to-end-tests/tests/runtime/sidebarNavigation.spec.ts
  end-to-end-tests/tests/telemetry/errors.spec.ts
  end-to-end-tests/utils.ts
  src/components/quickBar/QuickBarApp.tsx
  src/domConstants.ts
  src/sidebar/ConnectedSidebar.test.tsx
  src/sidebar/ConnectedSidebar.tsx
  src/sidebar/Tabs.module.scss
  src/sidebar/Tabs.tsx
  src/sidebar/TemporaryPanelTabPane.tsx
  src/sidebar/UnavailableOverlay.tsx
  src/sidebar/connectedTarget.tsx
  src/sidebar/unavailableOverlay.module.scss
  src/store/sidebar/sidebarSlice.ts
  src/store/sidebar/thunks/removeFormPanel.ts
  src/testUtils/factories/sidebarEntryFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/sidebarTypes.ts
  webpack.config.mjs
Labels: enhancement, mv3

#8353 #8347 Fix custom document stylesheets nested stylesheet inheritance
  end-to-end-tests/tests/runtime/sidebarPanelTheme.spec.ts
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/renderers/documentView/DocumentView.tsx
  src/bricks/renderers/documentView/DocumentViewProps.tsx
  src/bricks/transformers/ephemeralForm/EphemeralFormContent.tsx
  src/components/StylesheetsContext.ts
  src/tsconfig.strictNullChecks.json
Labels: bug, regression

#8370 playwright pr comment
  .github/workflows/ci.yml
  .github/workflows/inclusiveness-analyzer.yaml
  playwright.config.ts
Labels: developer experience, testing

#8350 run e2e tests for beta-release unless skipped
  .github/workflows/beta-release.yaml
  .github/workflows/ci.yml
  .github/workflows/release.yaml
Labels: infrastructure, testing
