Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-11, with the labels that each got.

#9391 #3164: enable React strict mode in development mode
  src/analysis/AnalysisAnnotationsContext.ts
  src/components/fields/schemaFields/widgets/__snapshots__/SchemaButtonVariantWidget.test.tsx.snap
  src/components/fields/schemaFields/widgets/__snapshots__/SchemaSelectWidget.test.tsx.snap
  src/components/floatingActions/FloatingActions.tsx
  src/components/form/widgets/RemoteMultiSelectWidget.test.tsx
  src/components/form/widgets/RemoteSelectWidget.test.tsx
  src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
  src/components/quickBar/QuickBarApp.tsx
  src/contentScript/snippetShortcutMenu/snippetShortcutMenuController.tsx
  src/contentScript/textSelectionMenu/selectionMenuController.tsx
  src/contrib/automationanywhere/__snapshots__/BotOptions.test.tsx.snap
  src/contrib/uipath/__snapshots__/ProcessOptions.test.tsx.snap
  src/extensionConsole/options.tsx
  src/extensionConsole/pages/activateMod/__snapshots__/ActivateModPage.test.tsx.snap
  src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap
  src/hooks/useOnMountOnly.ts
  src/hooks/useReportError.ts
  src/pageEditor/pageEditor.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataTabJsonTree.test.tsx
  src/pageEditor/tabs/effect/__snapshots__/BrickConfiguration.test.tsx.snap
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
  src/sidebar/SidebarBody.test.tsx
  src/sidebar/activateMod/__snapshots__/ActivateModPanel.test.tsx.snap
  src/sidebar/sidebar.tsx
  src/telemetry/trace.ts
  src/testUtils/testHelpers.tsx
Labels: developer experience, performance

#9387 #9336 Introduce Form Builder Rich-Text Field
  knip.mjs
  package-lock.json
  package.json
  src/bricks/readers/ElementReader.test.ts
  src/bricks/renderers/CustomFormComponent.tsx
  src/bricks/transformers/ephemeralForm/EphemeralFormContent.tsx
  src/components/formBuilder/formBuilderHelpers.ts
  src/components/formBuilder/preview/FormPreview.tsx
  src/components/formBuilder/widgets/RichTextWidget.test.tsx
  src/components/formBuilder/widgets/RichTextWidget.tsx
  src/components/richTextEditor/RichTextEditor.module.scss
  src/components/richTextEditor/RichTextEditor.stories.tsx
  src/components/richTextEditor/RichTextEditor.tsx
  src/components/richTextEditor/toolbar/BoldButton.tsx
  src/components/richTextEditor/toolbar/ItalicButton.tsx
  src/components/richTextEditor/toolbar/Toolbar.tsx
  src/pageEditor/fields/formFieldTypeOptions.ts
  src/testUtils/testEnv.js
Labels: enhancement, form builder

#9412 Revert "Refactor Offscreen page to use webext-messenger (#9383)"
  src/background/capture.ts
  src/offscreen/errorReport.ts
  src/offscreen/messenger/api.ts
  src/offscreen/messenger/registration.ts
  src/offscreen/offscreen.ts
  src/telemetry/logging.test.ts
  src/telemetry/reportToApplicationErrorTelemetry.test.ts
  src/telemetry/reportToApplicationErrorTelemetry.ts
  src/tinyPages/offscreen.html
  src/tinyPages/offscreen.ts
  src/tinyPages/offscreenDocumentController.ts
  src/tinyPages/offscreenProtocol.ts
  webpack.config.mjs
Labels: bug

#9409 Fix Upload Mixpanel Lexicon workflow & set to run in CI
  .github/workflows/upload-mixpanel-lexicon.yml
  tsconfig.json
Labels: developer experience

#9414 removing srcdoc sandbox iframe hack
  scripts/__snapshots__/manifest.test.js.snap
  src/contentScript/contentScriptCore.ts
  src/manifest.json
Labels: enhancement, runtime

#9413 Page Editor pane to configure mod variables definition
  end-to-end-tests/pageObjects/pageEditor/modEditorPane.ts
  end-to-end-tests/tests/pageEditor/modVariablesDefinition.spec.ts
  end-to-end-tests/tests/pageEditor/modVariablesDefinition.spec.ts-snapshots/add-save-mod-variable-definition/mod-variables-definition.yaml
  end-to-end-tests/tests/pageEditor/modVariablesDefinition.spec.ts-snapshots/new-mod-variable-without-brick/mod-variables-definition-no-brick.yaml
  src/analysis/analysisVisitors/pageStateAnalysis/modVariableSchemasVisitor.test.ts
  src/analysis/analysisVisitors/pageStateAnalysis/modVariableSchemasVisitor.ts
  src/auth/featureFlags.ts
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/components/form/Form.tsx
  src/components/tabLayout/EditorTabLayout.tsx
  src/pageEditor/panes/ModEditorPane.tsx
  src/pageEditor/starterBricks/adapter.ts
  src/pageEditor/starterBricks/base.ts
  src/pageEditor/store/analysisManager.ts
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  src/pageEditor/tabs/modVariablesDefinition/ModVariablesDefinitionEditor.module.scss
  src/pageEditor/tabs/modVariablesDefinition/ModVariablesDefinitionEditor.test.tsx
  src/pageEditor/tabs/modVariablesDefinition/ModVariablesDefinitionEditor.tsx
  src/pageEditor/tabs/modVariablesDefinition/ModVariablesTable.module.scss
  src/pageEditor/tabs/modVariablesDefinition/ModVariablesTable.tsx
  src/pageEditor/tabs/modVariablesDefinition/modVariablesDefinitionEditorHelpers.test.ts
  src/pageEditor/tabs/modVariablesDefinition/modVariablesDefinitionEditorHelpers.ts
  src/pageEditor/tabs/modVariablesDefinition/modVariablesDefinitionEditorTypes.ts
  src/pageEditor/tabs/modVariablesDefinition/useInferredModVariablesQuery.ts
  src/runtime/runtimeTypes.test.ts
  src/runtime/runtimeTypes.ts
  src/store/modComponents/modInstanceUtils.ts
Labels: enhancement, page editor

#9415 #9151 Add MarketplaceActivate and LinkExtension events to lexicon
  src/activation/useActivateMod.ts
  src/telemetry/events.ts
  src/telemetry/lexicon.ts
Labels: developer experience

#9416 #9338 Add Heading Level Dropdown to Rich Text Editor
  src/components/richTextEditor/RichTextEditor.module.scss
  src/components/richTextEditor/RichTextEditor.test.tsx
  src/components/richTextEditor/toolbar/HeadingLevelDropdown.tsx
  src/components/richTextEditor/toolbar/Toolbar.tsx
Labels: enhancement, form builder

#9417 #3164: add explicit `PropsWithChildren` to types
  src/__mocks__/@/components/DelayedRender.tsx
  src/__mocks__/@/components/Stylesheets.tsx
  src/auth/RequireAuth.tsx
  src/auth/RequireScope.tsx
  src/bricks/transformers/ephemeralForm/EphemeralForm.tsx
  src/bricks/transformers/temporaryInfo/EphemeralPanel.tsx
  src/components/Centered.tsx
  src/components/DelayedRender.tsx
  src/components/ErrorBoundary.tsx
  src/components/InvalidatedContextGate.tsx
  src/components/Stylesheets.tsx
  src/components/banner/Banner.tsx
  src/components/form/Form.tsx
  src/components/form/widgets/KeyNameWidget.tsx
  src/components/formBuilder/DescriptionField.tsx
  src/components/formBuilder/DescriptionFieldTemplate.tsx
  src/components/logViewer/details/OutputDetail.tsx
  src/components/onboarding/OnboardingChecklistCard.tsx
  src/extensionConsole/components/RequireBrickRegistry.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/mods/modals/shareModals/PublishModModals.test.tsx
  src/extensionConsole/pages/onboarding/SetupPage.tsx
  src/extensionConsole/pages/packageEditor/referenceTab/DetailSection.tsx
  src/extensionConsole/pages/settings/SettingsPage.tsx
  src/hooks/useFlags.test.tsx
  src/pageEditor/components/DimensionGate.tsx
  src/pageEditor/context/TabInspectionGate.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Basic.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Button.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Card.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Container.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Image.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/List.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Pipeline.tsx
  src/pageEditor/documentBuilder/preview/elementsPreview/Unknown.tsx
  src/pageEditor/fields/CollapsibleFieldSection.tsx
  src/pageEditor/modListingPanel/ModListItem.tsx
  src/pageEditor/modListingPanel/ModListingPanel.tsx
  src/pageEditor/panes/insert/InsertPane.tsx
  src/pageEditor/tabs/editTab/dataPanel/DataTabPane.tsx
  src/pageEditor/tabs/editTab/editorNodeLayout/nodeSummary.tsx
  src/pageEditor/tabs/effect/BrickPreview.tsx
  src/tinyPages/RestrictedUrlPopupApp.tsx
Labels: developer experience

#9420 #9419: move userSelectElementRefs into extended content script platform
  .eslintrc.js
  src/bricks/transformers/getAllTransformers.ts
  src/bricks/transformers/selectElement.test.ts
  src/bricks/transformers/selectElement.ts
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/platform/contentScriptPlatformProtocol.ts
  src/platform/platformBase.ts
  src/platform/platformProtocol.ts
  src/testUtils/platformMock.ts
Labels: platform-protocol

#9418 Remove unnecessary EditorState vars
  src/pageEditor/hooks/useAddNewModComponent.ts
  src/pageEditor/layout/EditorContent.tsx
  src/pageEditor/panes/BetaPane.tsx
  src/pageEditor/store/editor/editorSelectors/editorErrorSelectors.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.ts
  src/pageEditor/store/editor/pageEditorTypes.ts
  src/store/editorMigrations.test.ts
Labels: developer experience, page editor

#9423 #3164: drop deprecated `act` hook wrapper method
  src/activation/useActivateMod.test.ts
  src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts
  src/extensionConsole/pages/settings/useDeploymentKeySetting.test.ts
  src/hooks/useAsyncState.test.ts
  src/pageEditor/documentBuilder/hooks/useDuplicateElement.test.ts
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useCreateModFromMod.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.test.ts
  src/pageEditor/hooks/useDeleteDraftModComponent.test.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/testHelpers.ts
  src/testUtils/testHelpers.tsx
Labels: dependencies, testing

#9432 Fix `useIsMounted` for strict mode
  src/hooks/useIsMounted.ts
Labels: bug

#9424 #9338 Add Rich Text Editor toolbar buttons
  knip.mjs
  package-lock.json
  package.json
  src/components/richTextEditor/RichTextEditor.module.scss
  src/components/richTextEditor/RichTextEditor.test.tsx
  src/components/richTextEditor/RichTextEditor.tsx
  src/components/richTextEditor/toolbar/BulletedListButton.tsx
  src/components/richTextEditor/toolbar/HorizontalRuleButton.tsx
  src/components/richTextEditor/toolbar/NumberedListButton.tsx
  src/components/richTextEditor/toolbar/RemoveTextFormattingButton.tsx
  src/components/richTextEditor/toolbar/StrikethroughButton.tsx
  src/components/richTextEditor/toolbar/Toolbar.tsx
  src/components/richTextEditor/toolbar/UnderlineButton.tsx
Labels: enhancement

#9434 #3164: drop direct use of `@testing-library/react-hooks`
  .eslintrc.js
  src/activation/useActivateMod.test.ts
  src/components/fields/schemaFields/widgets/varPopup/useKeyboardNavigation.test.ts
  src/components/quickBar/useActionGenerators.test.tsx
  src/components/quickBar/useActions.test.tsx
  src/data/service/api.test.tsx
  src/errors/errorHelpers.test.tsx
  src/extensionConsole/pages/mods/utils/useReactivateMod.test.ts
  src/extensionConsole/pages/packageEditor/useSubmitPackage.test.tsx
  src/extensionConsole/pages/settings/useDeploymentKeySetting.test.ts
  src/hooks/useAbortSignal.test.ts
  src/hooks/useAsyncExternalStore.test.ts
  src/hooks/useAsyncState.test.ts
  src/hooks/useAutoFocus.test.ts
  src/hooks/useDeriveAsyncState.test.ts
  src/hooks/useDocumentVisibility.test.ts
  src/hooks/useEventListener.test.ts
  src/hooks/useIsMounted.test.ts
  src/hooks/useMemoCompare.test.ts
  src/hooks/useMergeAsyncState.test.ts
  src/hooks/useOnMountOnly.test.ts
  src/hooks/useScrollLock.test.ts
  src/hooks/useTimeoutState.test.ts
  src/hooks/useUndo.test.ts
  src/hooks/useWindowSize.test.ts
  src/pageEditor/documentBuilder/hooks/useDuplicateElement.test.ts
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useCreateModFromMod.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.test.ts
  src/pageEditor/hooks/useDeleteDraftModComponent.test.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
  src/permissions/useExtensionPermissions.test.ts
  src/store/enterprise/useManagedStorageState.test.ts
  src/testUtils/renderHookHelpers.ts
  src/testUtils/testHelpers.tsx
Labels: testing

#9438 Refactor page editor state types
  src/background/deploymentUpdater.test.ts
  src/pageEditor/modListingPanel/ModListingPanel.tsx
  src/pageEditor/store/editor/editorSelectors/editorModSelectors.test.ts
  src/pageEditor/store/editor/editorSelectors/editorNavigationSelectors.ts
  src/pageEditor/store/editor/editorSlice.test.ts
  src/pageEditor/store/editor/editorSlice.ts
  src/pageEditor/store/editor/editorSliceHelpers.test.ts
  src/pageEditor/store/editor/pageEditorTypes/editorStateEphemeral.ts
  src/pageEditor/store/editor/pageEditorTypes/editorStateMigrated.ts
  src/pageEditor/store/editor/pageEditorTypes/editorStateSynced.ts
  src/pageEditor/store/editor/pageEditorTypes/index.ts
  src/pageEditor/tabs/editTab/useReportTraceError.test.tsx
  src/store/editorInitialState.ts
  src/store/editorMigrations.test.ts
  src/store/editorMigrations.ts
Labels: developer experience, page editor, 30% time

#9440 Disable linting pre commit hook
  .pre-commit-config.yaml
Labels: developer experience

#9443 Remove @types/react-redux
  package-lock.json
  package.json
Labels: dependencies

#9442 Ignore variable expression in get variable schema
  src/bricks/effects/pageState.test.ts
  src/bricks/effects/pageState.ts
Labels: bug, page editor

#9439 #9433: basic mod version history tab in Page Editor behind feature flag
  applications/browser-extension/src/auth/featureFlags.ts
  applications/browser-extension/src/components/logViewer/EntryRow.tsx
  applications/browser-extension/src/pageEditor/hooks/useSaveMod.test.ts
  applications/browser-extension/src/pageEditor/hooks/useSaveMod.ts
  applications/browser-extension/src/pageEditor/panes/ModEditorPane.tsx
  applications/browser-extension/src/pageEditor/tabs/modVersionHistory/ModVersionHistory.test.tsx
  applications/browser-extension/src/pageEditor/tabs/modVersionHistory/ModVersionHistory.tsx
  applications/browser-extension/src/testUtils/factories/registryFactories.ts
  applications/browser-extension/src/types/contract.ts
  applications/browser-extension/src/utils/stringUtils.ts
Labels: user experience, page editor

#9456 "Find within mod" data panel tab behind feature flag
  applications/browser-extension/src/auth/featureFlags.ts
  applications/browser-extension/src/bricks/exampleBrickConfigs.ts
  applications/browser-extension/src/contentScript/platform/contentScriptPlatformProtocol.ts
  applications/browser-extension/src/pageEditor/documentBuilder/edit/ElementEditor.tsx
  applications/browser-extension/src/pageEditor/hooks/useEnsureFormStates.ts
  applications/browser-extension/src/pageEditor/modListingPanel/ActivatedModComponentListItem.tsx
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorDataPanelSelectors.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorModSelectors.test.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSlice.ts
  applications/browser-extension/src/pageEditor/store/editor/pageEditorTypes/editorStateMigrated.ts
  applications/browser-extension/src/pageEditor/store/editor/pageEditorTypes/editorStateSynced.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/BrickDataPanel.tsx
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/DataTabPane.tsx
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/StarterBrickDataPanel.tsx
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/dataPanelTypes.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/FindTab.test.tsx
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/FindTab.tsx
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/ResultItem.module.scss
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/ResultItem.tsx
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/breadcrumbLabelHelpers.test.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/breadcrumbLabelHelpers.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/findTypes.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/searchIndexVisitor.test.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/searchIndexVisitor.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/useFindInMod.ts
  applications/browser-extension/src/store/editorInitialState.ts
  applications/browser-extension/src/store/editorMigrations.test.ts
  applications/browser-extension/src/store/editorMigrations.ts
  applications/browser-extension/src/testUtils/factories/modComponentFactories.ts
  applications/browser-extension/src/utils/arrayUtils.test.ts
  applications/browser-extension/src/utils/arrayUtils.ts
  applications/browser-extension/src/utils/stringUtils.test.ts
  applications/browser-extension/src/utils/stringUtils.ts
Labels: enhancement, page editor

#9497 Drop unused `prop-types` package
  applications/browser-extension/package.json
  package-lock.json
Labels: dependencies, developer experience

#9499 #9498: Retarget `npm` Dependabot
  .github/dependabot.yml
Labels: developer experience, regression

#9504 Mark extension `dist` directory as excluded in IntelliJ
  pixiebrix-extension.iml
Labels: developer experience

#9491 #9430: extracting first util lib
  .github/workflows/ci.yml
  applications/browser-extension/package.json
  applications/browser-extension/src/pageEditor/store/editor/editorSlice.test.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSlice.ts
  libraries/utils/jest.config.js
  libraries/utils/package.json
  libraries/utils/src/debugUtils.test.ts
  libraries/utils/src/debugUtils.ts
  libraries/utils/tsconfig.json
  package-lock.json
  package.json
Labels: developer experience

#9501 Bump object-hash to 3.0.0
  applications/browser-extension/package.json
  package-lock.json
Labels: dependencies, javascript

#9505 #9457: move `knip` to repository root
  .github/workflows/ci.yml
  .github/workflows/upload-mixpanel-lexicon.yml
  .secrets.baseline
  applications/browser-extension/knip.mjs
  applications/browser-extension/package.json
  applications/browser-extension/src/store/editorMigrations.ts
  applications/browser-extension/webpack.sharedConfig.js
  knip.mjs
  libraries/utils/package.json
  package-lock.json
  package.json
Labels: developer experience, regression

#9506 Add eslint config for `libraries/utils`
  .github/workflows/ci.yml
  libraries/utils/.eslintrc.js
  libraries/utils/package.json
  libraries/utils/src/debugUtils.ts
  libraries/utils/src/globals.d.ts
  package.json
Labels: developer experience

#9495 #9492 Add database to Rich Text Editor form builder field
  applications/browser-extension/src/components/formBuilder/edit/ActiveField.tsx
  applications/browser-extension/src/components/formBuilder/edit/fieldEditor/FieldEditor.module.scss
  applications/browser-extension/src/components/formBuilder/edit/fieldEditor/FieldEditor.tsx
  applications/browser-extension/src/components/formBuilder/edit/fieldEditor/RichTextFields.tsx
  applications/browser-extension/src/components/formBuilder/edit/fieldEditor/TextAreaFields.tsx
  applications/browser-extension/src/components/formBuilder/widgets/RichTextWidget.test.tsx
  applications/browser-extension/src/components/formBuilder/widgets/RichTextWidget.tsx
Labels: enhancement

#9507 Refactoring common tsconfig
  applications/browser-extension/package.json
  applications/browser-extension/tsconfig.json
  libraries/utils/tsconfig.json
  package.json
  pixiebrix-extension.iml
  tsconfig.base.json
Labels: developer experience

#9508 #9430: initialize nx configuration, and use nx task runner
  .github/workflows/ci.yml
  .gitignore
  applications/browser-extension/package.json
  libraries/utils/package.json
  nx.json
  package-lock.json
  package.json
  pixiebrix-extension.iml
Labels: developer experience

#9509 Dependabot manual updates
  applications/browser-extension/package.json
  applications/browser-extension/src/components/fields/schemaFields/widgets/__snapshots__/CodeEditorWidget.test.tsx.snap
  applications/browser-extension/src/pageEditor/store/castState.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSlice.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSliceHelpers.ts
  applications/browser-extension/src/store/sidebar/sidebarSlice.ts
  applications/browser-extension/src/utils/modUtils.ts
  knip.mjs
  package-lock.json
Labels: dependencies, javascript

#9514 fix uploading the complete e2e test report
  .github/workflows/ci.yml
Labels: testing, regression

#9518 fix rainforest and sourcemaps upload scripts
  .github/workflows/beta-release.yaml
  applications/browser-extension/scripts/upload-extension.sh
  applications/browser-extension/scripts/upload-sourcemaps.sh
Labels: developer experience, regression

#9512 #9511: fix error toast when starting new mod
  applications/browser-extension/end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  applications/browser-extension/end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts
  applications/browser-extension/src/pageEditor/hooks/useAddNewModComponent.ts
  applications/browser-extension/src/pageEditor/modals/addBrickModal/useAddBrick.ts
Labels: bug, regression, page editor

#9515 Add IntelliJ nx console plugin settings file to git
  .idea/nx-angular-config.xml
Labels: developer experience

#9502 Bump urlpattern-polyfill to 10.0.0 and move to dev dependencies
  applications/browser-extension/package.json
  applications/browser-extension/src/globals.d.ts
  package-lock.json
Labels: dependencies, javascript

#9503 Bump prettier to 3.3.3 and reformat files
  .pre-commit-config.yaml
  .prettierignore
  applications/browser-extension/src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  applications/browser-extension/src/background/auth/partnerIntegrations/launchAuthIntegration.ts
  applications/browser-extension/src/components/MarketplaceListingIcon.tsx
  applications/browser-extension/src/components/fields/schemaFields/integrations/IntegrationDependencyWidget.tsx
  applications/browser-extension/src/components/fields/schemaFields/widgets/DatabaseCreateModal.tsx
  applications/browser-extension/src/components/fields/schemaFields/widgets/DatabaseWidget.tsx
  applications/browser-extension/src/components/fields/schemaFields/widgets/ObjectWidget.tsx
  applications/browser-extension/src/components/fields/schemaFields/widgets/varPopup/SourceLabel.tsx
  applications/browser-extension/src/components/form/widgets/RemoteMultiSelectWidget.tsx
  applications/browser-extension/src/extensionConsole/pages/packageEditor/useSubmitPackage.ts
  applications/browser-extension/src/pageEditor/store/runtime/runtimeSelectors.ts
  applications/browser-extension/src/store/sidebar/sidebarSlice.ts
  applications/browser-extension/src/testUtils/permissionsMock.ts
  package-lock.json
  package.json
Labels: dependencies, developer experience, javascript

#9516 Enforce `react-hooks/exhaustive-deps`
  applications/browser-extension/.eslintrc.js
  applications/browser-extension/src/components/ConfirmationModal.stories.tsx
  applications/browser-extension/src/extensionConsole/pages/mods/ModsPageActions.tsx
  applications/browser-extension/src/extensionConsole/pages/mods/ModsPageSidebar.tsx
  applications/browser-extension/src/extensionConsole/pages/mods/gridView/GridView.tsx
  applications/browser-extension/src/pageEditor/documentBuilder/preview/ElementPreview.tsx
Labels: developer experience

#9521 Only upload the dist directory to AWS
  applications/browser-extension/scripts/upload-extension.sh
Labels: regression

#9522 #9430: tsconfig references refactor
  .github/workflows/ci.yml
  .github/workflows/end-to-end-tests.yml
  .gitignore
  applications/browser-extension/tsconfig.json
  knip.mjs
  libraries/utils/.eslintrc.js
  libraries/utils/package.json
  libraries/utils/src/debugUtils.test.ts
  libraries/utils/tsconfig.json
  libraries/utils/tsconfig.lib.json
  libraries/utils/tsconfig.test.json
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
  tsconfig.json
Labels: developer experience

#9525 Fix display property on RichTextEditor error toast
  applications/browser-extension/src/components/richTextEditor/ErrorToast.tsx
  applications/browser-extension/src/components/richTextEditor/RichTextEditor.module.scss
Labels: bug

#9490 Drop currentModId as a concept
  applications/browser-extension/end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  applications/browser-extension/src/components/formBuilder/edit/ActiveField.tsx
  applications/browser-extension/src/pageEditor/hooks/useCreateModFromUnsavedMod.ts
  applications/browser-extension/src/pageEditor/hooks/useEnsureFormStates.ts
  applications/browser-extension/src/pageEditor/hooks/useRegisterDraftModInstanceOnAllFrames.ts
  applications/browser-extension/src/pageEditor/modListingPanel/ModListItem.tsx
  applications/browser-extension/src/pageEditor/modListingPanel/ModSidebarListItems.tsx
  applications/browser-extension/src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  applications/browser-extension/src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx
  applications/browser-extension/src/pageEditor/modals/addBrickModal/useAddBrick.ts
  applications/browser-extension/src/pageEditor/store/editor/editorInvariantMiddleware.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorDataPanelSelectors.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorModSelectors.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorNavigationSelectors.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorPipelineSelectors.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSlice.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSliceHelpers.ts
  applications/browser-extension/src/pageEditor/store/editor/pageEditorTypes/editorStateMigrated.ts
  applications/browser-extension/src/pageEditor/tabs/editTab/EditTab.tsx
  applications/browser-extension/src/pageEditor/tabs/editTab/dataPanel/tabs/FindTab/useFindInMod.ts
  applications/browser-extension/src/store/editorMigrations.ts
  applications/browser-extension/src/store/editorStorage.test.ts
Labels: developer experience, page editor, 30% time

#9528 fix logic for setting alternate background in mod list items
  applications/browser-extension/src/pageEditor/modListingPanel/ModListItem.tsx
Labels: bug

#9524 refactoring utils project to use barrel output
  .github/workflows/ci.yml
  applications/browser-extension/package.json
  applications/browser-extension/src/pageEditor/store/editor/editorSlice.ts
  applications/browser-extension/tsconfig.json
  knip.mjs
  libraries/util-debug/.eslintrc.js
  libraries/util-debug/jest.config.js
  libraries/util-debug/package.json
  libraries/util-debug/src/index.ts
  libraries/util-debug/src/lib/debugUtils.test.ts
  libraries/util-debug/src/lib/debugUtils.ts
  libraries/util-debug/src/lib/globals.d.ts
  libraries/util-debug/tsconfig.json
  libraries/util-debug/tsconfig.lib.json
  libraries/util-debug/tsconfig.test.json
  nx.json
  package-lock.json
  package.json
  pixiebrix-extension.iml
  tsconfig.json
Labels: developer experience

#9520 #9433: mod commit message modal
  applications/browser-extension/end-to-end-tests/pageObjects/pageEditor/pageEditorPage.ts
  applications/browser-extension/end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-button-starter-brick-to-mod.yaml
  applications/browser-extension/end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-context-menu-starter-brick-to-mod.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-quick-bar-starter-brick-to-mod.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-sidebar-panel-starter-brick-to-mod.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/addStarterBrick.spec.ts-snapshots/Add-starter-brick-to-mod/add-trigger-starter-brick-to-mod.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-added.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-copied-to-another-mod.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-copy-pasted.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/brick-removed.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/brickActions.spec.ts-snapshots/brick-actions-panel-behavior/bricks-moved.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/brickConfiguration.spec.ts-snapshots/brick-configuration/starter-brick-configuration-changes.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/modEditorPane.spec.ts-snapshots/mod-editor-pane-behavior/updated-inputs.diff
  applications/browser-extension/end-to-end-tests/tests/pageEditor/saveMod.spec.ts
  applications/browser-extension/src/background/deploymentUpdater.test.ts
  applications/browser-extension/src/background/installer.ts
  applications/browser-extension/src/data/service/api.ts
  applications/browser-extension/src/extensionConsole/pages/mods/utils/buildGetModVersionStatus.test.ts
  applications/browser-extension/src/extensionConsole/pages/packageEditor/PackageHistory.test.tsx
  applications/browser-extension/src/modDefinitions/modDefinitions.test.tsx
  applications/browser-extension/src/pageEditor/hooks/useSaveMod.test.ts
  applications/browser-extension/src/pageEditor/hooks/useSaveMod.ts
  applications/browser-extension/src/pageEditor/modListingPanel/ModListItem.test.tsx
  applications/browser-extension/src/pageEditor/modListingPanel/modals/CreateModModal.tsx
  applications/browser-extension/src/pageEditor/modListingPanel/modals/SaveAsNewModModal.tsx
  applications/browser-extension/src/pageEditor/modListingPanel/modals/SaveModVersionModal.test.tsx
  applications/browser-extension/src/pageEditor/modListingPanel/modals/SaveModVersionModal.tsx
  applications/browser-extension/src/pageEditor/modals/Modals.tsx
  applications/browser-extension/src/pageEditor/panes/ModEditorPane.tsx
  applications/browser-extension/src/pageEditor/panes/save/saveHelpers.ts
  applications/browser-extension/src/pageEditor/starterBricks/base.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSelectors/editorModalSelectors.ts
  applications/browser-extension/src/pageEditor/store/editor/editorSlice.ts
  applications/browser-extension/src/pageEditor/store/editor/pageEditorTypes/index.ts
  applications/browser-extension/src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  applications/browser-extension/src/pageEditor/tabs/modVersionHistory/ModVersionHistory.tsx
  applications/browser-extension/src/platform/platformContext.ts
  applications/browser-extension/src/registry/packageRegistry.test.ts
  applications/browser-extension/src/runtime/pipelineTests/component.test.ts
  applications/browser-extension/src/store/modComponents/modComponentMigrations.ts
  applications/browser-extension/src/testUtils/factories/brickFactories.ts
  applications/browser-extension/src/testUtils/factories/databaseFactories.ts
  applications/browser-extension/src/testUtils/factories/deploymentFactories.ts
  applications/browser-extension/src/testUtils/factories/metadataFactory.ts
  applications/browser-extension/src/testUtils/factories/modViewItemFactory.ts
  applications/browser-extension/src/testUtils/factories/registryFactories.ts
  applications/browser-extension/src/testUtils/platformMock.ts
  applications/browser-extension/src/types/helpers.test.ts
  applications/browser-extension/src/types/helpers.ts
  applications/browser-extension/src/types/semVerHelpers.test.ts
  applications/browser-extension/src/types/semVerHelpers.ts
  applications/browser-extension/src/types/swagger.ts
  applications/browser-extension/src/utils/deploymentUtils.test.ts
  applications/browser-extension/src/utils/deploymentUtils.ts
  applications/browser-extension/src/utils/extensionUtils.ts
  applications/browser-extension/src/utils/modUtils.ts
  applications/browser-extension/src/utils/objToYaml.test.ts
Labels: enhancement, page editor

#9527 #9433: use PaginatedTable for Mod Version History
  applications/browser-extension/package.json
  applications/browser-extension/src/components/paginatedTable/PaginatedTable.tsx
  applications/browser-extension/src/pageEditor/tabs/modVersionHistory/ModVersionHistory.test.tsx
  applications/browser-extension/src/pageEditor/tabs/modVersionHistory/ModVersionHistory.tsx
  applications/browser-extension/src/types/contract.ts
  knip.mjs
  package-lock.json
Labels: enhancement, user experience, page editor

#9532 Fix flaky mod definitions test
  .idea/nx-angular-config.xml
  applications/browser-extension/src/modDefinitions/modDefinitions.test.tsx
Labels: testing, regression

#9531 Bugfix: Don't throw error in FormPreview if assetDatabase is not a UUID
  applications/browser-extension/src/components/formBuilder/widgets/RichTextWidget.tsx
  applications/browser-extension/src/components/richTextEditor/RichTextEditor.tsx
Labels: bug
