Repository pixiebrix/pixiebrix-extension, pull requests merged in 2024-03, with the labels that each got.

#7776 #7775: confirm delete in the workshop
  src/components/ConfirmationModal.tsx
  src/extensionConsole/pages/brickEditor/EditPage.tsx
  src/extensionConsole/pages/brickEditor/useSubmitBrick.test.tsx
  src/extensionConsole/pages/brickEditor/useSubmitBrick.ts
Labels: user experience

#7761 #7689 Add auth utility for Playwright tests
  .github/workflows/ci.yml
  .gitignore
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/env.ts
  end-to-end-tests/example.spec.ts
  playwright.config.ts
  scripts/env.d.ts
  src/tsconfig.strictNullChecks.json
Labels: testing

#7764 Improve input field contrast in extension console and app
  src/vendors/theme/assets/styles/_variables.scss
Labels: papercut

#7762 Box shadow for text selection popover
  src/contentScript/selectionTooltip/tooltipController.tsx
Labels: user experience, low priority

#7790 #7784: skip waiting for managed storage after initial wait
  src/__mocks__/browserMock.mjs
  src/auth/useLinkState.ts
  src/auth/usePartnerAuthData.ts
  src/auth/useRequiredPartnerAuth.ts
  src/background/background.ts
  src/background/deploymentUpdater.test.ts
  src/background/installer.test.ts
  src/background/installer.ts
  src/background/restrictUnauthenticatedUrlAccess.test.ts
  src/background/telemetry.ts
  src/components/logViewer/LogTable.stories.tsx
  src/extensionConsole/Navbar.tsx
  src/extensionConsole/pages/BrowserBanner.test.tsx
  src/extensionConsole/pages/onboarding/SetupPage.test.tsx
  src/mv3/SessionStorage.test.ts
  src/mv3/SessionStorage.ts
  src/store/enterprise/managedStorage.test.ts
  src/store/enterprise/managedStorage.ts
  src/store/enterprise/useManagedStorageState.test.ts
  src/store/enterprise/useManagedStorageState.ts
  src/testUtils/testAfterEnv.ts
  src/testUtils/testEnv.js
  src/themes/themeStore.test.ts
  src/utils/promiseUtils.test.ts
  src/utils/promiseUtils.ts
Labels: performance

#7805 #7729: Handle Gmail's deselection on mousedown
  src/contentScript/selectionTooltip/SelectionToolbar.tsx
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/utils/selectionController.ts
Labels: bug

#7791 Drop unused `mode` code
  src/auth/RequireScope.tsx
  src/extensionConsole/Navbar.tsx
  src/store/settings/settingsSlice.ts
  src/store/settings/settingsTypes.ts
Labels: developer experience, low priority

#7804 #7680: move registry types to registryTypes
  src/bricks/transformers/GetBrickInterfaceTransformer.ts
  src/bricks/transformers/RunBrickByIdTransformer.ts
  src/bricks/transformers/getAllTransformers.ts
  src/integrations/locator.ts
  src/registry/memoryRegistry.ts
  src/runtime/reducePipeline.ts
  src/types/registryTypes.ts
Labels: developer experience, low priority

#7783 #7766: add invariant checks when creating/copying a mod
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useBuildAndValidateMod.ts
  src/pageEditor/hooks/useCreateModFromMod.test.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useCreateModFromModComponent.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/sidebar/modals/AddToRecipeModal.tsx
  src/pageEditor/sidebar/modals/CreateModModal.tsx
  src/pageEditor/testHelpers.ts
  src/pageEditor/utils.ts
  src/store/defaultMiddlewareConfig.ts
Labels: bug, page editor

#7810 Use "Local Integration" terminology in Extension Console
  src/components/integrations/IntegrationConfigEditorModal.tsx
  src/extensionConsole/Sidebar.tsx
  src/extensionConsole/pages/integrations/IntegrationsPage.tsx
Labels: user experience

#7802 #7801: schema validation bug fixes/improvements
  eslint-local-rules/persistBackgroundData.txt
  schemas/component.json
  src/bricks/effects/alert.test.ts
  src/bricks/effects/assignModVariable.test.ts
  src/bricks/readers/factory.ts
  src/bricks/registry.test.ts
  src/bricks/registry.ts
  src/bricks/transformers/IdentityTransformer.test.ts
  src/bricks/transformers/brickFactory.ts
  src/bricks/transformers/parseDate.test.ts
  src/components/documentBuilder/preview/ElementPreview.test.tsx
  src/components/documentBuilder/preview/__snapshots__/ElementPreview.test.tsx.snap
  src/components/integrations/IntegrationConfigEditorModal.tsx
  src/contrib/google/sheets/bricks/append.ts
  src/contrib/google/sheets/bricks/lookup.ts
  src/contrib/google/sheets/core/schemas.ts
  src/contrib/google/sheets/core/useSpreadsheetId.ts
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/RequireGoogleSheet.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.tsx
  src/contrib/zapier/push.ts
  src/extensionConsole/pages/brickEditor/validate.ts
  src/hooks/useAsyncModOptionsValidationSchema.ts
  src/hooks/useDeriveAsyncState.ts
  src/integrations/util/extractIntegrationIdsFromSchema.test.ts
  src/registry/packageRegistry.ts
  src/runtime/getType.ts
  src/runtime/pipelineTests/validateInput.test.ts
  src/runtime/runtimeUtils.ts
  src/testUtils/factories/brickFactories.ts
  src/testUtils/factories/integrationFactories.ts
  src/testUtils/factories/stringFactories.ts
  src/tsconfig.strictNullChecks.json
  src/validators/generic.ts
  src/validators/schemaValidator.test.ts
  src/validators/schemaValidator.ts
Labels: bug, performance

#7815 #7788: preserve input border color without changing non-inputs
  src/vendors/theme/assets/styles/_variables.scss
  src/vendors/theme/assets/styles/components/_forms.scss
Labels: user experience

#7817 EsLint: add no-unstable-nested-components and forbid-elements
  .eslintrc.js
  src/extensionConsole/pages/brickEditor/SharingTable.tsx
  src/extensionConsole/pages/settings/FactoryResetSettings.tsx
  src/extensionConsole/pages/settings/SettingToggle.tsx
  src/pageEditor/fields/SelectorMatchField.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/panes/insert/InsertMenuItemPane.tsx
  src/pageEditor/panes/insert/InsertPanelPane.tsx
  src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
Labels: developer experience

#7816 implement jest/prefer-expect-resolves
  .eslintrc.js
  src/auth/RequireAuth.test.tsx
  src/background/auth/getToken.test.ts
  src/background/deploymentUpdater.test.ts
  src/bricks/available.test.ts
  src/bricks/effects/InsertAtCursorEffect.test.ts
  src/components/fields/schemaFields/SchemaField.test.tsx
  src/components/fields/schemaFields/widgets/CodeEditorWidget.test.tsx
  src/components/integrations/AuthWidget.test.tsx
  src/contrib/google/sheets/core/sheetsApi.test.ts
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx
  src/extensionConsole/pages/activateMod/IntegrationsBody.test.tsx
  src/extensionConsole/pages/deployments/DeploymentModal.test.tsx
  src/pageEditor/sidebar/ActivatedModComponentListItem.test.tsx
  src/pageEditor/sidebar/ModListItem.test.tsx
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.test.tsx
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/utils/deploymentUtils.test.ts
  src/utils/inference/inferSingleElementSelector.test.ts
  src/utils/promiseUtils.test.ts
Labels: developer experience

#7818 #7788: adds password styling change missed in previous pr
  src/components/fields/schemaFields/widgets/PasswordWidget.module.scss
  src/themes/colors.scss
  src/vendors/theme/assets/styles/_variables.scss
Labels: bug, user experience

#7811 #7729: Handle Gmail's deselection on mousedown /2
  src/contentScript/selectionTooltip/tooltipController.tsx
Labels: bug

#7826 #7822: await initial remote registry sync on packageRegistry read operations
  src/registry/packageRegistry.test.ts
  src/registry/packageRegistry.ts
Labels: bug

#7825 4858 connect datadog rum and traces
  src/extensionConsole/options.tsx
  src/pageEditor/pageEditor.tsx
  src/sidebar/sidebar.tsx
  src/telemetry/dnt.ts
  src/telemetry/performance.test.ts
  src/telemetry/performance.ts
  src/tsconfig.strictNullChecks.json
Labels: infrastructure

#7828 enforce comments when we ignore lint rules
  .eslintrc.js
Labels: developer experience

#7827 #7774: save host page element focus when clicking into MV2 sidebar
  src/bricks/effects/InsertAtCursorEffect.ts
  src/contentScript/contentScriptCore.ts
  src/contentScript/sidebarController.tsx
  src/contentScript/sidebarDomControllerLite.ts
  src/contentScript/textEditorDom.ts
  src/utils/focusController.ts
Labels: bug

#7831 #7827: Restore MV3 support
  src/bricks/effects/InsertAtCursorEffect.ts
  src/contentScript/sidebarController.tsx
  src/contentScript/textEditorDom.ts
  src/utils/focusController.ts
Labels: bug, regression, mv3

#7833 Add focus controller developer note in comment
  src/utils/focusController.ts
Labels: developer experience, low priority

#7834 ESLint: fix missing comments for expect-expect eslint rule
  src/components/fields/schemaFields/BasicSchemaField.test.tsx
  src/components/fields/schemaFields/ChildObjectField.test.tsx
  src/components/fields/schemaFields/SchemaField.test.tsx
  src/components/fields/schemaFields/widgets/ObjectWidget.test.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/TabField.test.tsx
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/pageEditor/panes/EditorPane.test.tsx
  src/utils/inference/selectorInference.test.ts
Labels: developer experience

#7829 ESLint: error on missing lint ignore comments
  .eslintrc.js
  src/analysis/analysisVisitors/varAnalysis/parseTemplateVariables.ts
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.ts
  src/auth/authUtils.ts
  src/auth/featureFlagStorage.test.ts
  src/background/auth/authStorage.ts
  src/background/auth/codeGrantFlow.ts
  src/background/auth/implicitGrantFlow.ts
  src/background/restrictUnauthenticatedUrlAccess.test.ts
  src/background/setToolbarIconFromTheme.test.ts
  src/background/telemetry.test.ts
  src/bricks/effects/pageState.test.ts
  src/bricks/registry.test.ts
  src/bricks/transformers/ephemeralForm/formTransformer.test.ts
  src/bricks/transformers/mapping.ts
  src/bricks/transformers/parseUrl.ts
  src/components/EmotionShadowRoot.ts
  src/components/documentBuilder/documentTree.tsx
  src/components/documentBuilder/hooks/useMoveWithinParent.ts
  src/components/documentBuilder/preview/DocumentPreview.test.tsx
  src/contentScript/lifecycle.test.ts
  src/contentScript/lifecycle.ts
  src/contentScript/loadActivationEnhancementsCore.test.ts
  src/extensionConsole/pages/BrowserBanner.test.tsx
  src/hooks/useFlags.test.tsx
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.test.ts
  src/mods/useModViewItems.test.tsx
  src/mods/useMods.test.ts
  src/permissions/useExtensionPermissions.test.ts
  src/store/enterprise/managedStorage.test.ts
  src/store/enterprise/useManagedStorageState.test.ts
  src/testUtils/userMock.ts
  src/themes/themeStore.test.ts
Labels: developer experience

#7837 #7836: fix package definition validation due to updated_at and sharing metadata
  .idea/.gitignore
  src/types/contract.ts
  src/types/modDefinitionTypes.ts
  src/validators/schemaValidator.test.ts
  src/validators/schemaValidator.ts
Labels: bug, regression

#7824 #7821 - Fix issue preventing save-as-new-mod with sidebar component
  src/modDefinitions/modDefinitions.test.tsx
  src/pageEditor/hooks/useBuildAndValidateMod.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.ts
  src/pageEditor/hooks/useCompareModComponentCounts.test.ts
  src/pageEditor/hooks/useCompareModComponentCounts.ts
  src/pageEditor/hooks/useCreateModFromMod.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.test.ts
  src/pageEditor/hooks/useCreateModFromModComponent.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/panes/save/saveHelpers.ts
  src/pageEditor/sidebar/modals/CreateModModal.tsx
  src/pageEditor/slices/editorSlice.ts
Labels: bug

#7808 Remove package config from deployments response
  src/background/deploymentUpdater.test.ts
  src/background/deploymentUpdater.ts
  src/data/service/api.ts
  src/data/service/apiVersioning.ts
  src/data/service/baseQuery.ts
  src/extensionConsole/pages/brickEditor/BrickHistory.test.tsx
  src/extensionConsole/pages/brickEditor/BrickHistory.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.test.ts
  src/extensionConsole/pages/deployments/useAutoDeploy.ts
  src/modDefinitions/modDefinitionRawApiCalls.ts
  src/permissions/deploymentPermissionsHelpers.ts
  src/testUtils/factories/brickFactories.ts
  src/testUtils/factories/deploymentFactories.ts
  src/tsconfig.strictNullChecks.json
  src/types/contract.ts
  src/types/deploymentTypes.ts
  src/types/swagger.ts
  src/utils/deploymentUtils.test.ts
  src/utils/deploymentUtils.ts
Labels: performance, priority

#7843 #7835: save focus on sidebar load
  src/contentScript/sidebarController.tsx
Labels: bug, sidebar

#7845 #7844: fix NPE in deployments async state
  src/__mocks__/@/telemetry/telemetryHelpers.ts
  src/extensionConsole/pages/deployments/DeploymentsContext.test.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/useAutoDeploy.ts
  src/hooks/useBrowserIdentifier.ts
  src/hooks/useFlags.ts
  src/telemetry/telemetryHelpers.ts
  src/tsconfig.strictNullChecks.json
Labels: bug, regression

#7785 #7663 fix multiple modal forms from trigger
  src/bricks/transformers/ephemeralForm/formTransformer.test.ts
  src/pageEditor/toolbar/ReloadToolbar.tsx
  src/platform/forms/formController.ts
Labels: bug

#7851 #7840: Allow legacy JQuery reader definitions with no selectors
  contrib/readers/empty-jquery-reader.yaml
  schemas/reader.json
  src/validators/schemaValidator.test.ts
Labels: bug, regression

#7832 #7809: Edge: Add support for target="_blank" from the sidePanel
  .eslintrc.js
  package-lock.json
  package.json
  src/__snapshots__/Storyshots.test.js.snap
  src/pageEditor/NonScriptablePage.tsx
  src/pageEditor/components/LoginCard.tsx
  src/pageEditor/panes/__snapshots__/NonScriptablePage.test.tsx.snap
  src/sidebar/DefaultPanel.tsx
  src/sidebar/Header.tsx
  src/sidebar/LoginPanel.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/__snapshots__/ConnectedSidebar.test.tsx.snap
  src/sidebar/__snapshots__/Header.test.tsx.snap
  src/sidebar/__snapshots__/SidebarBody.test.tsx.snap
  src/sidebar/modLauncher/ActiveSidebarModsList.tsx
  src/sidebar/sidebar.html
  src/sidebar/sidebar.tsx
  src/tsconfig.strictNullChecks.json
  src/utils/browserUtils.ts
  src/utils/openAllLinksInPopups.ts
Labels: mv3, edge

#7842 #7830: Insert at cursor in Draft JS from MV2 sidebar
  src/bricks/effects/InsertAtCursorEffect.ts
  src/contentScript/sidebarController.tsx
  src/utils/selectionController.ts
Labels: bug, sidebar

#7862 #7814: Fix DraftJS support on empty fields (Insert Text brick)
  src/contentScript/textEditorDom.ts
  src/utils/domFieldUtils.ts
Labels: bug, brick

#7852 #7846: banner indicating IDB is unresponsive
  src/components/DatabaseUnresponsiveBanner.test.tsx
  src/components/DatabaseUnresponsiveBanner.tsx
  src/extensionConsole/App.tsx
  src/pageEditor/PanelContent.tsx
  src/pageEditor/TabConnectionErrorBanner.tsx
  src/sidebar/SidebarBody.tsx
  src/telemetry/events.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience

#7859 Automatically strip leading backslash in text snippet/command definition
  src/bricks/effects/AddTextCommand.test.ts
  src/bricks/effects/AddTextCommand.ts
  src/bricks/effects/AddTextSnippets.test.ts
  src/bricks/effects/AddTextSnippets.ts
Labels: user experience, brick

#7860 #7690 Add Playwright Extension Console smoke test
  .github/workflows/ci.yml
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/env.ts
  end-to-end-tests/example.spec.ts
  end-to-end-tests/extensionConsoleActivation.ts
  end-to-end-tests/fixtures.ts
  playwright.config.ts
  src/tsconfig.strictNullChecks.json
Labels: testing

#7866 Make `visualInjection` pixel clickable
  src/development/visualInjection.ts
Labels: developer experience, low priority

#7864 Improve Jest ESM config
  jest.config.js
Labels: developer experience

#7884 #7690: load extension console after linking extension
  end-to-end-tests/example.spec.ts
  end-to-end-tests/fixtures.ts
  playwright.config.ts
Labels: testing

#7886 #7885: fix panels in modals/popovers
  src/extensionPages/extensionPagePlatform.ts
  src/tinyPages/ephemeralPanel.tsx
Labels: bug, regression, runtime

#7889 #7809: Fix Edge sidePanel links crash bug
  src/utils/openAllLinksInPopups.ts
Labels: bug, edge

#7890 #7888: AA Automation Co-Pilot branding
  src/__snapshots__/Storyshots.test.js.snap
  src/background/installer.ts
  src/contrib/automationanywhere/aaFrameProtocol.ts
  src/extensionConsole/pages/onboarding/SetupPage.test.tsx
  src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
  src/extensionConsole/pages/onboarding/partner/ControlRoomTokenForm.tsx
  src/extensionConsole/pages/onboarding/partner/PartnerSetupCard.tsx
  src/sidebar/LoginPanel.tsx
Labels: user experience, enterprise

#7881 Remove retired ignore_user_state request param
  src/background/starterMods.ts
  src/data/service/api.ts
Labels: infrastructure, developer experience

#7896 #7690: refactoring linking logic into fixture
  .eslintrc.js
  end-to-end-tests/auth.setup.ts
  end-to-end-tests/env.ts
  end-to-end-tests/example.spec.ts
  end-to-end-tests/extensionConsoleActivation.ts
  end-to-end-tests/fixtures/extensionBase.ts
  end-to-end-tests/tests/extensionConsoleSmoke.spec.ts
  src/tsconfig.strictNullChecks.json
Labels: testing

#7865 #7819: Avoid deeply-nested components
  .eslintrc.js
  src/__snapshots__/Storyshots.test.js.snap
  src/components/brickModalNoTags/BrickDetail.tsx
  src/components/brickModalNoTags/BrickModal.module.scss
  src/components/brickModalNoTags/BrickModal.tsx
  src/components/paginatedTable/PaginatedTable.tsx
  src/components/quickBar/QuickBarApp.tsx
  src/components/quickBar/QuickBarResults.tsx
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/brickEditor/EditPage.tsx
  src/extensionConsole/pages/brickEditor/Editor.tsx
  src/extensionConsole/pages/brickEditor/referenceTab/BlockResult.module.scss
  src/extensionConsole/pages/brickEditor/referenceTab/BlockResult.tsx
  src/extensionConsole/pages/integrations/ZapierIntegrationModal.tsx
  src/extensionConsole/pages/mods/emptyView/EmptyView.module.scss
  src/extensionConsole/pages/mods/emptyView/EmptyView.tsx
  src/extensionConsole/pages/mods/gridView/GridCard.module.scss
  src/extensionConsole/pages/mods/gridView/GridCard.tsx
  src/extensionConsole/pages/mods/gridView/GridCardErrorBoundary.tsx
  src/extensionConsole/pages/workshop/__snapshots__/WorkshopPage.test.tsx.snap
  src/pageEditor/PanelContent.tsx
  src/pageEditor/panes/HomePane.module.scss
  src/pageEditor/panes/HomePane.tsx
  src/pageEditor/tabs/dataPanelTabs.module.scss
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
Labels: developer experience

#7901 #7900: introducing axe-core to track a11y issues
  end-to-end-tests/tests/modsPageSmoke.spec.ts
  end-to-end-tests/utils.ts
  package-lock.json
  package.json
Labels: user experience, testing

#7911 #7690: reduce flakiness of page fixture
  end-to-end-tests/fixtures/extensionBase.ts
  end-to-end-tests/pageObjects/modsPage.ts
Labels: testing

#7912 #7690 First Playwright regression checklist test
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
  src/tsconfig.strictNullChecks.json
Labels: testing

#7887 strictNullChecks: locator, renderers, more
  src/analysis/analysisVisitors/varAnalysis/varAnalysis.test.ts
  src/background/deploymentUpdater.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/background/proxyUtils.test.ts
  src/background/proxyUtils.ts
  src/background/requests.ts
  src/bricks/effects/highlight.ts
  src/bricks/effects/pageState.ts
  src/bricks/readers/factory.ts
  src/bricks/transformers/controlFlow/TryExcept.test.ts
  src/bricks/transformers/controlFlow/TryExcept.ts
  src/bricks/transformers/temporaryInfo/DisplayTemporaryInfo.ts
  src/components/integrations/AuthWidget.test.tsx
  src/components/integrations/AuthWidget.tsx
  src/contrib/google/sheets/core/useGoogleAccount.ts
  src/contrib/google/sheets/core/useSpreadsheetId.test.tsx
  src/contrib/google/sheets/core/useSpreadsheetId.ts
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.tsx
  src/data/service/requestErrorUtils.test.ts
  src/errors/clientRequestErrors.test.ts
  src/errors/networkErrorHelpers.ts
  src/extensionConsole/pages/activateExtension/useCloudExtensionPermissions.ts
  src/extensionConsole/pages/activateMod/IntegrationsBody.test.tsx
  src/extensionConsole/pages/activateMod/useModPermissions.ts
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/integrations/IntegrationsPage.tsx
  src/extensionConsole/pages/onboarding/partner/ControlRoomTokenForm.tsx
  src/hooks/auth.ts
  src/hooks/useMemoCompare.ts
  src/hooks/useMergeAsyncState.ts
  src/hooks/useRefreshRegistries.ts
  src/integrations/autoConfigure.ts
  src/integrations/locator.ts
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.test.ts
  src/integrations/useSanitizedIntegrationConfigFormikAdapter.ts
  src/integrations/util/locateSanitizedIntegrationConfigWithRetry.ts
  src/pageEditor/hooks/useRemoveModComponentFromStorage.tsx
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/sidebar/modals/AddToRecipeModal.tsx
  src/pageEditor/sidebar/modals/MoveFromModModal.tsx
  src/runtime/pipelineTests/serviceContext.test.ts
  src/runtime/reducePipeline.ts
  src/runtime/renderers.ts
  src/runtime/runtimeUtils.ts
  src/sidebar/activateMod/ActivateModPanel.test.tsx
  src/tsconfig.strictNullChecks.json
  src/utils/domUtils.ts
  src/validators/formValidator.ts
Labels: developer experience

#7917 Fix forbidContext/expectContext usage
  src/contrib/ckeditor/ckeditorProtocol.ts
  src/sidebar/sidebar.tsx
  src/telemetry/performance.ts
Labels: bug, low priority

#7916 Fix `isVisible` usage
  scripts/__snapshots__/manifest.test.js.snap
  src/bricks/readers/ElementReader.test.ts
  src/manifest.json
  src/testUtils/testEnv.js
  src/utils/domUtils.ts
Labels: low priority

#7918 #7813: Remove `rootAware` support from insert-text brick and improve focus logic
  package-lock.json
  package.json
  src/bricks/effects/InsertAtCursorEffect.test.ts
  src/bricks/effects/InsertAtCursorEffect.ts
  src/bricks/effects/attachAutocomplete.ts
  src/contentScript/commandPopover/commandUtils.ts
  src/contentScript/textEditorDom.ts
  src/contrib/ckeditor/ckeditorDom.ts
  src/utils/domFieldUtils.ts
  src/utils/focusController.ts
Labels: bug, brick

#7921 Fix copyright notices
  src/bricks/effects/forms.test.ts
  src/bricks/transformers/convertDocument.ts
  src/data/model/ControlRoom.ts
  src/data/model/Me.ts
  src/data/model/MeOrganization.ts
  src/data/model/MeOrganizationMembership.ts
  src/data/model/MeUserGroupMembership.ts
  src/data/model/OrganizationTheme.ts
  src/data/model/PartnerPrincipal.ts
  src/data/model/UserMilestone.ts
  src/data/model/UserOrganizationMembershipRole.ts
  src/data/model/UserPartner.ts
  src/extensionConsole/components/IDBErrorDisplay.stories.tsx
  src/starterBricks/triggerEventReaders.ts
Labels: low priority

#7923 #7823: fix missing return in replaceAtCommand
  src/contentScript/commandPopover/CommandPopover.tsx
  src/contentScript/commandPopover/commandUtils.test.ts
  src/contentScript/commandPopover/commandUtils.ts
  src/tsconfig.strictNullChecks.json
Labels: bug

#7914 #7691: Address e2e test flakiness due to Extension reload and Extension Console loading times
  end-to-end-tests/fixtures/extensionBase.ts
  playwright.config.ts
Labels: testing

#7924 #7893: make snippet search case insensitive
  src/contentScript/commandPopover/CommandPopover.tsx
  src/contentScript/commandPopover/commandPopoverSlice.test.ts
  src/contentScript/commandPopover/commandPopoverSlice.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience

#7926 #7850: adds # rows field for textarea in form builder
  src/components/formBuilder/edit/FieldEditor.tsx
  src/components/formBuilder/edit/FormEditor.test.tsx
  src/pageEditor/testHelpers.ts
Labels: enhancement

#7927 #7857: add preview to text command popover
  src/bricks/effects/AddTextCommand.test.ts
  src/bricks/effects/AddTextCommand.ts
  src/bricks/effects/AddTextSnippets.test.ts
  src/bricks/effects/AddTextSnippets.ts
  src/contentScript/commandPopover/CommandPopover.scss
  src/contentScript/commandPopover/CommandPopover.tsx
  src/contentScript/commandPopover/commandUtils.test.ts
  src/contentScript/commandPopover/commandUtils.ts
  src/pageEditor/exampleBrickConfigs.ts
  src/platform/platformTypes/commandPopoverProtocol.ts
  src/utils/expressionUtils.ts
Labels: enhancement

#7929 refactor activate mod logic into page object
  end-to-end-tests/fixtures/extensionBase.ts
  end-to-end-tests/pageObjects/modsPage.ts
  end-to-end-tests/tests/extensionConsoleActivation.spec.ts
  end-to-end-tests/tests/modsPageSmoke.spec.ts
Labels: developer experience, testing

#7933 #7839: enable mv3 build for playwright e2e ci workflow
  .github/workflows/ci.yml
  end-to-end-tests/fixtures/extensionBase.ts
  playwright.config.ts
  webpack.config.mjs
Labels: testing

#7928 #7858: add text command popover navigation footer
  src/contentScript/commandPopover/CommandPopover.scss
  src/contentScript/commandPopover/CommandPopover.tsx
Labels: enhancement, user experience

#7930 #7855: add no matches state for text command popover
  src/contentScript/commandPopover/CommandPopover.scss
  src/contentScript/commandPopover/CommandPopover.test.tsx
  src/contentScript/commandPopover/CommandPopover.tsx
  src/themes/colors.scss
  src/tsconfig.strictNullChecks.json
Labels: user experience

#7935 Improve canvas utils in the browser action
  jest.config.js
  package-lock.json
  package.json
  src/background/setToolbarIconFromTheme.test.ts
  src/background/setToolbarIconFromTheme.ts
  src/components/formBuilder/ImageCropWidget.tsx
  src/contentScript/commandPopover/CommandPopover.tsx
  src/testUtils/testEnv.js
  src/tsconfig.strictNullChecks.json
  src/utils/canvasUtils.test.ts
  src/utils/canvasUtils.ts
Labels: mv3

#7932 #7854: change text selection menu alignment to bottom
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/utils/textAreaUtils.ts
Labels: user experience

#7942 CommandPopover: Fix scrollbar style on some websites
  src/contentScript/commandPopover/CommandPopover.scss
Labels: bug

#7959 #7956: only route google sheets API calls through the background worker (1/3)
  src/__mocks__/@/background/messenger/api.ts
  src/background/auth/authStorage.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/messenger/strict/api.ts
  src/background/messenger/strict/registration.ts
  src/contrib/google/sheets/bricks/append.test.ts
  src/contrib/google/sheets/bricks/append.ts
  src/contrib/google/sheets/bricks/lookup.test.ts
  src/contrib/google/sheets/bricks/lookup.ts
  src/contrib/google/sheets/core/sheetsApi.ts
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/AppendSpreadsheetOptions.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.test.tsx
  src/contrib/google/sheets/ui/LookupSpreadsheetOptions.tsx
  src/contrib/google/sheets/ui/RequireGoogleSheet.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.test.tsx
  src/contrib/google/sheets/ui/SpreadsheetPickerWidget.tsx
  src/extensionPages/extensionPagePlatform.ts
  src/integrations/autoConfigure.ts
  src/pageEditor/tabs/modOptionsValues/ModOptionsValuesEditor.test.tsx
  src/tsconfig.strictNullChecks.json
Labels: enhancement, developer experience

#7937 #7807: form builder add submit button affordance to paragraph text field
  scripts/DiscardFilePlugin.mjs
  scripts/__snapshots__/manifest.test.js.snap
  src/bricks/transformers/ephemeralForm/EphemeralForm.tsx
  src/bricks/transformers/ephemeralForm/EphemeralFormContent.tsx
  src/components/StylesheetsContext.ts
  src/components/fields/IconWidget.tsx
  src/components/formBuilder/TextAreaWidget.module.scss
  src/components/formBuilder/TextAreaWidget.test.tsx
  src/components/formBuilder/TextAreaWidget.tsx
  src/components/formBuilder/edit/FieldEditor.tsx
  src/components/formBuilder/edit/FormEditor.test.tsx
  src/components/formBuilder/formEditor.testCases.ts
  src/manifest.json
  src/themes/colors.scss
  src/tsconfig.strictNullChecks.json
  webpack.config.mjs
Labels: enhancement, brick

#7962 UX polish on command and selection popovers
  src/contentScript/commandPopover/CommandPopover.scss
  src/contentScript/commandPopover/commandController.tsx
  src/contentScript/selectionTooltip/SelectionToolbar.scss
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/contentScript/tooltipDom.ts
Labels: user experience

#7965 Disable Storybook PRs from dependabot
  .github/dependabot.yml
Labels: dependencies

#7973 Update PR checklist
  .github/pull_request_template.md
Labels: developer experience, low priority

#7974 Automatically reload inactive page editors on invalidation
  src/components/InvalidatedContextGate.tsx
  src/hooks/useDocumentVisibility.test.ts
  src/hooks/useDocumentVisibility.ts
  src/pageEditor/Panel.tsx
  src/tsconfig.strictNullChecks.json
Labels: user experience, developer experience, low priority, page editor

#7971 Bump knip to v5
  .github/workflows/ci.yml
  knip.mjs
  src/testUtils/renderWithCommonStore.ts
  src/vendors/page-metadata-parser/parser.js
Labels: dependencies

#7964 #7963: fix brick input validation for integrations with required properties
  src/runtime/pipelineTests/validateInput.test.ts
  src/validators/schemaValidator.test.ts
  src/validators/schemaValidator.ts
Labels: bug, regression, runtime, release blocker

#7957 #7954: parameterize interactive login for web auth flow (2/3)
  src/background/auth/authErrors.ts
  src/background/auth/authHelpers.test.ts
  src/background/auth/authHelpers.ts
  src/background/auth/codeGrantFlow.ts
  src/background/auth/implicitGrantFlow.ts
  src/background/auth/launchOAuth2Flow.test.ts
  src/background/auth/launchOAuth2Flow.ts
  src/background/backgroundPlatform.ts
  src/background/messenger/api.ts
  src/background/partnerIntegrations.ts
  src/background/performConfiguredRequest.test.ts
  src/background/refreshToken.ts
  src/background/requests.test.ts
  src/background/requests.ts
  src/bricks/renderers/customForm.ts
  src/contentScript/contentScriptPlatform.ts
  src/contrib/automationanywhere/RunBot.test.ts
  src/contrib/uipath/ProcessOptions.tsx
  src/contrib/uipath/uipathHooks.ts
  src/contrib/zapier/PushOptions.tsx
  src/extensionConsole/pages/onboarding/partner/ControlRoomOAuthForm.tsx
  src/extensionPages/extensionPagePlatform.ts
  src/integrations/integrationTypes.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement

#7981 #7978: fix vertical alignment of close buttons
  src/sidebar/Tabs.module.scss
Labels: bug

#7941 Move business logic out of `@/vendors` folder
  .github/workflows/pr.yml
  .storybook/preview.js
  src/background/telemetry.ts
  src/components/AceEditor.tsx
  src/components/AceEditorSync.tsx
  src/components/DiffEditor.tsx
  src/components/DiffEditorSync.tsx
  src/components/documentBuilder/createNewElement.test.ts
  src/components/fields/schemaFields/widgets/CodeEditorWidget.tsx
  src/extensionConsole/options.tsx
  src/extensionConsole/pages/brickEditor/BrickHistory.tsx
  src/extensionConsole/pages/brickEditor/CodeEditor.tsx
  src/extensionConsole/pages/brickEditor/referenceTab/BrickDetail.tsx
  src/globals.d.ts
  src/pageEditor/pageEditor.tsx
  src/sidebar/sidebar.tsx
  src/starterBricks/helpers.ts
  src/starterBricks/menuItemExtension.ts
  src/starterBricks/triggerExtension.ts
  src/tinyPages/walkthroughModal.tsx
  src/tsconfig.strictNullChecks.json
  src/types/helpers.ts
  src/utils/global.scss
  src/utils/themes.scss
  src/vendors/hoverintent.d.ts
  src/vendors/jQueryInitialize.d.ts
  src/vendors/jQueryInitialize.js
  src/vendors/mixpanel.ts
  src/vendors/mixpanelDetectBrowser.ts
  src/vendors/page-metadata-parser/parser.d.ts
  src/vendors/page-metadata-parser/url-utils.js
  src/vendors/theme/app/app.scss
  src/vendors/validateUuid.ts
Labels: developer experience, low priority

#7972 #7673: Avoid CORS issues in ImageReader
  src/bricks/readers/ImageExifReader.ts
  src/bricks/readers/ImageReader.ts
  src/tsconfig.strictNullChecks.json
  src/utils/imageUtils.ts
Labels: enhancement

#7977 A11y: Introduce ClickableElement
  .eslintrc.js
  eslint-local-rules/noRestrictedSyntax.tsx
  knip.mjs
  src/components/ClickableElement.test.tsx
  src/components/ClickableElement.tsx
  src/components/StopPropagation.test.tsx
  src/components/StopPropagation.tsx
  src/components/addBlockModal/BlockGridItem.tsx
  src/components/documentBuilder/preview/DocumentPreview.tsx
  src/pageEditor/tabs/editTab/editorNodes/PipelineFooterNode.tsx
  src/tsconfig.strictNullChecks.json
Labels: low priority, backlog, a11y

#7986 animate fade-in for the command and selection menus
  src/contentScript/commandPopover/commandController.tsx
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/tsconfig.strictNullChecks.json
  src/utils/a11yUtils.ts
Labels: user experience

#7988 Use insert/enter instructions for snippet shortcut menu
  src/contentScript/commandPopover/CommandPopover.tsx
Labels: user experience

#7989 #7882: Avoid errors on `Selection#getRangeAt()`
  .eslintrc.js
  .github/workflows/ci.yml
  eslint-local-rules/noRestrictedSyntax.tsx
  src/contentScript/commandPopover/commandController.tsx
  src/contentScript/commandPopover/commandUtils.ts
  src/contentScript/commandPopover/useKeyboardQuery.ts
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/utils/domUtils.ts
  src/utils/selectionController.ts
  src/vendors/page-metadata-parser/url-utils.js
Labels: bug, user experience

#7984 #7895 Fix integration config (AuthWidget) default form values
  src/components/integrations/AuthWidget.test.tsx
  src/components/integrations/AuthWidget.tsx
  src/components/integrations/IntegrationConfigEditorModal.test.tsx
  src/components/integrations/integrationHelpers.ts
  src/tsconfig.strictNullChecks.json
  src/utils/schemaUtils.ts
Labels: bug

#7999 fix command popover animation flash
  src/contentScript/commandPopover/commandController.tsx
Labels: bug, user experience

#7998 #7987: Fix Text Selection Menu losing placement when selected text is not visible
  src/contentScript/selectionTooltip/tooltipController.tsx
  src/tsconfig.strictNullChecks.json
  src/utils/debugUtils.ts
  src/utils/mathUtils.test.ts
  src/utils/mathUtils.ts
  src/utils/textAreaUtils.ts
Labels: bug, user experience

#8001 #7983: Fix duplicate message forwarding
  package-lock.json
  package.json
  src/pageEditor/toolbar/ReloadToolbar.tsx
Labels: bug, runtime

#8005 #8004: memoizes launchOAuth2Flow to prevent banners on login pages
  src/background/auth/launchOAuth2Flow.test.ts
  src/background/auth/launchOAuth2Flow.ts
Labels: bug

#8006 #7994: Hide selection menu when clicking outside
  src/contentScript/selectionTooltip/tooltipController.tsx
Labels: bug, user experience

#8008 #7993: fix text selection menu obscured within input
  src/utils/textAreaUtils.ts
Labels: bug, user experience

#8011 Rename text tooltip -> text selection menu
  src/__snapshots__/Storyshots.test.js.snap
  src/contentScript/contentScriptPlatform.ts
  src/contentScript/textSelectionMenu/ActionRegistry.test.ts
  src/contentScript/textSelectionMenu/ActionRegistry.ts
  src/contentScript/textSelectionMenu/SelectionMenu.scss
  src/contentScript/textSelectionMenu/SelectionMenu.stories.tsx
  src/contentScript/textSelectionMenu/SelectionMenu.tsx
  src/contentScript/textSelectionMenu/selectionMenuController.test.ts
  src/contentScript/textSelectionMenu/selectionMenuController.tsx
  src/contentScript/textSelectionMenu/useActionRegistry.ts
  src/platform/capabilities.ts
  src/platform/platformBase.ts
  src/platform/platformProtocol.ts
  src/platform/platformTypes/textSelectionMenuProtocol.ts
  src/starterBricks/contextMenu.ts
  src/testUtils/platformMock.ts
  src/tsconfig.strictNullChecks.json
  src/utils/debugUtils.ts
Labels: developer experience

#7996 #7767 AA Run API Task javascript brick
  src/components/form/widgets/SelectWidget.tsx
  src/contrib/automationanywhere/ApiTaskOptions.tsx
  src/contrib/automationanywhere/BotOptions.test.tsx
  src/contrib/automationanywhere/BotOptions.tsx
  src/contrib/automationanywhere/RunApiTask.ts
  src/contrib/automationanywhere/RunBot.ts
  src/contrib/automationanywhere/aaApi.ts
  src/contrib/automationanywhere/aaTypes.ts
  src/contrib/automationanywhere/aaUtils.test.ts
  src/contrib/automationanywhere/aaUtils.ts
  src/contrib/automationanywhere/contract.ts
  src/contrib/automationanywhere/util.ts
  src/contrib/editors.ts
  src/contrib/registerContribBlocks.ts
  src/development/headers.test.ts
  src/tsconfig.strictNullChecks.json
Labels: enhancement, brick

#8002 Call `reactivateTab` directly, rename `activateTab` to `focusTab`
  src/activation/useActivateRecipe.test.ts
  src/activation/useActivateRecipe.ts
  src/background/executor.ts
  src/background/messenger/api.ts
  src/background/messenger/registration.ts
  src/background/navigation.ts
  src/bricks/effects/tabs.ts
  src/contentScript/messenger/api.ts
  src/extensionConsole/pages/brickEditor/useSubmitBrick.ts
  src/extensionConsole/pages/settings/FactoryResetSettings.tsx
  src/modDefinitions/modDefinitions.test.tsx
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/hooks/useSaveMod.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.ts
Labels: developer experience, performance, small

#8020 #8019: update `frame-src` to allow `http:`
  scripts/__snapshots__/manifest.test.js.snap
  src/manifest.json
Labels: enhancement, customer

#8016 #8009: LoginBanners: Reduce chance of style conflicts
  src/components/EmotionShadowRoot.ts
  src/contentScript/integrations/LoginBanners.tsx
  src/contentScript/integrations/bannerDomController.tsx
  src/contentScript/integrations/deferredLoginController.test.tsx
  src/contentScript/integrations/deferredLoginController.ts
  src/contentScript/messenger/registration.ts
  src/contentScript/sidebarDomControllerLite.ts
Labels: bug, user experience

#8021 Update snippet shortcut brick names
  src/bricks/effects/AddTextCommand.test.ts
  src/bricks/effects/AddTextCommand.ts
  src/bricks/effects/AddTextSnippets.ts
  src/pageEditor/exampleBrickConfigs.ts
Labels: user experience, do not merge

#7976 #7558: Improve document/form builder responsiveness
  src/__snapshots__/Storyshots.test.js.snap
  src/components/documentBuilder/edit/DocumentOptions.module.scss
  src/components/documentBuilder/edit/DocumentOptions.test.tsx
  src/components/documentBuilder/edit/DocumentOptions.tsx
  src/components/documentBuilder/edit/ElementEditor.tsx
  src/components/documentBuilder/edit/RemoveElement.tsx
  src/components/formBuilder/FormBuilder.tsx
  src/components/formBuilder/edit/ActiveField.tsx
  src/components/formBuilder/edit/FormEditor.module.scss
  src/components/formBuilder/edit/FormEditor.tsx
  src/components/formBuilder/edit/FormIntroFields.tsx
  src/components/formBuilder/edit/__snapshots__/FormEditor.test.tsx.snap
  src/pageEditor/fields/CollapsibleFieldSection.module.scss
  src/pageEditor/fields/CollapsibleFieldSection.tsx
  src/pageEditor/fields/FormModalOptions.tsx
  src/pageEditor/fields/FormRendererOptions.tsx
  src/pageEditor/panes/__snapshots__/EditorPane.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/ExtraPermissionsSection.test.tsx.snap
  src/pageEditor/tabs/__snapshots__/MatchRulesSection.test.tsx.snap
  src/pageEditor/tabs/effect/__snapshots__/BrickConfiguration.test.tsx.snap
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.tsx
  src/pageEditor/tabs/trigger/__snapshots__/TriggerConfiguration.test.tsx.snap
Labels: bug, user experience, low priority, page editor, mv3

#8037 Hide community link in extension console for restricted users
  src/data/model/UserPartner.ts
  src/extensionConsole/Sidebar.test.tsx
  src/extensionConsole/Sidebar.tsx
Labels: bug, enterprise

#8031 #8030: add slow/bad selector analysis warnings
  src/analysis/analysisVisitors/selectorAnalysis.test.ts
  src/analysis/analysisVisitors/selectorAnalysis.ts
  src/analysis/analysisVisitors/templateAnalysis.ts
  src/globals.d.ts
  src/pageEditor/analysisManager.ts
  src/utils/domUtils.test.ts
  src/utils/domUtils.ts
  src/vendors/jQueryInitialize.js
Labels: enhancement, page editor, analysis

#8052 Add knip to the dev dependencies
  .github/workflows/ci.yml
  end-to-end-tests/pageObjects/modsPage.ts
  knip.mjs
  package-lock.json
  package.json
  src/__mocks__/webext-detect-page.ts
  src/background/backgroundDomWatcher.ts
  src/background/contentScript.test.ts
  src/background/contextMenus.test.ts
  src/background/deploymentUpdater.test.ts
  src/background/performConfiguredRequest.test.ts
  src/bricks/transformers/brickFactory.test.ts
  src/contrib/google/sheets/core/useCurrentOrigin.test.ts
  src/contrib/uipath/LocalProcessOptions.test.tsx
  src/contrib/uipath/ProcessOptions.test.tsx
  src/runtime/pipelineTests/component.test.ts
  src/testUtils/testAfterEnv.ts
  src/tsconfig.strictNullChecks.json
Labels: dependencies, developer experience, low priority

#8062 Add inclusiveness analyzer to CI
  .github/workflows/ci.yml
  eslint-local-rules/noCrossBoundaryImports.js
  eslint-local-rules/noCrossBoundaryImports.test.js
  src/utils/inference/selectorInferenceUtils.ts
Labels: developer experience

#8051 Add `useOnMountOnly`
  src/components/brickModalNoTags/BrickModal.tsx
  src/components/quickBar/QuickBarApp.tsx
  src/components/quickBar/useActions.ts
  src/contrib/google/sheets/ui/RequireGoogleSheet.tsx
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/globals.d.ts
  src/hooks/useOnMountOnly.test.ts
  src/hooks/useOnMountOnly.ts
  src/pageEditor/tabs/editTab/dataPanel/DataPanel.tsx
  src/sidebar/Tabs.tsx
  src/sidebar/activateMod/ActivateModPanel.tsx
  src/tinyPages/RestrictedUrlPopupApp.tsx
  src/tsconfig.strictNullChecks.json
Labels: developer experience, low priority

#8064 #8060 Fix hide-sidebar brick, unfreeze/clone brick input schemas before passing into the schema validator
  src/validators/schemaValidator.test.ts
  src/validators/schemaValidator.ts
Labels: bug, regression

#8069 #8063: improve user-visible error message for InsertAtCursorEffect brick
  src/bricks/effects/InsertAtCursorEffect.test.ts
  src/bricks/effects/InsertAtCursorEffect.ts
  src/contentScript/textEditorDom.ts
  src/tsconfig.strictNullChecks.json
Labels: user experience

#8072 Fix form margin regression
  src/__snapshots__/Storyshots.test.js.snap
  src/components/formBuilder/FieldTemplate.module.scss
  src/components/formBuilder/preview/FormPreview.tsx
  src/components/formBuilder/preview/__snapshots__/FormPreview.test.tsx.snap
Labels: bug, regression, form builder

#8077 rename selectors in extensionsSelectors
  src/activation/useActivateModWizard.ts
  src/activation/useActivateRecipe.ts
  src/background/deploymentUpdater.ts
  src/background/modUpdater.ts
  src/extensionConsole/pages/activateMod/ActivateModCard.tsx
  src/extensionConsole/pages/activateMod/ActivateModPage.tsx
  src/extensionConsole/pages/brickEditor/EditPage.tsx
  src/extensionConsole/pages/deployments/DeploymentsContext.tsx
  src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModalBody.tsx
  src/extensionConsole/pages/mods/utils/useReinstall.ts
  src/extensionConsole/pages/settings/useDiagnostics.ts
  src/mods/useModViewItems.tsx
  src/mods/useMods.ts
  src/pageEditor/analysisManager.ts
  src/pageEditor/hooks/useDeactivateMod.tsx
  src/pageEditor/hooks/useResetExtension.ts
  src/pageEditor/hooks/useUpsertModComponentFormState.test.ts
  src/pageEditor/panes/save/SaveDataIntegrityErrorModal.tsx
  src/pageEditor/panes/save/useSavingWizard.ts
  src/pageEditor/slices/editorSelectors.ts
  src/pageEditor/tabs/modMetadata/ModMetadataEditor.tsx
  src/sidebar/activateMod/ActivateModInputs.tsx
  src/sidebar/activateMod/ActivateMultipleModsPanel.tsx
  src/sidebar/activateMod/RequireMods.tsx
  src/sidebar/sidebarSelectors.ts
  src/store/extensionsSelectors.ts
  src/utils/modUtils.ts
Labels: developer experience

#8078 Rename install starter mods to activate
  src/activation/useActivateRecipe.test.ts
  src/activation/useActivateRecipe.ts
  src/background/deploymentUpdater.ts
  src/background/messenger/registration.ts
  src/background/modUpdater.test.ts
  src/background/modUpdater.ts
  src/background/starterMods.test.ts
  src/background/starterMods.ts
  src/extensionConsole/pages/activateExtension/ActivateExtensionCard.tsx
  src/extensionConsole/pages/deployments/activateDeployments.ts
  src/extensionConsole/pages/mods/hooks/useModsPageActions.test.tsx
  src/extensionConsole/pages/mods/modals/convertToRecipeModal/ConvertToRecipeModal.test.tsx
  src/extensionConsole/pages/mods/utils/useReinstall.test.ts
  src/extensionConsole/pages/mods/utils/useReinstall.ts
  src/modDefinitions/modDefinitions.test.tsx
  src/pageEditor/hooks/useBuildAndValidateMod.test.ts
  src/pageEditor/hooks/useCheckModStarterBrickInvariants.test.ts
  src/pageEditor/hooks/useCompareModComponentCounts.test.ts
  src/pageEditor/hooks/useCreateModFromMod.test.ts
  src/pageEditor/hooks/useCreateModFromMod.ts
  src/pageEditor/hooks/useSaveMod.test.ts
  src/pageEditor/panes/save/saveHelpers.test.ts
  src/pageEditor/tabs/modOptionsDefinitions/ModOptionsDefinitionEditor.test.tsx
  src/store/checkAvailableInstalledExtensions.test.ts
  src/store/extensionsSlice.ts
  src/store/sessionChanges/sessionChangesListenerMiddleware.ts
Labels: developer experience

#8079 #7174 add manifest version to event telemetry
  src/background/telemetry.test.ts
  src/background/telemetry.ts
Labels: telemetry

#8082 #7960 e2e smoke test for the sidebar in MV2 and MV3
  .env.example
  .eslintrc.js
  .github/workflows/ci.yml
  end-to-end-tests/README.md
  end-to-end-tests/env.ts
  end-to-end-tests/fixtures/extensionBase.ts
  end-to-end-tests/pageObjects/modsPage.ts
  end-to-end-tests/tests/modsPageSmoke.spec.ts
  end-to-end-tests/tests/sidebarSmoke.spec.ts
  end-to-end-tests/utils.ts
  playwright.config.ts
  scripts/manifest.mjs
  src/contentScript/textSelectionMenu/selectionMenuController.tsx
  src/domConstants.ts
  webpack.config.mjs
Labels: testing

#8073 Drop some comments and logging
  src/bricks/renderers/documentView/DocumentViewLazy.tsx
  src/bricks/transformers/controlFlow/WithAsyncModVariable.ts
  src/contentScript/sidebarController.tsx
  src/contentScript/sidebarDomControllerLite.ts
  src/pageEditor/PanelContent.tsx
  src/pageEditor/protocol.ts
  src/starterBricks/tourController.ts
  src/types/helpers.ts
Labels: developer experience, low priority

#8091 Fix bugs in `ActivateExtensionCard`
  src/extensionConsole/pages/activateExtension/ServicesRow.tsx
Labels: bug, user experience
